### ISSUE TITLE
This repo's FeatureContext should be exposed to be used on other packages testing 

### ISSUE THREAD

**Issue by bwowk** [Behat/Behat#1000]
[Behat/features/bootstrap/FeatureContext.php](https://github.com/Behat/Behat/blob/6029eebe48691439c8351ded005c60ab1bded7a5/features/bootstrap/FeatureContext.php) should be exposed for external usage as a MetaContext, or something like that. This Context is pretty useful to make self-tests on extensions, so it would be great if it was included on the package.

**Comment by pamil** [comment]
@bwowk I've created a library for testing Behat extensions, take a look at https://github.com/FriendsOfBehat/TestContext :)

**Comment by everzet** [comment]
I prefer core to be small. Both to give wider community reason/motivation to contribute and to keep things simple on the maintenance side.
