### ISSUE TITLE
Ability to run scenarios in "sets" or in "ranges"

### ISSUE THREAD

**Issue by walterdolce** [Behat/Behat#1002]
Sometimes a feature encompasses scenarios which, in turn, could be seen (and run) as a "unit".

For example, imagine a feature like the following:
```
Feature: account creation

   Scenario: user is able to create an account
   
   # Handling fields validation
   Scenario: user can't create an account without specifying the name
   Scenario: user can't create an account without specifying the email address
      # ...
```

In cases like the one above, wouldn't it be useful to be able run scenario in "sets" or "ranges"?

Example:
```
behat some_feature:13,33  # Run scenarios at line 13 through line 33
```

There's an assumption I'm making here: I assume there may or may not be a scenario at line 33 and if not, Behat wouldn't care. It would just run whatever scenario is encountered from line 13 until line 33.

Hope this makes sense. I'd be interested to know how you feel / what you think about this.

**Comment by Taluu** [comment]
You can already do it :

```gherking
Feature: foo bar

Scenario: Doing something
When I do something
Then I expect something

Scenario: Doing something else
When I do something else
Then I expect something else
```

`$ bin/behat foo.feature:3-9`

Will run both scenarios

**Comment by walterdolce** [comment]
I didn't know that. Thank you @Taluu !

This can be closed then. Is this documented anywhere? I didn't find this feature in the docs..

**Comment by edno** [comment]
@walterdolce, it's available in the command line help: http://behat.org/en/v2.5/guides/6.cli.html

**Comment by walterdolce** [comment]
Oh I missed that, thanks @edno !
