### ISSUE TITLE
Inability to use the same step definition in distinct contexts

### ISSUE THREAD

**Issue by walterdolce** [Behat/Behat#1003]
It is not clear how best this scenario (pun not intended) should be tackled when it comes to have a step definition used by two different contexts and when that same step definition is an integral part of those contexts, yet it's defined in the same way in both.

Assume the following:
```
# login.feature
Scenario: User logs in
   Given I go to the login page and enter my email address
   And I solve the Google CAPTCHA challenge
   When I click on the login button
   Then I am logged in 

# create_account.feature
Scenario: User creates an account
    Given I go to the create account page and enter my details
    And I solve the Google CAPTCHA challenge
    When I click on the register button
    Then my account is created
```

Now, assume the use of the PageObjectExtension. Both `LoginContext` and `CreateAccountContext` get injected the `Login` and `CreateAccount` page objects in the constructor, like so:
```
class CreateAccountContext ...
    function __constructor(CreateAccountPage $page) ...

class LoginContext ...
    function __constructor(LoginPage $page) ...
```

Now, the contexts both share `And I solve the Google CAPTCHA challenge`. But this step it's specifically scoped to each context. This means that this step definition has to do something like the following:
```
# CreateAccountContext
$this->createAccountPage->getElement( ... )-> ...

# LoginContext
$this->login->getElement( ... )-> ...
```
Same step definition, same logic, but specific to each context (it's two different pages in the end).

*Problem 1*: can't have this step defined in both contexts, Behat deems this as ambiguous because it doesn't know which one to pick.
*Problem 2*: can't use a dictionary traits used in both contexts, same problem (and I would rather avoid falling into the dictionaries traits trap anyway).
*Problem 3*: can't leverage the use of so-called shared helpers as defined in the example [here](https://github.com/everzet/behat-shared-helpers-example). I tried to follow it but it simply didn't work. Probably because I was mixing PageObject and the other extension which seems quite young and limited at the moment.
*Problem 4*: can't use the [ScenarioStateBehatExtension](https://github.com/gorghoa/ScenarioStateBehatExtension) anymore either it seems. Looks like now Behat complains about context methods containing parameters not defined in the step definition.

Am I missing something?
Have you come across this? 
If so, what solution did you implement and why?

Thanks.

**Comment by walterdolce** [comment]
Thanks @debo,  that could do the trick.

I should have mentioned I am aware I could use just defined the step above as:
```
And I solve the Google CAPTCHA challenge on the login page

And I solve the Google CAPTCHA challenge on the create account page
```
And so make the step really specific. But I am curious as to how people coming across this has solved the problem.

**Comment by everzet** [comment]
Hi Walter. What's the point of introducing abstraction layer to your context if you're not abstracting your implementation detail away from it? :)))

Your particular page object should abstract away the captcha challenge between shared, but simpler interface. This technically means that instead of writing:

```
# CreateAccountContext
$this->createAccountPage->getElement( ... )-> ...

# LoginContext
$this->login->getElement( ... )-> ...
```

you should write:

```
$this->captcha->fill()
```

Depending on the situation then you'll be able to use the same context, but a different page object, implementing same interface.
