### ISSUE TITLE
Syntax Error unexpected 'class' (T_CLASS) in QuestionHelper.php

### ISSUE THREAD

**Issue by slarti-b** [Behat/Behat#1004]
Thought I'd try this out, so I followed the quick start at http://behat.org/en/latest/quick_start.html#installation.  I took method 2 and downlaod the phar with 
`wget https://github.com/Behat/Behat/releases/download/v3.3.0/behat.phar`

Then, as per the guide, I ran ` php behat.phar -V`.  What I get is:
```
[adamc@adamc-centos ~]$  php behat.phar -V
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in phar:///home/adamc/behat.phar/vendor/symfony/console/Helper/QuestionHelper.php on line 85
PHP Stack trace:
PHP   1. {main}() /home/adamc/behat.phar:0
PHP   2. require() /home/adamc/behat.phar:10
PHP   3. Behat\Testwork\ApplicationFactory->createApplication() phar:///home/adamc/behat.phar/bin/behat:33
PHP   4. Behat\Testwork\Cli\Application->__construct() phar:///home/adamc/behat.phar/src/Behat/Testwork/ApplicationFactory.php:72
PHP   5. Symfony\Component\Console\Application->__construct() phar:///home/adamc/behat.phar/src/Behat/Testwork/Cli/Application.php:58
PHP   6. Symfony\Component\Console\Application->getDefaultHelperSet() phar:///home/adamc/behat.phar/vendor/symfony/console/Application.php:83
PHP   7. Composer\Autoload\ClassLoader->loadClass() phar:///home/adamc/behat.phar/vendor/symfony/console/Application.php:934
PHP   8. Composer\Autoload\includeFile() phar:///home/adamc/behat.phar/vendor/composer/ClassLoader.php:322
```

I'm running PHP 5.4.45 on a Centos 6.5 based environment.  (We are planning upgrade PHP version soon, but the docs say it's for 5.3+ (http://behat.org/en/latest/guides.html).  The download page for 3.3.0 seems to imply PHP 5.3 support may be no more but that it should work on 5.4+ at least for now. I can't find an official "requirements" list)

**Comment by avant1** [comment]
Behat itself [requires PHP 5.3](https://github.com/Behat/Behat/blob/919293abeea1df5b4d57b5c67a2d9e8d91999820/composer.json#L17), but seems like phar file is being build using PHP 5.5. Depending on PHP version `composer` installs different versions of packages (that are compatible with that PHP version). And as result that phar file cannot be used on php versions prior to 5.5.

For now you can install Behat using `composer`. 

But this is a problem, and probably should be fixed, changing phar file build process or at least note in docs would be useful.

@everzet Is phar build automated? I can't find that functionality in this repository.

**Comment by everzet** [comment]
nope, I was building it locally, so it's worse - it is built on 7.1. :/

**Comment by avant1** [comment]
This process can be automated, here is an article describing it: https://andreas.heigl.org/2017/01/18/building-a-phar-automated/

Should `phar` be built on PHP 5.3 only, or maybe we can add multiple `phar` files for each release, built on 5.3 and 7.1 for example?

**Comment by ciaranmcnulty** [comment]
At the time we added automated PHAR generation to PhpSpec, @everzet was experimenting with signing the PHARs for Behat and it looked complicated to automate :-)

**Comment by everzet** [comment]
Should be automatically building against 5.4 from now on. It is notoriously hard to debug, so it might take couple releases to ensure it all works...
