### ISSUE TITLE
identify which feature is running ( *.feature )

### ISSUE THREAD

**Issue by spagu** [Behat/Behat#1005]
Hi, I see great work on behat in version 3! But I am just wondering how to identify which feature file is being processed.  $this->FeatureName ?

**Comment by jakzal** [comment]
With hooks you can hook into behat's process: http://behat.readthedocs.io/en/latest/user_guide/context/hooks.html

For example, with the BeforeFeature hook you gain access to [BeforeFeatureScope](https://github.com/Behat/Behat/blob/master/src/Behat/Behat/Hook/Scope/BeforeFeatureScope.php) which eposes some [feature details](https://github.com/Behat/Gherkin/blob/master/src/Behat/Gherkin/Node/FeatureNode.php) (title among other things). You can store this in your context for future use.

Let me just add that if you feel you need this you're probably doing something hackish.
