### ISSUE TITLE
Want to get idea for running test in parallel 

### ISSUE THREAD

**Issue by sakonachhoeurng** [Behat/Behat#1006]
Hello,

I would like to know how can I run test in parallel. I would like to get idea from all of you. I try to use for packaging but feel that it is not work for me. I am using latest of behat version.

Thanks for collaboration,
Sakona

**Comment by jakzal** [comment]
In past, when I didn't know parallelisation is a solution to the wrong problem, I used GNU parallel to execute my features in parallel. See http://zalas.eu/running-behat-in-parallel-with-selenium-grid/

Google "Behat parallel" for more options and even some Behat extensions.

Alternative to parallelisation is making your tests fast by avoiding going through the UI all the time (executing most of scenarios through your service layer, decoupled from the infrastructure like db).

**Comment by spolischook** [comment]
for UI tests with behat we are use simple bash script that create db and host for every worker and that run every testsuite in workers. For Travis-ci we are use only 2 workers, but locally I setup 4 workers and it works well - all my 4 cores was loaded by 100%.

**Comment by sakonachhoeurng** [comment]
Thanks for your suggestion @jakzal and @spolischook, Before asking that I try to use this one [https://packagist.org/packages/tonicforhealth/behat-parallel-scenario](url) I seem not understand, it works as run one scenario then open the browser then finish, and then it run other scenario. Do you think it work as parallels? 
For @jakzal  I will try out your suggestion.
I use OS Ubuntu 14.04 for my current working

**Comment by jakzal** [comment]
@sakonachhoeurng by the way, I'm not sure if this is the right place to discuss this. This tracker is used for Behat development, and Behat doesn't have (or will have) native support for running tests in parallel (see https://github.com/Behat/Behat/issues/159#issuecomment-168751860).

**Comment by sakonachhoeurng** [comment]
@jakzal yes, sure for this. I can try other way, thanks for anyway suggestion.
