### ISSUE TITLE
Spelling Correction - Behat Home Page

### ISSUE THREAD

**Issue by markrogoyski** [Behat/Behat#1007]
There is a spelling mistake on the Behat homepage: http://behat.org/en/latest/

The word 'continuous' is misspelled as 'continous'.

Context:

> Behat is an open source Behavior-Driven Development framework for PHP. It is a tool to support you in delivering software that matters through **_continous_** communication, deliberate discovery and test-automation.

**Comment by jakzal** [comment]
Thanks for reporting. See https://github.com/Behat/docs/pull/116 for a fix.
