### ISSUE TITLE
Registering context programatically stops --dry-run from detecting step definitions

### ISSUE THREAD

**Issue by forceedge01** [Behat/Behat#1010]
<b>Why do I need this?</b>
We've recently moved from the monolithic model of a featureContext to small more manageable contextFiles. We can register them in behat.yml individually but want a way around it so we don't have to manage/resolve conflicts every now and then on those changes.

<b>Pseudo code:</b>
```
/**
 * @BeforeSuite
 */
public static function registerContextClasses(BeforeSuiteScope $scope)
{
    $contextClasses = [...];
    foreach $contextClasses as $contextClass 
        $scope->getEnvironment()->registerContextClass($contextClass)
}
```

The above code registers multiple context classes with Behat, this works absolutely fine but when I run behat --dry-run it does not recognise any step definitions which are defined in the context classes. Also behat -d '\<search term\>' does not give me definitions.

I presume this is because the BeforeSuite hook does not get executed altogether when running --dry-run or -d, am I doing it wrong? Is there a better way to make all of this work?

Using Behat v3.3.0

Thanks.

**Comment by spolischook** [comment]
> Is there a better way to make all of this work?

Yea! Just define contexts in your suite configuration

**Comment by forceedge01** [comment]
@spolischook Thanks for replying. Not sure if suite configuration has anything to do with autoloading context classes. Anyway googled what you said and got here http://behat.org/en/latest/user_guide/configuration/suites.html, don't see this solves my problem. Maybe i've misunderstood something.

To keep this discussion short and sweet, I would really appreciate an example of the suggested implementation please.

Thanks.

**Comment by spolischook** [comment]
@forceedge01 Your link is right. You can define all contexts in configuration for each suite individually, but if you need something like autoload contexts we have some implementation in our project.
There are shared contexts https://git.io/vS3RX that will added to every autoloaded suite.
There is extension method that create suite for each bundle that has at list one feature and add shared contexts with its own Feature context to it

**Comment by forceedge01** [comment]
Thanks @spolischook for the examples really helpful, much appreciated. So to be to autoload context files properly one solution would be to create an extension which then autoloads relevant context files in. I was trying this in a Context file rather than an extension but I guess the execution path of Behat 3 does not support that fully. It makes sense to be honest to not trigger the BeforeSuite hook if the suite is not going to run.

Sounds good I will try creating a miniature extension based on the implementation you've provided. Thanks very much for your help :)
