### ISSUE TITLE
Selenium2Driver maxInstances parameter

### ISSUE THREAD

**Issue by mi-haque** [Behat/Behat#1012]
while I tried to add maxInstances parameter in the desired capabilities option, I got this error:

[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                                     
  Unrecognized option "maxInstances" under "behat.extensions.behat_minkextension_extension.selenium2.capabilities"  

So when I take a look into the source code I could see there is no maxInstances parameter defined inside the default properties of selenium2Driver class:

    /**
     * Returns the default capabilities
     *
     * @return array
     */
    public static function getDefaultCapabilities()
    {
        return array(
            'browserName'       => 'firefox',
            'version'           => '9',
            'platform'          => 'ANY',
            'browserVersion'    => '9',
            'browser'           => 'firefox',
            'name'              => 'Behat Test',
            'deviceOrientation' => 'portrait',
            'deviceType'        => 'tablet',
            'selenium-version'  => '2.31.0'
        );
    }

I wonder Why it so ??? or is there any work around for this if I want to execute my test cases on parallel firefox instances with selenium grid

**Comment by jakzal** [comment]
@mi-haque this should be reported to [MinkExtension](https://github.com/Behat/MinkExtension). As far as I remember each capability needs to be explicitly added to the config: https://github.com/Behat/MinkExtension/blob/master/src/Behat/MinkExtension/ServiceContainer/Driver/Selenium2Factory.php#L88

Can be closed here.

**Comment by mi-haque** [comment]
Moved to [ MinkExtension](https://github.com/Behat/MinkExtension/issues/277).
