### ISSUE TITLE
multiple paths arguments

### ISSUE THREAD

**Issue by mathroc** [Behat/Behat#1015]
I have an error when trying to run behat with multiple feature files:

> $ vendor/bin/behat 1.feature 2.feature
  [Symfony\Component\Console\Exception\RuntimeException]
  Too many arguments, expected arguments "paths".
behat [-s|--suite SUITE] [-f|--format FORMAT] [-o|--out OUT] [--format-settings FORMAT-SETTINGS] [--init] [--lang LANG] [--name NAME] [--tags TAGS] [--role ROLE] [--story-syntax] [-d|--definitions DEFINITIONS] [--snippets-for [SNIPPETS-FOR]] [--snippets-type SNIPPETS-TYPE] [--append-snippets] [--no-snippets] [--strict] [--order ORDER] [--rerun] [--stop-on-failure] [--dry-run] [--] [<paths>]

did I misunderstood the ` [<paths>]` part ?

ps: I also tried `vendor/bin/behat -- 1.feature 2.feature` ⇒ same results

**Comment by Taluu** [comment]
Looks like this isn't expecting an array (https://github.com/Behat/Behat/blob/master/src/Behat/Testwork/Tester/Cli/ExerciseController.php#L94)

**Comment by avant1** [comment]
There is a PR that adds this functionality to Behat: #996
For now only one feature file can be passed.

**Comment by mathroc** [comment]
indeed, I didn't searched PRs for this. too bad it's a BC for extensions :(

should it be renamed `path` until it supports multiple paths ? (maybe this is a BC too)

**Comment by mathroc** [comment]
indeed, I didn't searched PRs for this. too bad it's a BC for extensions :(

should it be renamed `path` until it supports multiple paths ? (but this is probably a BC too for extensions)

**Comment by everzet** [comment]
In the meantime you can probably use a shortcut with a temporary `*.scenarios` file:

```
your_first.feature:lineno
your_second.feature:lineno
```

**Comment by ewbarnard** [comment]
For searchers who find this issue late to the party: I get this error message when I accidentally use single hyphen rather than double hyphen (e.g., -snippets-for rather than the correct --snippets-for) in the runner options. Once I fixed the argument syntax all proceeded correctly; the error message disappeared.
