### ISSUE TITLE
Features cached makes it difficult to fix and test again

### ISSUE THREAD

**Issue by nathanh0** [Behat/Behat#1019]
Being my first time using Behat, I have been tasked to learn everything within a few days. I looked for this issue on google, but maybe I was searching the wrong terms.

Since I am doing a lot of MinkContext, the feature issues are not always related to basic Behat syntax. This means I am having to edit frequently the feature file to update CSS selectors and other requirements to reach 100% pass on all steps.

### Issue

When editing an already existing feature, there seems to be some kind of `cache` preventing my changed file from being picked up by behat. Only significant changes will cause the file to be reread by Behat.

Is this a Behat thing, or something going on with our linux distro? If there's a setting to tweak this somewhere, what file do I need to look in or update to get Behat to stop caching our files. We only have a few scenarios at this time, so we don't need caching for 3 feature files that are less than 20 lines each.

### Steps to reproduce

 1. Create a `test.feature` file containing a scenario that will have a step which fails.
 2. Run behat to see your error.
 3. Edit your `test.feature` file and then save your changes to fix the issue.
 4. Run behat again.
 5. If your change was small (fixing a word, etc) you will see the same error (as if you did not update your file).

### Expected

 - Behat should reread the feature, especially if failures occurred.

### Workarounds

 - Adding 10 blank lines between two steps causes the file to be reread in Behat.
 - Change the name of the file/feature name.
 - Have not tried "deleting" the file and remaking it, would assume this would not make a difference.

Hopefully this is a "dumb" post I am doing and someone can tell me what to do to keep productivity up and get around this issue.

Thank you for Behat!

**Comment by Taluu** [comment]
Hello,

I don't seem to have the problem. I think this is OS related, not Behat...

**Comment by everzet** [comment]
You can disable cache via config:

```
default:
  gherkin:
    cache: ~
```
