### ISSUE TITLE
Running code after @AfterSuite

### ISSUE THREAD

**Issue by rask** [Behat/Behat#1021]
I'm attempting a following setup:

1. User install Chrome and ChromeDriver into their `$PATH`
2. User clones my project with Behat in it and configures a few things
3. User runs Behat tests
4. Behat `@BeforeSuite` starts up ChromeDriver
5. Behat uses the Selenium2 driver against ChromeDriver
6. Tests run
7. After all tests have run, Behat `@AfterSuite` kills the running ChromeDriver process

The problem I'm having with `@AfterSuite` is that the Selenium driver tries to close the current driver session _after_ `@AfterSuite` is run it seems.

Is there any way to run code after all drivers have closed their sessions or am I supposed to do this some other way? I'd rather not implement any sleeping or some such.

Let me know if this issue should be created in some other project issue tracker (e.g. Mink, Selenium, etc.).

**Comment by Taluu** [comment]
Hey,

I think the `@AfterSuite` is not gonna cut it because of priorities I guess. I don't know how the Selenium driver is built, but I guess that the priority of this one is lower than `@AfterSuite`.

Your solution would be that rather than using `@AfterSuite`, you should use the real event with the right priority.

**Comment by rask** [comment]
I'll need to read up on the events and listeners.

I decided to go with a timeout of a few seconds to fire the ChromeDriver kill command. Works for now but I'm worried it might break from time to time.

**Comment by everzet** [comment]
Keep in mind that `*Suite` hooks are called only once.
