### ISSUE TITLE
[question] unparsed text in scenario

### ISSUE THREAD

**Issue by mathroc** [Behat/Behat#1022]
I'm not sure this is a bug or intended, right now, if a line in a scenario does not begin with a keyword (given, then, when or and) it's outputted without throwing an error. I understand this is similar to how a feature is described but wonder if it supposed to be allowed, exemple:

```gherkin
Feature: Some terse yet descriptive text of what is desired
  Textual description of the business value of this feature
  Business rules that govern the scope of the feature
  Any additional information that will make the feature easier to understand

  Scenario: Some determinable business situation
    # the next keyword has a type
    Give some precondition
      And some other precondition
    When some action by the actor
      And some other action
      And yet another action
    Then some testable outcome is achieved
      And something else we can check happens too
```

when running this, the "step" `Give some precondition` would be ignored and not really noticeable (except with colored output)

I was expecting to get an error, what do you think ?

**Comment by everzet** [comment]
This is because scenario titles are allowed to span multiple lines:

```
Scenario: This title
  spans multiple lines
  before the actual steps start
  Given ...
  When ...
  Then ...
```
