### ISSUE TITLE
Skip more than one tag by command line

### ISSUE THREAD

**Issue by mjaeggi** [Behat/Behat#1023]
I have a feature file with 3 scenarios:
```
scenario: Scenario 1

@manual
scenario: Scenario 2

@wip 
scenario: Scenario 3
```
The thing is that when I run Behat with `--tags=~manual&&~wip` the third scenario is executed and if I run with `--tags=~wip&&~manual` the second scenario is executed. 

How can I skip both tags in a single run?

**Comment by NeverResponse** [comment]
Have You tried quoting the tags? etc `--tags="~wip&&~manual"`

**Comment by mjaeggi** [comment]
Yes, I already tried that way with the same result

**Comment by spolischook** [comment]
You can try discover FilterController to find the bug

**Comment by everzet** [comment]
Use `,` instead of `&&`. `&&` means literally "both sides should be present", `,` means "either side" or simply `or`.

So:

```
--tags=~manual,~wip
```
