### ISSUE TITLE
Scenario outline with <parameters> from Examples section in title.

### ISSUE THREAD

**Issue by unekhriukova** [Behat/Behat#1024]
Hello, guys.
 I've found a possibility of using the <parameters> from Examples section in the Scenario Outline title in the Cucumber: https://github.com/cucumber/cucumber-js/issues/267
I've tried to use this in behat, but it does not work for me. 
In PhpStorm when I use this parameter in title, it is highlighted and 'go to source' command moves the cursor to the same name column in Examples section. 
When tests are run, I see the parameter is not substituted to its value, just stayed as it is, 
e.g.  

Scenario Outline: Login with &lt;email&gt;.

Seems like this feature is not implemented yet in behat, may be it will be a good idea to do it.

**Comment by spolischook** [comment]
Is it just for title customizing or it also will be a step implementation?

**Comment by unekhriukova** [comment]
As a step implementation this feature is already exist. So just for title customizing.

**Comment by bwowk** [comment]
Well, I can't see how the `Scenario Outline: Login with <email>.` would have it's token replaced. From which Example line would it get its replacement?

For the pretty formatter the ExampleNode titles are not even printed, only the OutlineNode title.

On the other hand, I believe it makes sense in case any other formatter uses the ExampleNode title.

Anyway, this would be done on the Gherkin package (https://github.com/Behat/Gherkin/blob/master/src/Behat/Gherkin/Node/OutlineNode.php#L207), not on Behat core.
You should close this issue and open another one on https://github.com/Behat/Gherkin

**Comment by bwowk** [comment]
`For the pretty formatter the ExampleNode titles are not even printed, only the OutlineNode title.`
Correction: ExampleNode titles are printed, and they're the corresponding line on the examples table

**Comment by everzet** [comment]
@bwowk once again - thanks for nudging in :)
