### ISSUE TITLE
Testing login session with Behat

### ISSUE THREAD

**Issue by wout** [Behat/Behat#1025]
I am testing an XML and JSON REST API with Behat. For authentication, I use Sentinel. Now, if I log in a user through Behat, and I test the status of the login session, the API returns a negative response (e.g. user not logged in). When I do the exact same thing manually in a browser using AJAX requests, everything works fine. So the end result is fine but the scenario fails. Any suggestions on how to overcome this issue?

**Comment by Taluu** [comment]
Do you save the token somewhere ? What are your context, which extension ?

**Comment by wout** [comment]
Sentinel takes care of maintaining the login session.

Aside from the regular context setup nothing special going on there. I just build up a request url using a series of steps, one step to log in the user with the correct credentials and one step to test the status of the login session.

Furthermore, I am not using any specific extensions.

**Comment by wout** [comment]
I included more info on the Stackoverflow issue:
http://stackoverflow.com/questions/43479251/testing-login-session-with-behat

**Comment by everzet** [comment]
As this seems to be usage question in relation to interconnection of different tech, StackOverflow is a better place for it.
