### ISSUE TITLE
How to show failed steps during test when progress format is sepcified

### ISSUE THREAD

**Issue by alexdesignworks** [Behat/Behat#1026]
When specifying `--format=progress`, the output is in TAP format and failed steps are marked as `F`. All the fail steps are listed at the very end of the run, rather then in-place right after the fail ocures.

I was wondering if there is a flag to show failed steps right after when they occur without stopping the rest of the steps.

Something like this:
```
......F
 Failed step: And I visit homepage
......
```

**Comment by Taluu** [comment]
Nope there isn't. But you could make a listener that breaks the output buffering and echo something. But then you would have the failed message twice.

**Comment by alexdesignworks** [comment]
Ok, so I've made this https://github.com/integratedexperts/behat-format-progress-fail
with an output like this:
```
..
      --- FAIL ---
      --- (features/apples.feature):6
      Background:
            Then I should have 3 apples
      ......U.......
      --- FAIL ---
      --- (features/apples.feature):6
```
