### ISSUE TITLE
Manually run behat scenarios without test framework?

### ISSUE THREAD

**Issue by albus-optimus** [Behat/Behat#1029]
Hello. I need to execute gherkin scenarios from DB/dynamically generated without test framework.
Help me please setup Behat for this. My version:

```
#!/usr/bin/env php
<?php
if (is_file($autoload = getcwd() . '/vendor/autoload.php')) {
    require $autoload;
}

$keywords = include('vendor/behat/gherkin/i18n.php');
$keywords = new Behat\Gherkin\Keywords\ArrayKeywords($keywords);

$lexer  = new Behat\Gherkin\Lexer($keywords);
$parser = new Behat\Gherkin\Parser($lexer);

$scenario = getScenario('magic');
$feature = $parser->parse($scenario);


$RuntimeStepTester = new \Behat\Behat\Tester\Runtime\RuntimeStepTester(new \Behat\Behat\Definition\DefinitionFinder(), new \Behat\Testwork\Call\CallCenter());
$GenericSuiteGenerator = new \Behat\Testwork\Suite\Generator\GenericSuiteGenerator(['paths' => ['features'], 'contexts' => ['FeatureContext']]);
$env = new \Behat\Behat\Context\Environment\InitializedContextEnvironment($GenericSuiteGenerator->generateSuite('default', []));

include('features/bootstrap/FeatureContext.php');
$context = new FeatureContext();
$env->registerContext($context);


echo $feature->getTitle() . "\n";
echo $feature->getDescription() . "\n";

foreach($feature->getScenarios() as $scenario) {
    echo $scenario->getTitle() . "\n";

    $skip = false;
    foreach($scenario->getSteps() as $step) {
        echo $step->getText() . "\n";

        $setup = $RuntimeStepTester->setUp($env, $feature, $step, $skip);
        $skipSetup = !$setup->isSuccessful() || $skip;

        $testResult = $RuntimeStepTester->test($env, $feature, $step, $skipSetup);
        $skip = !$testResult->isPassed() || $skip;

        $teardown = $RuntimeStepTester->tearDown($env, $feature, $step, $skipSetup, $testResult);
        $skip = $skip || $skipSetup || !$teardown->isSuccessful();
    }
}
```

But this don't execute steps because don't initialized SearchEngine which requires the initialization of many dependencies. Initiate them with a hardcore is a terrible idea.

Is there a way to initialize all a few lines? Or example of such use?

**Comment by everzet** [comment]
Can you give more context on the use-case you're trying to address?

**Comment by stof** [comment]
Your code is missing lots of features from Behat (scenario execution is not properly isolated for instance).
I strongly suggest you to avoid executed scenarios like this, as you would have to reimplement most features of Behat (as you use only of the the very low level feature).

IMO, it would be much better to write a Behat extension registering a custom loader for scenarios (looking into your DB) and then using Behat itself to run it. It would avoid reimplementing Behat itself

**Comment by albus-optimus** [comment]
Hello! I very easily solved my problem with Codeception. It has 146% support of behat scenarios and provides many useful tools.

**Comment by everzet** [comment]
Cool. Closing this then.
