### ISSUE TITLE
Behat Laravel DB

### ISSUE THREAD

**Issue by SamyOteroGlez** [Behat/Behat#1030]
Hi guys. Not sure if this is the best place to ask but, at least it is the Behat place.

I've been having issues with behat and laravel working together.
I configured Behat with Laravel. I have this simple scenario:

```
Scenario: Login as an admin
    Given I add an admin to the db
    When I login as an admin
    Then I should be in the welcome page
```
In the FeatureContext Class I add the admin user to the db using factories.

Everything works fine if I don't use the browser. But, when I start the selenium server and I add the @javascript tag to the Scenario, the test run fine, the browser start fine, but the login process fails because there is no users in the db. Yes the same user with the same credentials that I just added in the first step. But if I check by querying the db before executing the login the user is there.

BTW, I only have defined one connection, I triple-checked that.

So, what is happening here? Any ideas?

Thanks.

Samy

**Comment by spolischook** [comment]
Double check application url in the browser address field

**Comment by SamyOteroGlez** [comment]
The url seems to be the correct one

Thanks

**Comment by SamyOteroGlez** [comment]
I know that could be related with the Laravel environments, if you run the tests in under the test environment previously defined and you access to the app through the browser, the app will not be running under the test environment. 

To avoid that problem I just defined a unique environment for everything (at least until solve this issue, this will change in the future) and also I have only one db, no test databases.

Thanks.

**Comment by SamyOteroGlez** [comment]
I think I solved the issue.

For some reason DB::beginTransaction() and DB::rollback() does not work properly with Behat.

Here is my solution

```
/**
     * @javascript
     * @BeforeFeature
     */
    public static function before(BeforeFeatureScope $scope)
    {
        putenv('APP_ENV=local');

        $tableNames = Schema::getConnection()->getDoctrineSchemaManager()->listTableNames();
        
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');

        foreach ($tableNames as $name) {
            //if you don't want to truncate migrations
            if ($name == 'migrations') {
                continue;
            }
            DB::table($name)->delete();
        }
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');

        Artisan::call('migrate');
        
        try {
            Artisan::call('db:seed');
        } catch (Exception $e) {
            dump('seeder failed');
        }
    }


/**
     * @javascript
     * @AfterFeature
     */
    public static function after(AfterFeatureScope $scope)
    {
        putenv('APP_ENV=local');
        Artisan::call('migrate:rollback');
        
        $tableNames = Schema::getConnection()->getDoctrineSchemaManager()->listTableNames();
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        
        foreach ($tableNames as $name) {
            //if you don't want to truncate migrations
            if ($name == 'migrations') {
                continue;
            }
            DB::table($name)->delete();
            //Schema::dropIfExists($name);
        }
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    }
```

**Comment by stof** [comment]
if you use selenium, the page processing will not happen in the same process than the Behat code (as selenium will hit your webserver). So it won't be doing its DB calls inside the transaction you start in the Behat process.

**Comment by SamyOteroGlez** [comment]
Thanks @stof.

So here what could be the best approach for my tests? I want some test running without selenium and others with selenium.

Many thanks.

**Comment by stof** [comment]
Well, for tests using seleniums, the approach you need is the one you gave just above (resetting the DB for real)

**Comment by SamyOteroGlez** [comment]
Thanks!

Cheers.
