### ISSUE TITLE
Create Step definitions for common steps 

### ISSUE THREAD

**Issue by imakhil** [Behat/Behat#1032]
i want to reduce no. of step in a test case by creating a step definitions for the bunch of test cases repeated in scenarios so that instead of writing all the steps again just write the step definition and all the test cases will be executed under it

**Comment by stof** [comment]
I don't understand what you mean. Can you give more details ?

**Comment by spolischook** [comment]
I think he means chained steps, @imakhil see https://github.com/Behat/Behat/issues/546
