### ISSUE TITLE
Coding standards for extension?

### ISSUE THREAD

**Issue by alexdesignworks** [Behat/Behat#1033]
Could someone please provide information about which coding standards are used for Behat extensions. `Symfony`? `PSR1` & `PSR2`?

**Comment by ciaranmcnulty** [comment]
Extensions are by definition someone else's project so they can use whatever coding standards they want

**Comment by alexdesignworks** [comment]
@ciaranmcnulty 
Do you know which coding standard is used for Behat project?

**Comment by ciaranmcnulty** [comment]
There are are some custom rules in scrutiniser config
