### ISSUE TITLE
failed to open stream: Resource temporarily unavailable

### ISSUE THREAD

**Issue by sergioatzori** [Behat/Behat#1034]
Hi, I'm experiencing a really weird issue while running my behat tests. In a total random fashion behat stops running and throws:
```
[Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                                    
  Warning: file_put_contents(/path/to/app/var/cache/api-backoffice/bdd/appBddDebugProjectContainerCompiler.log): failed to open stream: Resource temporarily unavailable
```
I'm using behat 3.3, I can't figure out what's happening.
Thank you

**Comment by everzet** [comment]
This seems to have nothing to do with Behat and has much to do with your Symfony environment configuration. Behat doesn't use neither `Symfony\Component\Debug` nor container cache.

**Comment by ciaranmcnulty** [comment]
@everzet FYI Symfony console 3.2.8 is wrapping Errors in DebugException (fixed already in master) so this a generic PHP fatal, in case you get similar reports

Definitely seems like the issue is the symfony cache not writeable so not Behat related

**Comment by sergioatzori** [comment]
OK thank you.
I found no issue outside Symfony environment and I'm experiencing this only running behat tests.
Should I post an issue on Symfony's github?
