### ISSUE TITLE
PHP 5.3 Short Array Syntax In MixedArgumentOrganiser.php

### ISSUE THREAD

**Issue by alexfinnarn** [Behat/Behat#1035]
I see that you changed some code to use short array syntax and then set that back in commits like https://github.com/Behat/Behat/commit/a02da149a4a4bcf2de279429e762b110b6b21cee. 

I just ran into a case where https://github.com/Behat/Behat/blob/d7cc1409e17824d3041fab6cd89bb623f5d9caf8/src/Behat/Testwork/Argument/MixedArgumentOrganiser.php#L239 ended up causing a test run to error. 

If you are in the mood to revert back to PHP 5.3 syntax there, then go nuts. Otherwise, you can ignore or close this issue.

**Comment by everzet** [comment]
Missed this one :/
