### ISSUE TITLE
Getting an error while running behat case on any browser(firefox, chrome)

### ISSUE THREAD

**Issue by achandna** [Behat/Behat#1037]
Could not open connection: Notice: Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT_FOLLOWLOCATION' in vendor/instaclick/php-webdriver/lib/WebDriver/WebDriver.php line 76 (Behat\Mink\Exception\DriverException)

Webdriver version: 2.53, 2.53.1
chromedriver browser version: 2.29, 2.27
firefox: 46,49

**Comment by bwowk** [comment]
Hey @achandna.
That issue is related to the Mink Selenium Driver, I'm guessing. You should close this one and open another on https://github.com/minkphp/MinkSelenium2Driver instead :)

**Comment by everzet** [comment]
@bwowk thanks for helping people out! This matters a lot for community and helps contributors greatly.
