### ISSUE TITLE
`Tests\FeatureContext` context class not found and can not be used.

### ISSUE THREAD

**Issue by sakonachhoeurng** [Behat/Behat#1038]
I also looked at to close issue and follow what answer are, but I still have problem the same.
My code structure
![image](https://cloud.githubusercontent.com/assets/12217854/26347933/5277de90-3fd5-11e7-9ede-c17ca9ef443f.png)
In my `Behat.yml` that I take `namespace` to put as code below
```
 - TYPO3\Blog\Tests\Behaviour\Features\Bootstrap\FeatureContext
 - TYPO3\Blog\Tests\Behaviour\Features\Bootstrap\FeatureAPIContext
```
My `autoload`
```
 "autoload": {
        "psr-4": {
            "TYPO3\\Blog\\Tests\\Behaviour\\Features\\Bootstrap\\": "Tests/Behaviour/Features/Bootstrap"
        }
    },
```

I do not have any idea to do that I try to search and follow the same as https://github.com/Behat/Behat/issues/557
please help for this issue.

**Comment by j1v3** [comment]
Are you sure you don't have a typo on the name of "Bootstrap" directory ?

In my case solved this issue symply by replacing a capital letter with the name of my file... 

Now my directories structure is like this:

`-> features` 
 `--> context`  
 `---> Authorization` 

my autoload like this  
>"autoload": { 
--"psr-4": {  
---"": "src/",  
---"AppBundle\\Tests\\Behat\\Context\\": "features/context/"  
--}  
-}

for running my class like this on `behat.yml`:
`                - AppBundle\Tests\Behat\Context\Authorization\IntegrationLoginContext: []`

I don't know if this is the best solution ... but it works for me!
