### ISSUE TITLE
Exit code with no scenarios, no steps

### ISSUE THREAD

**Issue by Ocramius** [Behat/Behat#1039]
Given the following output:

```
vendor/bin/behat 
No scenarios
No steps
0m0.01s (3.78Mb)
```

Considering https://github.com/Behat/Behat/issues/867 and https://github.com/Behat/Behat/issues/221

Should the exit code of the behat binary still be `0`? A failure seems more obvious to me here.

**Comment by pamil** [comment]
It's the behaviour when run with `--strict` flag.

**Comment by spolischook** [comment]
@Ocramius as we talking with you today, this issue was resolved and can be closed.
