### ISSUE TITLE
AfterScenario, Steps and Arguments

### ISSUE THREAD

**Issue by Pryrios** [Behat/Behat#1041]
Hi,

I am a Drupaler trying to do some cleanup after a particular scenario. I have created an AfterScenario function on my FeatureContext.php like this:
```

    /**
     * @AfterScenario @database
     */
    public function cleanDatabase(AfterScenarioScope $scope)
    {
        $scenario = $scope->getScenario();
        $steps = $scenario->getSteps();

        foreach ($steps as $key => $step) {
            if ($step->hasArguments()) {
                $arguments = $step->getArguments();
            }
        }
    }
```
My thought was that if I have a step like:

`And I fill in "SFID" with "36541287"`

Then I would get "SFID" and "36541287" as argument values and "getArguments()" would return them to me. Then I can use them to do the cleanup in my Drupal.

The issue is that it seems I don't have any arguments on any step. All steps return me FALSE on hasArguments() and if I var_dump each step, it basically shows that there are no arguments.

Maybe I am not understanding what arguments are or either there's something wrong on my behat. ¿Can someone throw some light here, please? Or suggest how I could achieve what I wanted in any other way (if possible at all)?

Thank you!

PD:
pryrios@localhost:$ ../vendor/bin/behat --version
behat version 3.1.0

**Comment by spolischook** [comment]
>> Then I can use them to do the cleanup in my Drupal.

I don't believe that your approach  will work  

I suggest to create db dump before suite and restore database from dump after each scenario.
For better performance use ramfs for your db.

**Comment by Pryrios** [comment]
Thank you, I will try that, seems a cleaner approach.

**Comment by oabdelsamad** [comment]
Close #1061
