### ISSUE TITLE
Behat DI broken with symfony 3.3 ?

### ISSUE THREAD

**Issue by Stoakes** [Behat/Behat#1045]
Hello,

I just updated my project to Symfony 3.3 and my tests are not working anymore (while everything was ok yesterday). It seems to be like a dependency injection error.

Here is the error and my [behat.yml](https://gist.github.com/Stoakes/8478f1ceee891777d1899d8a8965a39f) file

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function FeatureContext::__construct(), 0 passed and exactly 2 expected in /app/features/bootstrap/FeatureContext.php:58
Stack trace:
#0 [internal function]: FeatureContext->__construct()
#1 /app/vendor/behat/behat/src/Behat/Behat/Context/ContextFactory.php(123): ReflectionClass->newInstance()
#2 /app/vendor/behat/behat/src/Behat/Behat/Context/ContextFactory.php(80): Behat\Behat\Context\ContextFactory->createInstance(Object(ReflectionClass), Array)
#3 /app/vendor/behat/behat/src/Behat/Behat/Context/Environment/Handler/ContextEnvironmentHandler.php(104): Behat\Behat\Context\ContextFactory->createContext('FeatureContext', Array)
#4 /app/vendor/behat/behat/src/Behat/Testwork/Environment/EnvironmentManager.php(93): Behat\Behat\Context\Environment\Handler\ContextEnvironmentHandler->isolateEnvironment(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\ScenarioNode))
#5 /app/vendor/behat/behat/src/Behat/Behat/Tester/Run in /app/features/bootstrap/FeatureContext.php on line 58
```

FYI here is the [composer trace](https://gist.github.com/Stoakes/8478f1ceee891777d1899d8a8965a39f#file-composer-update-txt) of my update and my new [composer.lock](https://gist.github.com/Stoakes/8478f1ceee891777d1899d8a8965a39f#file-composer-lock) file.

Have you got any idea ?

Thanks

**Comment by glennunipro** [comment]
I have updated my Symfony to 3.3, seems to work...

Your Behat version has also updated from `3.3.0` to `3.3.1` which includes a change to the way dependency injection works for typehinted parameters (although you're using named parameters which should not have affected it, but there is a chance).

Try reverting Behat back to 3.3.0 and see if that resolves it.

Also, it could be that your `behat.yml` does not have a parent `default` key. Is it a typo, or do you really mean to have `indefault` as the parent key?

https://gist.github.com/Stoakes/8478f1ceee891777d1899d8a8965a39f#file-behat-yml-L1

**Comment by Stoakes** [comment]
So focused on sf 3.3 that I didn't check my behat.yml file. My bad.

Thanks.

**Comment by FinauKaufusi** [comment]
Would be good to share how you fix your behat.yml file.
