### ISSUE TITLE
Behat logo image broken on README.md

### ISSUE THREAD

**Issue by bwowk** [Behat/Behat#1047]
This image, used on the README.md, is broken:
![broken img](https://camo.githubusercontent.com/d8d967f1ba57d0f7857152ff0c3ca6503deb48f4/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f3238323739372f62656861742f62656861742e706e67)

**Comment by everzet** [comment]
fixed
