### ISSUE TITLE
[Problem] PHP Notice/Error Handling

### ISSUE THREAD

**Issue by awaisabir** [Behat/Behat#1050]
Hi,
I am writing a Slack Integration to notify on failed Behat tests for my workplace, and I am running into a certain problem. I am currently using the `AfterStep` Hook to check if the Step in a Scenario fails, and if so, execute the following code:
```
$exception = $scope->getTestResult()->getException();

// Get the position of 'Stack'
$stackOccurence = strpos($exception, 'Stack');

// Parse the exception right before 'Stack'
$specificError = substr($exception, 0, $stackOccurence);

// Get the feature
$featureContext = $scope->getFeature()->getDescription();
```

However, the issue I am having, is the fact that if there is a PHP Error/Notice the ```getException()``` does not seem to catch it. But for any other error it seems to be working fine. In another part of the codebase I am sending a screenshot over as well, but it doesn't seem to send when I have a Error/Notice as well.Would anyone know why exactly this is? If you require more context, I am happy to elaborate a bit further!

Thanks in advance!

**Comment by everzet** [comment]
Can you provide us with simple steps to reproduce a situation when exception isn't caught?
