### ISSUE TITLE
Skip step

### ISSUE THREAD

**Issue by spolischook** [Behat/Behat#1051]
I whould like to skip some steps in some condition.
I can't do it from ```BeforeStepTested``` event
All that I found, that I can replace [RuntimeStepTester](https://github.com/Behat/Behat/blob/3f5c2060d394de31b4842858f2b10b39c8fb335d/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php) and return FailedSetup but I guess my step will be failed, but I need just skip it.

**Comment by avant1** [comment]
You can skip full step execution inside step definition:

```php
    /**
     * @Given the sky is blue
     */
    public function theSkyIsBlue()
    {
        if (!$this->planet->canSkyColorBeChanged()) {
            return;
        }

        //perform sky color change
    }

```

**Comment by spolischook** [comment]
@avant1 Yep, but I need to do it in some hook or listener, without changes the conde of my/other contexts

**Comment by avant1** [comment]
Can you describe your use case? Maybe something similar can be achieved in a simplier way.

**Comment by spolischook** [comment]
I have some bad thing in my Extension - scenario coupling.
I some of the step in current feature was failed I should skip all other steps, even in other scenarios.

**Comment by bwowk** [comment]
I can't really picture why you would need a condition like that :astonished:
Anyway, you can check for that condition on a `@BeforeFeature` hook, and throw an exception in case it's not fulfilled. Then all the scenarios will be skipped:
```php
/**
 * @BeforeFeature @skip_if_foo
 */
public static function assertNotFoo() {
    if (foo) {
        throw new Exception("Foo!");
    }
}
```

The `@skip_if_foo` tag is optional, if you want to run that check only on the Features tagged like that.

**Comment by spolischook** [comment]
@bwowk I don't want to skip all feature, but skip all steps in feature after failed steps, even steps from other scenarios

**Comment by bwowk** [comment]
Do the same as above on a `@BeforeScenario`, but checking for a static `foo` var on your context, then create a `@AfterStep` hook that uses an `AfterStepScope` to check if the step is the one you wanna check and if it failed, and sets `foo` if it did.

And please explain your use case better when opening an issue.
