### ISSUE TITLE
Maybe --snippets-for=cli to default to outputting snippets for generation in terminal?

### ISSUE THREAD

**Issue by WillGibson** [Behat/Behat#1057]
I would prefer the snippets to just come out in full in my terminal without the need to hit enter.

I've tried a few ways to get there, but --no-interaction seems to kill off snippet generation.

Is there already a way to achieve what I'm trying to do?

Or would something like `--snippets-for=cli` be useful?

**Comment by bwowk** [comment]
There's already a `--snippets-for` option. You just need to pass it the Feature you want snippets generated for as an argument like so: `behat --snippets-for FeatureContext `

**Comment by WillGibson** [comment]
I get that, but I just want them to come out in terminal without me being offered choices of having to hit enter.

**Comment by everzet** [comment]
@WillGibson you can disable interaction with `--no-interaction` flag. But Behat needs you to tell it which context to generate snippets for with `--snippets-for=...`, so if you want snippets generated non-interactive you need to use the flag.

**Comment by WillGibson** [comment]
@everzet That doesn't actually provide the behaviour I would prefer, which is simply that I would like the snippets to come out in the CLI without needing to hit enter, like it used to do in the old days by default.

This is because we organise our contexts in a way that means that generally when it outputs a load of generated steps, we often want to distribute them around a few contexts, so it's easier just to copy and paste.

I might look at submitting a PR for this if I get some quiet time.

**Comment by everzet** [comment]
@WillGibson Behat never generated snippets silently without you telling it which context to generate it for. This is because Behat tries really hard to avoid name collisions in the context method names. It's just before you had `implements SnippetAcceptingContext` on some of your contexts and now you have `--snippets-for`.

**Comment by WillGibson** [comment]
@everzet I'm not sure we're talking about the same thing, let me see if I can  explain better with an example.

I know it's not really a big deal, but I would like to be able to tell Behat to just spit the generated snippets out in the CLI, like it does when you hit enter. E.g.

```
behat src/something.feature --snippets-for=cli
Feature: Something

  Scenario: Do a thing
    Given I have done one thing
    When I do a second thing
    Then I should see a third thing

1 scenario (1 undefined)
3 steps (3 undefined)
0m2.00s (17.74Mb)

 >> default suite has undefined steps. Define them with these snippets:

    /**
     * @Given I have done one thing
     */
    public function iHaveDoneOneThing()
    {
        throw new PendingException();
    }

    /**
     * @When I do a second thing
     */
    public function iDoASecondThing()
    {
        throw new PendingException();
    }

    /**
     * @Then I should see a third thing
     */
    public function iShouldSeeAThirdThing()
    {
        throw new PendingException();
    }
```
