### ISSUE TITLE
Soft Assert 

### ISSUE THREAD

**Issue by oabdelsamad2** [Behat/Behat#1061]
Hi all, 

I was wondering if there is a way to have a soft assert method just like the one used in JAVA. It would be really cool if we have such a feature.

Thank you!

**Comment by bwowk** [comment]
Is #1049 what you mean?

**Comment by oabdelsamad** [comment]
@bwowk This is exactly what I want. Thank you so!

**Comment by jakzal** [comment]
@oabdelsamad since this is a duplicate can you close please?

**Comment by oabdelsamad** [comment]
Close 1061
