### ISSUE TITLE
Is there any extension for Behat to test and validate content from RSS feeds?

### ISSUE THREAD

**Issue by sswarupa2017** [Behat/Behat#1063]
I am new to Behat and need to write some tests to validate RSS feed content in current sprint. Wanted to see if there are any extensions/examples that I can reuse. Pl. let me know ASAP if you have any idea. I have looked online and know how to convert from RSS to xml using simplexml_load_file($url) parser. Not sure how I can access the html and then write my our step defs. Thank you!!

**Comment by LoopKarma** [comment]
I guess you can use [MinkContext](https://github.com/Behat/MinkExtension/blob/master/src/Behat/MinkExtension/Context/MinkContext.php) from [MinkExtension](https://github.com/Behat/MinkExtension) for behat
