### ISSUE TITLE
Using strict flag with rerun doesn't prevent the undefined steps from passing

### ISSUE THREAD

**Issue by relte** [Behat/Behat#1065]
Given I have an undefined step and run:
```
bin/behat --tags="my_feature" --colors --format=progress -n --strict
```
- if all is passing besides the undefined step, the execution doesn't pass (exit code 1), then I run the command with `--rerun`:
```
bin/behat --tags="my_feature" --colors --format=progress -n --strict --rerun
```
which produces the same output, so in this case `--strict` does work
- if some test fails, the execution of course doesn't pass (exit code 1), but running `--rerun` makes it pass (it ignores the undefined step)

Here is what I use if it makes any difference:
```
"require-dev": {
        "behat/behat": "^3.2",
        "behat/mink": "^1.7",
        "behat/mink-browserkit-driver": "^1.3",
        "behat/mink-extension": "^2.2",
        "behat/mink-selenium2-driver": "^1.3",
        "friends-of-behat/context-service-extension": "^0.3",
        "friends-of-behat/cross-container-extension": "^0.3.0",
        "friends-of-behat/performance-extension": "^1.0",
        "friends-of-behat/service-container-extension": "^0.3",
        "friends-of-behat/suite-settings-extension": "^1.0",
        "friends-of-behat/symfony-extension": "^0.2.1",
        "friends-of-behat/variadic-extension": "^0.1",
        //...
},
```

**Comment by jon-acker** [comment]
It seems to be that this is expected behaviour.

If I understand correctly this would require a  feature with at least two scenarios: the first contains a failure and the second has an undefined step.

Using the --rerun switch, *only* the scenario that failed is run, and if it gets fixed and now passes, the result is success (exit code 0), because that single scenario passes.

**Comment by ciaranmcnulty** [comment]
This is still counter-intuitive behaviour
