### ISSUE TITLE
Behat with limit running scenarios

### ISSUE THREAD

**Issue by lasotaartur** [Behat/Behat#1066]
It will be nice add limit (from, to) running scenarios while running tests.

**Comment by stof** [comment]
I don't understand what you mean

**Comment by lasotaartur** [comment]
`bin/behat --limit 10` means run max 10 scenarios.
It will be helpful for creating separate jobs in CI.

**Comment by nifr** [comment]
@lasotaartur You can work around this using [tags](http://behat.readthedocs.io/en/latest/user_guide/configuration/suites.html#suite-filters). I implemented something similar for concurrent behat executions in our CI.

```
@feature-1
Feature: Verify billing

  @scenario-1
  Scenario: Missing product description
  @scenario-2
  Scenario: Several products
```

 Now execute ...

    bin/behat --tags "$(echo '@'feature-{1..2}'&&@scenario-'{1..4} | tr '[:blank:]' ',')" 

... which resolves to:

    bin/behat --tags @feature-1&&@scenario-1,@feature-1&&@scenario-2,@feature-1&&@scenario-3,@feature-2&&@scenario-1,@feature-2&&@scenario-2,@feature-2&&@scenario-3

**Comment by everzet** [comment]
Behat doesn't give execution order guarantees. With that, your suggestion doesn't work easily. I'd suggest looking into explicit segmentation strategies as nifr suggested.
