### ISSUE TITLE
phar files are not provided on github

### ISSUE THREAD

**Issue by drzraf** [Behat/Behat#1078]
phar bundles are a wonderful way to provide a software such as Behat.
Sadly, recent releases are still not available through GitHub downloads.

**Comment by jakzal** [comment]
Perhaps it was forgotten again.

As a workaround, you can create a phar file yourself:

First, fetch Behat sources:

```
git clone https://github.com/Behat/Behat.git
cd Behat/
composer install
```

Next, install the [box project](https://github.com/box-project/box2) and build the phar:

```
curl -LSs https://box-project.github.io/box2/installer.php | php
./box.phar build
```

**Comment by drzraf** [comment]
indeed (thank you for the tips).
but that would be ever better if such a phar file could be built and provided by @everzet on the official github releases page.

**Comment by ikappas** [comment]
@everzet Any update on this issue?

**Comment by everzet** [comment]
I tried to set up automatic build of phars on tags via Travis. It's notoriously hard to debug, so help welcome.

In the meantime, you can do it manually as @jakzal describes

**Comment by jakzal** [comment]
@everzet I could have a look one weekend.

**Comment by everzet** [comment]
@jakzal that would be awesome!

**Comment by jakzal** [comment]
@everzet looks like it's already set up as it should be. The only thing I can currently think of is that the github api key is invalid or not exported.

The following command is able to generate a new key and store it securely inside `.travis.yml`:

```
travis setup releases --force
```

It will reformat your `.travis.yml`, but you could use it to generate the key, copy it, revert `.travis.yml` to its current state and add the key back.

**Comment by everzet** [comment]
WIll try this noon

**Comment by GregJohnStewart** [comment]
Another bump to this issue, would love to play around with the framework, but hard to do with no phar :(

**Comment by Pierstoval** [comment]
Do you folks need help in providing phars in each new release?

**Comment by GregJohnStewart** [comment]
It would be nice.... currently using a severely outdated version of the suite because of this :(

**Comment by drzraf** [comment]
https://github.com/Behat/Behat/blob/master/.travis.yml#L40 seems ok.
https://github.com/Behat/Behat/blob/master/box.json seems ok.
https://travis-ci.org/Behat/Behat seems ok.
So I believe GitHub CI ("deploy" job) stopped working at some point.
AFAICT we have no public log from GitHub CI that would let us inspect further what goes wrong.

@everzet / @ciaranmcnulty any plan to solve this that's already 2 years without a phar/usable-release.

**Comment by jaapio** [comment]
Any change to get a fix for this issue soon? Or even a manually build phar & signed phar on the latest release?
If you are interessted I could provide you the setup we are working on in @phpdocumentor to automatically build an publish using github actions.

**Comment by drzraf** [comment]
ping?
https://github.com/Behat/Behat/pull/1259

**Comment by jrfnl** [comment]
Was just looking for the phar as well and running into this. Would be great if this could be sorted.

**Comment by ciaranmcnulty** [comment]
I believe this is now resolved (at least the last releases have PHAR)
