### ISSUE TITLE
Order of execution of feature scenarios

### ISSUE THREAD

**Issue by walterdolce** [Behat/Behat#1084]
Hi.

What's the order of execution of the scenarios in a feature? I'm using Behat `3.4.1` and it seems to be randomic when someone just runs `behat some_feature.feature`? 

I can see is definitely not done in alphabetical order (taking the scenario title as sorting source). I couldn't find anything that explains how this is done in the docs, but perhaps I missed something.

Thank you.

**Comment by jakzal** [comment]
I believe they're run in the order they're defined. Have a look at the `LazyFeatureIterator` and `Behat\Gherkin\Parser` classes.

Obviously, you shouldn't rely on the order of scenarios. This is most likely the reason why it's not documented.

**Comment by ciaranmcnulty** [comment]
Worth checking the `--order=random` CLI flag, or associated config key in Yaml, isn't being used

**Comment by ciaranmcnulty** [comment]
but yes it's otherwise meant to be the same sequence as the feature file

**Comment by walterdolce** [comment]
Oh. Never paid attention to the order parameter. Thanks Ciaran. That is most definitely useful.

This was more of a question rather than a bug report. I believe I got more insights than expected :)

Thanks both!
