### ISSUE TITLE
Feature request: Tags for steps?

### ISSUE THREAD

**Issue by Trogie** [Behat/Behat#1086]
Hello, 

I'm thinking about writing a jira ticket updating tool so that labels/fields in the tickets can be updated after feature/scenario/step run. The problem I face is that tags only appear on feature and scenario level, not on step level.

To test some tickets in Jira, I sometimes only add 1 step in a scenario and then add a comment at the end of the line with the ticketnumber.

Would adding a 'tag' functionality to steps not be interesting?

**Comment by stof** [comment]
I don't think the Gherkin language supports that (it supports tags per example for scenario outline, which we are missing, but I think this is the only place where we miss support for tags)

**Comment by Trogie** [comment]
Yes I know Gherkin doesnt have this but we could 'throw the first stone'?

**Comment by spolischook** [comment]
You can tag method of context instead of step itself.

**Comment by glennunipro** [comment]
Sounds handy for debugging purposes, but it is definitely more suited to being a Behat Extension rather than core Behat.

Tags are for organisational purposes, making it easy to run a feature or scenario -- it doesn't make sense to organise or run a single step imo.

**Comment by ciaranmcnulty** [comment]
To 'throw the first stone' I'd encourage you to start discussion with the cucumber/cucumber project
