### ISSUE TITLE
Can't add new outputs

### ISSUE THREAD

**Issue by spolischook** [Behat/Behat#1088]
The problem with the code:

```php
foreach ($outputs as $i => $out) {
    if ($this->isStandardOutput($out)) {
        continue;
    }

    $outputPath = $this->locateOutputPath($out);
    if (isset($formats[$i])) {
        $this->manager->setFormatterParameter($formats[$i], 'output_path', $outputPath);
        $this->manager->setFormatterParameter($formats[$i], 'output_decorate', $decorated);
    }
}
```

Commited by @everzet 4 years ago https://github.com/Behat/Behat/blame/269777f1477b132031f048aa45620aef787d8425/src/Behat/Testwork/Output/Cli/OutputController.php#L169-L180
Actually outputs could be two kind of things:
- StdOut
- File

In our case, we are need a DataBase as output.

**Comment by ciaranmcnulty** [comment]
I think this is ok, Formatters names imply string/stdout/file

Other reporting methods can be done in extensions
