### ISSUE TITLE
How do I create my own formatter?

### ISSUE THREAD

**Issue by aledeg** [Behat/Behat#1090]
I searched on-line and I couldn't find something really helpful.
Is there a documentation somewhere?

**Comment by spolischook** [comment]
Just investigate existing solution in Behat. Implementations of [FormatterFactory](https://github.com/Behat/Behat/blob/master/src/Behat/Testwork/Output/ServiceContainer/Formatter/FormatterFactory.php) is a good starting point.
Be aware that for now only two outputs is supported - file and stdout, see https://github.com/Behat/Behat/issues/1088

**Comment by alexdesignworks** [comment]
@aledeg check this out https://github.com/integratedexperts/behat-format-progress-fail

**Comment by aledeg** [comment]
Thanks guys. I'll have a look and try to make my own.
