### ISSUE TITLE
3.4.1 - Unable to access contexts from each other despite what the doc says

### ISSUE THREAD

**Issue by dianaarnos** [Behat/Behat#1092]
Hi there!
I need to access a context from another one and tried what is told here: [accessing contexts from each other](http://behat.org/en/latest/cookbooks/accessing_contexts_from_each_other.html)

The problem is that the `getEnvironment()` from `BeforeScenarioScope` does not have a `getContext()` method because it returns an `Environment` object.

Searching through the source code, I found out that the `getContext()` is found under `InitializedContextEnvironment` class but we can only get this object through `ContextEnvironmentHandler` class by calling the `isolateEnvironment()` method and I can't do that through any available hook.

So:
1 - the documentation needs to be updated
2 - is there any other way I can get the initialized context that I need or should I make a hook of my own?

{edit: I was unable to label this :disappointed:  }

**Comment by spolischook** [comment]
Did you try this solution in practice? It's working, but method is not highlighting by IDE because of interface.
Any way, it's working however is very dirty hack. It would be better to have meta context, like in behat 2 but it's not possible for now.

**Comment by dianaarnos** [comment]
@spolischook which solution, exactly? The one in the doc I tried and I only get an `Environment` object and was unable to get an initialized context in any way. So I can't use the `getContext()`

**Comment by spolischook** [comment]
It's working in our case, see -  https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/SecurityBundle/Tests/Behat/Context/ACLContext.php#L38-L42

**Comment by stof** [comment]
The environment returned by the getter in BeforeScenarioScope **is** an isolated one, as this hook runs after the isolation is performed.

**Comment by dianaarnos** [comment]
I'll try to reproduce this in the next days and come back here :)
