### ISSUE TITLE
@BeforeSuite and @BeforeFeature hooks ran before context __construct()

### ISSUE THREAD

**Issue by stevepetcu** [Behat/Behat#1094]
Hi,

I am new to Behat and I was messing around with some Contexts today.

I wanted to `__construct()` a context and pass in some parameters from my `behat.yml`, then do something with those parameters in a method that was to be run `@BeforeSuite`. 

I kept getting errors, because my constructor _wasn't being run_. Turns out, tagging a method with `@BeforeSuite`, or `@BeforeFeature` will cause it to be run before the constructor.

For example:
```
public function __construct()
    {
        echo "Third";
    }

    /** @BeforeSuite */
    public static function first()
    {
        echo "First";
    }

    /** @BeforeFeature */
    public static function second()
    {
        echo "Second";
    }

    /** @BeforeScenario */
    public static function fourth()
    {
        echo "Fourth";
    }
```

These functions will be run in the order of what their `echo` says. Furthermore, I can't tag a `__construct()` with a hook, because it's not a static method.

The solution would be to have a parent class with the construct and use the arguments in child classes, where they can be tagged with any hook.

Is this intentional, or should we look into it?

**Comment by ciaranmcnulty** [comment]
The Context is re-instantiated for each Scenario - this is why everything up to beforeScenario must be static

**Comment by stevepetcu** [comment]
I see. So that's why the constructor is ran after the `@BeforeSuite` and `@BeforeFeature` hooks.

And this also means that everything that happens after the Scenario hooks, including that, doesn't have to be static.

Thanks!
