### ISSUE TITLE
Examples Cross + step execution chaining

### ISSUE THREAD

**Issue by danchukas** [Behat/Behat#1101]
Good day :)

I see more people need "Examples Cross" for minimise Examples strings  and step execution chaining for very usefully and speed testing.
I add this functional as 
https://github.com/danchukas/Behat + https://github.com/danchukas/Gherkin.
My team use it, all works without any problem, my fork - is few addition php code. All are very happy.

Please, merge my project with your, or better refactor and merge.

____ Example Сross  _____

:gift: внідрив Example Сross 
http://joxi.ru/Dr8yg8Ou4qnZRm
Особливості:
1. :warning: Example Сross - перебирає всі можливі варіанти.
2. пусті ячейки не враховує - тобто к-ть елементів в різних стовпцях можуть відрізнятись.
3. Example Сross блоки можуть бути як з Example блоками так і без них.
4. к-ть блоків Example Сross і Example від тепер може бути довільна. доцільно щоб зменшити час тестування на надлишкових комбінаціях.
5. плагін шторма не атводоповнює слово Cross, але все інше підтримує аналогічно до звичайного Examples.

_____ step execution chaining ________
http://joxi.ru/82QQndNtjJ3GM2

Thanks you for this good soft ! We use Behat few months on big project by 6 developers/QA

* for use my fork - in your project's composer add :

"repositories": [
    {
      "type": "git",
      "url": "https://github.com/danchukas/Behat.git"
    },
    {
      "type": "git",
      "url": "https://github.com/danchukas/gherkin.git"
    }
  ],

  "require-dev": {
    "behat/behat": "3.4.x-dev@dev",
  },

**Comment by ciaranmcnulty** [comment]
Forking a project is a lot of maintenance when new features come out.

Perhaps you could explain more about the feature and make a PR? Or alternatively you could bundle your changes into a behat extension that people could install?

**Comment by danchukas** [comment]
As extension:
- I am not sure I can do it now. I think it takes very much my time. I see existed extension, it is little hard, and not all works.

About feature:
1. You can write only:
Examples Cross:
|a|b|c|d|
|1|1|1|1|
||2|2|2|
| |3|| |

instead of:
Examples:
|a|b|c|d|
|1|1|1|1|
|1|2|1|1|
|1|1|2|1|
|1|2|2|1|
|1|3|1|1|
|1|3|2|1|
|1|1|1|2|
|1|2|1|2|
|1|1|2|2|
|1|2|2|2|
|1|3|1|2|
|1|3|2|2|


2. You can reuse written 1 or group of steps by cut past to new step in context . Hierarchy of inner steps are not limited. 

Situation:

I have scenario for "Place ad", that contains 16 steps.
I need scenario for edit ad, rate, remove, archive, ...
Than I need copy past all 16 steps into each new scenario, or create new method in Context where will be all 16 steps as methods what called that 16 steps. So, I need understand how work every step, find all methods, all arguments, and then create new method. If something changed on 16 steps - QA would long understand how fix it.

I propose only copy 16 steps to return of new method.
QA what write tests, simple do it by less 1 minute.
If something changed on 16 steps - QA easy find what QA must change.

Example:
....
Given I am on "/b"
When I click on "c"
And I  click on "d"
And I  click on "g"
And I  click on "e"
And I  click on "r"
....

I can group it as:

    /**
     * @Then Some Grouped Step
     */
    public function some_grouped_step()
    {
        return [
            'I am on "/b"',
            'I click on "c"',
            'I click on "d"',
            'I click on "g"',
            'I click on "e"',
            'I click on "r"',
        ];
    }

And use it in this and next feature as:

Given Some Grouped Step

In 2.5 used  new When(...), new Given(...). For us It not very usefully. More easy for day-to-day work of QA my variant. 

____
* What is PR I  don't know.
* "Forking a project is a lot of maintenance when new features come out." - I know it and write there - please, add this functionality to main behat.

**Comment by danchukas** [comment]
and it  https://github.com/Behat/Behat/issues/1082
already fixed in my fork
https://github.com/danchukas/Gherkin

**Comment by jakzal** [comment]
What you're trying to introduce is a new feature to the gherkin language. It's unlikely to be merged to this project as it would make it diverges from the official gherkin syntax (coming from cucumber). 

I think your best shot is to try to suggest it to cucumber, or maintain it as an extension. As Ciaran said, forking Behat is probably the worst choice because of maintenance overhead.

**Comment by danchukas** [comment]
Ok.
I please Cucumber add "Examples Cross" there: https://github.com/cucumber/cucumber/issues/301
I hope for success answer.

**Comment by danchukas** [comment]
But what about "chained execution steps" (grouped steps, inner steps) ? 
Can you add this very important feature to repository ?

**Comment by everzet** [comment]
@danchukas at this point in time we're not adding any functionality to the Gherkin language outside of what Cucumber does.
