### ISSUE TITLE
Interaction with react components

### ISSUE THREAD

**Issue by leftty** [Behat/Behat#1102]
Currently we are switching our old app to one based on React. In a menu we have a react component in which we need to type some letters and the a dropdown opens with some suggestions. After this happens we need to select one of the options that appeared by clicking on it.
When trying to interact with this component we encountered difficulties in typing some characters in the react-select component as well as selecting the options that appeared in the dropdown.
Does anyone have any suggestion on how I can better interact with such components.

Thanks in advance.

**Comment by jakzal** [comment]
Behat has nothing to do with web interactions. You're probably looking for Mink or the MinkExtension for Behat.

**Comment by spolischook** [comment]
This issue can be closed as well

**Comment by leftty** [comment]
Before selecting the option I have to find a way to type some characters in the react-select component, which I haven't managed to do yet. I will close this issue.

**Comment by Penguinatormike** [comment]
> Before selecting the option I have to find a way to type some characters in the react-select component, which I haven't managed to do yet. I will close this issue.

In case anyone else was wondering how to type into react-select, this is what I did. 

$driver->getWebDriverSession()
            ->element('xpath', "//input[@id='react-select-3-input']")
            ->postValue(['value' => ['CatDog']]);

ref: https://github.com/Behat/MinkExtension/issues/257#issuecomment-248895655

Note: I am using react-select v3.0.4
