### ISSUE TITLE
Clarify please next steps to make Firefox work with latest version

### ISSUE THREAD

**Issue by FlashBytes** [Behat/Behat#1105]
Hello Behat community. I am using the latest Behat version and I am very happy with it. Thanks for the hard work improving this framework.

Where I am missing out knowledge is how to make the latest Firefox versions work together with Behat. I use an almost 2 years FF version right now but would like to use what normal customers are using: Versions NOT 2 years old.

I know that the issues are related to the introduction of Selenium 3 (which I like a lot) and I also use Behat in a Docker setup (https://github.com/SeleniumHQ/docker-selenium). Chrome works fine btw. .

I saw different ideas on stackoverflow and other forums to use Goutte instead of selenium 2 to drive Firefox, but I got the error message with all browser infos, but that it cannot be used. I was spending already around 6 hours in research to make this happen.

What is right now holding us back to use the latest Firefox? Is there a way how we could contribute to code to make it happen? What do we need? I think if there is a clear to do, we as Behat users are having a change to implement support but we need to understand the issue first in detail.

Thanks to all contributors of Behat and Mink!

**Comment by jakzal** [comment]
Since this has nothing to do with Behat directly you'd be better off creating this ticket in Mink or MinkExtension.

There's nothing to do here.

**Comment by FlashBytes** [comment]
Thanks for the fast feedback. I will follow the chain of tools until I found the rabbit hole.

Enjoy
