### ISSUE TITLE
Drop `container-interop/container-interop` dependency

### ISSUE THREAD

**Issue by mdrost** [Behat/Behat#1110]
As `container-interop/container-interop` [is going to be abandoned](https://github.com/container-interop/container-interop/issues/94) I encourage you to drop that dependency and rely only on `psr/container`.

**Comment by Taluu** [comment]
Would be a BC Break (but imo would be an acceptable one)

**Comment by dimacros** [comment]
The package is deprecated. You must remove the dependency.

**Comment by danepowell** [comment]
To be clear, apart from the stability and security concerns related to relying on deprecated packages, all users of Behat will now get a scary yellow deprecation warning like this from Composer:
> Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.

**Comment by pamil** [comment]
Fixed by #1281.

**Comment by tedw** [comment]
FYI `container-interop/container-interop` was added back to `composer.json` in Sept. 2021 https://github.com/Behat/Behat/pull/1281#issuecomment-1111383428
