### ISSUE TITLE
Exceptions in @BeforeScenario should mark test as failed instead of skipped.

### ISSUE THREAD

**Issue by Jan0707** [Behat/Behat#1112]
Hi folks,

I am currently dealing with a flaky test that causes an exception in my @BeforeScenario hook. This marks the test as skipped. I'd rather have them marked as failed (Given that actual pre-condition failed this seems more consistent for us).

I cannot find a way to do that :( Any help would be highly appreciated.

**Comment by avant1** [comment]
As I know Behat process exists with zero status code when skipped scenarios found. Is it your main problem?

If so, try to add `--strict` option. It will consider any not passed step as failed and process exit code will be non-zero.

**Comment by ciaranmcnulty** [comment]
Yes, `--strict` is the way to solve this
