### ISSUE TITLE
Hooking after Background

### ISSUE THREAD

**Issue by bstrx** [Behat/Behat#1114]
Are there any plans to introduce an AfterBackground hook?

I want to create a db dump after the first run of background and don't run this feature's background anymore - db will be recreated from that dump. I expect to see some performance boost on features with heavy background. 
For now I don't see a way how to catch that moment when background is already done and no scenario step executed yet.

**Comment by shwetaneelsharma** [comment]
@bstrx So, how often do you plan to run these tests? I am asking this because I was wondering if somehow you could use tagged hooks here with a bit of workaround. If I understand how often you run the entire test suite, may be I will be able to help you with a possible workaround.

**Comment by stof** [comment]
the background would run for all scenarios anyway, so how to you plan to avoid re-executing it ?

**Comment by shwetaneelsharma** [comment]
So, does the background script in your case create a DB dump? Also, could you help me with what kind of extensions you are using in Behat?
