### ISSUE TITLE
Ambiguous match exception for same step

### ISSUE THREAD

**Issue by scoolen** [Behat/Behat#1115]
Is seems to me that this exception doesn't have to be thrown if ambiguous definitions point to the same step, correct?

Suppose I create this step:
```php
/**
 * @Then the thing should equal :value
 * @Then the thing should equal null
 */
public function assertValue($value = null)
```

In my opinion this should be perfectly fine.

**Comment by ciaranmcnulty** [comment]
Possibly, but we would need some way to decide which parameters to pass - this could be ambiguous

**Comment by scoolen** [comment]
I see your point: if the argument is omitted, in this case "value", it still should be present with the default value of ``null``. For example in ``Behat\Behat\Definition\SearchResult``.

**Comment by alexdesignworks** [comment]
@scoolen AFAIK, the idea is that you supposed to handle `:value` as optional and handle default value in your function's argument (which you already doing). To make `:value` optional, the strep definition should be written as regex.

**Comment by ciaranmcnulty** [comment]
I don't think there's a sensible answer here
