### ISSUE TITLE
bug while combining two formats

### ISSUE THREAD

**Issue by bruno-ds** [Behat/Behat#1119]
Hello,
I can't run this : 
```
vendor/bin/behat --format progress --format junit --out var/test/behat-log-junit
```
because it output this error : 
> Filename expected as `output_path` parameter, but got `/var/www/hub/var/test/behat-log-junit`.  

------------------------
if I try with a filename, it fails ("default" is the name of my test suite) : 
```
vendor/bin/behat --format progress --format junit --out var/test/behat-log-junit/default.xml
```
> Directory expected for the `output_path` option, but a filename was given.

those command run correctly : 
```
vendor/bin/behat --format junit --out var/test/behat-log-junit
vendor/bin/behat --format progress
```

**Comment by jakzal** [comment]
Since you specified multiple `--format` options you need to pass the same number of `--out` options. Use `std` for standard output:

```
vendor/bin/behat --format progress --out std --format junit --out var/test/behat-log-junit
```

See the docs for full overview: http://behat.org/en/latest/user_guide/command_line_tool/formatting.html

**Comment by bruno-ds** [comment]
Thank you.

I had read this doc. It's a personal feeling, but maybe the documentation should say this :

> If you specifie multiple --format options you need to pass the same number of --out options. Use std for standard output
