### ISSUE TITLE
Behat allows multiple gherkin given-when etc formats for a single step function

### ISSUE THREAD

**Issue by phil-davis** [Behat/Behat#1122]
I am starting to write gherkin step text regex using the standard:
1) For a "when" type step that should be taking a real action to be tested, write it as an active sentence.
2) For a "given" type step that should be setting up state (in any old way) prior to the "when" that does the action that the scenario is really meant to be testing, write the step text as a passive sentence.
3) For a "then" step that is supposed to test something, use the word "should" somewhere in the text.

Doing this seems to help for readers to be able to focus on the active "when" action(s) and the subsequent "then" expected results. (And speed-read over the "given" steps written in the passive.)

So for many steps that can be used as "given" or "when" I get 2 ways of writing the sentence. In English they can turn out to have reasonably different word order, so writing a single regex that matches both possibilities, although possible, obfuscates things.

I discovered that I can write 2 step regex definitions for a single method and it works, I can use either in the feature file - e.g.:
```
	 * @When /^user "([^"]*)" from server "(LOCAL|REMOTE)" shares "([^"]*)" with user "([^"]*)" from server "(LOCAL|REMOTE)" using the API$/
	 * @Given /^user "([^"]*)" from server "(LOCAL|REMOTE)" has shared "([^"]*)" with user "([^"]*)" from server "(LOCAL|REMOTE)"$/

```
(yes, in the example above writing a single regex is not so hard)

Is this an intended feature of the Behat-Gherkin parsing?
(I like it)

If so, then should it be officially documented?

**Comment by jakzal** [comment]
Reading [this post from over 6 yrs ago](http://everzet.com/post/6487273052/behat-v12-poll), the feature was intended. I think there's no other cucumber implementation that supports it though.

**Comment by phil-davis** [comment]
Suggested doc enhancement PR https://github.com/Behat/docs/pull/124

That will make the behaviour more easily noticed, rather than just being mentioned in a blog that recedes into the past.

**Comment by phil-davis** [comment]
Doc has been added.

**Comment by stof** [comment]
Closing this issue, as the doc PR has been merged.
