### ISSUE TITLE
Context file choice should not be shown if --append-snippets not used

### ISSUE THREAD

**Issue by jon-acker** [Behat/Behat#1124]
There is no point in showing a list of files when steps are not matched if the user has not specified  --append-snippets, because without this switch the snippets are simply printed to stdout.

IMO the correct behaviour is: the choice of context files should only be given when --append-snippets is used.

**Comment by bitwombat** [comment]
Agreed. The user is referring to the list of _contexts_. So this output:
```
 >> default suite has undefined steps. Please choose the context to generate snippets:

  [0] None
  [1] FeatureContext
 > 1

--- FeatureContext has missing steps. Define them with these snippets:

    /**
     * @Given I am not logged in
     */
    public function iAmNotLoggedIn()
    {
        throw new PendingException();
    }

```
Seems like a reasonable cleanup. I spent some time puzzling over why it wasn't writing to FeatureContext when I had selected it. If you know about the file, and my choice, why aren't you writing to it? Oh yeah, `--append-snippets`

**Comment by ciaranmcnulty** [comment]
The only thing selecting a context does is make sure the method names don’t collide with existing methods
