### ISSUE TITLE
Question on integration with PHPUnit

### ISSUE THREAD

**Issue by crocodile2u** [Behat/Behat#1126]
Hello,

I have an idea of integrating Behat with PHPUnit. The intention is to have an abstract TestCase class (or a trait) which will be capable of reading a feature file and executing it against a context, like this:

```php
$this->assertFeatureBehavesAsSpecified($featureFilename);
```
The context in this case is actually the test class itself.

I was looking into the Behat project code, and I think it should be possible to accomplish this by parsing a feature with **GherkinFileLoader->parseFeature()** and then passing the result to **RuntimeFeatureTester**. However, there are tons of dependencies (**Environment** etc) which I am sometimes not sure how to instantiate correctly. If someone familiar with the source code and classes structure helped me out a little, maybe I could make a nice tool in the end.

Thanks.

**Comment by jon-acker** [comment]
Hi @crocodile2u - Both Behat and PHPUnit are Test Frameworks, it does not make sense to integrate one into the other. In fact Behat is much more of a "pure" test framework as it merely orchestrates the extensions - which do all the work.
If you just want a test class that can parse gherkin - you can use the Gherkin extension by itself.

**Comment by jakzal** [comment]
> maybe I could make a nice tool in the end

What would be a good use case for such a tool? It seems you're trying to rewrite Behat with PHPUnit as a runner from what you describe.

**Comment by jonathanjfshaw** [comment]
I just created a library that does this: jonathanjfshaw/phpunitbehat.
Repo: https://github.com/jonathanjfshaw/phpunitbehat
I wrote a blog post explaining it: https://medium.com/@jonathanjfshaw/write-better-tests-by-using-behat-with-phpunit

What I like about integrating Behat and PHPUnit is that you can define your feature in the same file as the step definitions it needs. This makes it easy to write good tests that explain themselves well.

**Comment by ciaranmcnulty** [comment]
I do think this is a good idea; I sort of don't think it's Behat :)
