### ISSUE TITLE
Definition arguments with Unicode characters are ignored

### ISSUE THREAD

**Issue by ilovemistakes** [Behat/Behat#1129]
I have a definition with index argument:
`@Then I take :index thing`
Where index is supposed to be transformable, e.g. "1st", "2nd", etc. Steps like "Then I take 2nd thing" match perfectly.
Then I translate this definition to the other language:
`<source>I take :index thing</source>
<target>Я беру :index вещь</target>`
And then I am writing a feature with text:
`Тогда я беру 2ую вещь`
Behat cannot match this step to the original definition, because the definition's pattern is transformed to regex without unicode mode. Transformation is made by `src/Behat/Behat/Definition/Pattern/Policy/TurnipPatternPolicy.php`, which relies on `\w` as a pattern for "st", "nd", etc. But the final regex has no unicode-mode flag. Is there a reason for that?
If I manually change line 103 to:
`return '/^' . $regex . '$/iu';`
(just add `u` flag), then it locates all my "2ая" and "3ья" fine.

**Comment by jon-acker** [comment]
I'm not aware of any reason the turnip pattern matcher wouldn't use unicode - sounds like this deserves a PR 👍

**Comment by ilovemistakes** [comment]
Created #1130
