### ISSUE TITLE
No ability to generate random in Drupal\Driver\BlackboxDriver

### ISSUE THREAD

**Issue by alice-0-kim** [Behat/Behat#1131]
Hi,

This is just a minor suggestion, but when the error `No ability to generate random in Drupal\Driver\BlackboxDriver. Put `@api` into your feature and add an API driver (ex: `api_driver: drupal`) in behat.yml. (Drupal\Driver\Exception\UnsupportedDriverActionException)` is thrown, it would be much appreciated if the url for the documentation page(https://behat-drupal-extension.readthedocs.io/en/3.1/drush.html) is provided if possible as a reference.

Thank you.

**Comment by spolischook** [comment]
Move your issue to appropriate repository https://github.com/jhedstrom/drupalextension
