### ISSUE TITLE
Error: No scenarios No steps in the Output

### ISSUE THREAD

**Issue by sinner** [Behat/Behat#1132]
Behat Version behat 3.4.3

I'm running the following command to test a certain test feature file:

```sh
user@docker-api-app$ vendor/bin/behat --name=game-config
No scenarios
No steps
0m0.01s (4.06Mb)
```

My game-config.feature file contains the following code:

```yml
Feature: Fetch Games and Game Configuration Feature

  In order to allow an anonymous user to fetch the game configuration
  In order to allow an anonymous user to fetch the games list

  Background:
    Given there are some games with the following details:
      | id | name         |
      | 1  | Duck Hunt    |
      | 2  | Crazy Circle |
    And I set header "Content-Type" with value "application/json"

  Scenario: The response of the list of games should be 200
    When I send a "GET" request to "/games"
    Then the response code should be 200

```

But when I run the tests without the `--name` tag this test feature file runs together with the other tests.

**Comment by dsinn** [comment]
If you want to test that feature by _filename_, try `vendor/bin/behat features/game-config.feature`.

If you want to test that feature by _feature name_, try `vendor/bin/behat --name="Game Configuration"`.  I think `--name` just matches what comes after `Feature:` within the feature file, based on the [old documentation](http://docs.behat.org/en/v2.5/guides/6.cli.html).

**Comment by pradeep-perpetualny** [comment]
I tried the way mentioned but still I am getting the error message: for below feature

**Comment by pradeep-perpetualny** [comment]
I tried but still getting the same error message:
Feature: Sample Feature for Centennial Program

Scenario Outline: testcase_02 Sample Search test

Given the user loads search page "https://www.cfr.org"
When the user clicks on the search icon
And the user searches for "Daily News Brief"
Then the user should see return "Â(c) 2020 Council on Foreign Relations. All rights
reserved. Privacy Policy and Terms of Use."

Examples:
| url | searchFor | result |
| / | Richard Haass | Richard |

Command used in terminal: behat --name="Sample Feature for Centennial Program"
O/P:
No scenarios
No steps
0m0.05s (8.23Mb)
