### ISSUE TITLE
Reference segment of feature/scenario by another feature

### ISSUE THREAD

**Issue by bartonhammond** [Behat/Behat#1135]
Would it be possible to mark some portion of a feature/scenario to identify it as reusable code?
For example, if one feature had
```
    Scenario: I log in 
    StartSegment: login   #the "login" segment definition
    And I fill the "username" with "somename"
    And I fill the "password" with "password"
    And I click the "login" button
   EndSegment

   Scenario: After logging in I send a message
   Segment: login      #reference the 3 lines from above
   And then I send a message "this works!"
```
That way the steps don't get repeated everywhere.

I currently pull these "repeatable" code into the Context but then my user doesn't see it in the "features" which kind of defeats the purpose.  

Is this something we could add?  I'd be glad to help w/ that effort if I got a little direction of how to approach it.....

**Comment by jon-acker** [comment]
You can call other steps from within your context file, e.g.
```
$this->iFillInTheUsername('name')
```
will call your existing step. If that step is in a different context file there's a way of accessing that as well.

**Comment by spolischook** [comment]
While it's not a part of Gherkin specification nobody approve this to Behat, so you can implement it on your own extension, or as @jon-acker said you still have native workaround to implement that.

**Comment by bartonhammond** [comment]
@jon-acker - yes - I'm already doing that, I have large amounts of repeated code in my Context.  But when that Context function runs, there is no display in console log that reflects what is happening.  Therefore, the only `amigo` that knows what these steps are w/in the Context is the developer.

@spolischook I was looking at `extensions` yesterday wondering if I could use that.  Would you know of a specific extension that would be a good starting point for this?  I was hoping [https://github.com/Behat/ChainedStepsExtension](https://github.com/Behat/ChainedStepsExtension) this would have been helpful but I don't even understand what's its trying to do, especially 'cause it uses Russian.  Any suggestion would be greatly appreciated, thanks.

**Comment by spolischook** [comment]
ChainedStepsExtension is the right place. You can take ownership on this extension and translate steps to english. But you should be ready to invest huge amount of time to it. This extension mimic feature that was in Behat v2, and can't be implemented in Behat v3 by technical reasons. You should discover the versions history, existing codebase and prepare the solution. But as I said before, it can be weeks of month of time.

**Comment by timiTao** [comment]
@bartonhammond  I work with Behat long time and the reason that was ChainedSteps was abandon due to be in conflict with BDD itself. As gherkin aim is to provide Use Case scenario, that way you will start treating them as scripts made from others scripts etc. After some time debugging business scenarios will be hell as then will drop describing some logic clearly. 

Another thing, calling technical elements in the scenario is too very bad practice. Read at least about PageObject.

The `amigos` that you mention prepare the ground (dictionary) for the domain expert. That is ok if he doesn't know about the implementation of steps. If their description is not clear enough - then you have some smell of understanding what is done in given step.

@spolischook Is I know, It could be done less than a month - but that is the raw estimate.

**Comment by bartonhammond** [comment]
I took a different approach and it's working already. Basically I put a pre-processor in front of Behat.

I created `someSnippetName.snippet.feature` to contain the Steps for the variable `someSnippetName`.
Then I converted all the `someFeature.feature` to `someFeature.hbs.feature`
Inside the `hbs` file I use
```
{{{someSnippetName}}}
```
that gets replaced w/ the `snippet.feature` contents

I then write them out to a `temp` directory and updated my `behat.yml` to process these generated `feature` files.

Here's the code that does the conversion:
```
<?php
// Use composer autoloader
require_once './vendor/autoload.php';
use LightnCandy\LightnCandy;
$data = [];
try {
    foreach (glob("./features/gherkin/*.snippet.feature") as $filename) {
        $snippet = file_get_contents($filename);
        $name = pathinfo($filename)['filename'];
        $name = substr($name, 0, ( strlen($name) - strlen('.snippet')));
        $data[$name]= "#start $name\n" . rtrim($snippet) . "\n#end $name";
    }
    foreach (glob("./features/gherkin/*.hbs.feature") as $filename) {
        $template = file_get_contents($filename);
        $phpStr = LightnCandy::compile($template);  
        $renderer = LightnCandy::prepare($phpStr);
        $name = pathinfo($filename)['filename'];        
        $name = substr($name, 0, ( strlen($name) - strlen('.hbs')));
        $name = $name . ".feature";
        $string =  $renderer($data);
        file_put_contents("./features/temp/$name", $string);
    }
} catch (Exception $e) {
    \Psy\Shell::debug(get_defined_vars());    
    throw $e;
}
 ```
The benefit is that when the test is running, I see all the statements as they executed - every step is now displayed.
