### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in vendor/symfony/config/Definition/Builder/ArrayNodeDefinition.php on line 42

### ISSUE THREAD

**Issue by welly** [Behat/Behat#1149]
I have the following packages installed:

> "squizlabs/php_codesniffer": "*",
> "drupal/coder": "^8.2",
> "drupal/drupal-extension": "~3.0"

composer.lock reports

> "name": "behat/behat",
> "version": "v3.4.3",

When running behat --version, I get the following errors:

PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/web/vendor/symfony/config/Definition/Builder/ArrayNodeDefinition.php on line 42

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/web/vendor/symfony/config/Definition/Builder/ArrayNodeDefinition.php on line 42

Does anyone know what might be causing this? I'm running behat on a DrupalVM environment with PHP 5.6.

Many thanks

**Comment by welly** [comment]
Adding

>   "config": {
>     "platform": {
>       "php": "5.6"
>     }
>   },

to my composer.json file resolved the error.

**Comment by stof** [comment]
or running `composer` with PHP 5.6 as well.

**Comment by micheljp** [comment]
Do we need to be on PHP 5.6? I'm on PHP 7
