### ISSUE TITLE
json config feature

### ISSUE THREAD

**Issue by zucha** [Behat/Behat#1150]
Config of YAML should be rewritten in Json instead. :)

Yml files are not easy readable and user friendly.

**Comment by Taluu** [comment]
json is about the same...

**Comment by jakzal** [comment]
Yes, there are issues with handling yaml in php, but I'd say that Symfony yaml component used in Behat handles the task pretty well. Extensions can provide validation and I don't really see how switching to json would make the config any more friendly (apart from satisfying personal preferences).

I also don't see how json is more readable to yaml. If anything json brings more "noise".

What new would json bring apart from the syntax, a BC break, and more code to maintain in Behat?
How would it improve the end user experience?
