### ISSUE TITLE
one beforesuite hook for multicontext

### ISSUE THREAD

**Issue by ebrahimdunro** [Behat/Behat#1154]
Hi
I have a suite that has two context classes. I've written a trait that has a @beforeSuite static function and I added it to those two classes.
When I run behat, @beforeSuite function is called two times. 
What should I do?
please help me. Thanks

**Comment by jakzal** [comment]
Using traits is equivalent to copy & paste. If you don't want your hook be called twice, don't include it twice. 

Either include your twite in one of the contexts, or put your hook in its own context.

**Comment by spolischook** [comment]
Just distinguish context with beforesuite hook and include it in any suite you like.

**Comment by ebrahimdunro** [comment]
@jakzal I know about traits but now I understand that "behat" concatenates all context class**es** in a suit. wow! 
and Why!?

`default:

  suites:

    something:

      paths:

        - %paths.base%/tests/Features/Something

      contexts:

        - Anything\FirstContext

        - Anything\SecondContext`

with above config, behat actually make one class which has all of two classes. Also, both first and second context classes have their feature files.

**Comment by ciaranmcnulty** [comment]
It doesn’t make one class, no

**Comment by ebrahimdunro** [comment]
So why it use other classes method?? Could you please introduce me an article ? I couldn't find a good documentation about context, suite, profile.

**Comment by ciaranmcnulty** [comment]
When it runs a step, Behat looks in all the contexts of the current suite for a matching method. 

If more than one method matches the step (either by two different patterns matching the step, or in your case because you copy pasted them method into two contexts) you get an error message

**Comment by ebrahimdunro** [comment]
@ciaranmcnulty you're right. thanks.
not only steps, it uses my last context class `__construct` method for all features and scenarios in the suite. 
Thanks. alot
