### ISSUE TITLE
Mark step as skipped

### ISSUE THREAD

**Issue by MPV** [Behat/Behat#116]
Hi, 
Is there a way to mark a step as skipped?

We try to represent all important requirements in our feature files. 
A side effect of that is that it won't be possible to run automatic tests of everything (Flash, UI look and feel, etc). 

The simple way of handling this is just adding step definitions for those steps, but not actually doing anything in those steps (just letting them pass). That's what we've been doing so far. However, that way it is hard to measure how many, and which, steps are not being run. 

Does Behat have support for this? If not, would it be a good idea to add?

**Comment by spolischook** [comment]
@everzet can I throw SkippedException or something like that in hook to get skipped tests in the main report?

**Comment by Mikalai-Kabzar** [comment]
@everzet can I throw SkippedException or something like that in hook to get skipped tests in the main report?
I have the same question.
I want to integrate Behat with EPAM Report portal. How can I handle skipped tests?

**Comment by patwcummins** [comment]
@everzet It seems that we still need an equivalent to phpUnit's `markTestIncomplete` and `markTestSkipped`.

If some component of the testing infrastructure has dropped offline... a team may still want the rest of the tests to run.  skip/incomplete functionality would make this possible.

**Comment by garak** [comment]
I agree about the need of being able to skip a test at a lower level
