### ISSUE TITLE
Annoying warning message when trying to get context.

### ISSUE THREAD

**Issue by Sluimers** [Behat/Behat#1162]
Featurecontext.php
```php
...
/** @BeforeScenario */
    public function gatherContexts(BeforeScenarioScope $scope) {
        $this->apiContext = $scope
            ->getEnvironment()
            ->getContext(ApiContext::class);
    }
...
```

_Warning_
```
Method 'getContext' not found in \Behat\Testwork\Environment\Environment
Referenced method is not found in subject class.
```

**Comment by spolischook** [comment]
What the version of Behat you have?
It's works, at list with "behat/behat": "3.4.*"
See https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/SecurityBundle/Tests/Behat/Context/ACLContext.php#L41

**Comment by jakzal** [comment]
see https://github.com/Behat/Behat/issues/1161#issuecomment-402939539
