### ISSUE TITLE
Composer autloading and suites paths

### ISSUE THREAD

**Issue by johnrobertporter** [Behat/Behat#1166]
How is composer autoloading supposed to work? I have the following in my composer.json file:

```
    "autoload-dev": {
        "psr-4": {
            "Project\\Service\\": ["tests/unit", "tests/bahaviour"]
        }
    }
```

Behat can't find any of my namespaced classes though :/

I want to have:

```
- features
    - something.feature
    - else.feature
- tests
    - behaviour
        - SomethingContext.php (namespaced as Project\\Service\\SomethingContext)
        - ElseContext.php (namespaced as Project\\Service\\ElseContext)
```

Can you show me the config I would need?

**Comment by ciaranmcnulty** [comment]
It just uses the composer autoloader, so what you posted should work. How are you configuring suites in behat.yml?

**Comment by johnrobertporter** [comment]
I've tried it with no config, then I tried it with using the autoloader (as explained in the docs) but that just placed non-namespaced classes in the folder I described. Whatever I try, I can't pick up classes.

Also, I don't want to have to manually declare each Context in the config file, as this seems to defeat the purpose of autoloading?

I also used the paths for the suites to allow my features to be located where they are (separated from the php). This bit seems ok btw.

Last time I tried behat, it was the old version that allowed me to explicitly declare the features folder, and the bootstrap folder. How come it changed from something so simple?

Can you post an example config file that would achieve the description I'm after, if it's not too cheeky to ask?

**Comment by stof** [comment]
if you don't declare the context classes to use in the config file, Behat won't know which one to use. If you don't configure things, Behat defaults to using the `FeatureContext` class.

Autoloading is about letting PHP find the source file when asking for a class. It is not about autodiscovering context classes in Behat.

**Comment by johnrobertporter** [comment]
Ok, I'm just finding this a little weird. I'm used to PHPUnit where I just tell it folder locations, and it figures out what classes to load.

Do I need to define the contexts in config as the full namespace?

**Comment by jakzal** [comment]
> Ok, I'm just finding this a little weird. I'm used to PHPUnit where I just tell it folder locations, and it figures out what classes to load.

The same way, Behat finds all your feature files automatically. In case of Behat though, there's an additional layer - step definitions in your context files. These can't be automatically loaded as there might be multiple definitions of each step.

Behat lets you to group scenarios into suites. Each suite could use the same vocabulary (same steps) with different implementations. One use case for this is running the same scenarios on the domain level, against a web ui, and rest api (three suites, same steps, different implementations). This wouldn't be possible without explicit definitions.

If you don't like it or simply have a different use case, you could create a Behat extension that would load all the found context implementations (in your "sub" namespace).

> Do I need to define the contexts in config as the full namespace?

Yes.

**Comment by johnrobertporter** [comment]
Thanks. Not saying I don't like it, just confused after years of one approach to testing.

>>Do I need to define the contexts in config as the full namespace?
>
>Yes.

This is what I've been missing I think.

Thanks for the input guys!

**Comment by jakzal** [comment]
@johnrobertporter so could this issue be closed?

**Comment by johnrobertporter** [comment]
I guess so. I still think it's very weird though ;)

**Comment by johnrobertporter** [comment]
Hmm, just got back to this...

composer.json
```
    "autoload-dev": {
        "psr-4": {
            "Company\\DefaultContext\\": ["tests/behaviour"]
        }
    },
```

behat.yml
```
default:
  suites:
    default:
      paths:
        - '%paths.base%/features'
      contexts:
        - 'Company\\DefaultContext\\FeatureContext'
```

folder structure
```
/features
    /something.feature
/tests
    /behaviour
        /FeatureContext.php
```

`FeatureContext.php`
```
<?php

namespace Company\DefaultContext;

class FeatureContext extends Context
{
    ...
}
```

behat output
```
$ behat

In UninitializedContextEnvironment.php line 44:

  `Company\\DefaultContext\\FeatureContext` context class not found and can not be used.


behat [-s|--suite SUITE] [-f|--format FORMAT] [-o|--out OUT] [--format-settings FORMAT-SETTINGS] [--init] [--lang LANG] [--name NAME] [--tags TAGS] [--role ROLE] [--story-syntax] [-d|--definitions DEFINITIONS] [--snippets-for [SNIPPETS-FOR]] [--snippets-type SNIPPETS-TYPE] [--append-snippets] [--no-snippets] [--strict] [--order ORDER] [--rerun] [--stop-on-failure] [--dry-run] [--] [<paths>]
```

Any pointers?

**Comment by ciaranmcnulty** [comment]
Looks right, did you dump the composer autoloader?

**Comment by johnrobertporter** [comment]
Aha! It was the double back slashes.

**Comment by ciaranmcnulty** [comment]
Glad it's resolved 👍
