### ISSUE TITLE
Non conforming option name: --colors

### ISSUE THREAD

**Issue by tox2ik** [Behat/Behat#1169]
Please add the option  `--color` without a trailing s to do what `--colors` does.
Individuality is great in humans. Not so much with cli-tools. 
Most other tools use `--color`, including:

```
$ man ack | grep 'color\b' -m1
       --[no]color, --[no]colour

$ man git-diff | grep 'color\b' -m1
       --color[=<when>]

$ man grep  | grep 'color\b' -m1
       --color[=WHEN], --colour[=WHEN]

$ man cal | grep 'color\b'
       --color[=when]

$ man cfdisk | grep 'color\b'
       -L, --color[=when]

$ man diff | grep 'color\b'
       --color[=WHEN]
              specify the colors to use when --color is active  PALETTE  is  a

$ man dir | grep 'color\b'
       --color[=WHEN]

$ man dmesg  | grep 'color\b'
       -L, --color[=when]

$ man ebuild | grep 'color\b'
       --color < y | n >

$ man emerge  | grep 'color\b'
       --color < y | n >
```

**Comment by carlos-granados** [comment]
I don't see the real need to change the name of our option (and introduce a BC break) or to introduce a variant of the option name (and add more noise). Those tools may use `--color` but for example phpunit, which is a closer tool, also uses `--colors`. My vote is to close this issue. What do you think @ttomdewit @acoulton ?

**Comment by acoulton** [comment]
@carlos-granados agree, the confusion tradeoff of having two options that do the same thing and/or forcing users to change their scripts on the next major doesn't seem worth it to me. I'm sure there are other PHP tools that use `--colors` too. (Although I'm someone who has to look up these options for any tool because my brain always wants to use `--colours` :rofl: )

**Comment by carlos-granados** [comment]
Closing as won't implement

**Comment by tox2ik** [comment]
Oh well, how about --pigments? Surely that one is worth it :)

This is a pet peeve of mine. My observation is that different cultures of coders (gnu / bsd / go / rust / nodejs / etc) will have their own sets of similar, but cross-culturally incongruent flags. I'm just hoping for some convergence or adherence to established norms. Thanks for the reply, anyway.
