### ISSUE TITLE
Need help for writing my own behat extension

### ISSUE THREAD

**Issue by simonschaufi** [Behat/Behat#1175]
Hi, I am looking for hours now for a tutorial on how to write an own behat extension but even in the official documentation I couldn't find anything.

I looked through other behat extensions but some parts don't make sense to me what they are good for.

Let's take laravel behat extension as an example. The part that I really don't understand is this one:

https://github.com/laracasts/Behat-Laravel-Extension/blob/292a471321badec123a7f2b00edbde59be5759b0/src/ServiceContainer/BehatExtension.php#L84-L112

What's the meaning of these containers and definitions? How can I make use of them in my tests? What is the key in the definition used for?

I would be really happy if someone could point me to some useful resources where I can read more about it or explain it to me.

Thank you!

**Comment by Taluu** [comment]
The extension mechanism is using the mechanics from the dependency injection and event listeners to make it work. 

In the example you linked, it registers two services, one which is an event listener (here, after each scenario is tested if you look at the kernel initializer class) and another which is an argument resolver, loading the service needed. 

An extension registers configuration, services and tags them to make it available in the behat app. It can as you saw registers some event listeners / subscribers, add context initializers, add a custom container, registers argument resolvers, ... and so on.

**Comment by rpkamp** [comment]
The Definitions are used to set up the Dependency Injection Container (DIC) is using from Symfony.

Here is a nice starter on how it works: https://medium.com/manomano-tech/diving-into-symfonys-dependencyinjection-part-1-first-steps-with-the-container-2fad0593c052

Also, it has nothing to do with mocks.

**Comment by simonschaufi** [comment]
Thank you so much for this link. It made things very clear to me.
