### ISSUE TITLE
Behat dependency fails installation due to higher version of PHP required

### ISSUE THREAD

**Issue by forceedge01** [Behat/Behat#1178]
executing `composer require behat/behat --dev` with php 5.5.38. I get the following output. behat/behat should support above 5.3.2.

<img width="889" alt="screen shot 2018-09-14 at 08 48 03" src="https://user-images.githubusercontent.com/1619816/45537104-49f0eb00-b7fb-11e8-8516-99bfcb7be63d.png">

**Comment by stof** [comment]
that's not related to Behat, that's related to your *existing* dependencies (`doctrine/annotations` is marked as locked in the output, which means it is *already* part of your project).

It looks like your existing lock file was generated with a newer PHP version, and so your local set of dependencies is not compatible with PHP 5.5.38. Try running `composer install` instead. I'm quite sure it will fail in the same way.

`composer require` performs a partial update, which means that the solver is not allowed to upgrade or downgrade any of your existing packages, and so it cannot downgrade `doctrine/annotations`.

**Comment by stof** [comment]
I'm closing this issue, as it has nothing to do with Behat (try with any other package name in your broken project, and they will also fail...)
