### ISSUE TITLE
Temporarily skip scenario. 

### ISSUE THREAD

**Issue by nodeJerry** [Behat/Behat#1179]
Hi I have a suite of Behat tests that test an API.

One of the scenarios needs to be temporarily skipped.  

How can i skip the steps but leave the scenario and for the scenario to always respond positively. ie not fail the test.

**Comment by ciaranmcnulty** [comment]
You can comment out a step:

```
When I have a scenario
# But I don't want this step to run
Then everything will be cool
```

**Comment by nodeJerry** [comment]
Thanks Ciaran,

But i want to skip all steps in the scenario.

Effectively an "empty" scenario. 
The scenario text will still be visible / processed and return success. (even though empty)
But nothing was done behind he scene.

**Comment by spolischook** [comment]
This is actually what we talk about in issue https://github.com/Behat/Behat/issues/1051
But there is no way to do so

**Comment by Sam-Burns** [comment]
It's not uncommon to tag scenarios with an annotation like `@wip` (i.e. 'work in progress'), and exclude these in your Behat configuration under `suite/[suite name]/filter`, if that helps

**Comment by tkotosz** [comment]
@nodeJerry is this doing what you were looking for:
https://github.com/tkotosz/behat-skip-tests
