### ISSUE TITLE
'Date only' date type field is not created while running behat tests

### ISSUE THREAD

**Issue by amitsharmadoj** [Behat/Behat#1182]
After upgrading drupal core from 8.3.9 to 8.6.1 and behat from 3.1.0 to 3.3.1, behat tests are failing for dates of 'Date only' date type. There is no issue with 'Date and time' date type. 
It looks behat is not able to create dates of 'Date only' date type. I have tried different date formats but none is working.
I can create pages with 'Date only' dates and they appear correctly on the page in the desired format, it is just the behat test which is failing to generate it on the page.

My **test.feature** looks like (field_publication_date_of is 'Date only' date)
@api
Feature: I can see publication data on publication page.
  Background:
    Given I am an anonymous user
    And "publication" content:
      | title          | moderation_state | field_publication_author | field_publication_date_of |
      | test-title   | published             | test-author                       | 2016-09-01                     | 
 
 Scenario: I can see the correct publication data
    Given I am on "/test-title"
    And   I should see the text "test-author"
    And   I should see the text "September 2016"

**Error:**
001 Scenario: I can see publication data on publication page # features/publication.feature:35
      And I should see the text "September 2016"                                        # features/publication.feature:44
        The text "September 2016" was not found anywhere in the text of the current page. (Behat\Mink\Exception\ResponseTextException)

**Format tried:**
2016-09-01, 2016/09/01, 01/09/2016, 01-09-2016, 2016-09-01T05:00:00, 2016-09-01 12:12:12, 1 minutes ago etc
As I said it doesn't looks like format issue. Behat is not able to create date of 'Date only' type.
I have also tried putting break just before date test statement to see if date is being created in different format other than expected but date field along with its label is not at all present on the page.

**Versions used:**
```
behat/behat:    v3.3.1
behat/gherkin:    v4.5.1
behat/mink:    v1.7.1
behat/mink-extension:  2.3.1
behat/mink-goutte-driver:  v1.2.1      
behat/transliterator:    v1.2.0
drupal/core:    8.6.1
```

**Comment by ciaranmcnulty** [comment]
Behat doesn’t have a Date concept - what is the automation code behind those step definitions?

**Comment by amitsharmadoj** [comment]
Yes you are right. Issue is with drupal-driver. Apologies for putting up the issue at wrong place. 
Thanks for your help!

**Comment by MPParsley** [comment]
Posting a link to the issue at drupal-driver https://github.com/jhedstrom/DrupalDriver/issues/200
