### ISSUE TITLE
Behat nightly tests possible? 

### ISSUE THREAD

**Issue by bharatahuja04** [Behat/Behat#1186]
I want my set of feature files to run automatically once a day (at a given time interval) are there any tools that can support that?

**Comment by stof** [comment]
Behat itself is just a runner here. It is not managing your CI environment to run builds. That's a feature for your CI environment, not for Behat.

For instance, Travis supports defining a cron to automatically run a job every day, week or month.

I'm closing this issue, as it is not something in the scope of Behat.
