### ISSUE TITLE
Behat > Useful Resources > Broken link for Behat and Mink cheat sheet

### ISSUE THREAD

**Issue by p2635** [Behat/Behat#1187]
In this link: http://behat.org/en/latest/useful_resources.html, the 'Behat and Mink cheat sheet' is broken.

**Comment by bwowk** [comment]
@p2635 The repo for the docs is https://github.com/Behat/docs
There's already an issue for this over there: https://github.com/Behat/docs/issues/120

Can you close this one, please?
