### ISSUE TITLE
If a step argument is nullable, it should use `null` as value if no match

### ISSUE THREAD

**Issue by Taluu** [Behat/Behat#1189]
With the following step :

```php
/** 
 * @Then foo :bar 
 * @Then bar
 */
public function foo(?string $bar): void
{
}
```

If the second version of the step is used, it crashes saying that it can't find a value for `$bar` argument. IMO, if the parameter allows `null` value, it should validate and use `null` as a value if none is given.

I can try to work on a patch for that. WDYT ?

**Comment by ciaranmcnulty** [comment]
This should be an optional argument, IMO, which is different to `null`
