### ISSUE TITLE
Support for sending keys in browser for autocomplete etc

### ISSUE THREAD

**Issue by miiimooo** [Behat/Behat#1192]
I'm using behat with mink-selenium2-driver 1.3.1

I was looking for a way to be able to test an autocomplete done in react with downshift.

There has been some work on supporting selenium's sendKeys in mink recently here https://github.com/minkphp/Mink/pull/767 and here https://github.com/minkphp/MinkSelenium2Driver/pull/302

For some reason the version of mink-selenium2-driver used in my behat configuration is tagged at v1.3.1 so I've backported the second PR (302) to work with that here:

https://github.com/miiimooo/MinkSelenium2Driver/commit/d81b143c1a094a1005db1a6fb5497fea60b0c593

I can now write

    Given for "Search products" I enter "ra"

and my react downshift dropdown appears!

I was going to do a PR here but maybe it's wait for mink to accept the PR

**Comment by Taluu** [comment]
Anyway, it has nothing to do here in Behat's repository. It should be in mink actually, and I'm not even sure about that (that would be something too custom I think ?)
