### ISSUE TITLE
diferences between behat documentation and real live. What it's wrong?

### ISSUE THREAD

**Issue by oskarcalvo** [Behat/Behat#1196]
When I run `$ vendor/bin/behat --init`

I get this:

    <?php
    
    use Behat\Behat\Context\Context;
    use Behat\Gherkin\Node\PyStringNode;
    use Behat\Gherkin\Node\TableNode;
    
    /**
     * Defines application features from the specific context.
     */
    class FeatureContext implements Context
    {
        /**
         * Initializes context.
         *
         * Every scenario gets its own context instance.
         * You can also pass arbitrary arguments to the
         * context constructor through behat.yml.
         */
        public function __construct()
        {
        }
    }

But the [documentation][1]  show this: 

    <?php
    // features/bootstrap/FeatureContext.php
    
    use Behat\Behat\Context\SnippetAcceptingContext;
    use Behat\Gherkin\Node\PyStringNode;
    use Behat\Gherkin\Node\TableNode;
    
    class FeatureContext implements SnippetAcceptingContext
    {
        /**
         * Initializes context.
         */
        public function __construct()
        {
        }
    }

I'm not sure if it's because I don't a behat.yml file or it's other problem.

And it give me all the time this error:

      `FeatureContext` context class not found and can not be used. 

Thanks

Oskar

  [1]: http://behat.org/en/latest/user_guide/initialize.html

**Comment by spolischook** [comment]
Behat used default paths to find out your features and contexts - it's ok for very simple use cases, however explicitly defined suites in behat.yml is preferred way. 
So my suggestion is - add behat.yml configuration and define your suites where you should define Contexts(s) namespaces and feature(s) paths.
