### ISSUE TITLE
[question]Using behat from external directory with Extension

### ISSUE THREAD

**Issue by adeptofvoltron** [Behat/Behat#1197]
Hi, 
I was unable to do `composer require behat/behat` in my project because of dependency conflict.
So I installed it in my home directory by cloning behat. and making an alias
`alias  behat="~/Behat/bin/behat `
And basicly it worked. 
I could do 
behat --init,  write my own features and context in project directory.

Unlucky I want to add Mink to that and totally have no idea how to do it properly.

**Comment by nifr** [comment]
What do you mean by "I installed it in my home directory by cloning behat"? 
How exactly did you "install/clone" it?

FYI: You might get help and a faster reponse to your question by asking on a Q/A platform like stackoverflow 😄

**Comment by adeptofvoltron** [comment]
actually I used few options -
a)  I cloned behat in to ~/Behat dir...and i add ~/Behat/bin in to PATH variable
b) I created in ~/Behat dir a composer.json file like: 
```
{
    "require": {
        "behat/behat": "^3.5",
        "behat/mink": "^1.7",
        "behat/mink-goutte-driver": "^1.2",
        "behat/mink-extension": "^2.3"
    }
}
```
than after simple composer install I add ~/Behat/vendor/bin in to $PATH variable.

in both ways I had `behat` command in my CLI.

**Comment by jakzal** [comment]
Have a look at https://github.com/bamarni/composer-bin-plugin. It aims to solve such dependency issues.

**Comment by adeptofvoltron** [comment]
thx
