### ISSUE TITLE
[question/helping hand needed] Symfony service modification

### ISSUE THREAD

**Issue by djoos** [Behat/Behat#1201]
Hi there!

it seems that I am unable to modify a service on the container that gets called in a Behat test suite: the real issue I have is with appending mock responses for an external API to a [Guzzle MockHandler](https://github.com/guzzle/guzzle/blob/master/src/Handler/MockHandler.php) service, however for simplicity sake, I'll give an example of a simple setter called in my FeatureContext.

eg. I've got class `SomeClass`, which has the following method:
```
    private $attribute;

    public function __construct(
        $this->attribute ='initial value for attribute';
    )

   ...

    public function setAttribute($attribute) {
        $this->attribute = $attribute;
    }

    public function getAttribute() {
        return $this->attribute;
    }
```

`service.yml` contains:
```
    some_class:
        class: path\to\SomeClass
```

`FeatureContext` (FYI: implements `Behat\Symfony2Extension\Context\KernelAwareContext` interface and uses the `Behat\Symfony2Extension\Context\KernelDictionary` trait) then has the following `@Given`:
```
    /**
     * @Given attribute of some class is :value
     */
    public function setSomeClassAttribute($value)
    {
        $someClass = $this->getContainer()->get('some_class');

        $someClass->setAttribute("some other value for attribute");
    }
```

...which should mean that some_class' private $attribute should be set to "some value for attribute".

However, when I the next step `And I send a "GET" request to "/some/endpoint"` (FYI: using `Behat\MinkExtension\Context\MinkContext`, `Behatch\Context\RestContext` and `Behatch\Context\JsonContext`), I spot in the endpoint's controller that getAttribute is not what I thought it would be, while printing it out in the FeatureContext itself, the value *is* as expected:
```
        echo $this->get('some_class')->getAttribute(); // echoes out 'initial value for attribute' instead of 'some other value for attribute'
```

I've been going round in circles on this issue, not entirely understanding why the attribute update is ignored and consequently my idea of appending mock responses for external API calls in Behat's  FeatureContext fails.

Thanks in advance for shedding some light on this!

**Comment by spolischook** [comment]
Symfony Kernel was recreate for each scenario, so if you set property in one scenario but get it in other one - you'll get default value. I guess you can find related code in Environment for EnvironmentHandler classes

**Comment by jakzal** [comment]
If you use the Symfony2Extension, than I vaguely remember the container you get in your features is not the same instance as used by your app.

**Comment by djoos** [comment]
Hi @jakzal,

aha, that's an interesting lead as I am indeed making use of the Symfony2Extension...

Thank you!
