### ISSUE TITLE
Bin/behat opens file behat

### ISSUE THREAD

**Issue by lilru** [Behat/Behat#1203]
Hi, i'm very new in behat so I dont know so much.
I have a problem when trying to make any command like bin/behat or bin/behat -V... when I do it it opens the file in the directory bin/behat (file behat). I dont know how to solve it and I would apreciate your help so much. 
Thanks and have patience.

**Comment by jakzal** [comment]
Seems like you don't have PHP installed, and your operating system opens the file instead of executing it.
