### ISSUE TITLE
proposing increments

### ISSUE THREAD

**Issue by staminna** [Behat/Behat#1205]
Hi

Whenever I run behat, it keeps proposing increments in function names, such as:
custom.feature: `    Given I am logged in as a user with the "authenticated user" role(s)`
featureContext.php: 

```
class FeatureContext extends RawDrupalContext implements SnippetAcceptingContext {
  public function __construct() {
  }
    public function iAmLoggedInAsAUserWithTheRoleS($arg1)
    {
        throw new PendingException();
    }
}
```

$

>  behat
> --- FeatureContext has missing steps. Define them with these snippets:
>     public function iAmLoggedInAsAUserWithTheRoleS2($arg1)
>     {
>         throw new PendingException();
>     }

This behaviour is a recursing loop, because it keeps proposing 2,3,4,5,6, etc..
Behat version is latest up to date.
I removed the comments for better readability.

**Comment by ciaranmcnulty** [comment]
Does the generated method not have a pattern on it? (i.e. no '@given')?

**Comment by ciaranmcnulty** [comment]
Ah you said you removed the comments. What's likely is that the generated step pattern is failing to match your step.

This would obviously be a bug because we'd hope to generate a pattern that then matches the thing we generated it from!

If you can share the pattern it'd be helpful - most likely is that the `(s)` in the step is confusing things

**Comment by staminna** [comment]
I just removed the contents from the above post, not from the actual code ;)
I removed the (s) from the custom.feature but the issue remained the same.
I'm not sure what you mean by pattern? Here is my behat.yml file:

`default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
      base_url: 'localhost'
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drush:
        alias: 'local'
        root: 'C:\PGM\xampp2\htdocs\jrcsh'
      drupal:
        drupal_root: 'C:\PGM\xampp2\htdocs\jrcsh'
local:
  extensions:
    Behat\MinkExtension:
    base_url: 'localhost'
    Drupal\DrupalExtension:
      api_driver: 'drush'
      drush:
        alias: '@self'
        root: 'C:\PGM\xampp2\htdocs\jrcsh'
      drupal:
        drupal_root: 'c:\PGM\xampp2\htdocs\jrcsh'`
