### ISSUE TITLE
Add feature file to Junit output

### ISSUE THREAD

**Issue by marxjohnson** [Behat/Behat#1210]
We use behat for testing features on our Moodle-based VLE.  We have about 600 feautre files, which are run on each of 3 branches daily.

We publish the JUnit XML results to Jenkins, and send email notifications of failures.  For our PHPUnit tests, its trivial to indicate which file the failed test was in, since this is included in the XML output from PHPUnit.  However, Behat doesn't record this.  Our current solution is to process the XML and find the feature file that contains the feature text for each testsuite tag.  However, this is a) not 100% reliable and b) silly since Behat knows the name of the file when it's producing the output.

A quick hack around showed that adding `'file' => $feature->getFile()` to the array of attributes in JUnitFeaturePrinter produces the desired effect, similar to PHPUnit where the testsuite tag contains the name of the file.  Would this be a suitable solution?

**Comment by marxjohnson** [comment]
I've taken a look at [the schema](https://github.com/Behat/Behat/blob/master/features/bootstrap/schema/junit.xsd) used in Behat's own tests and it appears that it doesn't support the `file` attribute.  I also noticed that it does allow the `status` attribute, which has been causing errors when I try to publish the results in Jenkins.

Further investigation shows that the Jenkins xUnit plugin is using a [different (newer?) version of the JUnit schema](https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd).  This allows for the `file` attribute but not the `status` attribute.

In Behat's current JUnit schema, the only other place I can see to log the file name is in the `classname` field of `testcase`.  This seems like a minor abuse of that field, but I can't imagine that Behat would use it for anything else in the future, and it makes a reasonable amount of sense to me to have it there.

**Comment by ciaranmcnulty** [comment]
From what I recall, the JUnit schemas were written retrospectively so I can well imagine there are competing standards :-/

**Comment by cogentParadigm** [comment]
One way around the Jenkins xUnit plugin issue is to remove the attributes using yq.
```
yq -i 'del(.testsuites.testsuite[].testcase[].+@status)' build/logs/behat/default.xml
yq -i 'del(.testsuites.testsuite[].testcase[].+@file)' build/logs/behat/default.xml
```
