### ISSUE TITLE
Error message "you need to quote the scalar"

### ISSUE THREAD

**Issue by paddelboot** [Behat/Behat#1216]
Trying to configure my suites and contexts as described here (http://behat.org/en/latest/user_guide/configuration/suites.html), I get the following error in my terminal: 

`The reserved indicator "%" cannot start a plain scalar; you need to quote the scalar at line 7 (near "paths: [ %paths.base%/features ]").`

How do I "quote the scalar", since using actual quotes on the variable placeholder produces the same error?

Thanks.

**Comment by paddelboot** [comment]
I had to quote like this in my behat.yaml file:

`'%paths.base%/features'`. 

It would be helpful to update the documentation. Tags also need quoting: `'@tag'`.

**Comment by stof** [comment]
The doc source is available at https://github.com/Behat/docs
