### ISSUE TITLE
Behat Wait Time

### ISSUE THREAD

**Issue by alexandrubuganu** [Behat/Behat#1218]
I am using Drupal & Behat and I am testing a software. As a presentation for client the process need to run smoothly but the syntax need to be easy and with a good aspect.

I want to remove all the "Then I wait x seconds" after each step, and i want to set up an automatic time after each step or maybe a delay something.
Is there any solution for this? To make an automatic wait time after each step withouth writing the same sentence everytime?

Thanks

**Comment by stof** [comment]
you can register a `AfterStep` hook whcih would wait.

**Comment by FroggDev** [comment]
In your FeatureContext.php you can add afterStep() for each step
```
    /**
     * @AfterScenario
     */
    public function AfterScenario(): void
    {
        // stuff to do after scenario
    }

    /**
     * @AfterStep
     *
     * @param $scope
     */
    public function afterStep($scope): void
    {
        // Stuff to do after each step (for example take a screenshot)
    }
```

**Comment by jakzal** [comment]
@alexandresalome did you get sufficient help? Can we close this issue?
