### ISSUE TITLE
[Cli] Can I hide file comments ?

### ISSUE THREAD

**Issue by amouhzi** [Behat/Behat#1220]
Hello,

Is there an option to hide file comments ?

I just want to see the steps.

Thank you.

**Comment by ciaranmcnulty** [comment]
Can you give an example of what you'd like to see?

**Comment by carlos-granados** [comment]
I don't think that Behat displays the file comments anywhere, so I am guessing that if anything this is something that should be configured in the IDE, so outside of our realm. I think we should close this one. @acoulton @ttomdewit what do you think?

**Comment by acoulton** [comment]
Yeah I'm not sure what this is about but I don't think it's a behat issue.
