### ISSUE TITLE
Support field "Equals" and "Contains"

### ISSUE THREAD

**Issue by michael38autumn** [Behat/Behat#1223]
assertFieldContains() doesn't do what it's name suggests because it uses $this->assertSession()->fieldValue**Equals**($field, $value). This is unexpected and restrictive behaviour. The word "contains" in English implies can be anywhere within - e.g. strpos() - not strict equality "==".

For example assertResponseStatus($code) is documented as :-
     * Checks, that current page response status is equal to specified
     * Example: Then the response status code should be 200
     * Example: And the response status code should be 400
If there was a method called assertResponseStatusContains($code) then we might expect assertResponseStatusContains("2") to return true if there was a "2" anywhere in the response code.

ATM there is no way to perform an intuitive _contains_ check - only strictly _equality_. I propose to change assertFieldContains() to do a proper/intuitive _contains_ check - using strpos()/stripos(), and to introduce a assertFieldEquals() to do an exact check ("==").

Changing assertFieldContains() to do what it's name implies wouldn't break any existing code. However, it might cause problems for users who assume it means strict equality. Nevertheless, those users requiring strict equality could use the new accurately/intuitively named assertFieldEquals()...

**Comment by paulinevos** [comment]
Is there help wanted for this still?

**Comment by ciaranmcnulty** [comment]
This was a Mink question so should be handled in the appropriate repo
