### ISSUE TITLE
`getContext` is missing from the environment of `BeforeFeatureScope`

### ISSUE THREAD

**Issue by irinikp** [Behat/Behat#1232]
Hello!
Although we can access `getContext` through a `BeforeScenarioScope` as described [here](http://docs.behat.org/en/v3.0/cookbooks/accessing_contexts_from_each_other.html), we can't through a `BeforeFeatureScope`. Wouldn't that be nice?

**Comment by jakzal** [comment]
At the time `BeforeFeatureScope` is dispatched no context is initialised yet.

See http://docs.behat.org/en/v3.0/user_guide/context/hooks.html#feature-hooks

**Comment by irinikp** [comment]
OK @jakzal thanks! Is there any way I could use the context once before running all scenarios then?

**Comment by jakzal** [comment]
>  Is there any way I could use the context once before running all scenarios then?

* instantiate it yourself (which should light a few warning lights in your head ;) ) - not recommended
* run whatever you need to run in a pre-scenario hook. If you really only want to run it once, remember you've already run it and check the flag on subsequent runs.

What are you trying to do? 

It's desired to start with a clean state before each scenario. Running something before all scenarios is undesired, even if possible.
