### ISSUE TITLE
Negation of tags for before and after scenario not working?

### ISSUE THREAD

**Issue by golddragon007** [Behat/Behat#1235]
Documentation doesn't say anything how to negate a tag on a `@beforeScenario`. Previously it was enough to use `~` for negation. I.e.:

```
  /**
   * @beforeScenario ~@javascript
   */
```

But from 3.x this doesn't work anymore. Is there any other way than checking if the scenario has the tag inside the hook?

**Comment by andrewnicols** [comment]
Can confirm - the RunTimeScenarioHook is checking the Feature tags first, and then the tags from the combined Feature and Scenario.

This means that if you have a Feature file like:
```
@beforeScenarioHookTest
Feature: Check that the beforeScenario hooks match correctly

  @noMatch
  Scenario: This should not match
    Then it should not match

  @match
  Scenario: This should match
    Then it should match
```

See https://github.com/Behat/Behat/blob/master/src/Behat/Behat/Hook/Call/RuntimeScenarioHook.php#L75-L83

**Comment by golddragon007** [comment]
Hi @andrewnicols,
I think there was a miss understanding here. You applied the tags on the features, but I've applied them in the class where you define the steps. I had there a before scenario that only needed if the current step is not a javascript scenario. I think that was what I wanted here.

**Comment by andrewnicols** [comment]
The tags have to be applied in the feature for them to be picked up by the tag.

Your use case is exactly what I had too - we had a BeforeScenario hook which was only for `@javascript` and a different one for `@~javascript`. 

The hooks match the Feature and Scenario tags so the JavaScript hook is only called for JavaScript scenarios, and vice versa.
