### ISSUE TITLE
Class hash does not exist

### ISSUE THREAD

**Issue by elieobeid7** [Behat/Behat#1243]
I keep getting

```
In Container.php line 752:
  Class hash does not exist 
```

When I run behat on a laravel 5.5 project

I have php 7.1, ubuntu 16.04 and  `"behat/behat": "^3.5",`.

My coworkers don't seem to have this problem, only me. A pc specific issue?

I tried `composer dump-autoload` and ` php artisan cache:clear`, nothing works

**Comment by jakzal** [comment]
It seems to be an issue with your app. Behat does not have `Container.php`.

**Comment by elieobeid7** [comment]
interestingly if I run 

`vendor/bin/behat --tags=Ready`

I see no errors
