### ISSUE TITLE
Code Coverage for Behat Tests

### ISSUE THREAD

**Issue by InfobyteTarun** [Behat/Behat#1253]
Hi,

I am using behat for automation testing of our Drupal Project.

I am using this library: https://packagist.org/packages/leanphp/behat-code-coverage  (Version-3.2.1) for code coverage. However I could able to setup all and it is generating code coverage report as well. 

But the report is completely blank. Please help me to fix it. 

Should I go for different approach.

Thanks in advance!

**Comment by pfrenssen** [comment]
I think you are using the wrong tool for the job. Behat is not intended for testing your code, it is an implementation for BDD (Behavior Driven Development) for PHP projects. The goal of it is to describe how users interact with your project using a domain specific language.

If you need to validate your code base it is better to write classic unit tests in PHPUnit (or the Drupal specific KernelTest and FunctionalTest classes).

**Comment by InfobyteTarun** [comment]
We are automating end to end functional scenarios using Behat. Now we wanted to check that how much we have cover the code, that is why we wanted code coverage. Could you help me for the same.

**Comment by pamil** [comment]
I guess it's an issue in the code coverage extension, not in Behat itself.
