### ISSUE TITLE
Update https://behat.org/en/latest/quick_start.html

### ISSUE THREAD

**Issue by DonCallisto** [Behat/Behat#1261]
I've recently found that https://behat.org/en/latest/quick_start.html has a link to a mink repository fork that's archived. We should update it to https://github.com/minkphp/Mink but I've found that docs aren't under this repo.
Let me know if there's any chance for me to change it or if you need to do the work.

**Comment by jakzal** [comment]
Docs are here I think: https://github.com/Behat/docs

**Comment by DonCallisto** [comment]
Thanks @jakzal: https://github.com/Behat/docs/pull/132

**Comment by pamil** [comment]
I'll close this issue then in favour of the docs one.
