### ISSUE TITLE
Support Symfony 5 packages

### ISSUE THREAD

**Issue by DavidGarciaCat** [Behat/Behat#1262]
BeHat uses Symfony components as per the package requirements (easy to confirm when checking the composer JSON file).

Given the latest version of Symfony is already available (5.0.1 at the moment) and knowing about the other opened issue to say farewell to unsupported versions of Symfony https://github.com/Behat/Behat/issues/1258 I suggest enabling support for the new version too.

~~ Edit ~~

Please note that I read all the comments on the other issue; I just added this one here because the purpose of the other one is to remove support for unsupported versions of Symfony.

Decouple matters :-)

**Comment by stof** [comment]
Adding support for Symfony 5 will require dropping support for PHP < 7.2.

It is possible to write code compatible with Symfony 4.4 and 5.0 at the same time, but only when running on PHP 7.2+ (as it would require having the new typehints in our code to be compatible with the signature of 5.x interfaces, and adding types in child classes is forbidden in PHP 7.1 and older).

@everzet what is the plan to drop these PHP versions in Behat ?

**Comment by Orkin** [comment]
Hello, I have the same issue, I can't update my project to Symfony 5.0 because this is unsupported by behat (console component). Any information about plan for this support ?

**Comment by pana1990** [comment]
me too :(

**Comment by pierre-H** [comment]
same problem 😢

**Comment by pierre-H** [comment]
@everzet

**Comment by jaikdean** [comment]
> Adding support for Symfony 5 will require dropping support for PHP < 7.2.
> 
> It is possible to write code compatible with Symfony 4.4 and 5.0 at the same time, but only when running on PHP 7.2+ (as it would require having the new typehints in our code to be compatible with the signature of 5.x interfaces, and adding types in child classes is forbidden in PHP 7.1 and older).
> 
> @everzet what is the plan to drop these PHP versions in Behat ?

Given PHP <7.2 is no longer supported, it feels wrong for any project to move forward supporting old versions of something (PHP <7.2) rather than new versions of something else (Symfony 5.0).

I realise it's far from being that simple and that maintaining two major versions of Behat would be a burden. However, given it's been well over a year since the last release, it doesn't seem like the community are crying out for bug fixes or new features in 3.5, so perhaps it's a sensible time to make some BC breaks like this one for a 4.0 release?

**Comment by Nyholm** [comment]
There is a well crafted PR here: https://github.com/Behat/Behat/pull/1256

Please try it to make it easier for maintainers to review/merge.

**Comment by pamil** [comment]
v3.6.0 supports Symfony 5, thanks all! 🎉 https://github.com/Behat/Behat/releases/tag/3.6.0
