### ISSUE TITLE
Proxy for behat client

### ISSUE THREAD

**Issue by Maxime35-bzh** [Behat/Behat#1263]
Hi,

When I launch behat, it cannot access the selenium server because of the proxy on my machine. The proxy configuration in the behat.yml file is for selenium, not for the behat client.

On my research, I found the call to selenium that is done via instaclick/php-webdriver/lib/WebDriver/Service/CurlService. By putting 

> curl_setopt ($ curl, CURLOPT_PROXY, '');

 it works.

Is there another way to do it ?
Or is it possible to add it in the configuration of behat.yml ?
Either a proxy option, or add options to the $extraOptions array which is a parameter of the method.

Thx

**Comment by ciaranmcnulty** [comment]
This isn't a core thing, please ask in the relevant extension's repo
