### ISSUE TITLE
packagist requires php

### ISSUE THREAD

**Issue by michield** [Behat/Behat#1280]
https://packagist.org/packages/behat/behat#v3.6.1

says requires PHP 5.3.3 and up, but it is now 5.5 and up.
It won't work with PHP 5.4

**Comment by stof** [comment]
What do you mean by "it is now 5.5. and up` ?

**Comment by michield** [comment]
I can't remember exactly, but I linted the code with php5.4 and it gives errors, due to some parts having syntax that is [not 5.4 compatible](https://www.php.net/manual/en/migration55.new-features.php). IIRC it was the Classname::method notation.

**Comment by pamil** [comment]
Will be fixed by #1284.
