### ISSUE TITLE
Allow new print format "errors only" to ease CI reporting

### ISSUE THREAD

**Issue by matks** [Behat/Behat#1286]
Hi, I have a very long behat test suite running in Travis and it could be nice to have a dedicated output format with only the summary and the errors. Passing scenarios would be ignored.

So it would be something like `$ behat --format=errors-only`

I checked and it does not seem to be an already existing format or option 🤔 if I'm not wrong.

If you guys can confirm this is a valid feature request, I can try to make a PR 👍

**Comment by matks** [comment]
Hi @stof @ciaranmcnulty could you please just confirm
- this feature is not implemented in behat CLI
- if I make a PR to add it, there is no big issue to accept it if code is valid (in order for me to avoid submitting a useless PR) ?

**Comment by stof** [comment]
Well, there is a `progress` format, which displays a single char per step (a dot for passing steps, and other chars for other status), and then a summary and the errors at the end.
Your proposal looks like the same without the reporting of the progress (meaning you see nothing while it runs). I'm not sure that's necessary.

**Comment by matks** [comment]
> Well, there is a `progress` format, which displays a single char per step (a dot for passing steps, and other chars for other status), and then a summary and the errors at the end.
> Your proposal looks like the same without the reporting of the progress (meaning you see nothing while it runs). I'm not sure that's necessary.

Indeed it looks like `progress` is what I was searching for ! Thanks 👍
