### ISSUE TITLE
Suggestion: Use bullet points instead of "and" to concatenate steps

### ISSUE THREAD

**Issue by jcornide** [Behat/Behat#1287]
Hi,

I'm not sure if this is the right place to ask for this or that even maybe it's already possible, apologies in advance.

Wouldn't be a bit more easier to read that instead of this:
```
Given there is condition A
and there is condition B
and there is condition C
When I perform action A
And I perform action B
Then the result of A should be A
and the result of B should be B
and the result of C should be C
```

we could write the tests like this?
```
Given:
 - there is condition A
 - there is condition B
 - there is condition C
When:
 - I perform action A 
 - I perform action B
 - I perform action C
Then: 
 - the result of A should be A
 - the result of B should be B
 - the result of C should be C
```

**Comment by djdevin** [comment]
Maybe you could change the keywords. Not sure how actually implement it, but it seems possible with Behat/Gherkin:

https://github.com/Behat/Gherkin#usage-example

**Comment by stof** [comment]
the Gherkin syntax comes from the cucumber project. Behat will not invent its own syntax for it.

note that the following should work AFAICT (untested):

```
Given there is condition A
* there is condition B
* there is condition C
When I perform action A
* I perform action B
Then the result of A should be A
* the result of B should be B
* the result of C should be C
```

Note that I kept `Given`, `When` and `Then` rather than putting `*` for all steps, to keep a separation between the 3 sections (but the runner does not actually distinguish those)

**Comment by jcornide** [comment]
thank you stof, i didn't know that was possible
