### ISSUE TITLE
Script works properly in office network but getting error when working over VPN. 

### ISSUE THREAD

**Issue by SeemaFreedom** [Behat/Behat#1288]
Hello, 
I am beginner for behat and using behat with docker. Issue which I am facing is my behat script executes properly when I am working in office network but I receive "`FeatureContext` context class not found and can not be used" error when executing in over VPN.

Kindly suggest !!!

**Comment by ciaranmcnulty** [comment]
Sorry, this is a very open question and almost impossible to answer without more information
