### ISSUE TITLE
Unwanted characters when exporting a report 

### ISSUE THREAD

**Issue by dandeleon03** [Behat/Behat#1289]
I executed this command:

bin/behat -c behat.yml --format pretty --out ons_behat_automation2.xml
bin/behat -c behat.yml --format pretty --out ons_behat_automation2.txt

And the report has some unwanted characters showing up.
[ons_behat_automation2.txt](https://github.com/Behat/Behat/files/4485291/ons_behat_automation2.txt)

Can't upload the generated xml file.

Kindly check and advise. Thank you.

**Comment by ciaranmcnulty** [comment]
For some reason you're getting colourful output; try adding `--no-colors`
