### ISSUE TITLE
Behat reads a character that doesn't exist.

### ISSUE THREAD

**Issue by gitmerobert** [Behat/Behat#1290]
When I'm doing a Behat automation for the page's backend and added a script, then I've encountered an error on the specific scenario.
Here's the command to run the script and the result after running the script:
Comand: vendor/bin/behat -c vendor/behat.yml --tags=features-no-overridden

`@smoketest @admin @features-no-overridden
    Scenario: Validate if there are no displaying of Overridden features
        Given I am on "/user"
        When I fill in "Username" with "qa_admin"
        When I fill in "Password" with "test123"
        When I press "Log in"
        Then I am on "/users/promet-qa"
        When I follow "Structure"
        Then I am on "/admin/structure"
        When I follow "Features"
        Then I am on "/admin/structure/features"
            And I should not see "Overridden"`

**Results**:
`@smoketest @admin @features-no-overridden
  Scenario: Validate if there are no displaying of Overridden features # features/admin.feature:460
    Given I am on "/user"                                              # Behat\MinkExtension\Context\MinkContext::visit()
    When I fill in "Username" with "qa_admin"                          # Behat\MinkExtension\Context\MinkContext::fillField()
    When I fill in "Password" with "test123"                           # Behat\MinkExtension\Context\MinkContext::fillField()
    When I press "Log in"                                              # Behat\MinkExtension\Context\MinkContext::pressButton()
    Then I am on "/users/promet-qa"                                    # Behat\MinkExtension\Context\MinkContext::visit()
    When I follow "Structure"                                          # Behat\MinkExtension\Context\MinkContext::clickLink()
    Then I am on "/admin/structure"                                    # Behat\MinkExtension\Context\MinkContext::visit()
    When I follow "Features"                                           # Behat\MinkExtension\Context\MinkContext::clickLink()
    Then I am on "/admin/structure/features"                           # Behat\MinkExtension\Context\MinkContext::visit()
    And I should not see "Overridden"                                  # Behat\MinkExtension\Context\MinkContext::assertPageNotContainsText()
      The text "Overridden" appears in the text of this page, but it should not. (Behat\Mink\Exception\ResponseTextException)`

Issue: Behat reads a character that doesn't exist.

Kindly check and advise, please.

**Comment by ciaranmcnulty** [comment]
I'm not sure we can debug your failing test with the information here
