### ISSUE TITLE
Behat output colors not working in Github Actions

### ISSUE THREAD

**Issue by I-Valchev** [Behat/Behat#1293]
```
vendor/bin/behat --tags=javascript --format=progress --colors
```

I think this should output colors, but it does not work. Worth pointing out that it did work in Travis CI, but Github Actions doesn't seem to like it.

**Comment by stof** [comment]
What do you mean by `doesn't seem to like it` ? what happens ?

**Comment by I-Valchev** [comment]
There's no colors.

**Comment by I-Valchev** [comment]
Any ideas, @stof ?

**Comment by carlos-granados** [comment]
Just tested this and the colors show correctly in Github Actions, see screenshot, closing

<img width="652" alt="Screenshot 2024-11-02 at 18 30 52" src="https://github.com/user-attachments/assets/f055919d-f9af-4a1d-bc73-3c994e5e143a">
