### ISSUE TITLE
trigger_deprecation warning fired when TestworkEventDispatcherSymfony* triggered

### ISSUE THREAD

**Issue by graemedewe** [Behat/Behat#1295]
When:
https://github.com/Behat/Behat/blob/98cfd077dcb68a6f1e20f3faa94b31e63b0dd182/src/Behat/Testwork/EventDispatcher/TestworkEventDispatcher.php#L37 fires,

its triggering https://github.com/symfony/dependency-injection/blob/2ad6ca1ddebef63fc92c0165398a80cd8f60c765/ContainerBuilder.php#L1094

However:
 Behat\Testwork\EventDispatcher\TestworkEventDispatcherSymfony* are both marked as deprecated

resulting in

`PHP Deprecated:  The "event_dispatcher" service relies on the deprecated "Behat\Testwork\EventDispatcher\TestworkEventDispatcherSymfonyLegacy" class. It should either be deprecated or its implementation upgraded. in /app/vendor/symfony/dependency-injection/ContainerBuilder.php on line 1147`

So what option do I have as I have? as I get the same warning no matter which version of symfony/dependency-injection I include

**Comment by ciaranmcnulty** [comment]
Is this still an issue?
