### ISSUE TITLE
Behat run only the first feature files

### ISSUE THREAD

**Issue by RusHiiii** [Behat/Behat#1302]
Hello,
I am expecting an issue when I run my features, only the first file is executed all the other files are ignored, no errors in the console, very strange behaviour

I am currently updating my Symfony version from 4.3.9 to 4.4.9 and the dependencies. 
I used behat on a other project with SYmfony 4.4.9 and no problems. 

I don't have any idea which dependencies generate the problem.
I downgrade to an older version, same things, remove and reinstall behat too

Behat: 3.7.0
Symfony: 4.4.9

**Comment by stof** [comment]
Without a reproducing case, I fear we won't be able to help you.

**Comment by RusHiiii** [comment]
I know, I know, I am currently finding the dependencies which broke behat. If I found the right depedencies, I will update this issue

**Comment by nathansalter** [comment]
Also getting this issue. After checking all 200 dependencies of our project it turns out that `sentry/sentry` version `2.4.0` is causing this issue for us. Locking this to `2.3.2` fixed the issue for us.

**Comment by RusHiiii** [comment]
@nathansalter It seems to be the reason we are currently running sentry on 2.3.2 instead of 2.4 !

**Comment by guilliamxavier** [comment]
Reported on the Sentry side: https://github.com/getsentry/sentry-php/issues/1028

**Comment by Nightbr** [comment]
:pray: Good catch, several hours on this until I found this issue! Upgrade `sentry/sentry` to `2.4.`1 resolves the bug. Thanks!

Note: for us it stopped the behat suite (8 ran scenarios) at the first (handled) error (i.e. catching a 400) only in our CI (Gitlab CI) but worked completely in local (108 ran scenarios).
