### ISSUE TITLE
PHPUnit dependency is out of date

### ISSUE THREAD

**Issue by agjmills** [Behat/Behat#1304]
Would it be possible to bump the PHPUnit dependency to at least 8.5, please? Perhaps 8^.5 and ^9.0

Laravel 7.0 was released earlier this year and has that as a dependency, so I can't use behat if I want the latest version of the framework.

Many thanks

**Comment by pamil** [comment]
PHPUnit is a dev dependency so it shouldn't affect your application. Why can't you use Behat, what's the error?

**Comment by ciaranmcnulty** [comment]
Indeed, the dev dependency used by this project doesn't affect which versions of phpunit you can install
