### ISSUE TITLE
Feature request: inline comments inside TableNode

### ISSUE THREAD

**Issue by matks** [Behat/Behat#1324]
Hi,

I have some Behat tests that assert how computations of a cart (in a eCommerce context) are made. Something like "with a tax rate of X, a currency conversion rate of Y, provided I use a discount of Z percent, and my cart contains 5 items with unit price Z then cart total, tax included, should be ..."

I am using TableNode to assert multiple properties:
```
    Then my order should have following details:
      | total_products           | 238.00 |
      | total_products_wt        | 252.28 |
      | total_discounts_tax_excl | 9.43   |
      | total_discounts_tax_incl | 10.0   |
      | total_paid_tax_excl      | 298.57 |
      | total_paid_tax_incl      | 316.48 |
      | total_paid               | 316.48 |
      | total_paid_real          | 0.0    |
      | total_shipping_tax_excl  | 70.00  |
      | total_shipping_tax_incl  | 74.20  |
```

Sometimes, as the computation logic evolves, we need to re-compute these values but we need to do it manually to make sure the new values are correct. What I mean is that if Behat suddenly tells us "I expected 298.57 instead of 298.92" we need to check whether our code logic changed which means 298.92 is correct or this is an error, catched by Behat.

I consequently wanted to add the details of the computation next to each line. I tried the following:
```
      | total_products           | 238.00 |  # 238.00 is 119x2
```

But this results in a weird `Notice: Array to string conversion` that makes the step fail.

So if I am not wrong inline comments are not supported in Feature files: something like `When I do X # this is a comment, don't parse it`

I think this feature could be nice in Behat :) please tell me what you think

**Comment by jakubthedeveloper** [comment]
Hi @matks 

I like your idea, but there is a question, how should the comment be recognised?

Everything after the hash character may be the comment, but what if we want to use hash in the test data?

**Comment by matks** [comment]
> Hi @matks
> 
> I like your idea, but there is a question, how should the comment be recognised?
> 
> Everything after the hash character may be the comment, but what if we want to use hash in the test data?

Very good question :)

It makes me think "what if we want to use the pipe character `|` in test data too" 😄 

I can think of 2 answer for both questions:
- provide a way to acknowledge if the character is part of a string (and not a keyword): for example using quotes

```
      | field                               | value                                                                       |
      | total_paid_tax_excl     |  298.57                                                                   |
      | total_paid_tax_incl      | 316.48                                                                    |
      | label                              | 'This is a label that contains a pipe | character' |
```
⬆️ 
in the above example, we know the pipe used inside the string is 'just a character used in data set' because it is inside quotes

- provide a way to escape these characters: for example using backslash

```
      | field                               | value                                                                       |
      | total_paid_tax_excl     |  298.57                                                                   |
      | total_paid_tax_incl      | 316.48                                                                    |
      | label                              | This is a label that contains a pipe \| character  |
```
⬆️ 
in the above example, we know the pipe used inside the string is 'just a character used in data set' because it is preceded by a \

**Comment by ciaranmcnulty** [comment]
Good ideas, but this sort of discussion isn't a Behat design decision - we tend to follow cucumber on Gherkin syntax, so:

* Changes to syntax should be discussed on cucumber/cucumber
* If Behat's behaving differently to cucumber that should be raised on Behat/Gherkin

**Comment by jakubthedeveloper** [comment]
@matks In your example the pipe character works, here is the output of $tableNode->getRowsHash():

```
array(4) {
  ["field"]=>
  string(5) "value"
  ["total_paid_tax_excl"]=>
  string(6) "298.57"
  ["total_paid_tax_incl"]=>
  string(6) "316.48"
  ["label"]=>
  string(48) "This is a label that contains a pipe | character"
}
```

@ciaranmcnulty You are right, it's a Cucumber, not Behat thing.

**Comment by ciaranmcnulty** [comment]
We do diverge from cucumber sometimes and it's always good to identify changes, but first step is to see what cucumber does :)

There's test data here https://github.com/cucumber/common/tree/main/gherkin/testdata/good

You can use the cucumber-go binaries as a lightweight way to see how cucumber parses Gherkin into ASTs

**Comment by ciaranmcnulty** [comment]
Additionally, using the cucumber/gherkin-php is on the roadmap for Behat
