### ISSUE TITLE
Coverage considers closing curly brackets as "Not Executed"

### ISSUE THREAD

**Issue by Titou44** [Behat/Behat#1338]
We opened an issue on the php-code-coverage side, link: https://github.com/sebastianbergmann/php-code-coverage/issues/852. It appears that the problem should rather be with behat.

**Comment by stof** [comment]
Behat itself does not have a code coverage feature. You are probably using an extension for that, which is where things should be reported.

**Comment by ciaranmcnulty** [comment]
It actually looks like self-implemented coverage
