### ISSUE TITLE
Remove symfony/config 2.3 compatibility

### ISSUE THREAD

**Issue by simonhammes** [Behat/Behat#1347]
This line can be removed, since Behat currently requires at least symfony/config 4.4 (according to composer.json), right?
https://github.com/Behat/Behat/blob/689f1e43efd6efa5f1dbde56a1cb967f1a512cad/src/Behat/Testwork/Cli/DumpReferenceCommand.php#L54

(I am currently trying to fix all issues identified by Psalm on the lowest level)

EDIT: Same here https://github.com/Behat/Behat/blob/689f1e43efd6efa5f1dbde56a1cb967f1a512cad/src/Behat/Behat/HelperContainer/ServiceContainer/HelperContainerExtension.php#L114

EDIT 2: And here
https://github.com/Behat/Behat/blob/689f1e43efd6efa5f1dbde56a1cb967f1a512cad/src/Behat/Testwork/ServiceContainer/Configuration/ConfigurationTree.php#L39

**Comment by pamil** [comment]
Fixed by #1349.
