### ISSUE TITLE
Idea to have @beforeWhen @beforeThen 

### ISSUE THREAD

**Issue by ghost** [Behat/Behat#1352]
Well as you can guess from the title, this would introduce two new hooks that trigger before the first When and first Then in the scenario. This would give us much more options to clean up our code layer just beneath Gherkin. 

Here's a usecase about logging: 

```
Given there was a thing
When I do a thing to the thing
Then I want Mr. Logger to know that the thing happened. 
// BTW don't be this stupid in real code ;) 
```
Let's say the Given was a bit more complicated, and logging happened there as well, how would you distinguish between logs created during Given and logs created during Then?  We only want to test for logs written during the When after all. This is something you could solve with a @beforeWhen. On execution of this hook, you could create a variable which would contain the max(logId) from your logs table. Then you would only test against logs which where created with a higher logId. 

Two more things:
1) I know you can already do this by creating if statements in the @beforeScenario. This proposition just seems cleaner to me. 
2) We could also introduce a @beforeGiven as an alias of @beforeScnario. That fills the expectation of there being one, while not really cluttering anything. 

I'm willing to create a PR, I'm just curious whether you would like such a thing.

**Comment by stof** [comment]
The Then and Given are not different at execution time. they are just steps. (there is nothing forbidding you to use `Given` for everything, except that it would be a terrible practice)

**Comment by rpkamp** [comment]
FYI You can already do this with `@BeforeStep('I do a thing to the thing')`.

**Comment by davidmaes** [comment]
> You can already do this with `@BeforeStep I do a thing to the thing` (or `#[BeforeStep('I do a thing to the thing')]`).

You seem to misunderstand my proposition then. You need a lot of boilerplate to have it only trigger before the first time any steptype (given, when then) is executed.

**Comment by davidmaes** [comment]
> The Then and Given are not different at execution time. they are just steps. (there is nothing forbidding you to use `Given` for everything, except that it would be a terrible practice)

I must be explaining poorly, since that does not remotely addresses the case I'm making. I want a trigger that only triggers the first time a given, when then step is triggered. So not for any of the subsequent ands.

**Comment by carlos-granados** [comment]
@acoulton I think that this functionality would not be really useful for the vast majority of users and it could easily be accomplished by using a flag and a beforeStep hook, so I think we could close it, what do you think?

**Comment by stof** [comment]
Given that nothing force to use the keywords in a consistent way, I don't think we hook triggered only when a *different* keyword is used makes sense (also, what happens if you use `And` as keyword ?).
so I'm in favor of closing.

**Comment by acoulton** [comment]
I think things like this (basically "wrapping" some subset of steps) can actually be quite tricky to achieve so I understand where the request is coming from.

But I agree, since the keywords are essentially meaningless and interchangeable, this wouldn't be a good solution.

Ultimately it's pretty fundamental that behat (and cucumber) executes steps without any real knowledge of what has gone before or after them - so things that try to break that paradigm without being explicit in the feature will always be a bit awkward.

For the specific case explained here, it would make more sense to implement your Given steps so that they disable / tag the logger in some way that lets you filter those out when running assertions later.
