### ISSUE TITLE
Symfony-dependency  symfony/translation leads to error

### ISSUE THREAD

**Issue by fbecker-complex** [Behat/Behat#1359]
Behat-version: `3.8.1`
# Problem:
Since the upgrade from symfony/translation `v5.3.7` to `v5.3.8`, I receive the followinng error message while running `vendor/bin/behat --strict`:

`
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Translation\Formatter\MessageFormatter' not found in /home/runner/work/philipp/philipp/vendor-bin/behat/vendor/symfony/translation/Translator.php:97
`

`
Stack trace:
#0 [internal function]: Symfony\Component\Translation\Translator->__construct()
#1 /home/runner/work/[PROJECT]/vendor-bin/behat/vendor/symfony/dependency-injection/ContainerBuilder.php(1088): ReflectionClass->newInstanceArgs()
#2 /home/runner/work/[PROJECT]/vendor-bin/behat/vendor/symfony/dependency-injection/ContainerBuilder.php(597): Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#3 /home/runner/work/[PROJECT]/vendor-bin/behat/vendor/symfony/dependency-injection/ContainerBuilder.php(1211): Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#4 /home/runner/work/[PROJECT]/vendor-bin/behat/vendor/symfony/dependency-injection/ContainerBuilder.php(1159): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#5 /home/runner/work/ph in /home/runner/work/[PROJECT]/vendor-bin/behat/vendor/symfony/translation/Translator.php on line 97

Script behat --strict handling the behat event returned with error code 255
Error: Process completed with exit code 255.
`

**Comment by stof** [comment]
This looks weird to me. `Symfony\Component\Translation\Formatter\MessageFormatter` definitely exists in `symfony/translation` 5.3.8. could it be that you have a corrupted vendor folder (maybe something went wrong during the extraction of the zip archive) ?

**Comment by stof** [comment]
Actually, the subtree splits of Symfony seems to be broken. See https://github.com/symfony/symfony/issues/43212. I'm closing this issue as the bug is not in Behat.

**Comment by fbecker-complex** [comment]
> Actually, the subtree splits of Symfony seems to be broken. See [symfony/symfony#43212](https://github.com/symfony/symfony/issues/43212). I'm closing this issue as the bug is not in Behat.

Alright, thanks for the quick reply! :)
