### ISSUE TITLE
Replace %1% with %count% in bg,hu,ko translations

### ISSUE THREAD

**Issue by Sweetchuck** [Behat/Behat#1373]
File `./i18n.php` still contains `%1%` placeholders in translations, which is not used any more. It has to be replaced with `%count%`.

* [ ] bg
* [x] hu
* [ ] ko

**Comment by pamil** [comment]
Merged :)

**Comment by Sweetchuck** [comment]
@pamil I think this issue should be left open to fix the bg and ko translations as well

**Comment by pamil** [comment]
Oh yeah, you're right, sorry!
