### ISSUE TITLE
[Refactoring] Lack of PhpUnit tests

### ISSUE THREAD

**Issue by jakubthedeveloper** [Behat/Behat#1378]
Hi,

This is my first contribution to Behat so please don't flame me too quick ;)

I use Behat a lot in a closed-source project of my client and digging deeper into it I found that there are only a few PhpUnit tests. There are 16 test cases, 5 report warnings and the XML configuration has deprecated format. 

Code coverage looks very bad:

<a href="https://ibb.co/0cQgsFz"><img src="https://i.ibb.co/CzWkPMS/behat-phpunit.png" alt="behat-phpunit" border="0"></a>

Does it mean that PhpUnit tests are less important and we rely on the tests from .feature files? I see there is a lot of Behat tests in the features directory and they are very well written, but my concern is, isn't it more reliable for the testing framework (Behat) to be tested by another testing framework (PhpUnit)?

I can write PhpUnit tests for Behat if you only want it, also I can fix warnings and XML configuration. Just tell me that it is needed :)

PS. content of the features directory is the best documentation for Behat!

**Comment by stof** [comment]
Most of Behat is covered by the Behat scenarios covering end-to-end usage of Behat. The goal is not to have full coverage with PHPUnit tests. Those have been added in a few places where unit tests were easier.

> isn't it more reliable for the testing framework (Behat) to be tested by another testing framework (PhpUnit)?

Then, are you complaining that the PHPUnit testsuite is based on PHPUnit ? Or that testing PHP itself relies on a script written in PHP ?

**Comment by jakubthedeveloper** [comment]
Sorry if you found my question complaining, it wasn't my intention.
And you just cleared my doubts, so I'm clossing the issue.
