### ISSUE TITLE
multi Context problem

### ISSUE THREAD

**Issue by gabriImparaProgrammare** [Behat/Behat#1384]
Hi all,

i'm new on Behat. 
I already search in doc..
I would like to have a  single context per each scenario.
![Screenshot 2022-03-10 at 10 44 51](https://user-images.githubusercontent.com/97903301/157635323-6e055f7f-ce61-4d1b-9218-b3ea679671f1.png)

this is my behat.yml 

![Screenshot 2022-03-10 at 10 45 36](https://user-images.githubusercontent.com/97903301/157635430-97c01a56-a01d-463d-8980-ceb5d31cab6d.png)

If i do behat --append-snippets. He create unsion.tmp files with the function in my bootstrap folder, instead of creating them in the right files.
If I try to write the functions in the right files myself, when I go to run the Behat command, it gives me the
"undefined"

![Screenshot 2022-03-10 at 10 46 57](https://user-images.githubusercontent.com/97903301/157635651-1bd8defa-9280-4f76-9dc0-6cab85569544.png)

**Comment by ciaranmcnulty** [comment]
Unison seems to be some sort of file synchronisation thing? It's not something Behat is doing natively...

**Comment by gabriImparaProgrammare** [comment]
> Unison seems to be some sort of file synchronisation thing? It's not something Behat is doing natively...

First of all thanks for your reply..
Yeah i use unison strategy in docker-sync
I use symfony docker behat 3.1
