### ISSUE TITLE
Allow use with psr/container 2.0

### ISSUE THREAD

**Issue by kdambekalns** [Behat/Behat#1386]
We are using `psr/container` 2.0 in our codebase, but this leads to errors with Behat. See https://github.com/neos/flow-development-collection/pull/2428#discussion_r841516178

It would be great to allow `psr/container` 2.0 in `behat/behat`, too.

**Comment by olivermack** [comment]
As there is no further feedback in #1380 I'd like to kindly ask for any feedback here about the current status of this issue. Is there anything missing where one can contribute to get #1380 merged?
