### ISSUE TITLE
symfony/dom-crawler v6.1 broke form filling

### ISSUE THREAD

**Issue by gjuric** [Behat/Behat#1391]
I believe this is more related to https://github.com/FriendsOfBehat/MinkBrowserKitDriver but since the Issues are not enabled on that repository I am opening it here.

After an upgrade of `symfony/dom-crawler` from v6.0.9 to v6.1.0 ([diff](https://github.com/symfony/dom-crawler/compare/v6.0.9...v6.1.0)) I started getting the following errors:

    # Behat\WebContext::fillField()
    Form field with id|name|label|value|placeholder "name_of_the_field" not found. (Behat\Mink\Exception\ElementNotFoundException)

**Comment by gjuric** [comment]
After further investigation it looks like this does not work for searching a form element by `id`, but if I use the value of the `name` attribute then it works.

**Comment by pamil** [comment]
Could you report that on Symfony repository? Breaking compatibility changes in patch versions shouldn't happen there and there's nothing we could do about it here.
