### ISSUE TITLE
Feature request: sub-step progress

### ISSUE THREAD

**Issue by robocoder** [Behat/Behat#141]
1) TableNodes are useful for setting up data fixtures within a .feature file.

It would be nice to have a way to specify which table rows "passed".  Currently, it's all or nothing, i.e. the entire table shows up either all green or all red.

2)  Similarly, when steps are chained, and one fails, there's no visual indicator.

**Comment by Herod** [comment]
@everzet then this should be updated/removed?
http://knplabs.com/en/blog/behat-like-a-boss-meta-steps
