### ISSUE TITLE
Deprecated error PHP 8.1 compatibility.

### ISSUE THREAD

**Issue by albeortev** [Behat/Behat#1411]
The following error appears working with a Drupal when launching behat tests:

`Deprecated function: DOMElement::setAttribute(): Passing null to parameter #2 ($value) of type string is deprecated in Behat\Testwork\Output\Printer\JUnitOutputPrinter->addAttributesToNode() (line 118 of /var/www/html/vendor/behat/behat/src/Behat/Testwork/Output/Printer/JUnitOutputPrinter.php)`

**Comment by stof** [comment]
Fixed in https://github.com/Behat/Behat/pull/1410
