### ISSUE TITLE
Same step pattern, different step types are not allowed; additionally step type is ignored in feature files

### ISSUE THREAD

**Issue by uuf6429** [Behat/Behat#1425]
Steps defining all step type like so:
```php
    #[Given('/^I take a page screenshot(?: as (.+))?$/')]
    #[Then('/^I take a page screenshot(?: as (.+))?$/')]
    #[When('/^I take a page screenshot(?: as (.+))?$/')]
    public function takeScreenshot(?string $name = null): void
    {
```
are causing errors like so:
```gherkin
  Scenario: clicking on something  # features/something.feature:3
    Given that I do something
      Step "/^I take a page screenshot(?: as (.+))?$/" is already defined in <...>\Debug\Context::takeScreenshot()
      
      <...>\Debug\Context::takeScreenshot()
      <...>\Debug\Context::takeScreenshot()
    And I am on page 1
      Step "/^I take a page screenshot(?: as (.+))?$/" is already defined in <...>\Debug\Context::takeScreenshot()
```

The same thing is happening for PHPDoc-based step annotations.

If I remove the `#[Given..` and `#[Then..`, the errors are gone, and behat doesn't complain that I have a step defined as `When` but is used as `Given` in the feature file, for example.

Why does this happen? What's the point of using the step type (e.g. `@Given`) if it is ultimately ignored? (why not just have a `@Step` annotation/attribute in that case?)

In my opinion, steps should be consider unique by *step pattern* AND *step type*. Additionally, misusing steps (defined as `Given`, but used as `Then`) should trigger a runtime warning.

**Comment by stof** [comment]
The step type is purely indicative. It does not impact the matching at all.

And changing that would be a BC break so it cannot be done in Behat 3.x.
Note that the step type is also indicative in Cucumber, so the existing behavior is consistent.

**Comment by uuf6429** [comment]
Thanks for the reply!

From what you say, I think the only course of action is to relax the step duplicate check in cases where the annotations/attributes apply to the exact same step (and in which case it wouldn't be a BC break). Wdyt?

If I get some time, I'll see if I can make this happen.

**Comment by stof** [comment]
Well, there is strictly no benefit of adding it multiple times on the same method

**Comment by uuf6429** [comment]
> Well, there is strictly no benefit of adding it multiple times on the same method

That is true...in the short term at least.

In my opinion, I still don't like the ambiguity and I would rather have an `@Step` (if they are all treated equally) _or_ be more strict about Given/When/Then.

The way I see it, there are two ideal cases (as already mentioned) and a middle-ground (which is where we're at), and unfortunately, even that middle-ground is not implemented as expected due to the aforementioned uniqueness problem.
