### ISSUE TITLE
Suite hooks defined with Attributes not working

### ISSUE THREAD

**Issue by rrajkomar** [Behat/Behat#1435]
When I define a BeforeSuite hook using the attribute syntax, the method is never run.
```
use Behat\Testwork\Hook\Call\BeforeSuite;
[...]
#[BeforeSuite]
public static function beforeSuite(): void
{
    echo 'Not run';
}
```

but when using the annotation syntax it works
```
/** @BeforeSuite */
public static function beforeSuite(): void
{
    echo 'Not run';
}
```

Maybe this is the expected behaviour but it is counter intuitive as the documentation refers to the Behat\Testwork\Hook\Call\BeforeSuite as the correct class to use to hook before the suite is ran

**Comment by stof** [comment]
Attribute classes are in the `Behat\Hook` namespace. But it looks like the attribute reader has not been implemented with the full list of hooks but a partial list.

**Comment by stof** [comment]
@rpkamp was there a specific reason to implement only a subset of hooks in https://github.com/Behat/Behat/pull/1372 ?

**Comment by rpkamp** [comment]
No, no specific reason. I guess it was just an oversight :/

**Comment by rrajkomar** [comment]
@rpkamp  Any news on this subject ? When will the attribute hook be available ?

**Comment by rpkamp** [comment]
I've just opened a PR for BeforeSuite/AfterSuite attributes -- https://github.com/Behat/Behat/pull/1511

**Comment by carlos-granados** [comment]
Closed via https://github.com/Behat/Behat/pull/1511
