### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by dovanmanh080485** [Behat/Behat#1438]
Hello,
I'm new to Behat. 

public function iAmInTheLoginPath($arg1)
    {
        $sessionHeadless = $this->getMink()->getSession('goutte');
        $sessionHeadless->visit($arg1);
        $assertHeadless = $this->assertSession('goutte');
    } 
    
    I have an error.
    
     Given I am in the login "xxxxxxxxxxxxxxxxxxx" path                   # UserLoginContent::iAmInTheLoginPath()
      SSL certificate problem: unable to get local issuer certificate for "xxxxxxxxxxxxxxxxxxx". (Symfony\Component\HttpClient\Exception\TransportException)
      
      
      Please help me to resolve the error. Thanks

**Comment by stof** [comment]
Without knowing your setup, there is no way to help you as we cannot know why your certificate is invalid.

**Comment by dovanmanh080485** [comment]
> Without knowing your setup, there is no way to help you as we cannot know why your certificate is invalid.

Hello @stof Thanks for your reply.

This is my behat.yml

default:
  suites:
    suite_user:
      paths: [ '%paths.base%/features/suite_user' ]
      contexts:
        - UserLoginContent

**Comment by stof** [comment]
this does not allow me to know where your certificate comes from or which URL you load.

**Comment by acoulton** [comment]
Closing as this appears to be an issue either with the cert your HTTP server is serving, or the root/intermediate certs your network client library (e.g. curl) is configured to trust. Both of those are outside the scope/control of behat.

Start by testing from the command line whether you can make a request to your app (e.g. with curl or similar) and work from there.
