### ISSUE TITLE
[Bug] jUnit formatter produces empty testsuite names, it could use feature file as suite name

### ISSUE THREAD

**Issue by dkarlovi** [Behat/Behat#1444]
Example produced

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="default">
  <testsuite name="" tests="2" skipped="0" failures="0" errors="0" time="0">
    <testcase name="It receives a response via Symfony session (default)" classname="" status="passed" time="0" file="features/demo.feature"></testcase>
    <testcase name="It receives a response via Browserkit session" classname="" status="passed" time="0" file="features/demo.feature"></testcase>
  </testsuite>
</testsuites>

**Comment by uuf6429** [comment]
This is not a bug IMO: Behat will not run if you do not have at least `Feature:` in your feature file - the only way to get the behaviour you describe is to not have anything else after `Feature` (which then shouldn't be surprising that its usages will also be empty).

This is consistent with output of other formatters. If the behaviour is changed it, should be changed for all of them, not just junit.

**Comment by dkarlovi** [comment]
> the only way to get the behaviour you describe is to not have anything else after `Feature`

Was this fixed recently? Because I do have features described correctly in the feature header and this output was a copy paste.

**Comment by uuf6429** [comment]
> Was this fixed recently? Because I do have features described correctly in the feature header and this output was a copy paste.
Not as far as I know.
Can you provide the example feature file as well? Just to be clear we're discussing the same thing.

**Comment by uuf6429** [comment]
As you see here, it is indeed something and not a literal empty string:

https://github.com/Behat/Behat/blob/dfaa04d46816418e2d7f05a7d71489536a52567e/src/Behat/Behat/Output/Node/Printer/JUnit/JUnitFeaturePrinter.php#L62-L62

(last changed 10 years ago 😆)

**Comment by dkarlovi** [comment]
You're right, this file indeed didn't have the title! :clap: 

Seems like the feature should be forced to have a title, why not make this a syntax error. I'll add https://github.com/dantleech/gherkin-lint-php to my pipeline.
