### ISSUE TITLE
Parallelization of tests

### ISSUE THREAD

**Issue by benjamind01** [Behat/Behat#1446]
Has there been a discussion in this repository regarding the addition of a new option to improve test execution time through parallel testing?

This is a topic that many competitors are beginning to integrate, and many companies need to depend on it.

**Comment by dkarlovi** [comment]
We've used https://github.com/liuggio/fastest?tab=readme-ov-file#behat-extension for this in the past and it worked well. I imagine it wouldn't be too much of a problem to replicate that directly in Behat.

**Comment by Kolyunya** [comment]
I guess this one could be closed: https://github.com/Behat/Behat/issues/159#issuecomment-168751860

**Comment by dkarlovi** [comment]
Why close it, that comment is from almost 10 years ago, maybe the current maintainers see it as a valuable addition.

**Comment by swaibar** [comment]
This module is very nice: https://github.com/Daniel-Marynicz/BehatParallelExtension

**Comment by carlos-granados** [comment]
@acoulton given that this functionality is well supported by several well supported extensions I think we should close this issue. What do you think?

**Comment by acoulton** [comment]
@carlos-granados agreed. Even if there weren't already other options, there are lots of variables to what people need to parallelize tests effectively depending on the system under test and we are unlikely to come up with a good generic solution in core.

**Comment by acoulton** [comment]
@danon - to be honest, I'm not aware of any that integrate nicely with phpstorm.

As I understand it, either BehatParallelExtension or fastest (linked above) are the best options currently depending on what you're trying to achieve and how you need to isolate your individual scenarios.

**Comment by danon** [comment]
@acoulton Do you parallelize your tests in behat?

> As I understand it, either BehatParallelExtension or fastest (linked above) are the best options currently depending on what you're trying to achieve and how you need to isolate your individual scenarios.

Well, I practice continuous delivery and I designed my application to be testable from the ground up. In other words, I don't need isolation features from the framework, the application is written in such a way that even a synchronous test runner can run in the same process, and the tests wouldn't influence each other. The only feature I need is to run them in parallel so they take less time :D I'm using a selenium driver to click through the UI, and my test suite of about 25 tests takes a minute - way to long. I think if I run them at the same time, which I believe my app can handle, I could get the times way lower.

**Comment by acoulton** [comment]
@danon we actually don't at the moment. 

Our modern suites run fast enough that it's not been something worth spending time exploring.

Our slower suite (which takes about 10 mins end-to-end in CI) covers a legacy app we inherited and a lot of cases that are related to global server/app configuration or database state that would be tricky to isolate to run different scenarios in parallel. Additionally on that project, with Behat, appserver, database, Chrome, etc all on a single CI runner it is already making pretty efficient use of the CPUs available.

**Comment by acoulton** [comment]
> Does your modern suite exercise the web ui, maybe using selenium, cypress or chrome driver?

Yes, we use a combination of browserkit driver (for interactions that don't need JS) and the chrome driver.

**Comment by danon** [comment]
> > Does your modern suite exercise the web ui, maybe using selenium, cypress or chrome driver?
> 
> Yes, we use a combination of browserkit driver (for interactions that don't need JS) and the chrome driver.

Ag! A browserkit isn't an option for me, I rely heavily on JS. How fast does the chrome driver test execute on your machine? 🤔
