### ISSUE TITLE
SigintController does not check for both pcntl-functions used in execute()

### ISSUE THREAD

**Issue by messatsuu** [Behat/Behat#1447]
Currently the `SigintController`'s `execute()` function only checks for the existance of `pcntl_signal`, but, if I'm not mistaken it should check for `pcntl_async_signals` as well.

The function should probably look something like this:
```php
    public function execute(InputInterface $input, OutputInterface $output)
    {
        if (function_exists('pcntl_signal') && function_exists('pcntl_async_signals')) {
            pcntl_async_signals(true);

            /**
             * @psalm-suppress UndefinedConstant (SIGINT is defined in pcntl)
             */
            pcntl_signal(SIGINT, array($this, 'abortExercise'));
        }
    }

```

Or am I missing something? Thank you!

**Comment by ciaranmcnulty** [comment]
It's really just trying to detect whether the PCNTL extension is loaded, I think

**Comment by messatsuu** [comment]
Couldn't this be done with `extension_loaded()`? But that wouldn't cover the case that either of the functions are disabled in a `php-cli.ini`, e.g.
```ini
disable_functions = pcntl_async_signals
```

**Comment by ciaranmcnulty** [comment]
Any arbitrary function could be killed that way, we can't check all of them before calling throughout the codebase :)

It probably could be `extension_loaded` but I'd kinda want a compelling argument to make the change as this seems like something that'll vary across platforms/distros in ways we can't anticipate

**Comment by brandon-hargrave-cloudtec** [comment]
Sorry, I don't understand the argument to not implement this. How would checking if the function exists vary across platforms and distros? This is common practice in other packages already (monolog being one such example), and we are already checking for one of the functions. Whilse it is true that any function could be killed that way, it's only common practice and in some cases the default configuration (https://github.com/thecodingmachine/docker-images-php/issues/168 is one example I found) to set the pcntl functions to disabled.

**Comment by uuf6429** [comment]
Frankly both approaches described here feel wrong - you should just check for the pcntl extension, ideally via composer dependencies (`"require": {"ext-pcntl": "*"}`).

If you/users are mucking up the PHP install with `disble_functions` or worse (runkit, fake functions etc), it's kinda your/their fault.

**Comment by stof** [comment]
Requiring `ext-pcntl` as a mandatory requirement would make Behat incompatible with PHP on Windows as ext-pcntl is an extension that does not exist on Windows.
The goal is not to support `disable_functions` here (if you are on Unix and don't want the pcntl functions in your runtime, disable the extensions instead of disabling functions one by one)
