### ISSUE TITLE
phar is broken for the 3.14.0 release

### ISSUE THREAD

**Issue by jakzal** [Behat/Behat#1456]
## Steps to reproduce

```bash
wget https://github.com/Behat/Behat/releases/download/v3.14.0/behat.phar
php behat.phar --version
```

## Expected result 

Outputs the version

```
behat 3.14.0
```

## Actual result

Fatal error:

```
Fatal error: Uncaught PharException: manifest cannot be larger than 100 MB in phar "/project/behat.phar" in /project/behat.phar:9
Stack trace:
#0 /project/behat.phar(9): Phar::mapPhar('default.phar')
#1 {main}
  thrown in /project/behat.phar on line 9
```

![Reproduction steps](https://github.com/Behat/Behat/assets/190447/b0ab1f0c-86e1-4fef-af89-01271a3ee068)

## Environment

PHP 8.3 from the [official Docker image](https://hub.docker.com/_/php).

**Comment by jakzal** [comment]
Looking at the recent changes, the only relevant change that could break the phar during the upload is #1430.

**Comment by theofidry** [comment]
I'll check this ASAP, but I would highly recommend Behat to do a smoke test of the PHAR at least, e.g. calling `behat.phar --version`

**Comment by theofidry** [comment]
Looking at [this](https://github.com/stof/Behat/blob/7470472ccbb346928a248cf86fa1222cf28f3460/.github/workflows/build.yml#L104C61-L104C65) it's not really worth for me to try to investigate this any further.

I'm happy to help if there is issues with upgrading, but I'm not willing to support a version I had no hands in and that is [7 years old](https://github.com/box-project/box2/releases/2.7.5).

**Comment by acoulton** [comment]
The workflow is now fixed (by upgrading to latest box) by @heiglandreas in #1462 - there will be a valid phar for the next release, coming soon.
