### ISSUE TITLE
Extension for auto naming parameters

### ISSUE THREAD

**Issue by ash-m** [Behat/Behat#1458]
It's so easy to preface your value with phrasing describing the value you wish to pass. I know it doesn't follow cucumber syntax, but perhaps there is something we can add as an extension that would enable an unused character to identify a value's name; for example, we could indicate a word should be used when a value is preceded/followed by a comma:

    Given I am in a directory, "test" // $test
    And I have a file with filename, "foo" // $filename
    And I have a file with filename, "bar" // $filename
    When I run the command, "ls"  // $command

    Given there is a product, "Sith Lord Lightsaber", with the price-tag, £5 // $product, $priceTag
    When I add the product, "Sith Lord Lightsaber" to the basket // $product
    Then I should have 1 product in the basket // $arg1
    And the the basket should have an overall £9, price // $price

    Given the Maker has started a game with the word, "silky" // $word
    When the Breaker joins the Maker's game
    Then the Breaker must guess a word with a character-count, 5 // $characterCount

Maybe `word, "value", word` would take the left word. It wouldn't work everywhere and there is always the cost of readability, but I am VERY often writing in my scenario: `a foo "foo"` specifically because I don't always remember what $arg1 even is, especially if I define a lot of steps at once.

There are other ways one could decide to do this, like it doesn't appear that {} is used for anything in an actual feature file. Of course we have syntax that omits words `()` but I think that having {foo} would kind of pollute the readability of the feature.

Anyway, I only propose it as an optional extension. It would, at the very least, save _me_ time; and what's the worst case scenario? People have to change parameters like `$domain` instead of `$arg1`?

**Comment by ciaranmcnulty** [comment]
In general we aren't going to make any gherkin syntax changes here - rather we are striving for more and more compatibility.

It might be one for https://github.com/cucumber/gherkin if we can do it in a language-agnostic way?

**Comment by ash-m** [comment]
For anyone that comes across this, if you want to quickly remap your arguments to the word before (excluding "of"), here's an awk script:
```awk
/@(Given|When|Then)/ {
    str = $0
    while (str != "" && match(str, /(\S+)( of)? [^\w\s]?:(\S+)/, arr) > 0) {
        str = substr(str, RSTART + (RLENGTH ? RLENGTH : 1))
        k = n[arr[1]]++ ? arr[1] n[arr[1]] : arr[1]
        k = gensub(/(\s|-)(.)/, "_\\2", "g", k)
        k = gensub(/\W/, "", "g", k)
        a[k] = arr[3]
    }
}

/[:$]arg/ { for (key in a) { gsub(a[key], key) } }
/^    }/ { delete a; delete n } 1
```

It doesn't look for any special characters; it just takes the word beforehand. If you have multiple of the same you get a number: `function some_example($price, $address, $address2, $price2, $the) // some might not make sense`
