### ISSUE TITLE
getScenario() has to return a Scenario but returns an ExampleNode so the getTitle() function didn't works as expected

### ISSUE THREAD

**Issue by cavo789** [Behat/Behat#1470]
Hi all

I've multiple scenarios and some are `Scenario Outline`.

I'm using a hook for `@BeforeScenario` like 

```php
public function beforeScenario(BeforeScenarioScope $scope): void 
{
}
```

Below my debugging session in vscode:

![image](https://github.com/Behat/Behat/assets/355999/d6400a32-ba1c-43db-89fc-8cb92e904010)

We can see `$scope` is well a `BeforeScenarioScope` and in my console, `$scope->getScenario()` is returning an `ExampleNode` and that's **wrong** since the docblock for `getScenario()` tells it should be a Scenario

File src/Behat/Behat/Hook/Scope/BeforeScenarioScope.php
```php
    /**
     * Returns scenario.
     *
     * @return Scenario
     */
    public function getScenario()
    {
        return $this->scenario;
    }
```

(the docblock is not correct)

By dumping the `$scope` object, we can see there is a private attribute `outlineTitle` and I've retrieved a `getOutlineTitle()` so I'm unblocked...

But it is normal?  I'll need to check if I'm facing a Scenario or an ExampleNode and depending on what, use `getTitle()` in the first case and `getOutlineTitle()` in the second case.

Tanks

**Comment by uuf6429** [comment]
See also #1459 ... it might be related..

**Comment by carlos-granados** [comment]
@cavo789 the code is actually correct. The scenario scope declares that it returns a `Scenario` but this is actually an alias for a `ScenarioInterface`. `ExampleNode` implements the `ScenarioInterface` interface, so it is fine that this function returns an `ExampleNode`. You should be able to use the methods in the interface to retrieve any information that you need.

Closing this issue, thanks for reporting it.

**Comment by stof** [comment]
I would suggest removing the alias in the code, to avoid such confusion

**Comment by uuf6429** [comment]
@stof I believe that removing the alias won't solve the confusion/problem, it just replaces the wording:
- `wrong since the docblock for getScenario() tells it should be a Scenario` -> `... tells it should be a ScenarioInterface`
- `I'll need to check if I'm facing a Scenario or an ExampleNode` -> `... ScenarioInterface or an ExampleNode`

I would propose the following isntead (although I'm not against removing the alias either):
- `ExampleNode` is too vague. `ScenarioExampleNode` (or similar) might have avoided this issue altogether.
- to solve the 2nd point above, I propose that getTitle() automatically switches to the outline title, because that is what is expected most of the time.
   If I'm not mistaken, one can always have something like `if ($node instanceof ExampleNode) $originalTitle = $node->scenario->getTitle()` (pseudocode) if the original title is wanted.

Just my 2 cents though :)

**Comment by stof** [comment]
@uuf6429 seeing `@return ScenarioInterface` would allow users to see that it returns a ScenarioInterface, not a ScenarioNode object, without having to scroll up to see that there is an alias applied. If the return type says it should be a ScenarioInterface, things will be clear for users getting an ExampleNode when they see `class ExampleNode implements ScenarioInterface` 

Renaming node classes in behat/gherkin is a BC break, and I'm not sure this is worth it.

**Comment by uuf6429** [comment]
@stof on the whole it's clearer, true. But there is still a bit of a wtf factor when it comes to that class name.

Anyway, if such a renaming would/could make sense, we could make use of `class_alias`'es (until the next major release). We can reconsider later if this makes sense.

**Comment by stof** [comment]
Renaming ExampleNode to ScenarioExampleNode is not worth it IMO.

If we were doing BC breaks anyway, we would rather work on migrating to something like Cucumber's pickles, where the gherkin AST is turned into a separate data structure for the execution (where there is no difference between scenarios written as ScenarioNode or expanded from an Outline with multiple ExampleNode, and where BackgroundNode is gone as its steps are inlined)

**Comment by carlos-granados** [comment]
Agree with @stof that renaming `ExampleNode` and creating a BC break is not worth it. I think that removing the aliasing should be enough. I am reopening this issue so that we can implement this removal

**Comment by uuf6429** [comment]
Just to be clear: a class alias (class_alias()) would not be a BC break. But it wouldn't be worth it anyway, if there's a plan to rewrite this code completely.

**Comment by carlos-granados** [comment]
Closed via https://github.com/Behat/Behat/pull/1500
