### ISSUE TITLE
Branch protection rules to allow merging maintainer PRs

### ISSUE THREAD

**Issue by acoulton** [Behat/Behat#1482]
@everzet could you help with this?

# Proposal

* Change the protection rules to officially require only 1 review before merging.
* @carlos-granados and I agree on trust that we will not merge an external contribution until we've both looked at it.

# Background

As identified in #1463 the current branch protection means @carlos-granados and I cannot merge each other's contributions - because you can't review your own PR on GitHub, so we can't meet the "2 approvals required".

We don't want to have to keep placing demands on other/less-available maintainers (@stof kindly stepped in to approve that one). It also seems odd if @carlos-granados and I can jointly merge external contributions but not our own.

Other solutions I've considered:

- I don't think there's a GitHub setting to allow a maintainer to approve their own PR. 
- We could set up more complex layered rulesets so there's a hard restriction of 1 review approval and then a second rule for 2 approvals that maintainers can bypass. However that still can't be targeted at e.g. internal/external contributions so is more complex but no more secure than just having 1 rule and a trust-based workflow.

**Comment by everzet** [comment]
Done.

**Comment by everzet** [comment]
... both Behat and Gherkin repos BTW

**Comment by acoulton** [comment]
Amazing, thanks @everzet
