### ISSUE TITLE
Using interactive communication channels to discuss Behat development

### ISSUE THREAD

**Issue by AlexSkrypnyk** [Behat/Behat#1510]
Looking at the Gitter chats, it looks like the community has thinned quite significantly.

1. What is the view on continuing to use interactive channels like Gitter or Discord to discuss the development of the Behat itself and provide support for the community? 
2. Should we move to Discord?

**Comment by carlos-granados** [comment]
@AlexSkrypnyk this has already been discussed in this GitHub discussion https://github.com/Behat/Behat/discussions/1493 I am closing this issue, please add any input in the discussion
