### ISSUE TITLE
Improve test failure output when behat output does not match the expected output

### ISSUE THREAD

**Issue by acoulton** [Behat/Behat#1522]
#1515 improved the output for the basic `It should pass` and `It should fail` steps - but also highlighted that these are generally "fallback" assertions because in many cases we are (or should be) using `It should pass with:` or `It should fail with:` to assert that the behat output includes expected content.

These steps have to perform partial matches on the output to avoid excess verbosity in our feature files and coupling to irrelevant details.

However, working on #1521 I realised that the output of these steps is also quite hard to work with if the expectation fails. They're implemented using PHPUnit's `Assert::assertStringContainsString` which isn't ideal for this usecase because:

* It can only render the complete actual and expected strings, which in our case are often big blocks of text. If the difference is a single word (or e.g. a missing `.`) it's virtually impossible to see without copying the two blocks and pasting into a diffing tool.
* It renders explicit `\n` for newlines in the actual content (maybe other special characters) but prints the expected content as-is. As well as making the difference harder to spot, it also makes it difficult to paste the actual into a diff tool or indeed back into the scenario if you're happy with the actual output and just want to update the expectation.

We could improve DX quite a bit by making these assertions produce a more helpful output.

One option would be to experiment with `sebastian/diff` and see if we can get it to produce a diff which ignores any extra content before or after the expected string. Alternatively we could maybe use `str_contains` for the actual assertion, and then just show a diff of the whole output if it fails - which would probably still be easier to read than the status quo.

**Comment by carlos-granados** [comment]
Great idea, using some kind of diff tool would certainly help a lot

**Comment by jdeniau** [comment]
While doing #1515, I though of that too, because having the full output of the test output is useless and having a diff would be so much helpful !

**Comment by jdeniau** [comment]
I tried it quickly with sebastian/diff and it seems nice. A potential problem is with the extra content, but it gives us a "parse" that can probably help us clean the output.

![image](https://github.com/user-attachments/assets/149c7cbb-64b9-4761-8f05-68b60109c86c)

**Comment by acoulton** [comment]
Related - while looking at a build failure I've just noticed that the assertion from our `it should fail with no output` step is also quite unhelpful:

![image](https://github.com/user-attachments/assets/b0eb1699-7b5c-48e8-b857-5ff69679b92e)

We could probably just make that throw with the output rather than using the `assertEmpty`

**Comment by jdeniau** [comment]
I was thinking about the extra content in the output, due to the fact that we check only il the expected string is included in the actual output.
I think that it's OK to output the full diff instead of trying to locate the exact same diff lines:
- it's only a feature to improve behat's development experience (not a public API), 
- it's really easy for a human to ignore the extra lines and to focus on the diffed lines,
- creating a specific algorithm to remove the extra lines will result in a complex algorithm for something that, in the end, should not happen.

If your are OK with this, the implementation should be pretty straightforward.

**Comment by acoulton** [comment]
I had a similar thought - we could spend a lot of time trying to make a "relevant" diff and then find it doesn't show what we want or passes / fails unexpectedly. And as with the discussion on #1515 sometimes there might be information in the other parts of the output that explains why the expected part is not matching.

I'd be happy with a straightforward `str_contains()` to do the actual check (to match current behaviour) and then just render the whole diff if it fails - I think that will be massively clearer than what we have now.
