### ISSUE TITLE
PyString indentation issue

### ISSUE THREAD

**Issue by trampgeek** [Behat/Behat#1531]
**EDIT:  PLEASE IGNORE.** We have found the problem. A recent change to our JavaScript implements autoindent when one types directly into a textarea. Apparently, the "I set the field ... to" statement simulates character-by-character typing rather than simply setting the entire contents to the given value, as I had expected.

I am using behat in a Moodle development environment. A behat feature that has worked fine for months has suddenly stopped working, though the feature file itself is unchanged. The failure is occurring in three independent environments: GitHub CI, my own [moodle-plugin-ci](https://github.com/open-lms-open-source/moodle-plugin-ci) environment, and a native Moodle + behat environment on Linux. It can't be just a Moodle version problem, as the failure occurs with all Moodle versions in the GitHub CI run.

I have tracked the problem down to the following behat statement within the offending feature file, which inserts Python code into a form field:
<pre>
    And I set the field "id_template" to:
  """
  import subprocess, json, sys
  {{ STUDENT_ANSWER | e('py') }}
  tests = json.loads('''{{ TESTCASES | json_encode | e('py') }}''')
  test_results = [['Test', 'Expected', 'Got', 'iscorrect']]
  num_right = 0
  for test in tests:
    code = test['testcode']
    expected = int(test['expected'])
    got = eval(code)
    test_results.append([code, expected, got, expected == got])
    if expected == got:
      num_right += 1
  print(json.dumps({
    'testresults': test_results,
    'fraction': num_right / len(tests)
  }))
  """
</pre>

What that now produces in the target field is:

<pre>import subprocess, json, sys
{{ STUDENT_ANSWER | e('py') }}
tests = json.loads('''{{ TESTCASES | json_encode | e('py') }}''')
test_results = [['Test', 'Expected', 'Got', 'iscorrect']]
num_right = 0
for test in tests:
  code = test['testcode']
    expected = int(test['expected'])
      got = eval(code)
        test_results.append([code, expected, got, expected == got])
          if expected == got:
              num_right += 1
              print(json.dumps({
                'testresults': test_results,
                  'fraction': num_right / len(tests)
                      }))
</pre>

It appears that behat is autoindenting each line to match the previous line, then *adding* my own indentation to that. This is contrary to the specified behaviour:

"Indentation of the opening """ is not important, although common practice is two spaces in from the enclosing step. The indentation inside the triple quotes, however, is significant. Each line of the string passed to the step definition’s callback will be de-indented according to the opening """. Indentation beyond the column of the opening """ will therefore be preserved."

I have experimented with various alternative base-indentation levels within the PyString (e.g. no indentation, 2, 4 and more) and with different increments within the Python code (1 char, 2 chars and 4 chars). The problem persists in all cases.

I can't be sure what version of behat is running in the moodle-plugin-ci on github, but in my native environment it's behat 3.13.0. This is a relatively old version (April last year) so unless Moodle has somehow triggered an update from an even older version, it seems unlikely that the problem is with behat alone. OTOH the fact that the problem occurs with multiple versions of Moodle (4.1, 4.2, 4.3 and 4.4) and PHP (7.3, 7.4, 8.0, 8.1 and 8.2) seems to rule out Moodle as the source. Leaving with nowhere to look! Any help would be much appreciated.

**Comment by acoulton** [comment]
@trampgeek thanks for the update - yes, that's correct that (most of?) the browser-based Mink drivers set field values by typing into them, as that's the best simulation of user behaviour (e.g. firing keyboard and `input` events as well as just the final `change`).
