### ISSUE TITLE
Snippets using attributes need new import statements or using fully qualified names

### ISSUE THREAD

**Issue by carlos-granados** [Behat/Behat#1553]
Once https://github.com/Behat/Behat/issues/1379 is finished we will have snippets that will look like:

```
    #[Given('there is a step')]
    public function thereIsStep()
    {
        throw new PendingException();
    }
```

The problem is that for this to work, the user also needs to add a `use` statement like this one:
```
use Behat\Step\Given;
```
If they don't add it, the step won't work and they may be left wondering why.

We need to explore two possibilities:

- Also adding the `use` statement when adding or listing snippets    
- If that is not possible or it is too hard, using FQNs when generating the snippets. The user can then convert them to a `use` statement + class name if they want

**Comment by fmatsos** [comment]
All is done in PR #1549 

Snippet generation will add use statements too.
Also, we show which use statements need to be added when we display snippets to add (cf. https://github.com/Behat/Behat/pull/1549#issuecomment-2517680785).
