### ISSUE TITLE
[RFC] Upgrade code to latest PHP 8 features

### ISSUE THREAD

**Issue by fmatsos** [Behat/Behat#1561]
A rather significant project, but one that will need to be addressed at some point 😄 

As the title suggests, this involves upgrading the code using the latest features provided by PHP 8, such as constructor property promotion, method and property typing, replacing FQCNs with `::class`, etc.

This will allow:

* to have more modern code
* to remove superfluous code (PHPDoc, etc.)
* to facilitate debugging thanks to typing

I suggest creating one issue for each type of change to keep PR as small as possible, make reviewing easier and isolate changes.

**Comment by acoulton** [comment]
@fmatsos thanks for this - I completely agree but I'm going to close it as it is somewhat covered by / overlaps with #1306 and #1506 as well as the work that @carlos-granados has started to improve our Psalm level.

In the meantime we are taking the opportunity to upgrade individual parts of the codebase if / when they're affected by a PR for any other changes.
