### ISSUE TITLE
Migrate features from annotations to attributes

### ISSUE THREAD

**Issue by fmatsos** [Behat/Behat#1563]
With #1549 we started to migrate some annotations to their attributes equivalents. We have restricted migration to the only features and scenarios that are required in this PR.
Since changes are now merged, we can now migrate the rest to attributes too.

First concerns are Step annotations. But we can also migrate the other types of annotations (like Transform, beforeStep, etc.)

**Comment by carlos-granados** [comment]
Completed via https://github.com/Behat/Behat/pull/1564
