### ISSUE TITLE
Definition override does not work with attributes

### ISSUE THREAD

**Issue by fmatsos** [Behat/Behat#1565]
With migration in #1563, from annotations to attributes in features, a problem occurred with `definitions_override.feature`.

When we migrate the annotation from parent context to attribute, the tests don’t work anymore. But they pass when we rollback to annotation.
Of course, required use statements have been added to use the equivalent attribute.

**Comment by stof** [comment]
Note that as long as annotations are not dropped, this particular case is probably a case that deserves being tested with both attributes and annotations.

This feature is indeed broken for Attributes. `AttributeContextReader` does not contain the equivalent code than the logic in AnnotatedContextReader

**Comment by fmatsos** [comment]
In #1564 I kept annotations at the moment.
I'll check to complete the `AttributeContextReader` and update related feature next (I'll test both annotations AND attributes so).

Thx @stof!
