### ISSUE TITLE
behat.phar is not executable

### ISSUE THREAD

**Issue by dkmuir** [Behat/Behat#167]
With composer, all I need to do is:

``` bash
curl -s http://getcomposer.org/installer | php
mv composer.phar ~/bin/composer
```

With behat, I have to do:

``` bash
cd ~/bin
wget https://github.com/downloads/Behat/Behat/behat.phar
echo '#!/bin/sh
php behat.phar $@' > behat
chmod +x behat
```

I tried adding a shebang line to behat.phar, the first time I corrupted the archive (probably a character encoding issue), the second time, it made it fail the sha1 signature check. Installing via composer takes several minutes  vs 5-10 seconds for the phar, so it would be nice if the phar installation was a bit friendlier.

**Comment by richardfleming** [comment]
Hi.  Sorry to post in an old issue, but in the latest behat.phar, the shellbang is missing. 

I'm new to behat, so I don't know if this is expected behaviour 1.5 years later.

Rich

**Comment by shrikeh** [comment]
I'll take this one.

—

**Comment by richardfleming** [comment]
Perfect.  I'll download the latest from releases.

I downloaded behat by following the quick-intro guide on behat.org which instructs you to download https://github.com/downloads/Behat/Behat/behat.phar

Thanks!

**Comment by stof** [comment]
hmm, github.com/downloads is the legacy download system of Github, which has been shutdown more than 1 year ago. I did not even thought that the old files where still available through it. What you downloaded using this link is the 2.4.0 release
