### ISSUE TITLE
Access MinkExtension properties from AfterFeature hook

### ISSUE THREAD

**Issue by fgimenez** [Behat/Behat#196]
Hi, I would like to visit a cleanup url from an AfterFeature hook. The domain of this url is the same as the base_url MinkExtension parameter set up in behat.yml, but being the hook a static method I cannot use $this->getMinkParameter('base_url'). 

What is the best approach for reusing that value?

Thanks a lot, keep up the great work

-- Federico

**Comment by brice** [comment]
Hello, i have the same issue with Behat 3.0.15. What is the most clever solution to use? Thanks
