### ISSUE TITLE
Feature: Add option to command line tool showing full stacktrace if Exception occurs

### ISSUE THREAD

**Issue by dready** [Behat/Behat#205]
At the Moment if an Exception occurs there is no way of telling where it occured.

Normally PHP would generate a stacktrace letting me know where the failure occurs.

It would be great to have an option so i can see the full stacktrace information.

thx

**Comment by varas** [comment]
With 3.0.15 and running with `--verbose` I do not see the exception stacktrace, am I missing something?

**Comment by everzet** [comment]
@varas stack traces are hidden behind very verbose mode `-vv`

**Comment by varas** [comment]
Great! thanks

**Comment by jessedoj** [comment]
Has somethinjg changed since this was written? -vv is not an option it would appear?

`exec vendor/bin/behat --config=tests/behat/behat.yml --format=progress --vv`

The "--vv" option does not exist.

**Comment by jessedoj** [comment]
Got it. It now appears to be: --verbose=2

**Comment by acoulton** [comment]
@jessedoj the `-vv` is a shorthand argument so has one `-` e.g. `-v` = `--verbose=1`, `-vv` = `--verbose=2`, `-vvv` = `--verbose=3`.

**Comment by stof** [comment]
@jessedoj the issue is that you use `--vv` while the answer above was talking about `-vv` (notice the single dash)
