### ISSUE TITLE
Wrong exit code

### ISSUE THREAD

**Issue by jekakm** [Behat/Behat#221]
Hi, we have failed build, but behat script return 0 exit status code and travis-ci marked build as stable.
https://travis-ci.org/jekakm/ls-plugin_seo/builds/3607349

I run behat with command:
`HTTP_APP_ENV=test cd tests/behat/ && php behat.phar --config='../../plugins/seo/tests/behat/behat.yml'`

**Comment by frankcarey** [comment]
For those finding this - Note that there is now a --strict option
