### ISSUE TITLE
Definition list should use a localized story syntax

### ISSUE THREAD

**Issue by kix** [Behat/Behat#269]
When calling ```bin/behat -dl --lang=ru``` I get all the step definitions, yet the story syntax still uses english. Perhaps it would be nice to output Given/Then/When keywords in requested language too?

**Comment by jossemarGT** [comment]
Bumping in this old issue, is the story syntax localization supported for the3.0.15 release? In order to use Dado/Cuando/Entonces instead of Given/When/Then.

BTW, excuse me if I'm asking for something that already exist, but, I didn't find documentation related to syntax localization.

**Comment by jossemarGT** [comment]
If someone else has the same resquest/question, behat already support gherkin internalization as you can read in the [docs] (http://docs.behat.org/en/latest/guides/1.gherkin.html#gherkin-in-many-languages) also you can check the Behat/Gherkin repo and its [keyword sets](https://github.com/Behat/Gherkin/blob/master/i18n.php) for every supported language.

**Comment by stof** [comment]
Closing this as Behat 3 properly uses the translations for keywords (example step texts themselves are not translated, but maintaining such translations in gherkin is not worth it IMO)
