### ISSUE TITLE
Json format similar to Cucumber's (for Jenkins plugin and other things)

### ISSUE THREAD

**Issue by MPV** [Behat/Behat#292]
Hi, 
Have you seen this Jenkins plugin?
https://github.com/masterthought/jenkins-cucumber-jvm-reports-plugin

What do you think about supporting this plugin (i.e. the cucumber.json format)?
https://www.relishapp.com/cucumber/cucumber/docs/json-output-formatter

I've seen there is a JSON formatter for Behat but it appears to have a different format?
https://github.com/Behat/CommonFormatters/blob/master/src/Behat/CommonFormatters/JsonFormatter.php

Or do we have another formatter for Behat that supports this format already?

**Comment by pluseg** [comment]
Hi, guys! @everzet, @stof, we've created this formetter https://github.com/Behat/Behat/issues/639. Should we create PR with it? Could you give any feedback?

**Comment by everzet** [comment]
@pluseg care to send a PR for next minor - 3.2?

**Comment by MPV** [comment]
@pluseg / @everzet / @stof: Was this added into Behat?

**Comment by everzet** [comment]
No

**Comment by CeloJon** [comment]
@pluseg / @everzet / @stof. It is now possible to do the behat tests in Jenkins?
