### ISSUE TITLE
Can't exclude multiple tags from command line?

### ISSUE THREAD

**Issue by GalCohen** [Behat/Behat#334]
Tried all of these:

behat --tags ~test,test2

behat --tags ~@test,~@test2

behat --tags ~test,~test2

seems only the second tag gets excluded. What I want is two exclude tests that have either the first tag or the second tag.

**Comment by davidfaj** [comment]
> `,` is **"or"**. `&&` is **"and"**

I couldn't find this in Behat docs. Could this be written there?
