### ISSUE TITLE
Get a list of scenarios

### ISSUE THREAD

**Issue by patxi1980** [Behat/Behat#337]
I will find very usefull to have an option for formatting behat output only to list the scenarios that i have in the application.

The progress option is fine, but if i want only the list of scenarios i have it is useless.

The pretty option has the scenarios, but also have the steps, so it have too much information.

I understand that i have to have control of which scenarios i have and which not, but nowadays i have more than 200 scenarios (and growing), and sometimes it is difficult to know which ones are missing, and which ones are obsolete.

**Comment by netraagal** [comment]
Hi,
Is this solution developped on the actual version ?
