### ISSUE TITLE
git fsck errors with "contains duplicate file entries"

### ISSUE THREAD

**Issue by ithinkihaveacat** [Behat/Behat#341]
A clone of the Behat github repo, followed by a `git fsck` reports an error:

``` sh
$ git clone git@github.com:Behat/Behat.git
...
$ cd Behat
$ git fsck --no-reflog --full --strict
Checking object directories: 100% (256/256), done.
error in tree 7708dad681f44c1d69c369c9b1bd55832ee4eb52: contains duplicate file entries
Checking objects: 100% (13578/13578), done.
```

I'm not sure what the implications of this error are, but, for example, with the repo in this state it's not possible to push the clone into a new github repo:

``` sh
$ git push -u test master
Counting objects: 13425, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5972/5972), done.
remote: error: object 7708dad681f44c1d69c369c9b1bd55832ee4eb52:contains duplicate file entries
remote: fatal: Error in object
error: pack-objects died of signal 13
error: failed to push some refs to 'git@github.com:ithinkihaveacat/test.git'
```

(Forking via github does work, though.)

**Comment by yjqg6666** [comment]
$git ls-tree 7708dad681f44c1d69c369c9b1bd55832ee4eb52
160000 commit 7d7191e44d5d810d690ee16b17eca27743a7243a	gherkin
160000 commit 2ae542748a8065aba925b44b99755010dbf12ac9	symfony
160000 commit 76280e55c7058afcbce623eae571cf1bf7c22b84	symfony
160000 commit 29d7d138597baee23786285feba384ae694d51cf	symfony
160000 commit 9c807fe281c09655e9136df287aafc811bdd7ac1	symfony
160000 commit 348b27d333e9b4d65bd25ffb9cc69c419a5e83fe	symfony
160000 commit f70e0ba1b04e7db4b3aa6d122470291d4fb34732	symfony
160000 commit 0603a77abada52469a7b889124dae57618441613	symfony


that's the source of the error.

reference: https://stackoverflow.com/questions/13178720/tree-contains-duplicate-file-entries

**Comment by stof** [comment]
Well, this messed up commit (this is 582125d1348451e5a8ba3a14ca46d2711c461943) was pushed to Behat in 2011, before Github enabled the fsck safeguard on each push.

AFAIK, there is no way to fix this without rewriting the full history of the Behat repo since then, which would be a major mess for the community (anyone having a clone or a fork of Behat somewhere would have to delete it and start over from the new history).
I'm not sure it is worth it, especially given that it does not forbid forking the repo on Github (as Github reuses the existing objects when forking).

**Comment by ithinkihaveacat** [comment]
Given that this has almost certainly caused zero actual problems in the four years since this was reported (the hash in the comment makes it pretty easy to find!) I don't think there's any reason to actually do anything about this.

Maybe this will cause someone some grief or bewilderment in the year 2043 when someone needs to do an unusual repo transformation but hey, they can just get their personal robot to sort it out while they float about merrily in their self-driving airship…

**Comment by yjqg6666** [comment]
just FYI. All the methods mentioned will rewrite the history.  The repo just can not be pushed if the remote enabled the fsck (transfer.fsckObjects, fetch.fsckObjects, receive.fsckObjects).

**Comment by stof** [comment]
Of course they will rewrite the history, as the issue is precisely the history.
