### ISSUE TITLE
Allow step regexes to span multiple lines.

### ISSUE THREAD

**Issue by MarkMaldaba** [Behat/Behat#348]
Currently, the regexes used for step definitions are not allowed to span multiple lines, which makes them very hard to work with when they are long.  It also throws CodeSniffer warnings in our context files due to the line-length checks we have in place.

Standard DocBlock parsing allows for tags to span multiple lines, and Behat should support this.  If the line following the @tag line starts with more than one space character, then it is considered to be a continuation.

(See the parseTags() function at https://github.com/phpDocumentor/ReflectionDocBlock/blob/master/src/phpDocumentor/Reflection/DocBlock.php for the phpDocumentor parsing algorithm.)

Given that this will be in the middle of a regex, we need to handle white-space in a sane and understandable way.  I propose that all leading/trailing white-space is stripped from the lines, so that there is no unexpected behaviour.  In situations where there is white-space at the point of the line-break, we allow the regex to be closed/opened so that this can be explicitly included.

This means that either of the following would be equivalent:

```
/**
 * @When /^I do something that has quite a long description and sp
 *         ans multiple lines such as "([^"]*)"$/
 */
```
```
/**
 * @When /^I do something that has quite a long description and /
 *       /spans multiple lines such as "([^"]*)"$/
 */
```
They would both result in the following regex:
```/^I do something that has quite a long description and spans multiple lines such as "([^"]*)"$/```

However, this is just a suggestion for implementation.  You may be able to come up with a better alternative to handling this.

The important point is to allow these regular expressions to be wrapped.

**Comment by filipslomski** [comment]
:(
