### ISSUE TITLE
Reimplement the JUnit formatter for 3.0

### ISSUE THREAD

**Issue by stof** [Behat/Behat#358]
3.0-RC1 does not have reimplemented the JUnit formatter. It needs to be reimplemented.

As JUnit supports grouping several ``<testsuite>`` tags into a ``<testsuites>`` tag (see the PhpSpec JunitFormatter), I suggest the following setup:

- a scenario is represented by a ``<testcase>`` tag (which is the logical way)
- a feature is represented by a ``<testsuite>`` tag (it is a group of scenarios)
- a suite is represented by the ``<testsuites>`` tag (it is a group of features)
- each Behat suite generates a separate XML file

**Comment by jaymecd** [comment]
Any progress on this feature so far? Tnx

**Comment by nchagrass** [comment]
@jaymecd see https://github.com/Behat/Behat/pull/676

**Comment by j-arnaiz** [comment]
Hello,

Not official but I implemented a junit extension, feel free to try and improve ;)

https://packagist.org/packages/jarnaiz/behat-junit-formatter

Regards!

**Comment by everzet** [comment]
Coming in 3.1
