### ISSUE TITLE
Reimplement the HTML formatter for 3.0

### ISSUE THREAD

**Issue by stof** [Behat/Behat#359]
Behat 3.0-RC1 does not have the HTML formatter anymore.

The new implementation needs to take into account the issues reported bout the 2.5 HtmlFormatter

**Comment by dutchiexl** [comment]
I created a plugin for HTML reporting, It works out of the box. It creates an array of suits, features, steps ... that can be rendered in a single template.

Since this works closely with symfony I used twig as a dependency. You can check it out or fork me. I could use some help creating a nice report.

I also added the plugin to packagist

https://github.com/dutchiexl/BehatHtmlFormatterPlugin.git

https://packagist.org/packages/emuse/behat-html-formatter

**Comment by emwalpole** [comment]
@dutchiexl Nice, yours is wayyy simpler than mine :)! I should look into Twig more.

**Comment by dutchiexl** [comment]
I could use some help, so if anyone feels compelled, give me a sign ;)

**Comment by WouterJ** [comment]
Btw, I recommended waiting till the jUnit thing is merged, as it'll provide a file system outputter, which can come quite usefull for HTML reports.

**Comment by iso13** [comment]
Getting the following message:

Warning: file_put_contents(/Users/dtran/Work/starwood/behat/vendor/emuse/behat-html-formatter/src/../reports/test_report.html): failed to open stream: Permission denied in /Users/dtran/Work/starwood/behat/vendor/emuse/behat-html-formatter/src/BehatHTMLFormatter.php on line 314

So ran it as sudo bin/behat --tags @dave -p test --format html --out test.html

Not outputting the test.html.  Any insight?

**Comment by dutchiexl** [comment]
This tag doesn't do anything from the plugin perspective: --out test.html

the report is always called test_report.html and is inside vendor/emuse/behat-html-formatter/reports.

The permissions on the folder should be so that behat can write to the folder.

Does this help ?

**Comment by iso13** [comment]
Thanks.  That works like a charm.

**Comment by DaSayan** [comment]
@dutchiexl I forked from your plugin to generate a HTML report with Behat 2 HTML report format.
It's a little dirty and there is many to be done, but it works...
Also, I wanted and managed to make the plugin working without Twig (for some reasons)

**Comment by dutchiexl** [comment]
Working without twig would mean creating an abstraction layer, which means alot of work :). I could check it out, but I can't promise it will be high on my priority list :/

**Comment by ichionid** [comment]
@emwalpole seems like you laid down a really useful tool. Being a composer json ignorant(:p) could you guide me a guid on how to install your plugin?

**Comment by dutchiexl** [comment]
Are you going to use composer or not ?

**Comment by ichionid** [comment]
I can use composer. I installed the initial behat through composer. Problem is that I am not 100% sure how it works.

**Comment by dutchiexl** [comment]
you should add
"emuse/behat-html-formatter": "dev-master",

to your "require" section of composer and do a composer update. This will install the plugin. Then just use the guide in github

https://github.com/dutchiexl/BehatHtmlFormatterPlugin.git

If you get stuck let me know

**Comment by ichionid** [comment]
Ok package was discovered. However, adding the lines proposed in the readme file I get an "

Invalid type for path "testwork.formatters.output_path". Expected array, but got string"

My .yaml looks like:
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  formatters:
    html:
    output_path: %paths.base%/build/html/behat
  extensions:
    emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
      name: html 
    Behat\MinkExtension:
      goutte: ~
      browser_name: chrome
      javascript_session: selenium2
      selenium2: ~
      base_url: http://my.local.dev
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drush' 
      drush:
        alias: 'self'
      text:
        log_out: "Log out"
        log_in: "Log in"
Btw big thanks for the help!

**Comment by dutchiexl** [comment]
Are you using behat 3 ?

Is the file indented like this:
<pre>
  formatters:
    teamcity: false
    pretty: true
    html:
      output_path: %paths.base%/build/html
</pre>

**Comment by ichionid** [comment]
yes behat 3

**Comment by stof** [comment]
@ichionid you have an indentation issue for the ``output_path``. It should be a child of ``html``, but you configured it as a child of ``formatters``

**Comment by ichionid** [comment]
@stof  I messed up the formatting before :)

**Comment by stof** [comment]
@everzet the question now is whether we want to put an HTML formatter in core or we consider than an extension is enough for that.

I see several advantages on an extension:

- it allows proper dependency management (relying on Twig for templates for instance)
- it could allow to have several extensions with different approaches to the reporting. For Behat 2, there is some 'advanced_html' formatters out there (or whatever name they choose) because some people wanted more things (or less things) than in the core formatter

**Comment by dutchiexl** [comment]
I am a fan of the extension, this would give you the most flexibility.

**Comment by stof** [comment]
@dutchiexl are you willing to continue maintaining it ?

**Comment by dutchiexl** [comment]
For the moment I certainly am. I would have to see at what point the extension is growing, for at the moment I do not know how many people are using it, and if there are a lot of new requirements.

**Comment by DaSayan** [comment]
For my part, I will continue to develop on my fork of dutchiexl's plugin.
I have some ideas to implement, and many cleaning to do.

But the logic that I want to follow is a quite different from dutcihiexl's version (with no Twig for example), so I don't know if it will be possible to merge my developments into dutchiexl, or if my fork will split off...
@dutchiexl  : what do you think about this ?

**Comment by dutchiexl** [comment]
I believe that we would profit by using one repositorie. À lot of functionality would still be the Same even if different rendering engines are used. In my opinion the rendering should be an abstraction.

**Comment by DaSayan** [comment]
@dutchiexl Ok I am agree with you.
I am working to make the rendering behind an abstraction layer.. 
I think also that I will reintegrate your Twig report at side of the Behat 2 HTML report, behind this abstraction, and let the choice to choose the report format in the behat.yml config file. 
Also, it will be possible for somebody to add new report formats if he wants.

**Comment by narozhniyy** [comment]
Hi everyone, I add this to my behat.yml :
  formatters:
    html:
      output_path: %paths.base%/
    extensions:
      emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
        name: html
        renderer: Twig
        file_name: Index
        print_args: true
        print_outp: true
        loop_break: true

And behat show error :   [Behat\Testwork\Output\Exception\FormatterNotFoundException]                                                              
  `html` formatter is not found or has not been properly registered. Registered formatters: `junit`, `progress`, `pretty`.
Can anybody help me?

**Comment by legovaer** [comment]
Your issue does not belong here, the extension you are using is not inside the core of Behat. If you need support on this extension, create a new issue in the project page of [BehatHtmlFormatterPlugin](http://github.com/dutchiexl/BehatHtmlFormatterPlugin).

When you create your issue, make sure that the output of your behat.yml is formatted using [Markdown](https://guides.github.com/features/mastering-markdown/). That will be easier to read.

**Comment by narozhniyy** [comment]
@legovaer ok, thanks. How I can create html report with using Behat 3 core?

**Comment by legovaer** [comment]
@narozhniyy If you had read the entire page you would have noticed [this](https://github.com/Behat/Behat/issues/359#issuecomment-78283037) comment. Currently it's not possible to output HTML using only Behat 3.x's core functionality. 

However, using the [BehatHtmlFormatterPlugin](https://github.com/dutchiexl/BehatHtmlFormatterPlugin) extension developed by @dutchiexl will allow you to generate HTML. If you are facing any issues using this extension, create a new issue on the extension's GitHub project page.

**Comment by narozhniyy** [comment]
@legovaer this is the most useless discussion, read and write about that Behat 3 dosen't have html reports, people need examples, and solutions, and when I ask about ask about issue of one solution which describe on entire page you say don't write here, write in new issue, but this theme about Behat 3 html reports as and my question too.

**Comment by narozhniyy** [comment]
bin/behat --tags "@lb-compare" -f pretty -f html --out report.html

  [Behat\Testwork\Output\Exception\BadOutputPathException]                                    
  Filename expected as `output_path` parameter, but got `/var/www/behat3/behat/report.html`. 

I set filename as param in -out

**Comment by firegate666** [comment]
Stumbled across this issue and the BehatHtmlFormatterPlugin by @dutchiexl works awesome for me. Thx.

**Comment by davegerard** [comment]
Thanks so much @dutchiexl. I like the bouncing circle animation.

**Comment by rebajz** [comment]
@dutchiexl your html plugin is great. It possible to do in the future multi-language version? In behat 2.5.5 working --lang=cs and html report was in cs language....

**Comment by SamyOteroGlez** [comment]
I installed the plugin and I got this error: 
`[Symfony\Component\Config\Definition\Exception\DuplicateKeyException]  
  Duplicate key "html" for path "testwork.formatters".`
when run the behat command (vendor/bin/behat).

Here is my behat.yml:
`default:
    extensions:
          Behat\MinkExtension:
                base_url: http://localhost
                sessions:
                      first_session:
                          goutte: ~
                      second_session:
                          selenium2: ~
    formatters:
          html:
                output_path: %paths.base%
          extensions:
                emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
                name: html
                renderer: Twig,Behat2
                #file_name: report
                print_args: true
                print_outp: true
                loop_break: true`

here is my composer.json:
`{
  "require": {
    "behat/behat": "3.*@stable",
    "behat/mink": "1.*@Stable",
    "behat/mink-extension":  "*",
    "behat/mink-goutte-driver":     "*",
    "behat/mink-selenium2-driver":  "*",
    "behat/mink-sahi-driver":  "*",
    "emuse/behat-html-formatter": "0.1.*"
  }
}`

Any ideas?
Thanks in advanced.

**Comment by everzet** [comment]
I am really happy with HTML formatter being an extension. @dutchiexl are you still maintaining it? I'd be happy to give it official signal boost.

**Comment by everzet** [comment]
I think keeping HTML formatter outside the core makes sense. HTML formatter always felt like something very different to the rest of formatters. Conceptually it's more like a dashboard and I would like to see it evolving into something like interactive monitoring tool. Being part of core would constraint that.
