### ISSUE TITLE
Running scenarios and features in random order

### ISSUE THREAD

**Issue by redcapital** [Behat/Behat#43]
Running them in random order greatly helps when your tests aren't isolated enough or you are not confident in it. 
Ruby's [MiniTest](http://www.bootspring.com/2010/09/22/minitest-rubys-test-framework/) has such option (actually, it's a unit testing library, not BDD, but I don't see differences in this case). Take a look at the part **Randomization**. 
Basically, when you run your tests, the runner will run them in random order and show you a `seed` - special number. If something fails, you can rerun tests in a particular order passing that `seed` number to the runner as an argument.
I think it will be great to have this feature in Behat.

**Comment by c4rl** [comment]
Shot:

> Behat is not a testing tool

Chaser:

![behat-is-a-testing-tool](https://www.evernote.com/shard/s483/sh/884a2bf0-ebec-4930-92ed-7d4b6a34f291/6aa76145ef2171bb/res/4e113445-97ae-4cef-90b3-f0a3cb59e7a4/skitch.png)

**Comment by ircmaxell** [comment]
Requesting that this to be reopened, considering Behat is definitely used as a testing tool as much as a design tool.

**Comment by ciaranmcnulty** [comment]
This is actually in 3.1 IIRC

**Comment by ircmaxell** [comment]
Nevermind then

**Comment by greggles** [comment]
For anyone else who finds this the parameter is `--order=random`.

**Comment by patrinos** [comment]
It would be useful to allow for a randomization seed with --order=random so that a particular order (and issues discovered) is reproducible and therefore more easily debuggable. Within a CI workflow the seed could be the ticket number.
