### ISSUE TITLE
AfterStep hook doesn't run if the step fails

### ISSUE THREAD

**Issue by edysanchez** [Behat/Behat#504]
with behat 2.50 + mink-extension I had an afterStep hook which takes an screenshot when a step fails, with behat 3.0 that hook does not run when the step fails, I modified one of the hooks.feature scenario adding an afterStep hook and making a step fail to check and the same result (the hook does not run), it is that the expected behaviour?

**Comment by FedericoHenze** [comment]
This bug is happening again on the 3.1.1 version
