### ISSUE TITLE
Behat 3.0.4 parameter definition under Contexts

### ISSUE THREAD

**Issue by KashifSaadat** [Behat/Behat#524]
Hi,

Since updating from a beta version of Behat v3 to v3.0.4, I've been having issues with specifying parameters under my Contexts within the behat.yml file.

The context.feature example shows the following format:

```
    Given a file named "behat.yml" with:
      """
      default:
        suites:
          default:
            contexts:
              - FeatureContext:
                  parameter1: val_one
      """
```

My behat.yml is as follows:

```
default:
  autoload:
    '': %paths.base%/library
  suites:
    default:
      contexts:
        - FeatureContext:
            url:
              google:    'https://www.google.co.uk'
              bbc:         'https://www.bbc.co.uk'
            key2:         'val2'
```

This fails as my FeatureContext is passed NULL for the parameters. If I wrap all my parameters within FeatureContext under a 'parameters' key, then the above is loaded in successfully.

Please could you let me know the correct syntax to use for passing parameters through via the config file?

**Comment by sloba88** [comment]
But how do I nest parameters when I have FeatureContext class path defined? I am using Behat 3.0.15

```
default:
    suites:
        default:
            contexts: [Blah\Tests\FeatureContext]
```

I can't find this documented anywhere.

**Comment by stof** [comment]
Well, see the comment above giving the answer, where ``FeatureContext`` is the fully qualified class name of the context class. It works the same when the class is namespaced (except quoting the class name with single quotes may be needed to have a valid Yaml syntax because of the backslash, but I'm not even sure it is needed)

**Comment by sloba88** [comment]
Ah, I see, I somehow thought FeatureContext was reserved key name, not a class name. Thanks.

**Comment by weitzman** [comment]
This was the best place I found on the whole internet that explained how to pass params to context contructor. If its documented on docs.behat.org, I could not find it. Thanks.

**Comment by pwisowski** [comment]
default:
  suites:
    default:
      contexts:
        - FeatureContext:
            - base_url:
                'http://localhost:3000'

**Comment by pwisowski** [comment]
Try with '-' it should help

`default:
  suites:
    default:
      contexts:
        - FeatureContext:
            - base_url:
                'http://localhost:3000'
`
