### ISSUE TITLE
Calling a "step" from another one?

### ISSUE THREAD

**Issue by Ninir** [Behat/Behat#546]
Hi guys.

I have a question related to the new Shiny Behat version :)

Sometimes, you may be in a need of calling a step from another one. Previously, it was possible to do such thing from a given step:

``` php
/**
 * @When /^I do something$/
 */
public function iDoSomething($page)
{
    return new Step\Then('I should do this too');
}
```

Now, this stuff does not exist anymore, at least in the way presented above. From a code point of view, it is now a matter of calling a method much more than a step, as in:

``` php
/**
 * @When /^I do something$/
 */
public function iDoSomething($page)
{
    $this->iShouldDoThisToo();
}
```

However, is it a matter of organizing the code? Is there a way to call a given method for a given context?

If not, what would be the best thing to do for such thing please?

I may have missed something in the doc or misunderstood a given concept... Thanks for the help guys.

**Comment by johnhunt** [comment]
Unfortunately, I've found that actually removing this feature was a bad choice. I'm sure it could be abused but in my case (testing remote APIs) it was really important.. now trying to find a workaround :(

**Comment by timiTao** [comment]
@johnhunt This was abused too much. Maybe [PageObject](https://behat-page-object-extension.readthedocs.io/en/stable/) could help you with that matters :)
Or maybe you want to do too much in one scenario.

**Comment by johnhunt** [comment]
The only solution I've found is to create a monster context that does everything so I can run steps such as:
When I visit "https://blahblah" I expect the JSON node value "a.b.c" to equal "john" and retry 10 times, every 30 seconds.

What I'd really like to do is use the distinct out the box contexts and then just jump back.. oh well :/
