### ISSUE TITLE
Behat 3 - Communication between contexts

### ISSUE THREAD

**Issue by RynnHeldeD** [Behat/Behat#558]
Hello world ! :)

I am still exploring the huge potential of Behat 3 and got a new question about contexts.

On Behat 2, I was used to have a main FeatureContext which used many SubContexts. Then I was able to access/change class (context) methods/properties from other classes with : 

```
$this->getMainContext()->getSubcontext('subcontext_alias')->some_method();
```

From now, on Behat 3, the new doc says : 

> Basically, all contexts under contexts section of your behat.yml are the same for Behat. It will find and use methods in them same way it does in default FeatureContext. 

So if I have : 
## behat.yml

```
# behat.yml
contexts:
    - HelloContext
    - WorldContext
```
## HelloContext

```
# HelloContext.php
<?php
use Behat\Behat\Context\SnippetAcceptingContext;

class HelloContext implements SnippetAcceptingContext
{
     public $greetings = "Hello";
}
```

What should I do to be able to access and modify `$greetings` from `WorldContext` ?
## WorldContext

```
# WorldContext.php
<?php
use Behat\Behat\Context\Context;

class WorldContext implements Context
{
     public function changeGreetings(){
          // On Behat 2, I was doing 
          // $this->getMainContext()->getSubContext("HelloContext")->greetings .= " World !";
     }
}
```

Thanks !

**Comment by manuelgerstner** [comment]
This should solve the issue right? http://stackoverflow.com/questions/29674685/how-to-communicate-between-contexts-in-behat-3
