### ISSUE TITLE
Example row tagging

### ISSUE THREAD

**Issue by keithdtyler** [Behat/Behat#601]
Hi,

We have a lot of tests that can run in different locales. Our locales are represented as different sites spread across a few server nodes. However, for various reasons, we don't always want to run all locales (time consuming / limited changes to test). But the tests are otherwise the same.

We generallly have tests of the form:

``` gherkin
Scenario Outline: Go to main page and push button
Given I am on the "<country>" page
When I press the ".submit" button
Then I should see "<text>"
...

Examples:
| country | text |
| US | Hello |
| DE | Guten tag |
| FR | Bienvenue |
```

etc...

We tag the scenario with such things as `@us @de @fr` so that we can identify all test with, say, FR examples. But when we use `--tags=@fr`, it will find the whole scenario, and run the test three times, when we really only want it to run once, for FR.

It would be INCREDIBLY helpful if we could tag at the example, and have BEHAT execute only lines that match the requested tags. Such as:

``` gherkin
Examples:
| country | text |
@us @na | US | Hello |
@de @eu | DE | Guten tag |
@fr @eu | FR | Bienvenue |
```

Then we could do `--tags=@fr` to have only the FR example execute, or `--tags=@eu` to have DE and FR examples execute but not the US example.

The workaround to date has been to copy and paste the whole test, with only one example, and tag each scenario with `@us` or `@de` exclusively. But this is both wasteful, and also an awful maintenance nightmare -- we are going to end up with divergent tests because people will not know to make the same change in, say, 5+ copies of the same exact scenario!

**Comment by brianmrock** [comment]
Was this ever implemented?  This feature would be really useful for one of our projects.

**Comment by kocherovf** [comment]
Will you plan to implement this feature?

**Comment by ciaranmcnulty** [comment]
@kocherovf Who are you asking? It's an open-source project ;-)
