### ISSUE TITLE
Misleading message when locator points to feature(s) outside feature path

### ISSUE THREAD

**Issue by ciaranmcnulty** [Behat/Behat#630]
If I create a feature file outside of `features` and type:
```
bin/behat /path/to/my.feature
```
I get the error message `No specifications found at path(s) '/path/to/my.feature'.`

This is unclear, the message should reflect the fact that I specified a feature outside the allowed/configured paths.

**Comment by videni** [comment]
I don't think is syntax error, I  test it with a correct feature file ,  it still give this error ,

```
bin/behat --dry-run --append-snippets  features/order/browsing_orders.feature 
```
this  feature file is from Sylius
