### ISSUE TITLE
Output format junit/cucumber

### ISSUE THREAD

**Issue by movrack** [Behat/Behat#639]
Hello,

Before all, thanks! It's a really good job.

I am looking for formatting the output of V3. Currently as I see, there is only : progress and pretty.
I'd like to use it with Jenkins so I tried to search information about formatting with junit.
I found a topic for that who move 3 times #358 #378 #466, and #292 for the cucumber format.

Latest information look to be from april so 5 month ago.

Where we are ?
Which output is available ?
How I should configure my jenkins ?

Regards,

**Comment by timiTao** [comment]
@everzet will this be in behat at near future?

**Comment by Ere5** [comment]
Still no news about this?

**Comment by nchagrass** [comment]
it has been merged see #676

**Comment by Ere5** [comment]
Strange, i cant see it on available formats.
