### ISSUE TITLE
feature: Background Outline

### ISSUE THREAD

**Issue by jorgecolonconsulting** [Behat/Behat#64]
Having a Background Outline to test different variations of a given action or state would be great, that way you could cut down on some of the duplication that needs to be done now since Background Outline doesn't exist.

Example:

```
Feature: Sessions
    In order to query the API
    As a user
    I need to have a valid session

    Scenario Outline: Session header is sent and has to be valid
        # Internal Fuel URI is not the public URI, but it's the only way to fake a URI in Fuel internally.
        When I do a request on "<Internal Fuel URI>" via "<HTTP Method>"
        Given a Session HREF of "<Session HREF>"
        Then hasValidSession Method should return "<hasValidSession Boolean>"

        Examples:
        | Internal Fuel URI             | HTTP Method   | Session HREF          | hasValidSession Boolean   |
        | /sessions/post_index          | POST          | /sessions/abcdef      | TRUE                      |
        | /sessions/get_index           | GET           | /sessions/abcdef      | TRUE                      |
        | /sessions/update_index        | UPDATE        | /sessions/abcdef      | TRUE                      |
        | /sessions/delete_index        | DELETE        | /sessions/abcdef      | TRUE                      |
        |                               |               | /sessions/zyxwvu      | FALSE                     |
```

Can be changed to:

```
Feature: Sessions
    In order to query the API
    As a user
    I need to have a valid session

    Background Outline:
        When I do a request on "<Internal Fuel URI>" via "<HTTP Method>"

        Examples:
        | Internal Fuel URI             | HTTP Method   |
        | /sessions/post_index          | POST          |
        | /sessions/get_index           | GET           |
        | /sessions/update_index        | UPDATE        |
        | /sessions/delete_index        | DELETE        |
        |                               |               |

    Scenario Outline: Session header is sent and has to be valid
        # Internal Fuel URI is not the public URI, but it's the only way to fake a URI in Fuel internally.
        When I do a request on "<Internal Fuel URI>" via "<HTTP Method>"
        Given a Session HREF of "<Session HREF>"
        Then hasValidSession Method should return "<hasValidSession Boolean>"

        Examples:
        | Session HREF          | hasValidSession Boolean   |
        | /sessions/abcdef      | TRUE                      |
        | /sessions/abcdef      | TRUE                      |
        | /sessions/abcdef      | TRUE                      |
        | /sessions/abcdef      | TRUE                      |
        | /sessions/zyxwvu      | FALSE                     | 
```

Each Background Example will run once before each Scenario/Scenario Outline.

P.S. There's a reason why I used When, Given, Then instead of Given, When, Then.

**Comment by dancourse** [comment]
+1 for this suggestion. If the Background could take a table which the Scenario Outline also ran from it would save a LOT of duplication.

**Comment by muglio** [comment]
+1 Would <3  the ability to outline a background. It would be extremely helpful in bulk setting up test preconditions.

**Comment by stof** [comment]
Behat is **not** the creator of the Gherkin format (hint: this is the cucumber team). And our goal is to respect the Gherkin format so that feature files are independent of the tool used to automate their verification.

And given that neither @everzet nor me are convinced by this feature, we won't lobby to have such feature in gherkin itself

**Comment by deyikong** [comment]
7 years later, I still feel the need. You don't need to add it. but the need is there. I understand you want to respect the Gherkin format, but improvements are a better form of respect IMO.

**Comment by deyikong** [comment]
I was just searching about this feature, then I saw my comment... so there is still needs. :(

**Comment by irekg** [comment]
Yes there is. Tester from my team keeps bothering me with this issue. I also would like to have it.

**Comment by ciaranmcnulty** [comment]
As you say we want to stay compatible with Gherkin upstream (and there is effort to be more compatible in future)

I recommend opening this suggestion on cucumber/cucumber project and if it's accepted there we'd probably bring it into Behat
