### ISSUE TITLE
How to associate base_url between admin panel and site for two environments?

### ISSUE THREAD

**Issue by Sorbing** [Behat/Behat#643]
The situation:
1. There are 2 sites - `Admin Panel` and `Store Site`.
2. There are 2 environments - `stage` and `prod`.
3. I need to check the correct sorting of products on `Store Site`.
4. No direct access to the DB (to obtain sourсe sorting data for comparison). Therefore, the original data can be obtained only from `Admin Panel` page.

My scenario:
```
Given I am on "http://stage.admin.lcl/products/sorting"
And I remember the products sorting
When I am on "http://stage.store.lcl/home"
Then I compare the products sorting with Admin Panel
```
In my case, the dough is very related the `Admin Panel` and `Store Site`.. But I have no other way to get the source data for the test.
At the same time, it is necessary to test the scenario in different environments - `stage` and `prod`.

How do I specify the `base_url` for each site and each environmets, that would use the relative URLs in the scenarios?
Thanks.

**Comment by everzet** [comment]
What @gggeek said
