### ISSUE TITLE
Snippets for the following steps in the default suite were not generated (check your configuration)

### ISSUE THREAD

**Issue by umpirsky** [Behat/Behat#652]
If your context does not implement `SnippetAcceptingContext`, and you have undefined steps, when you run Behat you will get: 

```
--- Snippets for the following steps in the default suite were not generated (check your configuration):
...
```

I don't like "check your configuration" part, it can be missleading, as in this case, fix would be to just implement `SnippetAcceptingContext`.

**Comment by aRn0D** [comment]
I am agree with @umpirsky. It is not clear.

**Comment by ryancookdev** [comment]
I also agree. I lost some time looking through config settings trying to correct this.
