### ISSUE TITLE
Add a getScenario method to BeforeStepScope and AfterStepScope

### ISSUE THREAD

**Issue by cboyden** [Behat/Behat#653]
This would fix the issue reported in #650 - you could call $scope->getScenario()->hasTag() to check for the tag.

**Comment by stmllr** [comment]
The interface `StepScope` should provide an API for getting the scenario.

`StepScope` has an API for feature but not for scenario, though I would expect that from the structure `feature -> scenario -> step`

**Comment by kwisatz** [comment]
:+1:

**Comment by fugi** [comment]
:+1:

**Comment by rebajz** [comment]
I am looking forward to it so much. I need insert scenario name to screenshot name... ;-)
@AfterStep (afterStepScope)

**Comment by Taluu** [comment]
cf #795

**Comment by romaricdrigon** [comment]
Another way is : 
```php
            /** @var \Behat\Gherkin\Node\ScenarioNode $scenario */
            $scenario = current($scope->getFeature()->getScenarios());
```

Having a public method would a be must-have though. Event if it implements one of the "hacks" at the moment.

**Comment by Taluu** [comment]
The following is what I'm using currently ;

```php
<?php
    private function getScenario(StepScope $scope)
    {
        $scenario = null;

        $feature = $scope->getFeature();
        $step = $scope->getStep();
        $line = $step->getLine();

        foreach ($feature->getScenarios() as $tmp) {
            if ($tmp->getLine() > $line) {
                break;
            }

            $scenario = $tmp;
        }

        return $scenario;
    }
```
