### ISSUE TITLE
TranslatorExtension calls to deprecated method on Translator

### ISSUE THREAD

**Issue by bagonyi** [Behat/Behat#659]
Using `Translator::setFallbackLocale` in TranslatorExtension triggers a deprecation error using symfony/Translation 2.7.x-dev (commit e38aab50cf3c428dd018155ebaa3eabb88c5f27f introduced a `trigger_error()` 3 days ago).

Change:

    $definition->addMethodCall('setFallbackLocale', array($fallbackLocale));

To:

    $definition->addMethodCall('setFallbackLocales', array($fallbackLocale));

**Comment by zembaalbert** [comment]
+1 on this

**Comment by stof** [comment]
Fixed in https://github.com/Behat/Behat/commit/d8b73d1bd4925f926d8707c2d1e4ab5bd661c4b3 already

**Comment by zembaalbert** [comment]
as I see it's not released yet, right? probably it will be included in the next release. But, it's not a blocking issue anyways. 

cool. keep up the good work!

**Comment by stof** [comment]
yeah, it will be in the next release. We considered that it was not critical and so it did not deserved creating a new release just for that while we have some pending work in review.

anyway, I'm closing this issue

**Comment by sminnee** [comment]
FYI I fixed this on the 2.5 branch as well #717
