### ISSUE TITLE
Returning null from a @Transform function stops the transform happening

### ISSUE THREAD

**Issue by chrisemerson** [Behat/Behat#669]
I'm using the following feature file for testing:

    Feature: I should be able to transform values into different types for testing

        Scenario Outline: Converting different types
            Given I have the value "<value>"
            Then it should be of type "<type>"

            Examples:
                | value      | type       |
                | "soeuhtou" | string     |
                | 34         | integer    |
                | NULL       | null       |

And the following Feature Context:

    <?php
    use Behat\Behat\Context\Context;
    use Behat\Behat\Context\SnippetAcceptingContext;

    /**
     * Defines application features from the specific context.
     */
    class FeatureContext implements Context, SnippetAcceptingContext
    {
        /**
         * Initializes context.
         *
         * Every scenario gets its own context instance.
         * You can also pass arbitrary arguments to the
         * context constructor through behat.yml.
         */
        public function __construct()
        {
            unset($this->value);
        }

        /**
         * @Transform /^".*"$/
         */
        public function transformString($string)
        {
            return strval($string);
        }

        /**
         * @Transform /^\d+$/
         */
        public function transformInt($int)
        {
            return intval($int);
        }

        /**
         * @Transform /^NULL$/i
         */
        public function transformNull($null)
        {
            return null;
        }

        /**
         * @Given I have the value ":arg1"
         */
        public function iHaveTheValue($value)
        {
            $this->value = $value;
        }

        /**
         * @Then it should be of type :arg1
         */
        public function itShouldBeOfType($type)
        {
            if (gettype($this->value) != $type) {
                throw new Exception("Expected " . $type . ", got " . gettype($this->value) . " (value: " . $this->value . ")");
            }
        }
    }

Output:

    Feature: I should be able to transform values into different types for testing

      Scenario Outline: Converting different types # features\nulltransform.feature:3
        Given I have the value "<value>"           # FeatureContext::iHaveTheValue()
        Then it should be of type "<type>"         # FeatureContext::itShouldBeOfType()

        Examples:
          | value      | type    |
          | "soeuhtou" | string  |
          | 34         | integer |
          | NULL       | null    |
            Expected null, got string (value: NULL) (Exception)

    --- Failed scenarios:

        features\nulltransform.feature:11

    3 scenarios (2 passed, 1 failed)
    6 steps (5 passed, 1 failed)
    0m0.15s (5.46Mb)

The 'transformNull' method is definitely being hit when behat encounters the right value, but the transformation is ignored. Returning anything else causes the value to be transformed into whatever is returned, apart from null.

**Comment by sukei** [comment]
Here is the line of code that prevents null to be used as an acceptable value : https://github.com/Behat/Behat/blob/v3.0.14/src/Behat/Behat/Transformation/Transformer/RepositoryArgumentTransformer.php#L116-118

It's gonna be hard to change. Maybe we could use an object as a `null` value? Something like:

```php
/**
 * @Transform /^(~)$/
 */
public function castNull()
{
    return RepositoryArgumentTransformer::nullValue;
}
```

```php
if (null !== $newValue = $this->transformRegex($definitionCall, $transformation, $value)) {
    return $newValue === RepositoryArgumentTransformer::nullValue ? null : $newValue;
}
````

Any thought?

**Comment by timiTao** [comment]
i have idea, maybe create new extension
https://github.com/Behat/Behat/blob/master/src/Behat/Behat/Transformation/Transformer/ArgumentTransformer.php

that will will create i special chart, that normaly cann't be done in string? like null. 
I could be called specialChar(null),  specialChar(\n) etc 

?

One extension like this, i made - Clipboard for behat.

**Comment by chrisemerson** [comment]
The transformRegex, transformToken etc methods within RepositoryArgumentTransformer currently return null when they can't handle the current type of transform - perhaps they should be throwing exceptions instead of giving null a special meaning? That would make it a lot easier to handle.

**Comment by sukei** [comment]
@chrisemerson +1.

**Comment by everzet** [comment]
Thanks for reporting. This is definitely a bug.

**Comment by shrikeh** [comment]
I'll pick this one up.

**Comment by chrisemerson** [comment]
Awesome, thanks!
