### ISSUE TITLE
AutoGeneratedContext collects all contexts steps used in this suite ?

### ISSUE THREAD

**Issue by kendoctor** [Behat/Behat#670]
That's what I want. But, ...in V3. Step reusable, scenario reusable.

Step1 with more than one gherkin descriptions. (One To Many)
Step2 will never have the same gherkin description(s) with Step1.
It seems Step.GherkinDescriptions.
Then.
Context.Steps
MyProject.Contexts

Step3 reuse Context1.Step1 and Context2.Step2, Then exists in Context3

Then. Problem is in suites : which context should i put in ? 
Step3 depends on Context1 and Context2.

Idea. Build a auto-generated cached Context in run-time ?

AutoGeneratedContext collects all contexts steps used in this suite .

Extra:
smartTag in FriendlyContexts seems to need all features have correct definitions.
If not , I can not test just one feature file. It's not practical.

**Comment by everzet** [comment]
Gherkin is complex enough as it is. I don't see this functionality in the core. Feel free to build custom extension or join forces with Ryan from KnpLabs - they're building something like that.
