### ISSUE TITLE
 how to guarantee the code quality of implementation for user-defined steps or any others ?

### ISSUE THREAD

**Issue by kendoctor** [Behat/Behat#672]
I did not mention Gherkin programming. 
I mean How to organize Gherkin description.

Why?

As i read one post from someone, how to guarantee the code quality of  implementation for user-defined steps or any others ?

For example.

Given I login as Administrator.
Two ways achieve this goal.(symfony)
1.  if step1 : I on "login" page step2: i fill fields with exists,  combine these steps to get "I login as ..."
2.  through mink session ( only take effects in headless),  programmatically create token 

The second way is not right way obviously.

If i use first way, then I need a chaining step feature.

Ok. Let talk about next

Given there are following entities....

I programmatically construct these entities data to achieve a Given?
If these codes have issues, the Behat test will not predict to be right.

I consider Constructing Data of Application should Use Application functionality.

For example, on a ecommerce platform. As a shop owner, I create a product in Administration Backend.
If this product is published, then the product will be presented on the frontend page.

Then.

Feature: create a product
A: Scenario: create a product 
B: Scenario: publish a product

Feature: shopping
C: Scenario: browse products
D: Scenario: add to cart

The flow is A -> B -> C -> D
The platform data is built by users actions or interactions. Not programmatically.

**Comment by everzet** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/behat) for discussions. This repository is for development of Behat.
