### ISSUE TITLE
My ideal BDD looks like this.

### ISSUE THREAD

**Issue by kendoctor** [Behat/Behat#673]
1. Define Features, Feature Scenarios, Scenarios ...
2. Organize scenarios into flows.
3. Then go to test.

For example
1) Backend features
A. Scenario: As a shop owner, Create Product
B. Secnario: As a shop owner, Set Payment Methods
C. Scenario: As a shop owner, Create Shipments 
D. Scenario: As a shop owner, Configure Products Inventory Levels

2) Frontend features
E. Scenario: As a shop user,  Login as a shop owner
F. Scenario: As a shopping visitor, Browser products
G. Scenario: As a shopping visitor, Cart products
H. Scenario: As a shooping visitor, Checkout cart to make an order

3) Workflow building
(s) : Scenario
(f) : Flow
I.  Provide products in shop
   E(s) -> A(s) -> B(s)-> C(s) -> D(s) 
   E(s)  -> A(s)  -> C(s) -> D(s)  -> B (s) 
 
J. Shopping
I(f) -> F(s) -> G(s) -> H(s)

All data are constructed in the flow, not programmatically, via user interactions with application.

Repeating Works:
Scenario: Create a product
  Given  E(s)
  And    I click "create" in "assortment"
  Then  I should be on page "Product Creation"
  When I fill the form
  """
    Name : iphone 6
    Category: Electronics
    ...
 """
  And click "create"
  Then I should be on page "Product show"
  And I should see "Product Successfully created"
  Then repeat above(Given ignored) for 100 times with following Inputs(may be a excel file)
  | windows phone | ... |
  | ... |

Or repeating Scenario
E(s) -> A(s)x5 -> B(s)-> C(s) -> D(s) 

If scenario or flow is referenced by another scenario will be be ignored to test except repeating works.

Why constructs repeating data via user interactions?
Because today's applications many of them use javascript technology to collect data.
If using programmatically repeatedly create 100 entity records will never encounter problems,
But via user interactions in real browser create 100 entities not refreshing a page, maybe will get a memory leak problem.

By this way. For bdd ,our focus is defining much more user interactions steps, even Not one Given step exists, all Givens need user interactions to build, not programmatically.

**Comment by everzet** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/behat) for discussions. This repository is for development of Behat.

**Comment by kendoctor** [comment]
google services banned in china.

**Comment by everzet** [comment]
@kendoctor I didn't thought about it :( I'm sorry. I'm planning to establish a forum on Behat.org, where you also will be able to discuss these topics. In the meantime I guess IRC (#behat@freenode.net) is our best option for China :(

I'm sorry again for inconvenience.
