### ISSUE TITLE
Question about running scenario's multiple times

### ISSUE THREAD

**Issue by sandersjj** [Behat/Behat#679]
Hello,

I have got the following question. I hope there will be some co-developers who have actually the same expecience and can tell me how they solved this particulair issue.

Let's say I have the following scenario, and this scenario is an example to many other cases

> Given I am a Visitor
> And i want to subcribe  (In my feature context this registers a user)
> Then I should get "You are now Subcscribed" 

So when I will build this feature and run this, this scenario will pass. But the **second time** and up it should always fail because a user can only exist once in the system. 

How should this issue be addressed?

Thanks very much.

**Comment by everzet** [comment]
Cleanup environment after every scenario using `@AfterScenario` hook:
http://docs.behat.org/en/v2.5/guides/3.hooks.html
