### ISSUE TITLE
Is there a way to use CLI command parameters in an Extension

### ISSUE THREAD

**Issue by dutchiexl** [Behat/Behat#685]
Hi, I created an Extension with ExtensionInterface. It is used as a HTML formatter, but I would like to access the cli parameters inside the extension. Is there a way to do this?

**Comment by everzet** [comment]
Yes, create your own CLI `Controller` by implementing:
https://github.com/Behat/Behat/blob/master/src/Behat/Testwork/Cli/Controller.php

**Comment by dutchiexl** [comment]
AHA, ok and how do I implement this controller is my extension ?

**Comment by everzet** [comment]
@dutchiexl yes, but don't forget to [tag it as a controller](https://github.com/Behat/Behat/blob/master/src/Behat/Testwork/Output/ServiceContainer/OutputExtension.php#L148), so Behat will be able to find it in a big list of services **and** add this definition to the container ([like this](https://github.com/Behat/Behat/blob/master/src/Behat/Testwork/Output/ServiceContainer/OutputExtension.php#L149)).
