### ISSUE TITLE
RepositoryArgumentTransformer::isTableAndMatchesPattern doesn't support regular expression.

### ISSUE THREAD

**Issue by rajeshtaneja** [Behat/Behat#687]
In 2.x 
```
@Transform /^table:(.*)/ 
```
used to match all tables, but in 3.x it looks for first row in table for matching pattern. If I want to modify something in all tables then I have to add transformation like:
```
@Transform table:Firstname,XYZ
```

is there any specific reason for this change or it's a bug ?

**Comment by everzet** [comment]
I wouldn't say it is a bug. But it's definitely a missing feature from 2.5.

**Comment by rajeshtaneja** [comment]
Thanks Konstantin,
