### ISSUE TITLE
Improve progress formatter output to show more information about failure, similar to 2.x

### ISSUE THREAD

**Issue by rajeshtaneja** [Behat/Behat#688]
In 2.x progress formatter output was very descriptive for failure:
1. Had failure number
2. Failing step
3. Failing scenario with path
4. Feature in which failure happened.
```
01. Xpath matching locator "//li[@id='section-2']/descendant::div[@class='section-modchooser']/span/a" not found.
  In step `And I add a "Page" to section "2"'. # behat_course::i_add_to_section()
    From scenario `Test condition'.              # /home/rajesh/behat/availability_profile.feature:25
    Of feature `availability_profile'.
```
But in 3.x output is limited to:
1. Failing step with path
2. Exception.
```
Then I should see "You are logged in as Admin User" in the "page-footer" "region1" # /home/rajesh/behat/availability_profile.feature:25
      The "region1" selector type does not exist (Behat\Mink\Exception\ExpectationException)
```
It would be nice to have a failure information similar to 2.x

**Comment by everzet** [comment]
Thanks for reporting @rajeshtaneja :)

**Comment by WouterJ** [comment]
:+1: My coworkers just asked for this as well. When you aren't very familiair with Behat and the scenarios, it's hard to understand the Behat 3 output.

**Comment by DracoBlue** [comment]
👍 It's really a big issue, that progress-Reporter does not show which `@Example` line is the reason for breaking the build, because it shows only the Scenario affected.
