### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by canfiax** [Behat/Behat#690]
When running behat I get a lot of:

    libpng warning: iCCP: known incorrect sRGB profile

Like this: 

![image](https://cloud.githubusercontent.com/assets/3786627/5721595/b310fa82-9b33-11e4-8f0b-07b529ce86f5.png)

See 5 second video here: https://www.youtube.com/watch?v=hWFLFj5s_mU

This only seem to happen on my ".ohmyzsh" terminal. On my vagrant machine, that has this turned off, it does not occur.

Very strange, because it happend all of a sudden. Previously, with same setup, it did not show up...

**Comment by stof** [comment]
Behat does not do anything with libpng AFAIK. This seems related to what your are doing in your own contexts

**Comment by everzet** [comment]
You seem to use libpng and it tries very hard to communicate to you that you have incorrect sRGB profile. As @stof said - it seems to have nothing to do with Behat itself.

**Comment by canfiax** [comment]
What could I do to get rid of the error message? Where could I post an issue?

**Comment by nchagrass** [comment]
No offence : [google](http://lmgtfy.com/?q=libpng+warning%3A+iccp%3A+known+incorrect+sRGB+profile)
