### ISSUE TITLE
Ignoring particular section of a json response in tests

### ISSUE THREAD

**Issue by inanzzz** [Behat/Behat#692]
There is a particular section in my json response and I want my tests to pass even if that particular section is wrong? Might sound wrong but is it possible? Something like dynamic placeholders.

So, `batch1064` in value below always differs and I need to handle it. Test should pass whatever comes for that e.g. 123, ABC, yoho, bobo, niceOne, a, hirrr ......

```
  Scenario: Whatever whatever
    When I send a GET request to "/1/products?id=1"
    Then the response should contain json:
    """
    {
      "products": [
        {
          "name": "Aaaa",
          "images": [
            {
              "type": "url",
              "value": "http:\/\/www.abc.com\/imagegallery\/batch1064\/image.JPG"
            }
          ]
        }
      ]
    }
    """
```

**Comment by stof** [comment]
The step ``Then the response should contain json`` is not provided by Behat itself (Behat does not provide any steps itself). Please report it to the extension you use.

**Comment by inanzzz** [comment]
I just simplified the test. I have the method in FeatureContext file.

**Comment by stof** [comment]
Well, if the method is in your own feature context, changing the way the matching is done is something related to your own code, not to Behat. Just write a step definition which checks only what you need

**Comment by inanzzz** [comment]
PHP Matcher could be the solution.

https://github.com/coduo/php-matcher
