### ISSUE TITLE
Set up windows CI with AppVeyor

### ISSUE THREAD

**Issue by everzet** [Behat/Behat#696]
https://ci.appveyor.com

**Comment by timiTao** [comment]
isnt this for .NET? server, as i read on page ABOUT? 
And second this, wasn't travis running with behat? I'm simply intreseted why :)

**Comment by everzet** [comment]
@timiTao Travis tests Behat on unix. I'd still love to check if we're running properly on Windows.

**Comment by timiTao** [comment]
:+1:  :)

**Comment by stof** [comment]
The drawback is that PHP is not installed on Appveyor workers. Having to install PHP on their machines might be cumbersome: http://www.appveyor.com/docs/installed-software

**Comment by aaa2000** [comment]
Chocolatey is installed on Appveyor workers. I never used it but Chocolatey is a Machine Package Manager, somewhat like apt-get, but built with Windows in mind and there are PHP package https://chocolatey.org/packages?q=PHP
