### ISSUE TITLE
Tagged hooks before step. Error in documentation?

### ISSUE THREAD

**Issue by jirikrepl** [Behat/Behat#703]
Hi,
how can I do tagged hooks before (only tagged) step? According to docs I can. But how Can I write it in my feature?

http://docs.behat.org/en/latest/guides/3.hooks.html#tagged-hooks

**Comment by frankcarey** [comment]
Same issue here. I'm trying to run a function before every step in a scenario with a tag of @debug.      /** @BeforeStep */
hook works, but that will run for EVERY step in EVERY scenario. When I instead use 
    /** @BeforeStep @debug */
Then the function doesn't run.

**Comment by frankcarey** [comment]
#476 is related where steps don't have access to scenarios and thus tags

**Comment by frankcarey** [comment]
This is what I have to get around the issue:

```Php

/**
   * @BeforeStep
   */
  public function debugStepsBefore(BeforeStepScope $scope)
  {
    // Tests tagged with @debug will perform each step and wait for [ENTER] to proceed.
    if ($this->scenario->hasTag('debug')) {
      $env = $scope->getEnvironment();
      $drupalContext = $env->getContext('Drupal\DrupalExtension\Context\DrupalContext');
      $drupalContext->iPutABreakpoint();
    }
  }

  /**
   * @BeforeScenario
   */
   public function registerScenario(BeforeScenarioScope $scope) {
     // Scenario not usually available to steps, so we do ourselves.
     // See issue 
     $this->scenario = $scope->getScenario();
     //print  $this->scenario->getTitle();
   }
```

**Comment by everzet** [comment]
Nodes in Gherkin do not have access to their parents to eliminate cyclic references and improve performance. That is done at a cost of loosing some functionality like the one you show.
