### ISSUE TITLE
Outdated symfony dependencies

### ISSUE THREAD

**Issue by edvinasme** [Behat/Behat#704]
Currently installing behat causes some of the specific packages to be downgraded from their later versions. Considering the packages I believe this might be an issue presetned by misconfiguration of dependencies.

Adding behat/behat ~3.0 to composer.json causes these packages to be downgraded:

  - Removing twig/twig (v1.18.0)
  - Installing twig/twig (v1.17.0)
    Loading from cache

  - Removing symfony/assetic-bundle (v2.6.0)
  - Installing symfony/assetic-bundle (v2.5.0)
    Loading from cache

  - Removing sensiolabs/security-checker (v2.0.1)
  - Installing sensiolabs/security-checker (v2.0.0)
    Loading from cache

**Comment by stof** [comment]
what is the command you ran exactly ?

**Comment by stof** [comment]
Closing as there was no feedback
