### ISSUE TITLE
Fix/Change translated patterns

### ISSUE THREAD

**Issue by KingCrunch** [Behat/Behat#705]
Actually this is somehow more a question, than a real issue, although it's based on an issue.

The German translation of `MinkContext` is somehow messy, because it is translated 1:1 from English into German and now it sounds like Yoda is speaking to you. However, I see, that I cannot simply change the patterns, because that will break anyones testsuites, which makes use of them. Is theres a workflow on how to fix translated patterns?

**Comment by timiTao** [comment]
:+1: i would too to know that

**Comment by stof** [comment]
@everzet any idea how to deal with this ?

**Comment by everzet** [comment]
Do not use out-of-the-box stepdefs?

**Comment by KingCrunch** [comment]
@everzet Yeah, would be a solution, but they are so convenient -_-

**Comment by stof** [comment]
@everzet this does not answer about how we should handle the maintenance of these stepdefs

**Comment by everzet** [comment]
@stof same way we would handle any other BC-prone code, I guess - do not touch it until the new major. We can introduce separate "fixed" version of translation and advise people to use it on their own risk between majors.
