### ISSUE TITLE
When is planned to release 3.1.* ?

### ISSUE THREAD

**Issue by timiTao** [Behat/Behat#707]
As title, i wanted to ask @everzet about new release, because as i understand, this is nearby date, and will break some BC.

Some of functionality, as planned for 3.1, i see added in 3.0.

**Comment by openprivacy** [comment]
I am waiting for this, too. Am already using a locally patched version with the junit formatter to please Jenkins. Is there some way I/we can support the process?

**Comment by everzet** [comment]
@timiTao no BC breaks planned.

**Comment by everzet** [comment]
As soon as behat.org is done, I'll switch to 3.1

**Comment by stof** [comment]
@timiTao the 3.1 release will probably be done once #656 is completed (which will indeed be after behat.org is done)

**Comment by rajeshtaneja** [comment]
Hello @stof and @everzet, 

I can see you guys are working on behat.org, can you guys please provide estimate time for 3.1 release. We are in process of upgrading to behat 3.0.*, but seems #656 will resolve some associated issues and would be nice candidate for upgrade.

**Comment by stof** [comment]
@rajeshtaneja the only missing part in #656 is the BC layer for existing extensions. Note that this PR only affects extensions trying to extend the testers. Others won't be affected by changes done in 3.1

**Comment by rajeshtaneja** [comment]
Thanks @stof 

# We use scenario name and step name while saving screen shot, so #653 will help us fix this.
# Trying to support step chaining for BC
# We have custom formatters to extract feature-scenarios for distributing features between different jobs by passing it to re-run.

**Comment by PG2000** [comment]
@everzet
Can you give me some advice which issues should be solved.to release 3.1 ?

Thanks in advance for your support....

**Comment by openprivacy** [comment]
@stof, @everzet - #653 looks like it's been ready to go for a while now. Is anyone still maintaining this? I certainly understand if life (and work) has gotten in the way of your continued work here, but if so, perhaps put out a call for new or co-maintainers (or at least testing and integration help). Behat is a great tool - and you guys have done great work - but it's sliding into oblivion without maintenance. Unfortunately, I can't take on a primary role, but I can help with some testing. Or are people already moving on to other tools?

**Comment by mvhirsch** [comment]
@stof, @everzet I hope it's not to late for suggesting help. 
Is there anything left I can help you with to finish release 3.1?

**Comment by everzet** [comment]
working on it now

**Comment by mvhirsch** [comment]
Thank you very much!
