### ISSUE TITLE
model events only are trigged in single execution 

### ISSUE THREAD

**Issue by Tectok** [Behat/Behat#711]
I am making tests for my laravel app and, I used to run file per file my features, and it work's.
the problem hapens when I execute all the feature files for a general review of mi app

and this looks like:

```
Feature: Create materials
  
    In order to manage the Warehouse
    As a Warehouse admin
    I want to create new materials to the warehouse

  Scenario:                                                # features/CreateMaterialsFeature.feature:7
    And I have a group "Accesorios" with code 'ACC'        # FeatureContext::iHaveAGroupWithCode()
    And I am on "warehouse/materials/create"               # FeatureContext::visit()
    ...
    Then I should be on "warehouse/materials"              # FeatureContext::assertPageAddress()
    And I should see "Aislador Flow System 00-00"          # FeatureContext::assertPageContainsText()
    And I should see "ACC-0001"                            # FeatureContext::assertPageContainsText()
      The text "ACC-0001" was not found anywhere in the text of the current page. (Behat\Mink\Exception\ResponseTextException)
```
when I go to my file for replicate the error and review them, mi test is ok. 
this happen because I use a model trigger to designate the code ACC-0001 and this is only triggered in the single file environment of behat

**Comment by everzet** [comment]
I'm sorry Behat has nothing to do with Laravel. You probably should point your question to:
https://github.com/laracasts/Behat-Laravel-Extension
