### ISSUE TITLE
junit formatter problem

### ISSUE THREAD

**Issue by vincentaubert** [Behat/Behat#721]
Hello,

When I tried to launch my behat test suite uniquely with the junit formatter I got this error : 

[Symfony\Component\Debug\Exception\ContextErrorException]  
  Warning: mkdir(): Invalid path 

behat version : dev-master

**Comment by stof** [comment]
What is the command you used exactly ?

**Comment by vincentaubert** [comment]
bin/behat --format junit

**Comment by GuillaumeDievart** [comment]
You need to add the option --out=build/logs

**Comment by vincentaubert** [comment]
I works Thanks.

I close the issue

**Comment by jbenoit2011** [comment]
I had the same issue. Wouldn't be better to catch the error?

**Comment by jakzal** [comment]
@jbenoit2011 indeed, fancy sending a PR?
