### ISSUE TITLE
Did --expand get removed in 3.x ?

### ISSUE THREAD

**Issue by frankcarey** [Behat/Behat#723]
After searching CHANGES.md and the issues here, I can't seem to find any mention of the --expand being removed as a cli flag, but when I try to run it I get the following error in 3.0.15:

The "--expand" option does not exist.

My goal is to expand the scenario outlines we write like I did in 2.x

**Comment by frankcarey** [comment]
Some grepping in the codebase helped me find the answer:

bin/behat --format-settings='{"expand": true}'

Leaving this ticket open as it should really be added to CHANGES.md and documented in the docs.. I'd even make a case for making it the default honestly.

**Comment by frankcarey** [comment]
Related issue is that I'm trying to set these options by default in behat.yaml but the format-settings don't seem to work from there?

The latest docs only show the option to set a format, not it's options..
http://docs.behat.org/en/latest/guides/6.profiles.html#formatters

The 2.5 docs show the full set of options:
http://docs.behat.org/en/v2.5/guides/7.config.html#formatter

**Comment by frankcarey** [comment]
Any updates here? Was this intended?

**Comment by everzet** [comment]
Care to contribute: https://github.com/behat/docs ?
