### ISSUE TITLE
Background and BeforeScenario order is inconsistent 

### ISSUE THREAD

**Issue by Goutte** [Behat/Behat#726]
Say you have that feature :

```gherkin
Feature: Expose a bug
  In order to expose an inconsistent behavior in behat
  As a PHP traditionalist
  I need to print some foobar

Background:
  Given I print "Backround ran"

Scenario:
  Then I print "Foo"

Scenario:
  Then I print "Bar"
```

With those in your `FeatureContext` :

``` php

/**
 * @BeforeScenario
 */
public function printBeforeScenario(BeforeScenarioScope $scope)
{
    print('BeforeScenario');
}

/**
 * @AfterSuite
 */
public static function gimmeCookieNomNomNom(AfterSuiteScope $scope)
{
    // A fortune cookie each time the suite runs okay
    if ($scope->getTestResult()->isPassed()) {
        try { print(shell_exec('fortune')); } catch (\Exception $e) {}
    }
}

/**
 * @Given I print :something
 */
public function iPrint($something)
{
    print($something);
}

```

You'll get the following :

```
Feature: Expose a bug
  In order to expose an inconsistent behavior in behat
  As a PHP traditionalist
  I need to print some foobar

  Background:                     # features/test_bug.feature:6
    Given I print "Backround ran" # FeatureContext::iPrint()
      │ Backround ran

  ┌─ @BeforeScenario # FeatureContext::prepare()
  │
  │  BeforeScenario
  │
  Scenario:            # features/test_bug.feature:9
    Then I print "Foo" # FeatureContext::iPrint()
      │ Foo

  ┌─ @BeforeScenario # FeatureContext::prepare()
  │
  │  BeforeScenario
  │
  Scenario:            # features/test_bug.feature:12
    Given I print "Backround ran" # FeatureContext::iPrint()
      │ Backround ran
    Then I print "Bar" # FeatureContext::iPrint()
      │ Bar

│
│  A freelance is one who gets paid by the word -- per piece or perhaps.
│  		-- Robert Benchley
│  
│
└─ @AfterSuite 
```

Or, to summarize :

```
Backround ran
BeforeScenario
Foo

BeforeScenario
Backround ran
Bar
```

You can see that the _first_ scenario's background is ran **before** the `BeforeScenario` event.
The following scenarios all run their background **after** the `BeforeScenario` event.

I use the `BeforeScenario` to clear my database and the `Background` to load some (feature-specific) fixtures in it. Right now I'm putting a dummy Scenario at the top, since the other Scenarios behave consistently, but I figured I should say something. ;)

---

What's funny is there was the very same problem in [dherkin](https://pub.dartlang.org/packages/dherkin) (another bdd framework, for dart) a while back which we had a tough time to fix.

---

Also, the `fortune` print hooked on `AfterSuite` is totally unrelated, but I love it so much I could not resist. :cookie:

**Comment by Goutte** [comment]
Worth noting : I use Behat `3.0.15`.

**Comment by stof** [comment]
Are you sure that the background ran after the beforeScenario hook ? Looking at the output alone is not the right way to determine it, because the formatter can do what it want to display things (the JUnit formatter waits until the end of the suite to write the XML file for instance)

**Comment by Goutte** [comment]
Wait... **what** ?

I swear I had a Scenario that did not pass if it was the first scenario of a feature !
And now everything runs smoothly !? Who hacked my computer to fix this !?

Looks like I jumped the gun, again. Another good example of positive bias, since the above printing feature seemed to confirm the bug I was observing. (which must have been unrelated, then)

Thanks for the support, sorry for the bother, and good job making our lives easier ! ;)
