### ISSUE TITLE
Trouble with running behat through the composer

### ISSUE THREAD

**Issue by yuklia** [Behat/Behat#733]
I have a very odd trouble with running behat through the composer (php bin/behat). When i'm trying to do it i got nothing. Even no single error... When i'm trying do it through phar (php behat.phar -h) everithing ik Ok. I can't understand this magic.

What am i doing wrong?

    PHP 5.5.24-pl0-gentoo (cli) (built: Apr 28 2015 11:39:57) Copyright (c) 1997-2015 The PHP Group Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans

**Comment by dready** [comment]
same here.. empty project, just behat 3.* vendor/bin/behat --version returns absolutely nothing..

**Comment by dready** [comment]
ah.. disabling xdebug helps..

**Comment by stof** [comment]
This looks weird. I'm using Xdebug and Behat together and it works

**Comment by chrismacp** [comment]
Check your PHP error log, I had a similar issue and it was because of xDebug's 'xdebug.max_nesting_level' not being set to a high enough number by default.

**Comment by everzet** [comment]
I'm closing this issue as it is seems to be very old and might as well have been fixed. Please reopen with updated stats if that's not the case!
