### ISSUE TITLE
Better way to decide where to append snippets to

### ISSUE THREAD

**Issue by MarcelloDuarte** [Behat/Behat#734]
In previous versions, Behat had an `--append-to` option that allowed the user to specify the destination of snippets. In the current version the user is forced to implement an interface (`SnippetAcceptingInterface `) to notify Behat of the destination of the generated snippets. I think this is not intuitive. Can we go back to the old way or offering an alternative better way to do this?

**Comment by sroze** [comment]
I definitely agree with it. If such an `--append-to` option is not specified it would be nice to let [select in a list](http://symfony.com/doc/current/components/console/helpers/dialoghelper.html#let-the-user-choose-from-a-list-of-answers) of contexts if the user wants to append to snippets somewhere!

**Comment by everzet** [comment]
@sroze send a PR in
