### ISSUE TITLE
TableNode has truncated column names

### ISSUE THREAD

**Issue by unkind** [Behat/Behat#736]
I have scenario with the following table node:
```gherkin
| id  | name                | period                  | location
| 42  | BEER MEGA FEST'15   | 2015-12-01 - 2015-12-15 | Toronto, Canada
| 43  | BEER MEGA FEST'15   | 2015-12-22 - 2015-12-25 | Toronto, Canada
```
and Behat 3.0.15.

When I try to create transformation method I have to use truncated names ("locatio"):
```php
/**
 * @Transform table:id,name,period,locatio
 */
```
Otherwise Behat doesn't transform table node. 

It doesn't look like expected behavior.

**Comment by nchagrass** [comment]
As long as https://github.com/Behat/Behat/pull/591 don't get merged you will not be able to do so... (I might be wrong)

**Comment by unkind** [comment]
@nchagrass I think that PR is not related to this issue.

This issue is more general, by the way: column names in `TableNode` object are truncated, i.e. I receive node with "locatio" column name.

**Comment by unkind** [comment]
Ah, I didn't add "|" at the end of the table. It would be better to show error message.
