### ISSUE TITLE
Symlinking feature files does not work (c.f. #246)

### ISSUE THREAD

**Issue by cxscott** [Behat/Behat#738]
Hi,

A previously fixed bug has crept back in - symlinked feature files are not recognised.

If you run against a directory that contains symlinked files it simply ignores the symlinks and only processes the actual files in that folder.

If you specify a direct path to a feature that is a symlink on the command-line you get the error: "No specifications found at path(s) `xxx`."

I was able to resolve the first issue by adding RecursiveDirectoryIterator::FOLLOW_SYMLINKS to the flags passed into the constructor of RecursiveDirectoryIterator in the two places it was used.

The second issue looks like it may be harder to resolve however. The FileSystemFeatureLocator uses realpath() to parse the provided file which does resolve the symlink, but somehow the test still fails to run and the error above is returned.

**Comment by sherakama** [comment]
The FOLLOW_SYMLINKS is needed to even find the .feature files. The following PR fixes that.
https://github.com/Behat/Behat/pull/823

I also had to add the path, even outside of the project, to the suite paths configuration for the end result of the symbolic link as the internal filter would strip out any scenarios that did not originate from one of the base paths.

**Comment by everzet** [comment]
@sherakama nice. Thank your for PR. I'll review it ASAP
