### ISSUE TITLE
Modify behat.yml parameters from php file

### ISSUE THREAD

**Issue by aman4you** [Behat/Behat#745]
How can i set formatter and filter parameters of behat.yml from php file. Like output_path and tags.

**Comment by stof** [comment]
What is your use case exactly ?

**Comment by aman4you** [comment]
I save screenshot after step fail in directory of same name as of feature file directory. Providing the screenshot directory path in formatter parameter output_path. When i have more than one directory of feature files than may be i need to create more than one screenshot directory. But output_path is fixed, i need to change output path to save scrrenshot in different directories.

**Comment by stof** [comment]
Changing the config between features would not work anyway, even if you set the values from PHP rather than Yaml. Services are not reconfigured after the DI container is built.

**Comment by aman4you** [comment]
I am creating a directory of current date for screenshots manually and providing a path of that directory in output_path parameter. I want to create directory of current date named through php and set path in output_path parameter with that directory.

**Comment by everzet** [comment]
It seems to me you need to use hooks.
