### ISSUE TITLE
Difficult to understand BEHAT_PARAM environment variable

### ISSUE THREAD

**Issue by aman4you** [Behat/Behat#748]
To run feature files on different environment like dev, stage, live mainly i need to change base_url in same profile of behat.yml. Or i can write seperate profile for different environment in behat.yml. 

To overcome from above problem means make changes in behat.yml for different enviroment or write different profile. I can create BAHAT_PARAM enviroment variable and set base_url in variable that will override the profile(Which we run) base_url. But also in these case i need to change base_url every time for different enviroment. So what exacty benefit of BEHAT_PARAM.

**Comment by stof** [comment]
Using a config file is easier in case Behat is launched by a developer. The environment variable is mainly meant to be used on CI server where the common configuration way is though env variables.

**Comment by aman4you** [comment]
Thanks

**Comment by WouterJ** [comment]
This can be closed, @stof @everzet
