### ISSUE TITLE
Behat3 crashing with Symfony 2.7

### ISSUE THREAD

**Issue by romaricdrigon** [Behat/Behat#755]
Hi,

Behat3 seems not to handle deprecation warnings from Symfony 2.7+.
When running tests, pretty much every one will fail: 
```
 16384: The Symfony\Component\Security\Core\SecurityContext class is deprecated since version 2.6 and will be removed in 3.0. Use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage or Symfony\Component\Security\Core\Authorization\AuthorizationChecker instead. in vendor/symfony/symfony/src/Symfony/Component/Security/Core/SecurityContext.php line 14
```

Behat is the latest one from dev-master, all its extensions are up-to-date.

I tried to add this line to the top of `FeatureContext`, but it had no effects:
```php
define('BEHAT_ERROR_REPORTING', E_ALL & ~E_USER_DEPRECATED);
```

Any ideas?

**Comment by stof** [comment]
the constant does not work in Behat 3. The error reporting is configured in the behat.yml file instead.

Regarding the SecurityContext warning being triggered all the time, this is an issue in Symfony 2.7.0 (2.7.1 won't trigger it all the time anymore)

**Comment by romaricdrigon** [comment]
Ok. 
How to configure this in behat.yml then? Sorry I've found no doc for this.

**Comment by romaricdrigon** [comment]
So I've found. For reference, if it can help somebody else:
```yml
default:
    calls:
        error_reporting: 14335 # E_ALL & ~E_USER_DEPRECATED
```

The tests run, bit are polluted with deprecation messages all over. Those are coming from Symfony2 internals in my case, so I'm definitely waiting for 2.7.1!

Thanks for your help @stof

**Comment by romaricdrigon** [comment]
For suppressing deprecation notice, a dirty and temporary way, in Behat `FeatureContext.php`:
```php
    /**
     * @BeforeScenario
     */
    static public function suppressDepreciationNotices(\Behat\Behat\Hook\Scope\BeforeScenarioScope $scope)
    {
        error_reporting(E_ALL & ~E_USER_DEPRECATED);
    }
```

Best solution would be to register a custom handler, in the fashion of the PhpUnit bridge. Though I was unable to make that one work for now.
