### ISSUE TITLE
behat -dl command doesn't work if I change FeatureContext class name

### ISSUE THREAD

**Issue by nicocans** [Behat/Behat#756]
I would like to use ApplicationDriver.php and sub-class TestImplementation, instead of FeatureContext. But doing so, command behat -dl seems to need it:
  [Behat\Behat\Context\Exception\ContextNotFoundException]       
  `FeatureContext` context class not found and can not be used. 

how to handle this?

**Comment by stof** [comment]
well, have you configured the context class name in your behat.yml to tell Behat to use them ? If you don't configure anything, Behat will try to use the ``FeatureContext`` class

**Comment by stof** [comment]
well, have you configured the context class name in your behat.yml to tell Behat to use them ? If you don't configure anything, Behat will try to use the ``FeatureContext`` class

**Comment by nicocans** [comment]
yes, I did. everything works except that.

**Comment by everzet** [comment]
Feels like it is related to https://github.com/Behat/Behat/issues/802#issuecomment-167989339
