### ISSUE TITLE
Handle error issue all-or-nothing

### ISSUE THREAD

**Issue by mmoreram** [Behat/Behat#757]
Behat handles errors by checking the `error_reporting()` in a *all-or-nothing* way.

https://github.com/Behat/Behat/blob/a996f07b052f61cf224c4494d06c424bde1b341f/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php#L76

With the new deprecations in Symfony 2.7, this makes extremely impossible to work with it without adding the unwanted `error_reporting(0)`.

**Comment by stof** [comment]
We should check whether ``$level`` matches the binary flag returned by ``error_reporting()`` instead of checking whether the binary flag is 0.
