### ISSUE TITLE
Scenario outline examples are not isolated

### ISSUE THREAD

**Issue by jakzal** [Behat/Behat#758]
Context classes are shared between examples. It means that if a state is stored in a context property, it will leak to the next example. State doesn't leak between scenarios.

**Comment by jakzal** [comment]
Looks like #656 refactoring would fix this issue, but is there a quick fix we could do before #656 is finished?

**Comment by stof** [comment]
unfortunately, I don't think there is a quick fix.

@everzet any plan to finish #656 soon ?

**Comment by everzet** [comment]
I'm afraid we'll need to live with this one till 3.2. Unless somebody comes up with a quicker BC solution.

**Comment by tyx** [comment]
Hello,

Is this issue still planned for the 3.2 ?
