### ISSUE TITLE
No error on missing config file (specified with -c filename)

### ISSUE THREAD

**Issue by diamondsea** [Behat/Behat#759]
If behat is invoked with a `-c configfile.yml` parameter, and that file is not found, it does not display an error but continues running without it.

```
$ bin/behat -c missing_file.yml features/example.feature
# behat runs without displaying any error (presumably using default behat.yml file)
```

**Comment by adwww** [comment]
Hey, I had this issue too and thought that looks like it's worth fixing (PR attached). However it broke a test around the use of environment variables - I'm not sure fully what the impact is if others could take a look please?
