### ISSUE TITLE
Scope folder is missing. use Behat\Behat\Hook\****

### ISSUE THREAD

**Issue by BentCoder** [Behat/Behat#764]
Hi,

I cannot use some scopes/hooks that are supposed to be under `Behat\Behat\Hook\Scope` path. There is no `Scope` folder at all. Any reason why? As you can see in the image below, namespace is coloured with red.

Thanks

Note: I have all the other scopes/hooks under `Behat\Testwork\Hook\Scope` which is fine.

**composer.json**
```
    "require-dev": {
        "behat/behat" : "3.0.15",
        "behat/symfony2-extension" : "2.0.0",
        "behat/mink": "1.6.1",
        "behat/mink-extension": "2.0.1",
        "behat/mink-browserkit-driver": "1.2.0",
        "behat/mink-goutte-driver": "1.1.0",
        "behat/mink-selenium2-driver": "1.2.0"
    },
```
![image](https://cloud.githubusercontent.com/assets/8837278/8268842/15378dd0-1789-11e5-9f1b-4cf04485751d.png)

**Comment by BentCoder** [comment]
Is there anybody there!!!! Hellooooo.....

**Comment by ciaranmcnulty** [comment]
You're looking for these? https://github.com/Behat/Behat/tree/master/src/Behat/Behat/Hook/Scope

**Comment by BentCoder** [comment]
Yes but why composer won't fetch them though? Is there anything wrong with the package versions I'm using in composer? I was able to take screenshots with exactly same settings of composer.

**Comment by ciaranmcnulty** [comment]
No idea; it works for me.

**Comment by BentCoder** [comment]
OK it works now. Thanks. No clue why it didn't work.
