### ISSUE TITLE
Empty Background results in Skip of feature

### ISSUE THREAD

**Issue by jayS-de** [Behat/Behat#768]
I'm using behat 3.0.15 and had by accident an empty background definition with the result that all scenarios of the feature have been skipped. As it can be fixed by deleting the empty background this is only a minor issue.

```
Feature: Awesome stuff
    Background:
    Scenario: do awesome stuff
        Given something
        Then magic happens
```

**Comment by everzet** [comment]
Thank you for reporting it. Should be fixed in 3.1!
