### ISSUE TITLE
Behat 3 Scenario Outline

### ISSUE THREAD

**Issue by narozhniyy** [Behat/Behat#769]
Hello everyone.
Did you change syntax for Scenario Outline in Behat 3?
Can you show me examples?
Where I can read about this in your documentation?

thanks.

**Comment by legovaer** [comment]
You can find the documentation [here](http://behat.readthedocs.org/en/latest/guides/1.gherkin.html#scenario-outlines)

**Comment by WouterJ** [comment]
@stof @everzet this can be closed
