### ISSUE TITLE
Non-capturing groups are not matched (Behat 3)

### ISSUE THREAD

**Issue by Merenptah** [Behat/Behat#771]
Using 
```php
/**
 * @Given some (?:thing)
 */
```
will not match "Given some thing". This would be nice for defining a step for a group of things.

**Comment by ciaranmcnulty** [comment]
What is the use case for this? The example is hard for me to understand...

**Comment by jakzal** [comment]
There's no concept of non-capturing groups in turnip syntax. The following should work just fine:

```php
/**
 * @Given /^some (?:thing)$/
 */
```

**Comment by stof** [comment]
There is a Turnip syntax for optional words:

```php
/**
 * @Given some (thing)
 */
```

**Comment by Merenptah** [comment]
I'm sorry, I should have been more precise. 
I have the following use case. I have the function
```php
/**
 * @Given the person:
 * @params $entity
 */
public function givenTheEntity(array $entity) {
   // something happens
}
```
but I need this not only for "person", but also for some other things. The array gets in by a cast. But the function itself is always the same. I did not want to use something like "@Given the [^:]+:", because this is too general. Hence the idea to use "@Given the (?:person|somethingother|somethingelse):". I could not get this to work with a catching group (and I actually also do not want to get it to work with this), because of the already present input parameter.
But jakzal already answered my question, thanks for that.
