### ISSUE TITLE
Install documentation for Mink does not work

### ISSUE THREAD

**Issue by bailey86** [Behat/Behat#775]
Following the instructions on a clean install I get to 

bin/behat -dl

and get:

    kbailey@holley:~/projects/fp/test-emberjs/src$ bin/behat -dl
    PHP Warning:  array_map(): An error occurred while invoking the map callback in /home/kbailey/projects/fp/test-emberjs/src/vendor/symfony/dependency-injection/ContainerBuilder.php on line 1029
    PHP Warning:  array_map(): An error occurred while invoking the map callback in /home/kbailey/projects/fp/test-emberjs/src/vendor/symfony/dependency-injection/ContainerBuilder.php on line 1029
    PHP Warning:  array_map(): An error occurred while invoking the map callback in /home/kbailey/projects/fp/test-emberjs/src/vendor/symfony/dependency-injection/ContainerBuilder.php on line 1029
    PHP Warning:  array_map(): An error occurred while invoking the map callback in /home/kbailey/projects/fp/test-emberjs/src/vendor/symfony/dependency-injection/ContainerBuilder.php on line 1029
    PHP Warning:  array_map(): An error occurred while invoking the map callback in /home/kbailey/projects/fp/test-emberjs/src/vendor/symfony/dependency-injection/ContainerBuilder.php on line 1029
    PHP Warning:  array_map(): An error occurred while invoking the map callback in /home/kbailey/projects/fp/test-emberjs/src/vendor/symfony/dependency-injection/ContainerBuilder.php on line 1029
    PHP Warning:  array_map(): An error occurred while invoking the map callback in /home/kbailey/projects/fp/test-emberjs/src/vendor/symfony/dependency-injection/ContainerBuilder.php on line 1029

                                           
      [ReflectionException]                    
      Class Guzzle\Http\Client does not exist

**Comment by nicolas-grekas** [comment]
Given that the issue disappears as soon as an error handler is registered (yes, its strange... http://3v4l.org/kfu8v)
I'd say behat should just register some error handler to fix the issue.

**Comment by bailey86** [comment]
Not tested yet - but I think this is because I didn't have the package php5-curl installed.  (I had curl installed but no php5-curl).

It may be an idea to check if required PHP modules are installed at some point during the setup/running of Behat.

**Comment by WouterJ** [comment]
As Behat doesn't require curl, but some Mink drivers do, I propose to open this issue for the http://github.com/minkphp/ organization. I'm definitely +1 for adding better error handling for this.

**Comment by everzet** [comment]
This problem seems to be unrelated to this particular codebase. Feel free to reopen if I'm wrong.
