### ISSUE TITLE
Accents characters on steps bug

### ISSUE THREAD

**Issue by zazoomauro** [Behat/Behat#778]
I'm trying to run some Behat (3.0.15) tests from Jenkins but Behat is raising failed steps.

For example for this step:
    And I should click the header "Cómo Funciona" link

The error:

    And I should click the header "C??mo funciona" link #   
    test_behavior/Resources/features/Web/StaticPages/como_funciona.feature:9
    [exec]       "clickCMoFuncionaLink" method is not available on the Header     (BadMethodCallException)

**Comment by janipalsamaki** [comment]
Behat/Mink should handle accent marks fine. This works:

```
Scenario: Follow a link that contains accent mark
  Given I am on "https://es.wikipedia.org/wiki/Wikipedia:Portada"
  When I follow "Páginas nuevas"
  Then I should be on "https://es.wikipedia.org/wiki/Especial:P%C3%A1ginasNuevas"
```

This looks like a custom step definition. Care to share the implementation code for it?

`And I should click the header "Cómo Funciona" link`

Does this scenario work when you run it on command line (without Jenkins)?

**Comment by zazoomauro** [comment]
Locally (from command line) works fine and from the jenkins box command line works fine aswell

**Comment by janipalsamaki** [comment]
Maybe has something to do with the encoding settings in Jenkins, then (since the error message contains ?? instead of ó):

http://stackoverflow.com/questions/6076203/how-do-you-set-the-default-encoding-in-jenkins
