### ISSUE TITLE
Can't get the Scenario Outline title on a BeforeScenario hook

### ISSUE THREAD

**Issue by lmrafael** [Behat/Behat#780]
Hey folks!

I am hooking an 
```
/**
* @BeforeScenario
* @param BeforeScenarioScope $scope
*/
public function setupBeforeScenario(BeforeScenarioScope $scope)
```
on my Context but am having an problem when trying to get the Scenario title for an **Scenario Outline** with 
```
$scope->getScenario()->getTitle()
```
instead of getting whats after the **Scenario Outline:** key, I am getting the Example being executed for the current scenario run.

e.g.:
![screen shot 2015-08-24 at 15 56 35](https://cloud.githubusercontent.com/assets/2047805/9449401/c2e363ce-4a78-11e5-9d5c-4c7866021099.png)

For the Scenario above I should get **Title** as the return of
```
$scope->getScenario()->getTitle()
```
for each scenario run, but am getting **| zzz |** then **| www |**.

Am I doing something wrong or expecting something I shouldn't??

Thanks for the help!

**Comment by everzet** [comment]
The best thing to do here is to use hooks if you want to continue with your course of actions. That said, it seems to me you're doing something extremely complex and there should be a better way to achieve your outcome than hacking Behat event system.

**Comment by roydude** [comment]
I know this is closed, but I'm not sure why you think this is 'extremely complex' or that he's 'hacking Behat event system'?

`$scope->getScenario()->getTitle()`

... is the standard way to get the title of the scenario and it works for a 'scenario', but for a 'scenario outline' it gives the field being substituted instead. 

I'm having the same issue trying to create a runtime report file and this looks 100% like a bug in the Behat hook system to me?

**Comment by spolischook** [comment]
I'm also have this issue. I need to create a report if something went wrong with Scenario/Scenario Outline, and it seems to be great if I have title of Scenario Outline to get more verbose report.
