### ISSUE TITLE
'-f progress -o STDOUT -f junit -o xml' not working

### ISSUE THREAD

**Issue by wundo** [Behat/Behat#781]
On latest master, doing: 
$ behat -f pretty -o ~/pretty.out -f progress -o STDOUT -f junit -o xml

creates an ./STDOUT file

Why is that?

**Comment by stof** [comment]
well, this is expected. You are asking Behat to output in a STDOUT file, and it does what you are asking.

the way to output to the console output is to use ``std``, ``null`` or ``false`` for the option value, not ``STDOUT``

**Comment by wundo** [comment]
hmm we should update the documentation then.

**Comment by rakauchuk** [comment]
$ ./bin/behat --version
behat version 3.0-dev
@wundo +1
