### ISSUE TITLE
JUnit formatter not found

### ISSUE THREAD

**Issue by garyrutland** [Behat/Behat#783]
Hey,

I'm running behat v3.0.15 but getting the following message when trying to output JUnit:

    [Behat\Testwork\Output\Exception\FormatterNotFoundException]
    `junit` formatter is not found or has not been properly registered. Registered formatters: `progress`, `pretty`.

Is this meant to be the case?
If so, is there any possibility of it getting added back in?

Thanks,
Gary

**Comment by stof** [comment]
The JUnit formatter does not exist in 3.0. There is a pending PR to implement it for 3.1

**Comment by garyrutland** [comment]
Would it be worth updating your documentation then?
http://behat.readthedocs.org/en/v3.0/guides/7.run.html#format-options
As far as I can tell, this states that it does exist?

**Comment by OutOfBrain** [comment]
It is already implemented in "master", so you can use it

```javascript
default:
    formatters:
        junit:
            output_path: %paths.base%/build/behat
```

**Comment by gggeek** [comment]
Can't wait to see it in stable release :-)

**Comment by everzet** [comment]
working on it
