### ISSUE TITLE
Detecting unused step definitions

### ISSUE THREAD

**Issue by Sam-Burns** [Behat/Behat#784]
Would it be possible to implement a feature that can report on the classes and method names of available step definitions that were not used during a test run?

Unused step definitions are useless code, but they also slow down the selecting of a definition to use for a particular step.  It would be very helpful in the management of larger test suites if we could have a command line flag, e.g. `--list-unused-definitions` that outputs this information after the test run.  Alternatively, the information could be output as standard at the end of a dry run of the tests.

**Comment by Dyktus** [comment]
:+1: for this idea

**Comment by fonsecas72** [comment]
I would be willing to help anyone to implement something to achieve this.  +1

**Comment by Dyktus** [comment]
@Sam-Burns I want to get more details about this case.

At the beginning sorry for my english.

So only when you run all the tests in the suite this flag --list-unused-definitions should be available, am I right ? 
Try to imagine this situation:
- When you will run one *.feature this flag can output some unused definitions but only in this scenario not in all of them, right ? 

Correct me if I think wrong.

**Comment by Sam-Burns** [comment]
Yes, although I'm not sure it's very useful to use the flag when running a single test.  In principle, it should just provide the user with the information; but the information is most useful when running all the tests.  It's also useful during a dry run for very large test suites, I think.

**Comment by Dyktus** [comment]
I forked behat repository and just will try to write something on the weekend :+1: wish me luck

**Comment by Sam-Burns** [comment]
Excellent :-) Thank you!

**Comment by Sam-Burns** [comment]
@Dyktus Any thoughts on this idea? https://github.com/Sam-Burns/behat-context-file-usage.git

**Comment by Dyktus** [comment]
@Sam-Burns Looks great :+1: 
Really sorry but to be honest I didn't touch the code at all.

One idea. Where do you check if whole suite was run ? I mean what happens when I will run single test. I don't see the code responsible for that.

**Comment by Sam-Burns** [comment]
@Dyktus The extension doesn't behave differently depending on how Behat is run at present.  If you would like to request such a feature, maybe raise an issue against the extension?

**Comment by gggeek** [comment]
+1

**Comment by everzet** [comment]
I like the idea, but think it belongs in custom extension. Happy to promote yours @Sam-Burns ;)

**Comment by danchukas** [comment]
I like idea with --list-unused-definitions and --drop-unused-definitions.
I refactor scenarios now. And it is very difficult. 
PHPStorm's plugin Behat not see unused methods.
And find unused methods (specifically if used --append-snippets) is manual long work on every review code of pull request by members of team.
And when create, refactor, edit or delete steps or scenarios or even all features - we can't get any information about something went wrong.

Please, do it or say what I can use else for resolve this situation.

**Comment by nicwortel** [comment]
I tried installing https://github.com/Sam-Burns/behat-context-file-usage but due to outdated dependencies I couldn't install it in my project.

So I created my own solution, sharing it here in case anyone mind find it useful: https://github.com/nicwortel/behat-unused-step-definitions-extension
