### ISSUE TITLE
Failing to get the Table Node value in Step execution

### ISSUE THREAD

**Issue by lmrafael** [Behat/Behat#785]
When I execute the following step:
 ```
Then the values of the row on position "3" in "data" table are:
| Rendering engine | Browser     | Platform(s)      | Engine version | CSS grade |
| Gecko            | Firefox 2.0 | Win 98+ / OSX.2+ | 1.8            | A         |
```
which is mapped as such:
```
/**
 * @Then /^the (values|contents) of the row on position "(?P<rowPosition>[^"]+)" in "(?P<table>[^"]+)" table are:$/
 */
public function assertRowOnPosition($rowPosition, $table, TableNode $items){...}
```
i get the error:
```
Argument 3 passed to Apple\Automation\Behat\Context\BaseContext::assertRowOnPosition() must be an instance of Behat\Gherkin\Node\TableNode, string given
```
The variables receive these values (works only if I remove $items type):
```
$rowPosition: 3
$table: data
$items: data
```

It is messing up the arguments order. I can make it work adding dummy arguments in the function header like:
```
public function assertRowOnPosition($rowPosition, $table, $ignore, TableNode $items){...}
```
for the same regex.

The variables receive these values:
```
$rowPosition: 3
$table: data
$ignore: data
$items: the desired table node
```

Can you guys help me figure out what am I doing wrong here? Am I messing up the regex? Or is it really a bug?

Thanks!

**Comment by stof** [comment]
your issue is that ``(values|contents)`` is also a capturing group. and mixing named and positional capturing groups will indeed lead to weird things sometimes.
The fix is to use a non-capturing group in your regex if you don't care whether the step says ``values`` or ``contents`` (and to use a named group for it if you care)

**Comment by lmrafael** [comment]
So the problem lies in my regex inability. :sweat_smile:

As I need to have pre-fixed options for my step, I do care what it says, so I'm going with a named group. I tried setting it to ```(?<value>values|contents)```, but I am still getting the same result as before, and it doesn't works.

Moving forward I spitted my step into two:
```
/**
 * @Then /^the contents of the row on position "(?P<rowPosition>[^"]+)" in "(?P<table>[^"]+)" table are:$/
 * @Then /^the values of the row on position "(?P<rowPosition>[^"]+)" in "(?P<table>[^"]+)" table are:$/
 */
```
and worked like a charm. But still doesn't solve my problem, cause I can have steps like:
```
/**
 * @Then /^the (value|content) of the cell on row position "(?P<rowPosition>[^"]+)" and column position "(?P<columnPosition>[^"]+)" (is|should be|shall be)(?:| equal to) "(?P<value>[^"]+)"$/
 */
```
with lots of capturing groups, and I don't want to explode them into all possible combinations. :persevere:

So the key seems to really be that capturing group, and as I really am not confident at all in my advanced regex abilities, did I set it wrongly again? :baby: What can I put in there to try make it work?

**Comment by stof** [comment]
@lmrafael if you care about the value, you also need to add the ``$value`` argument.

and if you split your steps into 2 definitions, it makes me think you *don't* care about which word was used, as you will not be able to know which of them was used to call your step definition.

**Comment by lmrafael** [comment]
Agreed. I got it now!

Unfortunately me and my team are trying to create an base dictionary to be used along several projects we are running, we will maintain this base, and those projects' QA team will write the .features to them.

That is unfortunate because the QA team fought really bad so we would provide this dictionary with a more 'loose' grammar. Hence the ```(value|content)```. ```(is|should be|shall be)```, ```(?:| equal to)``` on our steps.

So I could meet my project requirement and be ok with behat specifications I rewrote my steps to something like this:
```
/**
 * @Then /^the (?P<namedGroup1>value|content) of the cell on :targetColumnName column which "(?P<columnName>[^"]+)" column has the :columnValue value (?P<namedGroup2>is|should be|shall be)(?:| equal to) :cellValue$/
 */
public function assertCellBasedOnColumnNameValueAndColumnName1($columnName, $columnValue, $targetColumnName, $cellValue, $namedGroup1, $namedGroup2)

```
and most of them worked alright, but when using TableNodes, the problem persisted:
```
/**
 * @Then /^the (?P<namedGroup1>values|contents) of the row which "(?P<columnName>[^"]+)" column has the "(?P<value>[^"]+)" value in "(?P<table>[^"]+)" table are:$/
 */
public function assertRowBasedOnColumnNameValue2($columnName, $value, TableNode $items, $table, $namedGroup1)
```
is still returning a Fatal Error for the TableNode argument ```(must be an instance of Behat\Gherkin\Node\TableNode, string given) ```, and only works when I add an dummy $ignore variable:
```
public function assertRowBasedOnColumnNameValue2($columnName, $value, $ignore, $table, $namedGroup1, TableNode $items)
```
Any Ideas?

**Comment by stof** [comment]
@lmrafael if your implementation does not care about whether the sentence use ``value`` or ``content`` (i.e. the behavior does not change), simply use a non-capturing group

**Comment by stof** [comment]
The TableNode has to be at the end of arguments though, even if you add more named arguments to account for named groups (the arguments of the regex are resolved to an array, and the TableNode is then added at the end)

**Comment by lmrafael** [comment]
Even though I don't care, I need them to be defined there. There will be auto-generated documentation and it needs to have those options... Project requirements... :sweat_smile:

So, moving the TableNode argument to the end did the trick! Everything is green! :tada::tada::tada:

Even so: 
I don't know if I am being naive again but, deactivating the arguments chaining when an named group is present wouldn't make sense? 

Something like, or you let the Behat chain them or you explicitly name them. 

This way we could write richer steps, where the regexes would only affect the step mapping to the .features written steps and not the arguments, so ... do you think that would be an nice to have enhancement, or would break more things than solve?

**Comment by lmrafael** [comment]
Damn. I knew I was bad at regexes, but I didn't knew how much. Just NOW I realized what you proposed to me.

```
(?:values|contents)
```

That's it. Everything is fine. No need to useless arguments. And I feel uberly stupid. 
:flushed::flushed::flushed:

Thanks for the patience man. Stupid me.
