### ISSUE TITLE
Behat 3 yaml: bootstrap

### ISSUE THREAD

**Issue by OutOfBrain** [Behat/Behat#787]
Hi,

I am trying to figure out how to setup a bootstrap.php file in behat.yml that is loaded for my tests. Right now I am requiring the file at the top of all my context files, but that can't be the final solution.

Anyone who can help?

**Comment by Taluu** [comment]
You can modify the `bin/behat` script, to load whatever you want it to load.

**Comment by stof** [comment]
@Taluu this is a bad idea. This ``bin/behat`` file is a vendor file (on any system supportign symlinks, it is just a symlink to the real Behat file).

@OutOfBrain what are you doing in this bootstrap.php file ? We don't have a bootstrap file in Behat, but we might have ways to achieve the feature you need.

**Comment by Taluu** [comment]
@stof I meant making your own file, instead of using the vendor file.

**Comment by firegate666** [comment]
In our bootstrap file we set up some basic constants, connections, load configs, add custom handlers and stuff like that. Similar to the bootstrap you can add for PHPUnit

**Comment by stof** [comment]
I think the right solution would be either to use a ``@BeforeSuite`` hook in your context (there is no ``@BeforeExercise`` because contexts are per suite, so it would still run for each suite) or to create a Behat extension doing the work for you (if the hook is not early enough for your needs)

**Comment by firegate666** [comment]
Hm, will think about a hook. I would have to define the `@BeforeSuite` hook in each context. My temp solution is a common parent class that does the trick.

**Comment by stof** [comment]
no, you just have to define it in a context which is applied in all your suites
