### ISSUE TITLE
Multi session behat scenarios

### ISSUE THREAD

**Issue by Trogie** [Behat/Behat#790]
Hello,

I'm investigating how I can work out/make multi session scenarios.

Our systems are headless drupals as backend (json generation) and angularjs apps frontend.

How do I make full E2E tests in this architecture?

I was thinking on making a context with 2 (or even more) sessions:
- one browser session (selenium2) so I can use the behat drupal extension
- one headless (goutte) session so I can verify json generation and schemas (behatch)
- second browser session (selenium2) for the frontend (behatch::browser)

The problem is, how do I start with this above?

**Comment by jmauerhan** [comment]
I've done this in 2.5, I'm not sure how much everything has changed with 3.0+ However, I would suggest not trying to test both at the same time, but each aspect individually, if at all possible. 

If you need to, here is how I did it in 2.5: Create a new instance of a Driver and it's Session in your context, and assign it to another variable in your context. 

My main driver was selenium, and this step opened a Goutte driver with the Goutte/Guzzle clients. I saved it to a property and used it for the rest of the tasks I needed it for.

```
$goutteClient = new \Behat\Mink\Driver\Goutte\Client();
$guzzleClient = new \Guzzle\Http\Client();
$goutteClient->setClient($guzzleClient);

$driver = new \Behat\Mink\Driver\GoutteDriver($goutteClient);
```

**Comment by everzet** [comment]
This problem seems to be unrelated to this particular codebase. Feel free to reopen if I'm wrong.

**Comment by stof** [comment]
MinkExtension 2.x (for Behat 3) allows to create as many sessions as you want. you will have to define your own steps though. The builtin MinkContext is only able to use the default session.
