### ISSUE TITLE
Loading Contexts dynamically in Extensions

### ISSUE THREAD

**Issue by Taluu** [Behat/Behat#791]
As there is a `ContextExtension`, I thought that it could be useful to have the possibility to dynamically load a Context.

The best example I have is if in your extension you have a parameter (let's say a `debug: true/false` parameter), and need to load (or not) a context if the parameter is true / set, which has some steps and some hooks (these could be registered in a listener though).

WDYT ?

**Comment by everzet** [comment]
Sounds to me like you need a custom https://github.com/Behat/Behat/blob/master/src/Behat/Testwork/Environment/Handler/EnvironmentHandler.php
