### ISSUE TITLE
Print or echo not outputting anything

### ISSUE THREAD

**Issue by Taluu** [Behat/Behat#793]
Just going through 3.0, and in 2.5 we had a method `printDebug` which let us print debug things as needed.

I tried to reimplement a similar mechanism (actually, just a debug context that needs to output things), but doing echo does not output anything.

Instead of echoing, should I inject some sort of outputter ? Where can I find it then ?

thanks.

**Comment by Taluu** [comment]
OK I think I found why : the `RuntimeCallHandler` has a bufferization (`ob_start` at line 128), so basically we have to do somehting like this :

```php
<?php

/// .... in the context
$buffer = ob_get_clean();

echo "...";
//...

ob_start();
echo $buffer;
```
And then the output is correctly altered. But I think this is really hackish, so unless anyone has a solution...

**Comment by janipalsamaki** [comment]
`print` should work just fine.

FeatureContext:

```
public static function printDebug($string) {
  print "$string\n";
}
```

Example output:

```
┌─ @BeforeSuite # FeatureContext::setupSuite()
│
│  Testing
│  
│
```

**Comment by Taluu** [comment]
print or echo is the same, and it doesn't work because of the output bufferization. So you basically have to clean the buffer, do your echos (or print or printf, ... outputting things), and then reopen it with the old buffer.

**Comment by everzet** [comment]
@Taluu why don't you just `echo`? `echo` is the new `printDebug`, you don't need to implement anything.

**Comment by Taluu** [comment]
It wasn't actually outputing anything, that's why. But maybe I did something wrong when I tried (before I opted for the solution of clearing the buffer and restore it afterwards, which works as expected)

**Comment by everzet** [comment]
@Taluu which formatter do you use?

**Comment by Taluu** [comment]
The progress formatter

**Comment by everzet** [comment]
short formatters do not output debug information. Switch to `pretty` and you'll see the output properly.

**Comment by Taluu** [comment]
Fair enough.

**Comment by Taluu** [comment]
Btw, is there anyway to detect the formatter in a `AfterScenario` event ? Or even change that (i'm using that on a scenario that has a `@debug` tag or if the scenario fails and I have a debug mode activated)
