### ISSUE TITLE
RepositoryArgumentTransform does not support Pystring nodes

### ISSUE THREAD

**Issue by Taluu** [Behat/Behat#794]
Whenever a regex is used in a `@Transform` annotation, it tests if the value is a string and if it matches against the regexp.

But, in the case it has look up into a `PyStringNode`, it is not considered a string... And thus, does not transform anything in there.

The fact that it does not transform anything in there is also valid (this should be, after all, a raw and untouched string), but we may need to inject different things in there... This is doable to replace with a `AfterStep` hook I suppose, but this could be a pain.

**Comment by everzet** [comment]
We wouldn't support PyString transformations. Running regexes on every single multiline in the project does not seem to produce good results, nor there are any simple ways to filter only particular PyStrings.

This is one place where generic solution probably wouldn't work.
