### ISSUE TITLE
Access the ScenarioNode from a `StepHook

### ISSUE THREAD

**Issue by Taluu** [Behat/Behat#795]
When a `StepScope` is fired in a `@AfterStep` (or `@BeforeStep`), we can access the `FeatureNode` and the `StepNode` but not the `ScenarioNode` in which the Step resides.

I think we should be able to access the `ScenarioNode` either from the `Scope` hook, or from the `StepNode` in Gherkin.

**Comment by Taluu** [comment]
Otherwise, this has to be done to access the said `ScenarioNode` :

```php
<?php
use Behat\Behat\Context\Context;
use Behat\Behat\Hook\Scope\StepScope;

class FeatureContext implements Context
{
    /** 
     * @BeforeStep
     * @AfterStep
     */
    public function stepHook(StepScope $scope)
    {
        $scenario = null;
        $env = $scope->getEnvironment();
        $feature = $scope->getFeature();
     
        $step = $scope->getStep();
        $line = $step->getLine();
     
        foreach ($feature->getScenarios() as $tmp) {
            if ($tmp->getLine() > $line) {
                break;
            }
     
           $scenario = $tmp;
        }
    }
}
```

Which isn't the most intuitive...

**Comment by stof** [comment]
> or from the StepNode in Gherkin.

this won't happen because it would force to make the Gherkin object graph cyclic again, which was precisely avoided in Gherkin 3+ because cyclic object graphs were preventing the refcount to release memory, forcing to use the garbage collector for that, which was increasing memory usage (the GC will delete them only later than what we can do now) and the CPU time (the GC has a performance impact when it enters into action).

**Comment by Taluu** [comment]
Ok, I can now see why fetching the parent node from a node (the FeatureNode from a ScenarioNode, the ScenarioNode from the StepNode and so on) is not possible.

So then from the `Hook` (in Behat) at least ; it shouldn't make any cyclic references, as we can already fetch the `FeatureNode` from the `StepHook`, right ?

**Comment by jhedstrom** [comment]
The logic above would normally work, but fails if there are background steps in the feature.

**Comment by everzet** [comment]
Use hooks and temporary state in your context (or trait). That's nasty, but will work.
