### ISSUE TITLE
I don't see failed scenario when use --format=progress

### ISSUE THREAD

**Issue by vittore** [Behat/Behat#796]
When I run this command:
```
bin/behat -s default --config=app/config/behat.yml   --stop-on-failure --format progress 
```

I get:
```
........F

--- Failed steps:

    And I should see "XYZ" # Features/guestCRUD.feature:17
      The text "XYZ" was not found anywhere in the text of the current page. (Behat\Mink\Exception\ResponseTextException)

1 scenario (1 failed)
9 steps (8 passed, 1 failed)
0m2.09s (63.26Mb)
```

But I don't get name of failed scenario. Is this correct?

Thanks in advance.
v.

**Comment by mheki** [comment]
What kind of name would you expect here?
IMO everything looks fine in your example. Take a look at this line:
```
And I should see "XYZ" # Features/guestCRUD.feature:17
```
you have a file path plus a line to the failing step, I think this is detailed enough to investigate your failure.
The thing is that `# Features/guestCRUD.feature:17` is written using the same font colour as a background. Did you miss it?

**Comment by vittore** [comment]
Ops! Thanks.

v.


2015-12-01 9:50 GMT+01:00 Marek Pietrzak <notifications@github.com>:

> What kind of name would you expect here?
> IMO everything looks fine in your example. Take a look at this line:
>
> And I should see "XYZ" # Features/guestCRUD.feature:17
>
> you have a file path plus a line to the failing step, I think this is
> detailed enough to investigate your failure.
> The thing is that # Features/guestCRUD.feature:17 is written using the
> same font colour as a background. Did you miss it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Behat/Behat/issues/796#issuecomment-160896980>.
>



-- 
http://www.zen.pn.it

**Comment by mheki** [comment]
Looks like the issue can be closed now :)
