### ISSUE TITLE
Extending FeatureContext in Behat3

### ISSUE THREAD

**Issue by jroy-998** [Behat/Behat#802]
When extending FeatureContext from a sub-context, there seem to be some strange behaviour going on.

It seems like a new FeatureContext is being created for each sub-context which extends it. For example the following:

**FeatureContext.php**

    class FeatureContext implements Context
    {
        /**
         * @BeforeScenario
         */
        public function setUp()
        {
            var_dump('setting up....');
        }
    }

**SomeSubContext.php**

    class SomeSubContext extends FeatureContext
    {
        //some steps here....
    }

Running behat here will result in the following:

     ┌─ @BeforeScenario # PrintSteps::setUp()
     │
     │  string(14) "setting up...."
     │  
     │
     ┌─ @BeforeScenario # AssertSteps::setUp()
     │
     │  string(14) "setting up...."
     │  
     │

As you can see, the @BeforeScenario hook has been run twice. This can cause problems when trying to share objects such as WebDrivers between FeatureContexts.

Is there any way this can be achieved, I seem to remember class inheritance was ok in Behat2? Was it taken out for a reason?

Thanks

**Comment by everzet** [comment]
Try renaming your `FeatureContext` to something else. I think you stumbled upon a known configuration bug where Behat always loads `FeatureContext` whenever it is present, even if you didn't told it to.

**Comment by everzet** [comment]
I checked and Behat works as expected. It seems what you were trying to do is having multiple custom contexts registered and extending base context class. In this case each of your contexts will have same hooks ran. This is expected and perfectly normal behaviour. Find better ways of reusing your steps and hooks outside of inheritance.
