### ISSUE TITLE
Should relativizePaths be called on exception message?

### ISSUE THREAD

**Issue by adamquaile** [Behat/Behat#804]
In https://github.com/Behat/Behat/blob/master/src/Behat/Testwork/Exception/ExceptionPresenter.php#L116 paths are relativized in the entire contents of the exception message. 

As I was debugging paths and subprocesses changing the current working directory, this stumped me for a while. 

What's the use-case for this? Should we be doing it on all of the message, or just a bit?

**Comment by stof** [comment]
we cannot do it on just a bit of the message, as we have no knowledge about how the message looks like

**Comment by adamquaile** [comment]
@stof Yes, I understand that. I'm trying to understand why it's done at all? Perhaps there's a good use-case, but it adds a layer of magic that can be confusing.

**Comment by everzet** [comment]
Convenience is the core reason for that. You seem to have hit and edge-case where it kind worked the other way around, though. Ideas?
