### ISSUE TITLE
Random failing tests in lines that do not exist

### ISSUE THREAD

**Issue by firegate666** [Behat/Behat#805]
We have random failing unit tests in our builds that point to a line in a feature file that does not exist

```
15:06:46      [exec] --- Failed steps:
15:06:46      [exec]     Then I should get an error message "Not enough ingredients" # tests/Ig/Grepo/Tests/Acceptance/Crafting/craft.feature:46
15:06:46      [exec]       Failed asserting that two strings are equal.
15:06:46      [exec]       --- Expected
15:06:46      [exec]       +++ Actual
15:06:46      [exec]       @@ @@
15:06:46      [exec]       -'Not enough ingredients'
15:06:46      [exec]       +'The recipe wasn't found.'
15:06:46      [exec] 
15:06:46      [exec] 13 scenarios (11 passed, 2 failed)
15:06:46      [exec] 57 steps (55 passed, 2 failed)
15:06:46      [exec] 0m0.61s (32.38Mb)
```

Line 46 does not exist in this file and has never existed. I have no clue about that.

Version: https://github.com/Behat/Behat/commit/149f8881a1df56496c37094f32d05b53e0cde37b

    behat version 3.0-dev

**Comment by everzet** [comment]
Did you find the source of the issue?

**Comment by everzet** [comment]
I'm closing this issue as it is seems to be very old and might as well have been fixed. Please reopen with updated stats if that's not the case!
