### ISSUE TITLE
Time to tag 3.0.16 (or 3.1.0)?

### ISSUE THREAD

**Issue by pocky** [Behat/Behat#806]
Symfony 3.0 is available and 2059cbe is required :)
Thanks!

**Comment by stof** [comment]
I will do it this weekend, unless @everzet can do it faster

**Comment by pocky** [comment]
Thanks!

**Comment by ibrasho** [comment]
Can we fix mink and all the extensions to allow Symfony 3.0 components?

The ones I noticed:
behat/mink is out-of-sync with minkphp/mink and require symfony/css-selector ~2.0: https://github.com/behat/Mink/blob/master/composer.json
MinkExtension still require symfony/config ~2.2: https://github.com/minkphp/Mink/blob/master/composer.json

**Comment by ibrasho** [comment]
I just noticed that `behat/mink` on packagist is actually `phpmink/mink` in github.

So only the extensions need updating it seems.

**Comment by ibrasho** [comment]
behat/mink need a need tag also.

https://github.com/minkphp/Mink/issues/682

**Comment by scaytrase** [comment]
@stof any updates on this?

**Comment by stof** [comment]
@scaytrase I was busy with the SymfonyCon, and so not able to work on releases. This will happen in the next days (but I cannot give a date yet)

**Comment by pkruithof** [comment]
@stof any progress on this? It's blocking the Symfony 3 upgrade for our project unfortunately.

**Comment by everzet** [comment]
Working on it
