### ISSUE TITLE
Behat hanging randomly

### ISSUE THREAD

**Issue by garyrutland** [Behat/Behat#809]
Hi,

I've been trying to debug an issue I've been getting for nearly a day now but can't see any obvious reason for it happening, sometimes it will work and sometimes it will just randomly hang (more often than not it will hang).
I am unsure if this is an issue with Behat or with PhantomJS, apologies if it is the latter.

I've attached two log outputs from a working test suite and a test suite that hangs and it just seems to call _execFuncAndWaitForLoadDecorator infinitely.

Any ideas?

Thanks,
Gary

[phantomjs-not-working.txt](https://github.com/Behat/Behat/files/64156/phantomjs-not-working.txt)
[phantomjs-working.txt](https://github.com/Behat/Behat/files/64155/phantomjs-working.txt)

**Comment by garyrutland** [comment]
After adding more debug, it always seems to be at the beforeStep stage.
Don't know if that is any help at all.

**Comment by stof** [comment]
Well, what do you have in your beforeStep ?

**Comment by garyrutland** [comment]
Originally, nothing, but all there is now is an echo.

    /**
     * @BeforeStep
     */
    public function beforeStep(BeforeStepScope $scope)
    {
        echo "Before step\n";
    }

**Comment by garyrutland** [comment]
I'm beginning to wonder if this is a Mink issue, always seems to be when navigating to either the homepage or a specific URL.

My feature file:

    Feature: Site

        Background:
            Given I am on the homepage

        Scenario: Homepage on a desktop
            Given I am on a desktop
            Then I should see "THE CHALLENGES"

        Scenario: Homepage on a tablet
            Given I am on a tablet
            Then I should see "THE CHALLENGES"

        Scenario: Homepage on a phone
            Given I am on a phone
            Then I should see "THE CHALLENGES"

Before step:

    /**
     * @BeforeStep
     */
    public function beforeStep()
    {
        echo "Before step\n";

        $session = $this->getSession();
        $url = $session->getCurrentUrl();
        echo "URL: {$url}\n";
    }

The output:

    ┌─ @BeforeSuite # FeatureContext::beforeSuite()
    │
    │  Before suite
    │
    │

    ┌─ @BeforeFeature # FeatureContext::beforeFeature()
    │
    │  Before feature
    │
    │

    Feature: Site

      Background:                  # features/site.feature:4
        ┌─ @BeforeStep # FeatureContext::beforeStep()
        │
        │  Before step
        │  URL: about:blank
        │
        │

Happens with both these commands:

    Given I am on the homepage
    Given I am on "/"

But every now and again it will work.

**Comment by everzet** [comment]
This problem seems to be unrelated to this particular codebase. It seems to be a Mink/PhantomJS issue and at best belongs to https://github.com/minkphp/MinkSelenium2Driver. Feel free to reopen if I'm wrong.
