### ISSUE TITLE
Could not install on php7

### ISSUE THREAD

**Issue by rennis23** [Behat/Behat#812]
Installation on php7 is not possible.
Required extension "ext-mbstring" not exists.

***composer output***
```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - behat/behat dev-master requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - behat/behat dev-master requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - Installation request for behat/behat dev-master -> satisfiable by behat/behat[dev-master]
```

**Comment by rennis23** [comment]
Pull request with fix https://github.com/Behat/Behat/pull/813

**Comment by stof** [comment]
Well, mbstring exists for PHP 7 too. It looks like you installed PHP 7 without the extension.

**Comment by rennis23** [comment]
You have right.
This is problem with my docker configuration.
If anybody used official [php7](https://hub.docker.com/_/php/) image from docker hub you must install mbstring by command.
```
docker-php-ext-install mbstring
```
