### ISSUE TITLE
Add Before and After steps for Scenario Outline.

### ISSUE THREAD

**Issue by blazarecki** [Behat/Behat#815]
Hi,

I want to work on a feature but before I want to know if you are interested or not.

The aim of the feature is to execute steps **before** and **after** an outline scenario which are execute only one time.

With this feature we can execute something we only need once in the before steps like loading fixtures in the database.

This is an example of what the feature could look like :

```guerkin
Scenario Outline:
    Then the <name> give <result>
    And ...
    And ...
    But ...

    Before:
        Given I do something when the scenario start

    After:
        Then I do something at the end of the scenario

    Exemples:
        | name | result |
        | A    | OK     |
        | B    | KO     |
```

For the given example the executed steps will be

```gherkin
Given I do something when the scenario start
Then the A give OK
And ...
And ...
But ...
Then the B give KO
And ...
And ...
But ...
Then I do something at the end of the scenario
```

What do you think of this feature ?

**Comment by stof** [comment]
If you need to load fixtures before the step, you should not be doing it only before the first outline. This is wrong. Outlines are meant to be isolated (even though a bug in Behat means that they are not fully isolated)

**Comment by everzet** [comment]
```
Given I do something when the scenario start
Then the A give OK
And ...
And ...
But ...
Then the B give KO
And ...
And ...
But ...
Then I do something at the end of the scenario
```

Scenario makes me think you're trying to use Behat for something it wasn't intended to be used to - not BDD.

**Comment by blazarecki** [comment]
Ok, I may try to use Behat as a pure testing tool. 

My idea was to have an "optimize outline scenario", because I don't want to: first, load fixtures in one scenario and then, launch outline scenario which use in read-only the previous loaded fixtures.

I wanted to have the readability of an outline scenario and the extensibility of a testing tools (before/after).

Thanks for the explanations.
