### ISSUE TITLE
More than two alternative words in definition comments

### ISSUE THREAD

**Issue by vanderlee** [Behat/Behat#818]
The 3.0 documentation gives this example of alternative words:
`@When there is/are :count monster(s)`

It's not possible to specify more than two alternatives. For instance, the following does not work:
`@When there is a customer/client/person/patron in the shop/store/showroom`

**Comment by stof** [comment]
This is indeed not supported in our Turnip syntax currently. Note that you can always achieve it by defining the step using a regex rather than turnip.

@everzet is it supported in the original turnip system ?

**Comment by everzet** [comment]
@stof I don't think so.
