### ISSUE TITLE
behat 3 phar file

### ISSUE THREAD

**Issue by peteraba** [Behat/Behat#824]
I really liked to be able to download behat 2 as a phar file from github. Any chance we could have the same for behat 3 as well?

**Comment by stof** [comment]
Each stable release has the phar file attached to it in github releases: https://github.com/Behat/Behat/releases

**Comment by javian** [comment]
3.1 does not seem to have it assuming that is considered stable.

**Comment by javian** [comment]
@stof has this just been overlooked for 3.1 ?

**Comment by stof** [comment]
yeah probably
