### ISSUE TITLE
Argument Resolver Docs?

### ISSUE THREAD

**Issue by mozzymoz** [Behat/Behat#826]
Hi there,
while playing around with SensioLabs/BehatPageObjectExtension I found that their PageContext ist deprecated and they suggest to use the argument resolver instead. After some searching I found that this is something Behat specific but couldn't figure out from the code what to do and how to use it.
Is there any documentation flying around somewhere?

**Comment by everzet** [comment]
Argument resolvers are an extension point in Behat. They provide no userland functionality out of the box, but some extensions can provide their own support for those. Like Symfony2Extension:
https://github.com/Behat/Symfony2Extension/blob/master/doc/index.rst#injecting-parameters
https://github.com/Behat/Symfony2Extension/blob/master/src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php

**Comment by jakzal** [comment]
@mozzymoz it's simpler then you think. Have a look at [the docs](http://behat-page-object-extension.readthedocs.org/en/latest/guide/working_with_page_objects.html#instantiating-a-page-object). 

I also added an additional explanation to the deprecation message.

If you think there's still use for the context, open an issue at https://github.com/sensiolabs/BehatPageObjectExtension

**Comment by mozzymoz** [comment]
@jakzal great thanks :)
