### ISSUE TITLE
Execution information gathering

### ISSUE THREAD

**Issue by JoaoGFarias** [Behat/Behat#828]
Hello guys,

I'm planning of developing an automatic scenario selection, using constraints informed by the user, using [techniques established by academia] (http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=6004519&url=http%3A%2F%2Fieeexplore.ieee.org%2Fxpls%2Fabs_all.jsp%3Farnumber%3D6004519). 

To do so, one key information I need to extract is the execution time of each scenario (steps would be good as well). I know how to extract suite time execution, but the only way I was able to get scenario time execution was getting this info directly on the project. This approach is not so good because my application would require any project under analysis to modify to give the info.

There is a way currently to get the scenario time execution in each suite execution?

**Comment by stof** [comment]
you can use an extension to get this info (or maybe only a custom output formatter if the info is already available and just not displayed, I don't remember).

**Comment by everzet** [comment]
I don't think there is. You can listen to events and estimate time in your own listener though
