### ISSUE TITLE
Catch  `\Throwable` in PHP 7 so that fatal errors do not halt test execution (how?)

### ISSUE THREAD

**Issue by peterjmit** [Behat/Behat#831]
I would like to contribute a patch for this, but I have a few questions before I can do that.

Now PHP 7 is out, fatal errors no longer need to halt test execution. It looks like appropriate place in  `makeCall` method in  in the [`CallCenter`](https://github.com/Behat/Behat/blob/718159921b1d844b8805b5ab2e7d1be34ca323cb/src/Behat/Testwork/Call/CallCenter.php) class

```php
public function makeCall(Call $call)
{
    try {
        $filteredCall = $this->filterCall($call);
        $result = $this->handleCall($filteredCall);
        $filteredResult = $this->filterResult($result);
    } catch (Exception $e) {
        return new CallResult($call, null, $e, null);
    } catch (\Throwable $e) {
        // Cast \Throwable to \Exception?
        $e = throwableToException($e);
        return new CallResult($call, null, $e, null);
    }

    return $filteredResult;
}
```

I have something along these lines working however I am not sure how to handle the cast of `Throwable` to `Exception` in the context of Behat.  Symfony handles it via [ `FatalThrowableException`](https://github.com/symfony/symfony/blob/a729462ce1405497b9bec285d2e83f6e60b987d5/src/Symfony/Component/Debug/Exception/FatalThrowableError.php) but to be frank I don't fully understand the constructor of that class, why is `ErrorException` instantiated but not assigned for example?

I would appreciate any pointers to getting a PR open (or a PR would be great too)

**Comment by stof** [comment]
> why is ErrorException instantiated but not assigned for example?

it is not instantiated. The ErrorException constructor is called because we want its behavior without having the behavior of the FatalErrorException constructor (which is in between in the class hierarchy)

**Comment by peterjmit** [comment]
@stof what does calling `ErrorException::__construct` do in this circumstance?

**Comment by stof** [comment]
@peterjmit it applies the logic of the ErrorException constructor (we would write it as ``parent::__construct`` if ErrorException was the direct parent in the class hierarchy)

**Comment by peterjmit** [comment]
@stof ah, I wasn't aware you could do that (effectively skip constructors up the class hierarchy if I am now understanding correctly) - you learn something new every day: thanks!

**Comment by everzet** [comment]
@peterjmit that would be awesome if you could PR this one!
