### ISSUE TITLE
SIGINT handling doesn't appear to work with PHP 7.0

### ISSUE THREAD

**Issue by davedevelopment** [Behat/Behat#832]
I think. I can definitely ctrl-c out of a simple suite with php 5.6.0, but the same suite under 7.0.(0,2,snapshot) just carries on running. I've done a bit of investigating, but I'm still not any closer to knowing what's going on :)

**Comment by davedevelopment** [comment]
I should add that I confirmed the signal handler in `SigintController` is successfully registered, it just doesn't seem to fire.

**Comment by everzet** [comment]
I did notice that too, but thought it was to do with the lack of readline module in my php7 environment. Did something change in regards how SIGINT capture works in php7?

**Comment by Taluu** [comment]
I also have this problem. But, in phpunit, it works perfectly, so maybe there could be a hint in it to correctly handle this ?

I tried to detect the function used (as this is a simple if on a `function_exists`), and it does return true...

**Comment by davedevelopment** [comment]
I do have readline compiled in. I only glanced through the changelog for 7.0.0 and couldn't see anything relevant. I've just had another play and managed to get a fairly minimal test case together without behat, will carry on playing with it and see where I get.

**Comment by davedevelopment** [comment]
It's something to do with the positioning of `declare(ticks=1)`. Reading the php docs, I assumed moving it up to the `bin/behat` executable would at least get it working, but didn't. Moving in to the block of a step does make it work.

``` cucumber
Feature: test
    Scenario: test
        Given I wait for 5 seconds
        Given I wait for 5 seconds
        Given I wait for 5 seconds
        Given I wait for 5 seconds
        Given I wait for 5 seconds
        Given I wait for 5 seconds
```

``` php
    /**
     * @Given I wait for 5 seconds
     */
    public function iWait()
    {
        declare(ticks = 1); # this makes the magic happen, removing it forces a full run
        $start = time();
        while(time() < $start + 5) {
            $a = 0; # tickable statement, php 7 would run the loop without ticking otherwise
        }
    }

```

I don't have any more time to dig in to this right now, but I guess there must be somewhere suitable for the `declare` directive to go.

**Comment by davedevelopment** [comment]
Filed a bug report, will see what they say https://bugs.php.net/bug.php?id=71448

**Comment by danepowell** [comment]
What's the latest status on this? It just bit me today, pretty annoying.

It looks like @peterjmit might have a fix, but I don't see an upstream PR for it.

**Comment by pies** [comment]
It's very annoying.
