### ISSUE TITLE
Running multiple *.feature files

### ISSUE THREAD

**Issue by eugene-dounar** [Behat/Behat#834]
Currently there is no way to run behat with multiple *.feature files in one execution. 
Use case is running suite in parallel. I want to run half my features on one server and another half on the other.

For example
```bash
bin/behat $(find ./features -name "*.feature"  | sed -n '0~2p'  | tr '\n' ' ')
```
but currently it throws RuntimeException "Too many arguments."

**Comment by avant1** [comment]
Are you familiar with https://github.com/m00t/behat-partial-runner?
We are using this extension for parallel tests execution.

But I agree, passing more than one `.feature` file to be runned can be useful.

**Comment by nicocans** [comment]
And why don't you use tags?

**Comment by eugene-dounar** [comment]
Tags like @thread1 @thread2 are ugly and do not allow dynamically setting
number of parallel instances. Moreover - -tags option overwrite my suite
tags

ср, 27 янв. 2016, 11:33, Nitche <notifications@github.com>:

**Comment by eugene-dounar** [comment]
Thanks, looks like what I need

вт, 26 янв. 2016, 22:06, Kirill <notifications@github.com>:

**Comment by frankcarey** [comment]
While I agree that behat should support setting more than one feature file, we have a workaround for circleCI that nicely handles parallelism. 

See https://github.com/NuCivic/dkan/blob/7.x-1.x/test/circle-behat.sh
You all it like:

`bash circle-behat.sh some/folder some/file.feature some/other/folder`

and it should work.

Downside is that if you are interested in creating junit output, each call overwrites the previous call when creating the default.xml file.

So, I think this is an important feature request. Behat should be able to handle this.

**Comment by TerjeBr** [comment]
@everzet Why is this closed?

Has this feature been implemented?

**Comment by spolischook** [comment]
@TerjeBr here is possible solution https://github.com/oroinc/platform/tree/master/src/Oro/Bundle/TestFrameworkBundle/BehatStatisticExtension

**Comment by webmozart** [comment]
I too wonder why this has been closed?

This would be very useful for analyzing scoping issues where one feature affects another due to shared state. Temporarily setting a tag for that bears the risk of committing that tag. That doesn't sound like a solution to me.

**Comment by rudiedirkx** [comment]
Added about a year ago: https://github.com/Behat/Behat/commit/cbf95ad4ca568d945d82fe01429f42fac1d6ac35#diff-2c3feb3e213b2710b7443b62922453c5898b348943c46a5a435a6abd1ef52ee1

Which links to this issue 🤦 I'm blind.
