### ISSUE TITLE
Hook that retries failed scenario

### ISSUE THREAD

**Issue by adrienbrault** [Behat/Behat#835]
Hi,

Is there a way to write a hook that would rerun failed scenarios ?

**Comment by jakzal** [comment]
Have you looked into how `./bin/behat --rerun` is implemented yet?

**Comment by rusk911** [comment]
There was a documentation page on 2.5 for spinning step function. Spent yesterday whole day for trying to get it working. I wanted to write somehing like "@When I repeat <some any other defined step> :number times", but seems it's impossible. I can call any method, defined for current context but can't just call it by passing step string nor get matched annotation from within a step method. Unfortunately behat+mink+selenium seems to work very unstable, failing tess randomly, which causes many hours spending on tests debugging....

Any solutions?

**Comment by everzet** [comment]
Couple actually:

1. Minimise amount of fragile UI tests you have
2. Manually handle spinning inside your step definitions

I wouldn't allow Behat core to support flaky tests. That is never right solution for those.
