### ISSUE TITLE
Inputs of the type "date" do not appear to be supported.

### ISSUE THREAD

**Issue by saturday** [Behat/Behat#840]
I'm using the Selenium2 driver. I have the following scenario:

```
  Scenario: I can add and update insurer coverage.
    Given I go to "/url/in/question.php"
    When I fill in "coverageInsurer" with "VA"
    And I fill in "coverageStartDate" with "2016-01-01"
    And I fill in "coverageEndDate" with "2016-10-23"
    And I press "Update User"
    Then the "coverageInsurer" field should contain "VA"
    And the "coverageStartDate" field should contain "2016-01-01"
    And the "coverageEndDate" field should contain "2016-10-23"
```

The `coverageStartDate` and `coverageEndDate` fields are `<input type="date">` elements. When running the test, the values are saved as "0000-00-00" for both fields. 

Are date input types not supported?

**Comment by saturday** [comment]
I ended up achieving the same thing with the executeScript method. I'm going to close this and possibly create a pull request for the Selenium2 driver so that date inputs are properly handled.

**Comment by stof** [comment]
Well, it depends whether Selenium itself supports these fields, which depend on the version of Selenium and of the instrumented browser.
In any case, this is not an issue in Behat (it may be reported against Mink, but my answer would be the same)
