### ISSUE TITLE
Display request returned values on terminal

### ISSUE THREAD

**Issue by Jerome1337** [Behat/Behat#844]
I'm using Behat on Symfony 2.

I made some `scenarios` to test REST API features, but I have some of this scenarios who return a `200` code but do not find any key in my JSON.

There is any possible way to display what the request get ?
Actually the `verbose` option only display errors if a JSON key is not found.

I think this could be helpful if this this is not possible now, and could help a lot when response codes  are good but not datas.

**Comment by stof** [comment]
Well, Behat displays whatever you put in the exception message when you trigger an exception to make the scenario fail. If you want more details, write a more detailed exception message.

**Comment by lfbn** [comment]
I'm using [RestApiExtension for Behat](https://github.com/rezzza/rest-api-behat-extension) that has methods [that print the request and response](https://github.com/rezzza/rest-api-behat-extension/blob/master/src/RestApiContext.php#L111). You could use this extension or do it yourself printing the response body, via the HTTP adapter you're using.

**Comment by Jerome1337** [comment]
Thanks guys for your help.

I'm using [WebApiExtension for Behat](https://github.com/LinioIT/behat-web-api-extension) and there is a custom step to print the response.

Just need to add `Then print response` in the feature
