### ISSUE TITLE
3.1 RC - Commandline parsing

### ISSUE THREAD

**Issue by davidsteinsland** [Behat/Behat#846]
OK, so I wanted to test out the new formatter and did:

```
./vendor/bin/behat -f junit -o junit -f pretty
```
> [Behat\Testwork\Output\Exception\BadOutputPathException]                                            
  Filename expected as `output_path` parameter, but got `junit`.  

Hmm.. Does order help?
```
./vendor/bin/behat -f pretty -f junit -o junit
```
> [Behat\Testwork\Output\Exception\BadOutputPathException]                                            
  Filename expected as `output_path` parameter, but got `junit`.

Ah, so I have to specify output for "pretty" also, even though stdout is default? Anyhow, a quick `behat --help` says that "STDOUT" is default, so let's try that:
```
./vendor/bin/behat -f junit -o junit -f pretty -o STDOUT
```
Hm. Output is actually dumped to a *file* called STDOUT.

One last try:
```
./vendor/bin/behat -f junit -o junit -f pretty -o /dev/stdout 
```

I mean... what? Is it that hard to wanting console output *and* a jUnit test report?

**Comment by everzet** [comment]
You should use `--out=std` for standard output. Look for examples here:
https://github.com/Behat/Behat/blob/master/features/multiple_formats.feature
