### ISSUE TITLE
3.1 RC - Empty jUnit test report

### ISSUE THREAD

**Issue by davidsteinsland** [Behat/Behat#847]
A failing testsuite is executed using:
```
./vendor/bin/behat -f junit -o junit
```

And here's the `junit/default.xml` file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="default"></testsuites>
```

Something ain't right...?

**Comment by everzet** [comment]
If you get a fatal error and you are on PHP prior to 7.0 - that is expected outcome. On PHP prior to 7.0, we can not recover from fatals and, obviously, can not generate the proper report.
