### ISSUE TITLE
Enabled exception for passed step

### ISSUE THREAD

**Issue by rebajz** [Behat/Behat#854]
I will like show some my text or something else if is step or scenario, scenario outline, or features as passed (green status).

Why for example for screenshots.

I use 3 type for screenshots. First is for fail step (here i know, how add my own info text with link to my screenshot - by THROW). Second is after scenario or scenario outline is passed. And third is for situatiton when i need doing screenshot (i have Then i need screenshot function). For second and third situation i will like add link to path with my screenshots.

I mean, this will be used for many users.... for many different situation...
If this option exist, please tell me, how i can add my text for passed step and scenario.

**Comment by jakob-erdmann** [comment]
An exception is the wrong thing to use in this case as showing the file path is expected behavior.

You can use a Logger that prints text to the console or a log file. I am using Monolog for this which makes it pretty simple. Just initialize the logger object and then call something like

````
$log->debug(sprintf('Sceenshot saved to: %s', $filePath));
````

**Comment by stof** [comment]
or even just ``echo sprintf('Sceenshot saved to: %s', $filePath)`` as formatters will display what the step definitions or hooks are displaying.

**Comment by stof** [comment]
Closing this as throwing exceptions for a working step just does not make sense. Exceptions indicate failures.
