### ISSUE TITLE
Rerun should only cache failed scenarios

### ISSUE THREAD

**Issue by rajeshtaneja** [Behat/Behat#856]
Rerun in Behat 3 cache scenarios which are failed and skipped both. Scenarios which are skipped were not intended for run and should not be cached for rerun (similar to behat 2.x)

Please consider caching scenarios for rerun, which are failed only.

**Comment by rajeshtaneja** [comment]
@everzet / @stof, What do you think about this ?

**Comment by everzet** [comment]
In my opinion that would complicate things without a good reason.

**Comment by rajeshtaneja** [comment]
As per documentation, rerun save list of **failed** scenarios to run them again also, 
we have few scenarios which we skip if running php7 or gd extension is not installed on the platform. In those cases the skipped scenarios are saved in the list.

This is not a major deal as exit code is 0 with skipped scenarios. It will be nice to either update docs or just include scenarios which are failed. 

I am not sure what complications are expected with this change, but would be nice to know.

Thanks for the feedback.

**Comment by everzet** [comment]
Should be fixed in master
