### ISSUE TITLE
Transform based on type of argument

### ISSUE THREAD

**Issue by ciaranmcnulty** [Behat/Behat#863]
Currently we associate Transforms with placeholders based on name, when they're really more about types.

An example might be I have a `:sender` and `:recipient` but they're both Emails.

We should support type-based transform matching:

```php
/**
 * @Transform
 */
function toEmail($string) : Email // use @return for PHP5
{
    return Email::fromString();
}

/**
 * @Then an email should be sent from :sender to :recipient
 */
function checkEmailWasSent(Email $sender, Email $recipient)
{
    // ...
}
```

**Comment by sroze** [comment]
Can't agree more on the need. Why not simply improving the existing syntax by optionally prefixing the `:` by the class name (with or without namespace)?

```php
/**
 * @Transform Email:
 */
function toEmail($string)
{
    return Email::fromString($string);
}

/**
 * @Then an email should be sent from :sender to :recipient
 */
function checkEmailWasSent(Email $sender, Email $recipient)
{
    // ...
}
```

That way, we can also mix the both, by having a transformer for a given type *and* argument name:
```php
/**
 * @Transform Email:secret
 */
function toSecretEmail($secret)
{
    return Email::fromSecret($secret);
}
```

**Comment by ciaranmcnulty** [comment]
That's a nice idea Samuel. 

I have a concern that the trailing comma is not obvious enough at first glance? Maybe something like `Email:*`?

**Comment by sroze** [comment]
True, that's not obvious at all. Why not simply having the colon (`:`) optional? It won't conflict with the table or regex transformers.

```php
use FQCN\Email;

/**
 * @Transform Email
 */
function toEmail($string)
{
    return Email::fromString($string);
}
```

**Comment by pamil** [comment]
What do you think about `@Transform Email::class`?

**Comment by stof** [comment]
@pamil what would be your syntax corresponding to the ``@Transform Email:secret`` case ?

**Comment by stof** [comment]
@sroze the issue with your ``<classname>:<token>`` proposal is that it conflicts with the table transformations

**Comment by sroze** [comment]
@stof when the class name is `Table`, this is true. That's an extremely rare case I would say. We can handle this specific case by throwing an exception and ask to use the FQCN of the `Table` class.

**Comment by stof** [comment]
This is not the only prefix used (we also have ``row`` and ``rowtable``). And using this pattern for class names would mean that we can never use this pattern anymore in the future for other kinds of builtin transformations.

And we cannot throw an exception, as this would prevent using the existing feature.

So IMO, we need to find a future-proof notations for such transformations.

**Comment by ciaranmcnulty** [comment]
`@Transform type:email` and maybe discuss further how Transforms can be composed together

**Comment by everzet** [comment]
My current thinking is to implement VO support with 3 behaviours:

## 1. Automatic `fromString` transformation by default

When no other transformation found, but the argument is type-hinted, Behat will attempt to call `Typehint::fromString($argument)`. This part is already implemented in #907 

## 2. Pure type-based based transformation for php7

Pure typed transformation, that matches all type-hints:

```php
/**
 * @Transform
 */
public function toUser($user) : User
{
    return User::fromString($user);
}
```

## 3. Both named and typed transformation for php7

In case you want to handle specific case differently, you'll be able to use both variable name AND type. Transformation will get applied ONLY if both match the argument:

```php
/**
 * @Transform :name
 */
public function toNamedUser($name) : User
{
    return User::named($name);
}
```

Thoughts?

**Comment by ciaranmcnulty** [comment]
2 and 3 both sound good to me; in each case I've tagged a `@Transform` explicitly

Nudging VOs to have `fromString` rather than something with a better name might be a nudge in the wrong direction.

**Comment by everzet** [comment]
@ciaranmcnulty you're having a problem with nudge or with default support for `fromString`?

**Comment by sroze** [comment]
Using PHP 7 typehints sounds a better approach that in the `@Transform` annotation 👍 

The last fallback (the `fromString` static constructor)  is used in many simple VOs and would be really convenient for the developers to be able to typehint their VO without any `@Transform` definition.

**Comment by ciaranmcnulty** [comment]
@everzet to separate the concerns about 1:

* I am nervous about adding any method naming style nudges, because I think method naming is contextual.
* I don't think `fromString` is a good name if there is an existing domain concept, so I fear that having a default may prevent consideration of other options.

It's such a weak method name that using `__construct` would be just as good

**Comment by ciaranmcnulty** [comment]
There is some work inside Cucumber to adopt an expression syntax similar to our Turnip expressions: https://github.com/cucumber/cucumber/tree/master/cucumber-expressions

What's interesting is that they introduce the name of a transformation that can be embedded into the syntax:

`@Given I am a user called {name:user}`

(Note it isn't a type, it's the name of a transform called `user` that quite possibly outputs `User` objects).

There is also an idea if implicit transforms that overlaps with @everzet's implicit transform ideas.

I think at this stage it's good to make sure the mechanism aligns with the cucumber concepts enough that we can consider adopting the expressions.

**Comment by everzet** [comment]
Implemented
