### ISSUE TITLE
Get raw markup of current page

### ISSUE THREAD

**Issue by ThomWilhelm** [Behat/Behat#865]
Not a bug as such, but when I call:

$page_markup = $this->getSession()->getPage()->getContent();

I notice this isn't exactly the same as the raw markup I receive if I load the page using a browser or a CURL client, for example some attributes in tags will be in a different order, for example:

```
$page_markup = <link rel="canonical" href="http://www.example.com/" />
Calling from browser = <link href="http://www.example.com/" rel="canonical" />
```

Is there a way to get the **_exact_** markup that was returned by the loading of the page?

I am using Behat 2.x, Selenium, and Firefox.

**Comment by ciaranmcnulty** [comment]
Mink gets this directly from the driver so it may be a concern of the specific selenium driver.

I think because we're just asking the browser for the markup, you'll get the browser's DOM tree. You could try using the `goutte` driver as that just does HTTP requests from PHP to fetch the page.

**Comment by ThomWilhelm** [comment]
Cheers @ciaranmcnulty I'd thought about switching drivers but have found Selenium better to handle javascript based functionality. Anyway, I tried using:

$this->getSession()->getPage()->getOuterHtml()

Which worked better but there are still some changes from the original request, for example the closing slash on tags such as <link rel="canonical" href="http://www.example.com/"> don't exist.

I think either I'll find a way to intercept the HTTP request made, or I could always fire off a new CURL request to the current URL.

**Comment by stof** [comment]
Anyway, closing this as it is not an issue in Behat. Your questions are related to Mink.
