### ISSUE TITLE
Allow creating new document/session/DOM/client from another source

### ISSUE THREAD

**Issue by rudiedirkx** [Behat/Behat#866]
(Original issue on https://github.com/minkphp/Mink/issues/700)

My test sends an e-mail, which is caught by a test mail service, and then reads the e-mail to see if the right stuff was sent to the right person. I want to do several checks on the e-mail, and click on a link. The e-mail is always HTML (or we can assume it is).

Currently, there is only one state: the page you're on. I want to make a `@Given I am reading the last sent mail to :address` that opens the mail and exposes a new DOM document to "see" and "follow" on.

I can hack `Symfony\Component\BrowserKit\Client` to add a method `setCrawlerFromHtml($html)` which creates a crawler from the e-mail content, but hacking is bad, mkay. For full disclosure:

```
// In Symfony\Component\BrowserKit\Client:
public function setCrawlerFromHtml($html) {
  $this->crawler = $this->createCrawlerFromContent('http://example.com/', $html, 'text/html');
}

// In my FeatureContext:
$this->getSession()->getDriver()->getClient()->setCrawlerFromHtml($html);

// In myfeature.feature:
  @mail
  Scenario: New manager logs in from invite mail
    Given I am reading the last sent mail to "mgr3@org.nl"
    When I follow "manager.email.invited.button"
    And the url should match "^/users/\d+/accept/[A-Za-z0-9]+$"
    And I fill in the following:
      | firstname              | Manager                   |
      | lastname               | Drie                      |
    And I press "submit"
    Then I should be on the homepage
    And I should be logged in
```

Is there a way, or could you provide a way, for a Mink Context to create a session/client/page/DOM from HTML?

Apparently it's not a Mink issue, but 'clearly' Behat.

**Comment by stof** [comment]
Closing this because it is not an issue with Behat. Behat does not care about what you are doing inside your steps.

As explained in the mink issue, the problem you have is probably a misunderstanding of the flow about when a browser is involved or no.
