### ISSUE TITLE
Behat exit code is 0, even with missing steps

### ISSUE THREAD

**Issue by rudiedirkx** [Behat/Behat#867]
I have an empty `FeatureContext` and a very simple feature:

```
Feature: Remember a variable
	Scenario: Remember a variable
		Given a value "50"
```

When I run behat, I'd expect warnings about the missing steps, and an exit code 1. I do get the missing steps warning:

```
Feature: Remember a variable

  Scenario: Remember a variable # features/simple.feature:2
    Given a value "50"

1 scenario (1 undefined)
1 step (1 undefined)
0m0.03s (5.55Mb)

--- FeatureContext has missing steps. Define them with these snippets:

    /**
     * @Given a value :arg1
     */
    public function aValue($arg1)
    {
        throw new PendingException();
    }
```

but the exit code is 0. That seems wrong...

I want to test if my behat plugin works. An important part is the exit code (I thought). Missing steps should be a fail IMO.

**Comment by everzet** [comment]
This is intended behaviour. To enforce failure on pending or undefined steps use `--strict` flag

**Comment by rudiedirkx** [comment]
I found that flag later. Mea culpa.
