### ISSUE TITLE
getCallResult() for UndefinedStepResult

### ISSUE THREAD

**Issue by rudiedirkx** [Behat/Behat#868]
I'm writing an `@AfterStep` hook to save last step's return value. Usually this is the flow:

1. `AfterStepScope->getTestResult()` => `ExecutedStepResult`
2. `ExecutedStepResult->getCallResult()` => `CallResult`
3. `CallResult->getReturn()` => any value

But `@AfterStep` is called for undefined steps too, but `UndefinedStepResult` don't have a method `getCallResult()`. (And if they had, their return value wouldn't be an object, or it wouldn't have a `getReturn()`.)

How do I handle that in my `@AfterStep` hook? This is what I do now, because it's slightly better than class checking IMO:

```
$result = $scope->getTestResult();
if (is_callable(array($result, 'getCallResult'))) {
  $result = $result->getCallResult();
  if (is_callable(array($result, 'getReturn'))) {
    $result = $result->getReturn();
  }
}
```

That seems really really weird, but apparently it's necessary.

I vote for giving all `StepResult` a method `getCallResult()` and some return `null` instead of an object. That would make handler code much prettier:

```
if ($result = $scope->getTestResult()->getCallResult()) {
  $result = $result->getReturn();
}
```

**Comment by jakob-erdmann** [comment]
Even when ``UndefinedStepResult`` has this method implemented there are other possible returned classes of ``getTestResult()``. So if you want to be on the safe side you would need to extend the ``TestResult`` interface and thus extend all implementing classes. Since ``ExecutedStepResult`` is the only child class of ``TestResult`` which makes actual use of ``getCallResult()`` this would be bad practice. I would suggest you to simply check the class of your test result like this:

````
$result = $scope->getTestResult();
if ($result instanceof ExecutedStepResult) {
    $callResult = $result->getCallResult();
    $returnObj = $callResult->getReturn();
}
````
In this way for every successfully executed step you will get the return value and you can handle it in whatever way you want and for all other steps you do nothing (or maybe something defined in an ``else`` part)

**Comment by rudiedirkx** [comment]
That feels strange. If there's an interface, I shouldn't have to specifically check a class. IMO `getTestResult` should return a 'valid' StepResult, which is predictable: always a `getCallResult()`. If I specifically check for `ExecutedStepResult`, and there's a new kind of (matching) StepResult, I'm excluding that implicitly. That feels strange.

**Comment by jakob-erdmann** [comment]
The interface does not specify ``getTestResult()`` for a very good reason. If the test has not been executed, then there is no result of the execution. So what should ``getTestResult()`` return in case a test is skipped or undefined?

**Comment by rudiedirkx** [comment]
`NULL`. Tests have a result. All test result types should have a way to fetch the result. I think it makes more sense to change the return type depending on test result type instead of the interface. That's the point of an interface, isn't it?

Maybe I'm biased, because I'm having this 'problem', but a different interface per test result type seems silly.

(I don't even understand why they have so many classes for a StepResult. They're all practically the same, and the difference is defined in 4 `TestResult` constants too.)

**Comment by stof** [comment]
@rudiedirkx having

**Comment by rudiedirkx** [comment]
But `getCallResult()` is never interfaced. Can I ever depend on it?

**Comment by everzet** [comment]
As @stof said, you're not getting away from that check - you're just changing the nature of it. And between checking for type and checking for null, I prefer type. Because misuse of type *always* yields clearer exceptions than misuse of null.
