### ISSUE TITLE
[Documentation] Docs on Formatting Behat Output

### ISSUE THREAD

**Issue by JoaoGFarias** [Behat/Behat#869]
Hi guys,

The old documentation page contains a [section](http://behat-docs.readthedocs.org/en/latest/user_guide/command_line_tool/formatting_behat_output.html#define-formatter) which was supposed to instruct how to override the default output.

I'm interested in override the console output.
I'm open this issue to keep tracked that this information would be important on the docs.

**Comment by everzet** [comment]
It's here now: http://docs.behat.org/en/v3.0/user_guide/command_line_tool/formatting.html
