### ISSUE TITLE
Behat fails silently, provides little support for new users

### ISSUE THREAD

**Issue by sentaidigital** [Behat/Behat#874]
When attempting to run a [quick start guide](http://behat-drupal-extension.readthedocs.org/en/3.1/localinstall.html) for a Behat project recently, the final step of the install `bin/behat -dl` produced no output.

In the end, after two days of going over everything, it turned out that behat.yaml should be called behat.yml. 

Behat itself was of no use in determining this was wrong.  Running `bin/behat -dl -v -v` produced the exact same blank output, and no log files anywhere detail what behat is doing.  A simple "Trying to load behat.yml: not found" would have been a good clue, if not when running at default verbosity, then certainly with a double -v.

**Comment by ciaranmcnulty** [comment]
Unfortunately behat.yml is not required, so not sure how we can address this

**Comment by sentaidigital** [comment]
With a --debug or some number of -v flags, behat should provide more information about what it is doing.  Status messages normally suppressed like "Trying to load behat.yml: not found" or "access denied",  "Loaded drupal-driver 1.0.0", stuff like that.  Something, anything, to give those of us debugging a test suite an idea why it is doing what it is doing.

In my case, Behat did nothing, and provided no output (even with -v -v) to give me even the barest clue.
