### ISSUE TITLE
Set "show_cmd" parameter in behat.yml to be able to open page in browser (ex.: "show_cmd: firefox %s") (RuntimeException)

### ISSUE THREAD

**Issue by bizmate** [Behat/Behat#875]
Hi all

I am currently stuck while running behat with laravel. The error is happening on ->visit function.

Mink maybe does not get some default option to be able to open the page without a custom driver. These set up always used to work and I am wondering what configuration to use since I just want to use browserkit or a light browser that does not require selenium for the moment.

When i run behat i get

```
Feature: Laravel 5 page
  As a behat tester
  In order use behat mink correctly
  I want to see the homepage to make sure visit does not throw a show_cmd exception

  Scenario: Laravel startup page displaying correctly # features/example.feature:6
    Given I am on the homepage                        # FeatureContext::iAmOnHomepage()
    Then show last response                           # FeatureContext::showLastResponse()
      Set "show_cmd" parameter in behat.yml to be able to open page in browser (ex.: "show_cmd: firefox %s") (RuntimeException)
    Then I should see "Laravel 5"                     # FeatureContext::assertPageContainsText()

--- Failed scenarios:

    features/example.feature:6

1 scenario (1 failed)
3 steps (1 passed, 1 failed, 1 skipped)
```

I have created a repo with a docker-compose setup and instructions on how to reproduce in details at https://github.com/bizmate/behat_show_cmd

Am I missing anything?

**Comment by everzet** [comment]
Because you're running from inside Docker, MinkExtension can not figure out how to show you the content of response. You could either use `show_cmd` configuration option of MinkExtension or use `print last response` instead of `show last response`
