### ISSUE TITLE
Add explaination on how to use PSR-4 autoloading to documentation

### ISSUE THREAD

**Issue by dariusvertex** [Behat/Behat#876]
Hello,

I had problems to autoload multiple context classes. Here is all explanation how much I had to think till I found the solution. Something like this should be in the documentation for sure:

http://stackoverflow.com/questions/36598315/behat-3-1-multiple-contexts-second-context-class-not-found/36599933#36599933

**Comment by everzet** [comment]
If Behat is a `dev` dependency in your `composer.json`, you don't need to configure anything. Behat by default will use Composer autoloader, meaning every class Composer can find, Behat will be able to find too. Simply configure PSR-4 autoloading in Behat and it should work. I think you're overthinking it.

I'm closing this - please, feel free to reopen if you think there's still major documentation issue.
