### ISSUE TITLE
Respecting the EOL of the feature file for PyStringNode

### ISSUE THREAD

**Issue by elier** [Behat/Behat#877]
The method getRaw() just join the lines using "\n".

It would be useful if it could detect the EOF of the feature file and use the same.
If you need to produce a string with CRLF, a basic string comparison with the PyStringNode will fail.
`
   public function getRaw()
   {
       return implode("\n", $this->strings);
   }
`

**Comment by everzet** [comment]
Moved the ticket to [Gherkin repository](https://github.com/Behat/Gherkin/issues/113)
