### ISSUE TITLE
Definition transformations

### ISSUE THREAD

**Issue by afurculita** [Behat/Behat#880]
There seems to be a problem with the scenario https://github.com/Behat/Behat/blob/master/features/definitions_transformations.feature#L242 : 
if I add 

``
            | "34" | string     |
``

to `Examples`, the test will not pass. Because the transformation:

```php
          /**
           * @Transform /^".*"$/
           */
          public function transformString($string)
          {
              return strval($string);
          }
```

does not work here. It doesn't work for:

``
          | "soeuhtou" | string     |
`` 

either. `soeuhtou` is considered a string by default, not because of the transformation.

If I want to use transformations so that `"34"` (or `'34'`) is considered a string and `34` is considered an integer, what should I do?

**Comment by afurculita** [comment]
ping @ciaranmcnulty @everzet

**Comment by spolischook** [comment]
Add PR with your own test cases to definitions_transformations.feature and make tests red.
Also I've just test "34" and it match to /^".*"$/ pattern, see http://rubular.com/r/OV07Y2g3Uu

**Comment by everzet** [comment]
Regex always captures parameters as strings. It is your responsibility as definition writer to cast the capture into the type it needs to be. `strval` attempts to guess the type string represents - in your case it is integer, not string.
