### ISSUE TITLE
Completely override a step result

### ISSUE THREAD

**Issue by rudiedirkx** [Behat/Behat#881]
I want to make an extension that defines a step like `expect the following step to fail with "xxxx"`. Is there a way for an extension to completely override a step's result: to make it pass if it fails?

**Comment by janipalsamaki** [comment]
Could you elaborate a bit on the use case?

**Comment by rudiedirkx** [comment]
Let's say your features uses custom and pre-defined steps (e.g. Mink) and you want a scenario where a certain user can do 4 things, and a scenario where they can't do those 4 things. It'd be nice to say _the next 4 steps must all fail, instead of pass, to pass_. The alternative is to create 4 new custom steps to assert the opposite, but that's confusing, because they're custom and pre-defined. In Behat 3 you can't reuse steps anymore =( so that's also not an easy option.

There are a few Step result-ish events, but I couldn't find one to actually change a FAIL to a PASS.

**Comment by ciaranmcnulty** [comment]
I don't think so - when we do skipping that's baked into the ScenarioTester and StepTester.

You'd need to decorate the StepTester and override the results of run in a stateful way - this probably can't be done via the events system.

**Comment by rudiedirkx** [comment]
Can I decorate the StepTester and still use the normal `behat` bin and its options etc? Can a plugin do that?

**Comment by everzet** [comment]
Yes it can. Check
https://github.com/Behat/Behat/blob/master/features/extensions.feature
https://github.com/ciaranmcnulty/behat-stepthroughextension
for reference
