### ISSUE TITLE
@Transform is changing data as expected, but Log output does not contain new change

### ISSUE THREAD

**Issue by ijerry** [Behat/Behat#888]
I have a transform function.
I put a break point in the body.
When i debug it. break point is reached.
I see it updating data.
```php
 /**
     * @Transform <TIME_STAMP>
     */
    public function transformTIME_STAMP()
    {
        return $this->date_stamp('Y-m-d H:i:s:u');  
    }
```
However. 
If i continue debugging . I can see it sending and receiving the correct modified data.

But when i look at the log out put of Behat it is showing the Original value.

Is there something I am missing ?

BTW I am using GUZZLE.

**Comment by ijerry** [comment]
One possible solution i suppose is to change the table in memory.
how do i get a handle to the table in memory
How do i change row information in it ?

**Comment by ijerry** [comment]
Any Takers ?

**Comment by ciaranmcnulty** [comment]
you probably want `@Transform :TIME_STAMP`

**Comment by ijerry** [comment]
/**
     * @Transform :TIME_STAMP
     */
    public function transformTIME_STAMP()
    {
        return $this->date_stamp('Y-m-d H:i:s:u');  
    }

Like this

**Comment by ijerry** [comment]
for this data => 
|"<TIME_STAMP>"  |

**Comment by ijerry** [comment]
I dont think this is a solution
Looking at behat documentation on table transformations:
Anything behind a colon refers to a column in the table ?

'class FeatureContext implements Context
{
    /**
     * @Transform table:name,followers
     */
'

**Comment by ijerry** [comment]
Do you agree Ciaran ?

**Comment by everzet** [comment]
Yes. And all columns should be present in the table.
