### ISSUE TITLE
Windows 10  behat –version Could not open input file: @bin_dir@\behat.

### ISSUE THREAD

**Issue by Gordiievskyi** [Behat/Behat#893]
Hi guys,

Can't use behat on windows 10 through composer or git clone. When get it(git or composer) and try to execute:behat –version I see an error: Could not open input file: @bin_dir@\behat.
If execute in git Bash behat –version I see behat: command not found.
Tests are also not run.

Tried to download behat both in phpStorm and from windows comand line. In storm it says behat not installed when I brows to vendor/behat/behat/bin/behat and reload. Same for clonned behat.

Also everything is fine when I use behat.phar of the same version.

Windows 10
php version 5.5.36
Behat version: 3.0.15 (Tag v3.0.15)

Will appreciate any help

**Comment by stof** [comment]
hmm, we should remove the ``behat.bat`` script, which was written for PEAR (which is not supported anymore).

Have you tried going into ``vendor/bin`` instead of ``vendor/behat/behat/bin/``, where composer should be generated its own behat.bat file working properly ?

**Comment by Gordiievskyi** [comment]
many thanks. It helped.
