### ISSUE TITLE
Is there a way to write to the output?

### ISSUE THREAD

**Issue by gimler** [Behat/Behat#896]
I search a way to write from my `BeforeSuite` Hook into the output.

```
    /**
     * @BeforeSuite
     */
    public static function prepare(BeforeSuiteScope $scope)
    {
        echo "Start database backup ...";
```

How can i do it with colors in a behat way?

**Comment by Taluu** [comment]
you need to use the formats that alows outputs (such as pretty format), and to have colors and all, you need to use the [asci colors codes](https://en.wikipedia.org/wiki/ANSI_escape_code).

**Comment by gimler** [comment]
Ok but how can i access the output formater in the hook?

**Comment by Taluu** [comment]
@gimler just an `echo` is fine. With this. You'll write on the current
output
Le 7 juil. 2016 12:52, "Serhii Polishchuk" <notifications@github.com> a
écrit :
