### ISSUE TITLE
Fatal error: Maximum function nesting level of '1024' reached

### ISSUE THREAD

**Issue by kenorb** [Behat/Behat#897]
I'm running behat tests as below:

    ./bin/behat -c /vagrant/behat-tests/scripts/behat.yml --profile=chrome-qa --tags=MyForm --format=pretty

however I've got the following error:

> PHP Fatal error:  Maximum function nesting level of '1024' reached, aborting! in /vagrant/behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Lexer.php on line 177

I've already increased xdebug.max_nesting_level to 1024, so I guess there is a infinite loop.

    Call Stack:
     1. {main}() /vagrant/behat-tests/global/vendor/behat/behat/bin/behat:0
     2. Symfony\Component\Console\Application->run() /vagrant/behat-tests/global/vendor/behat/behat/bin/behat:34
     3. Behat\Testwork\Cli\Application->doRun() /vagrant/behat-tests/global/vendor/symfony/console/Application.php:118
     4. Symfony\Component\Console\Application->doRun() /vagrant/behat-tests/global/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:121
     5. Symfony\Component\Console\Application->doRunCommand() /vagrant/behat-tests/global/vendor/symfony/console/Application.php:187
     6. Symfony\Component\Console\Command\Command->run() /vagrant/behat-tests/global/vendor/symfony/console/Application.php:821
     7. Behat\Testwork\Cli\Command->execute() /vagrant/behat-tests/global/vendor/symfony/console/Command/Command.php:256
     8. Behat\Testwork\Tester\Cli\ExerciseController->execute() /vagrant/behat-tests/global/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php:63
     9. Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications() /vagrant/behat-tests/global/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php:108
    10. Behat\Testwork\Ordering\OrderedExercise->test() /vagrant/behat-tests/global/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php:146
    11. Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test() /vagrant/behat-tests/global/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php:80
    12. Behat\Testwork\Tester\Runtime\RuntimeExercise->test() /vagrant/behat-tests/global/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php:70
    13. Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test() /vagrant/behat-tests/global/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php:71
    14. Behat\Testwork\Hook\Tester\HookableSuiteTester->test() /vagrant/behat-tests/global/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php:72
    15. Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test() /vagrant/behat-tests/global/vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php:73
    16. Behat\Testwork\Specification\GroupedSpecificationIterator->rewind() /vagrant/behat-tests/global/vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php:60
    17. Behat\Behat\Gherkin\Specification\LazyFeatureIterator->rewind() /vagrant/behat-tests/global/vendor/behat/behat/src/Behat/Testwork/Specification/GroupedSpecificationIterator.php:84
    18. Behat\Behat\Gherkin\Specification\LazyFeatureIterator->moveToNextAvailableFeature() /vagrant/behat-tests/global/vendor/behat/behat/src/Behat/Behat/Gherkin/Specification/LazyFeatureIterator.php:89
    19. Behat\Behat\Gherkin\Specification\LazyFeatureIterator->parseFeature() /vagrant/behat-tests/global/vendor/behat/behat/src/Behat/Behat/Gherkin/Specification/LazyFeatureIterator.php:184
    20. Behat\Gherkin\Gherkin->load() /vagrant/behat-tests/global/vendor/behat/behat/src/Behat/Behat/Gherkin/Specification/LazyFeatureIterator.php:200
    21. Behat\Gherkin\Loader\GherkinFileLoader->load() /vagrant/behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Gherkin.php:108
    22. Behat\Gherkin\Loader\GherkinFileLoader->parseFeature() /vagrant/behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Loader/GherkinFileLoader.php:77
    23. Behat\Gherkin\Parser->parse() /vagrant/behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Loader/GherkinFileLoader.php:98
    24. Behat\Gherkin\Parser->parseExpression() /vagrant/behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Parser.php:80
    ...
    1015. Behat\Gherkin\Parser->parseComment() /vagrant/behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Parser.php:207
    1016. Behat\Gherkin\Parser->parseExpression() /vagrant/behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Parser.php:621
    1017. Behat\Gherkin\Parser->parseComment() /vagrant/behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Parser.php:207
    1018. Behat\Gherkin\Parser->parseExpression() /vagrant/behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Parser.php:621
    1019. Behat\Gherkin\Parser->parseComment() /vagrant/behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Parser.php:207
    1020. Behat\Gherkin\Parser->parseExpression() /vagrant/behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Parser.php:621
    1021. Behat\Gherkin\Parser->predictTokenType() /vagrant/behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Parser.php:183
    1022. Behat\Gherkin\Lexer->predictToken() /vagrant/behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Parser.php:169
    1023. Behat\Gherkin\Lexer->getNextToken() /vagrant/behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Lexer.php:131
    1024. Behat\Gherkin\Lexer->scanComment() /vagrant/behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Lexer.php:221

Code context:

```
$ sed -n '79,81p' behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Parser.php
        while ('EOS' !== ($predicted = $this->predictTokenType())) {
            $node = $this->parseExpression();

$ sed -n '206,208p' behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Parser.php
            case 'Comment':
                return $this->parseComment();
            case 'Language':
$ sed -n '620,622p' behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Parser.php

        return $this->parseExpression();
    }
$ sed -n '182,185p' behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Parser.php
    {
        switch ($type = $this->predictTokenType()) {
            case 'Feature':
                return $this->parseFeature();
$ sed -n '168,170p' behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Parser.php
    {
        $token = $this->lexer->predictToken();

$ sed -n '130,132p' behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Lexer.php
        if (null === $this->stashedToken) {
            $this->stashedToken = $this->getNextToken();
        }
$ sed -n '220,222p' behat-tests/global/vendor/behat/gherkin/src/Behat/Gherkin/Lexer.php
            ?: $this->scanLanguage()
            ?: $this->scanComment()
            ?: $this->scanPyStringOp()
```

Related: #666, #727

**Comment by stof** [comment]
AFAIK, we don't have an infinite loop. But the parser uses recursion heavily, which means it can reach a deep nesting in case of big files.
Anyway, please provide the gherkin file triggering this error. We cannot do anything to solve the error if we can't reproduce it.

**Comment by kenorb** [comment]
Ok, thanks for explanation. I won't be able to provide gherkin file, since it has a lot of dependencies to internal classes. This also happens with `xdebug.max_nesting_level` set to 4000, but I believe it works for 10000.
I'll close it for now, in case I'll have more details if that's a bug, I'll provide further info. Thanks.

**Comment by rafalenden** [comment]
Looks like I had to disable Xdebug. This fixed the problem for me.
