### ISSUE TITLE
allure for behat as extention

### ISSUE THREAD

**Issue by Gordiievskyi** [Behat/Behat#898]
Hi guys,

First of all it's not a bug but PR
It whould be good to have such option in behat as allure report.
https://github.com/allure-framework/allure-core

Codeception has it. https://github.com/allure-framework/allure-codeception
If you have urgent tasks and can't change roadmap, please guide me to the documentation of how to add extension to behat.

Thanks in advance.

**Comment by stof** [comment]
I have no idea what Allure is

**Comment by Gordiievskyi** [comment]
That's a kind of report. In behat we have output in several formatts. There is extention https://github.com/dutchiexl/BehatHtmlFormatterPlugin . But it has lots of issues(only one metric as the biggest gap). So allure is report that can be added as adaptor to many tools(phpUnit for example).
That's how report will looks loke http://allure.qatools.ru/

**Comment by Gordiievskyi** [comment]
Am I right that to create extention that will be bale to listen such events like after step and do something there I need to implement two interfaces: EventSubscriberInterface and ExtensionInterface  ?

**Comment by stof** [comment]
You should implement the Formatter interface rather than just EventSubscriberInterface, so that people can configure the allure formatter like other formatters (this will also require you to implement the FormatterFactory and make your extension to register it inside the output extension in its ``init`` method)

**Comment by Gordiievskyi** [comment]
> so that people can configure the allure formatter like other formatters
You mean they than can write --format "allure"?
Also I am looking inti extension https://github.com/dutchiexl/BehatHtmlFormatterPlugin
And it doesn't have FormatterFactory, but I can use it as --format "html"

**Comment by Gordiievskyi** [comment]
Also, actually I don't need formattor of behat, Adaptor I have to implement will format and create file itself, all I need is to give him what to collect. Example: If after step hook shows up I need to give the result status(succes,failed,skipped etc) and step description, thats it. Adaptor will create xml with everything I gave him in xml format. So Should I implement  Formatter or EventSubscriberInterface, in this case ?

**Comment by stof** [comment]
the job of a formatter is precisely to create a file. In your case, the behat allure formatter will output the XML file needed for allure to generate its full shiny report

**Comment by Gordiievskyi** [comment]
Can you suggests Where can I see definitions of such events tester.exercise_completed.before ?

**Comment by Gordiievskyi** [comment]
Please need a help with enabling my extention. I am not an advanced user of php. http://behat-docs.readthedocs.io/en/latest/user_guide/extending_behat/developing_a_custom_extension.html
Its blank. Can you help with some doc?

BR

**Comment by Gordiievskyi** [comment]
I stuck with load my extension. Getting this:
Invalid argument supplied for foreach() in D:\automationTests\rp1-automationtraining\vendor\behat\behat\src\Behat\Testwork\ServiceContainer\ContainerLoader.php on line 96.

**Comment by Gordiievskyi** [comment]
Am I roght I need also implement OutputPrinter interface ? cause I am getting an error Call to a member function setOutputPath() on a non-object

**Comment by nifr** [comment]
@Gordiievskyi these kind of questions are better suited for a platform like [stackoverflow.com](https://stackoverflow.com). This is behat's issue tracker for bugs or feature-requests but not a question-and-answer-platform. You're probably not going to get much feedback over here.

It's a nice idea to create an Allure (never heard of that result showing tool before) formatter extension. As even the HTML formatter plugin [won't make it into behat's core](https://github.com/Behat/Behat/issues/359) ... an allure formatter won't make it either.

If you need help with the implementation of this formatter-extension, just share the code you've written on stackoverflow.com, add the concrete issue/exception and some information about what you've tried so far to solve the problem and people will almost definitely help you out.

**Comment by Gordiievskyi** [comment]
thanks for advice, will do, then I think issues should be closed

**Comment by timiTao** [comment]
@Gordiievskyi i created few extension and this could help you - some examples.
https://github.com/timiTao/BehatExtensionExamples

Look in features for each interface ;)
