### ISSUE TITLE
Phar archive on Github

### ISSUE THREAD

**Issue by Pierstoval** [Behat/Behat#899]
Hey guys!

Why don't you put the phar executable in Github releases anymore?
 
Is there a clear reason for this?

**Comment by scaytrase** [comment]
Agree. Phpstorm works better with phar now and 3.x is not bundled to the releases anymore

**Comment by Pierstoval** [comment]
Actually I had to `box build` behat manually for PhpStorm to use the phar archive...

**Comment by everzet** [comment]
I'll build and attach phrase to releases from now on. Didn't know people were using them :)

**Comment by Pierstoval** [comment]
@everzet Actually this is the best way to install behat (as well as phpunit, composer, etc.) because it does not plug all behat as a dependency to the project, because sometimes, PHP applications can introduce conflicts (it's the case with some phpunit version conflicting with some symfony versions).

Phar install is the best because no conflicts at all :smile: 

Can't wait for other phars to come ;)

**Comment by drzraf** [comment]
reopen?
