### ISSUE TITLE
Cannot ignore scenario using tags?

### ISSUE THREAD

**Issue by JesseLeite** [Behat/Behat#900]
It seems I cannot ignore a scenario using tags (behat version 3.1.0).

Running specific scenarios by tag DOES work:
`behat --tags '@onlythis'`

But ignoring specific scenarios by tag DOES NOT seem to work:
`behat --tags '~@ignorethis'`

Could I be doing something wrong, or is this a bug?

**Comment by janipalsamaki** [comment]
Works for me using `behat --tags '~@ignorethis'` (behat 3.1.0). Could you share your feature file where you have the scenario(s) tagged?

**Comment by JesseLeite** [comment]
Hmm, I tried again today and all seems fine.  I must have been doing something wrong, sorry I'll close this.
