### ISSUE TITLE
Improve symfony/dependency-injection to ^2.7

### ISSUE THREAD

**Issue by vincentchalamon** [Behat/Behat#914]
Since 2.7, `symfony/dependency-injection` add [service decoration](http://symfony.com/doc/current/service_container/service_decoration.html). This can be very useful, for instance in my case I need to decorate `PregMatchArgumentOrganiser`.

**Comment by jakzal** [comment]
Anything from 2.1 is currently allowed. You can force the minimum version in your extension.
