### ISSUE TITLE
Multiple format parameters

### ISSUE THREAD

**Issue by zendoodles** [Behat/Behat#917]
I need to output both junit and pretty, but using multiple format parameters with junit is broken.
I can output only junit:
```
$  vendor/bin/behat --strict --format junit --out behat
$  cat behat/default.xml 
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="default">
  <testsuite name="Installation" tests="2" skipped="0" failures="0" errors="0">
    <testcase name="Verify The site has a login page with user and pass fields." status="passed"></testcase>
    <testcase name="Verify I can add a file to a node." status="passed"></testcase>
  </testsuite>
</testsuites>
```

But when I add --format pretty, then junit gets confused. 
```
$  vendor/bin/behat --strict --format junit --out behat --format pretty

                                                                                      
  [Behat\Testwork\Output\Exception\BadOutputPathException]                            
  Filename expected as `output_path` parameter, but got `/var/www/test.local/behat`.  
                                                                                      

behat [-s|--suite SUITE] [-f|--format FORMAT] [-o|--out OUT] [--format-settings FORMAT-SETTINGS] [--init] [--lang LANG] [--name NAME] [--tags TAGS] [--role ROLE] [--story-syntax] [-d|--definitions DEFINITIONS] [--append-snippets] [--no-snippets] [--strict] [--order ORDER] [--rerun] [--stop-on-failure] [--dry-run] [--] [<paths>]

```

I have looked at https://github.com/Behat/Behat/blob/master/features/multiple_formats.feature as suggested in issue #846 and tried formatting my command in the ways that are there, but when using junit instead of progress, none of them work. Also, there are no tests for multiple formats using junit.

**Comment by jakzal** [comment]
You need to specify `--out` for all `--format`s:

```
behat --no-colors --strict --format junit --out behat --format pretty --out std
```

**Comment by zendoodles** [comment]
Interesting... Thank you! Now that I'm looking at the correct [documentation (v3.0 instead of v2.5)](http://docs.behat.org/en/v3.0/user_guide/command_line_tool/formatting.html) I see this is actually documented and I should have read the fine manual. 

What tripped me up was for the "progress" format in the test the `--out` parameter is not required:
```
behat --no-colors -f pretty -f progress --format-settings='{\"multiline\": false}
```

So I skimmed over that bit in the rest of the examples there. I would still argue it's a bug, but I don't feel strongly enough to dig into the code and fix it since I have everything working now. 

Not having these tests for junit is also a bug IMO, but again, not one I have time to fix atm.

Thanks!

**Comment by jakzal** [comment]
In this particular scenario there's no `--out` option passed, so defaults are used. As soon as you pass a single `--out` you need to define it for all formats (as format, out is an array).

Please close this issue if you consider it resolved.
