### ISSUE TITLE
Tag filters do not work in before and after step hooks

### ISSUE THREAD

**Issue by m00t** [Behat/Behat#918]
Documentation says it should work: http://docs.behat.org/en/v3.0/user_guide/context/hooks.html#tagged-hooks

But actually it doesn't. You can see there are no usages of `TagFilter` in `RuntimeStepHook` as opposed to `RuntimeFeatureHook` and `RuntimeScenarioHook`. Probably because there are no links to `ScenarioInterface` from `StepScope`. Is there any particular reason not to include link to scenario in `StepScope`?

**Comment by mathroc** [comment]
just needed the same, here is a workaround:

```php
    /**
     * @AfterStep
     */
    public function afterRequest(AfterStepScope $scope)
    {
        $step = $scope->getStep();
        $scenario = array_reduce(
            $scope->getFeature()->getScenarios(),
            function ($matchingScenario, $scenario) use ($step) {
                if ($matchingScenario !== null) {
                    return $matchingScenario;
                }
                if (in_array($step, $scenario->getSteps(), true)) {
                    return $scenario;
                }
            }
        );
        $tagFilter = new TagFilter("@your&&@tags");
        if (!$tagFilter->isScenarioMatch($scope->getFeature(), $scenario)) {
            return;
        }
        // write your step here
    }
```

**Comment by everzet** [comment]
@mathroc this logic wouldn't work if your scenario has backgrounds.

**Comment by everzet** [comment]
Sadly the way `StepTester` is implemented, it is not as trivial of change as I'd hope to and would require huge ripples of BC-support layers throughout the codebase if it is to be implemented.

Sadly this is one of these points, where I need to consider the value of feature against its cost and at this moment its overwhelmingly too expensive for what it is. So for now, I'd update documentation to explicitly state that step hooks don't work with tags.

**Comment by mathroc** [comment]
indeed, it was not working with scenari with background, here is an updated version:

```php
    public function shouldProcessJobs(StepScope $scope, $filter)
    {
        $step = $scope->getStep();
        $feature = $scope->getFeature();
        $background = $feature->getBackground();
        $scenario = array_reduce(
            array_merge($feature->getScenarios(), $background ? [$background] : []),
            function ($matchingScenario, $scenario) use ($step) {
                if ($matchingScenario !== null) {
                    return $matchingScenario;
                }
                if (in_array($step, $scenario->getSteps(), true)) {
                    return $scenario;
                }
            }
        );
        $tagFilter = new TagFilter($filter);
        return $tagFilter->isScenarioLikeMatch($scope->getFeature(), $scenario);
    }
```

I also needed to extend `TagFiler`:

```php
<?php

namespace FL\Api\Feature\Context;

use Behat\Gherkin\Filter\TagFilter as BaseTagFilter;
use Behat\Gherkin\Node\FeatureNode;
use Behat\Gherkin\Node\ScenarioLikeInterface;
use Behat\Gherkin\Node\TaggedNodeInterface;

class TagFilter extends BaseTagFilter
{
    /**
     * Checks if scenario or outline matches specified filter.
     *
     * @param FeatureNode           $feature  Feature node instance
     * @param ScenarioLikeInterface $scenario Scenario or Outline node instance
     *
     * @return Boolean
     */
    public function isScenarioLikeMatch(FeatureNode $feature, ScenarioLikeInterface $scenario)
    {
        return $this->isTagsMatchCondition(array_merge(
            $feature->getTags(),
            $scenario instanceof TaggedNodeInterface ? $scenario->getTags() : []
        ));
    }
}
```

I think most is covered this way. 
What might be unexpected is that the `@AfterStep` and `BeforeStep` for steps of the background unless the whole feature is tagged (tagging the scenario is not enough) maybe implementing the `TaggedNodeInterface` interface in `BackgroundNode` could help

@everzet what do you think about adding `StepScope::getTags()` that would returns :

* feature + scenario tags for "feature steps"
* feature tags for "background steps" (+ background tags if it makes sense to implement TaggedNodeInterface in NodeBackground)

and adding a method to `TagFilter` or making `TagFilter::isTagsMatchCondition` public ?

**Comment by crabmusket** [comment]
Future Googlers: I am sidestepping this issue by setting a property of the `FeatureContext` in `@BeforeScenario @mytag` and clearing it in `@AfterScenario @mytag`, and then in a 'global' `@AfterStep` handler I check for the flag. Ugly but works for a basic use case, including background steps.
