### ISSUE TITLE
Some breakpoints are not triggered

### ISSUE THREAD

**Issue by haringsrob** [Behat/Behat#919]
Hi,

Today during test debugging, I noticed that some breakpoints are not triggered. Below is a more extended description from the same issue on the phpstorm queue.

I have the idea that this might be due to the way that behat is executing because:

Debug session is started on the behat executable -> behat executes site -> nesting issue?

**What steps will reproduce the problem?**
1. Setup a site, using composer and add behat
2. Set a breakpoing inside a function and above the function
3. Create a test that will target that function

**What is the expected result?**
The debugger should stop at both breakpoint

**What happens instead?**
The debugger only stops at the breakpoint that is not in the function.

Please provide any additional information below.
Weird things:
At the location of the failing breakpoint, if I put a DIE() it dies, so the code is running. See xdebug log below.

Also tested with ZEND debugger, same behaviour.

Command line, and running using the phpstorm ui have the same result. Loading the page in the browser break correctly.

A snapshot of the debug session:
```
Log opened at 2016-08-10 13:10:42
I: Connecting to configured address/port: 127.0.0.1:9000.
I: Connected to client. :-)
-> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///private/var/folders/6h/w01gcf717_zbwyhnck7jw_s00000gn/T/ide-behat.php" language="PHP" xdebug:language_version="5.6.24" protocol_version="1.0" appid="6808" idekey="15248"><engine version="2.4.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATAhttp://xdebug.org]></url><copyright><![CDATA[Copyright (c) 2002-2016 by Derick Rethans]]></copyright></init>

<- feature_set -i 1 -n show_hidden -v 1
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="1" feature="show_hidden" success="1"></response>

<- feature_set -i 2 -n max_depth -v 1
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="2" feature="max_depth" success="1"></response>

<- feature_set -i 3 -n max_children -v 100
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="3" feature="max_children" success="1"></response>

<- status -i 4
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="status" transaction_id="4" status="starting" reason="ok"></response>

<- step_into -i 5
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="step_into" transaction_id="5" status="break" reason="ok"><xdebug:message filename="file:///private/var/folders/6h/w01gcf717_zbwyhnck7jw_s00000gn/T/ide-behat.php" lineno="3"></xdebug:message></response>

<- breakpoint_set -i 6 -t line -f file:///Users/rob/Sites/ec/information/build/includes/common.inc -n 2011
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="6" id="68080001"></response>

<- stack_get -i 7
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="stack_get" transaction_id="7"><stack where="{main}" level="0" type="file" filename="file:///private/var/folders/6h/w01gcf717_zbwyhnck7jw_s00000gn/T/ide-behat.php" lineno="3"></stack></response>

<- run -i 8
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="run" transaction_id="8" status="stopping" reason="ok"></response>

<- run -i 9
Log closed at 2016-08-10 13:11:02
```

**Comment by spolischook** [comment]
you need to enable your xdebug for cli.
In Ubuntu it might be /etc/php5/cli/php.ini

**Comment by haringsrob** [comment]
This is enabled.

If, for example I add a breakpoint on index.php it stops. But somewhere deeper into the code it will not.

**Comment by spolischook** [comment]
Create test.php
```php
$hello = 'world';
echo $hello;
```
And now set breakpoint and run it in console

```
php test.php
```
is this work for you?

**Comment by spolischook** [comment]
I guess no

**Comment by pamil** [comment]
What Mink driver do you use?

**Comment by haringsrob** [comment]
Hi @pamil,

```
"name": "behat/mink",
            "version": "v1.7.1",
            "source": {
                "type": "git",
                "url": "https://github.com/minkphp/Mink.git",
                "reference": "e6930b9c74693dff7f4e58577e1b1743399f3ff9"
            },
```

fyi: This is the command I use to test:
`php -dxdebug.remote_enable=1 -dxdebug.remote_mode=req -dxdebug.remote_port=9000 -dxdebug.remote_host=127.0.0.1 -dxdebug.var_display_max_data=9987 behat features/events.feature`

@spolischook as I said, it breaks in certain locations. But not deep into the code.

**Comment by everzet** [comment]
Sounds like a bug in Mink or XDebug. Can't imagine anything in Behat core causing this.
