### ISSUE TITLE
How to debug "Uncaught Error: Class 'Behat\Behat\ApplicationFactory' not found"

### ISSUE THREAD

**Issue by alberto56** [Behat/Behat#923]
Hi, I have installed behat as per the installation instructions on the [project page](https://github.com/Behat/Behat), yet I'm getting "Uncaught Error: Class 'Behat\Behat\ApplicationFactory' not found". What would be the best way to debug this? Thanks!

    FROM ubuntu

    RUN apt-get update && apt-get upgrade -y
    RUN apt-get -y install curl
    RUN apt-get -y install php
    RUN apt-get -y install git
    RUN apt-get -y install zip
    RUN apt-get -y install unzip
    RUN apt-get -y install php7.0-mbstring

    RUN mkdir /behat
    RUN cd /behat && curl -sS https://getcomposer.org/installer | php
    RUN cd /behat && php composer.phar require behat/behat='~3.0.6'
    RUN cd /behat && ./vendor/bin/behat

This results in 

    PHP Fatal error:  Uncaught Error: Class 'Behat\Behat\ApplicationFactory' not found in /behat/vendor/behat/behat/bin/behat:30
    Stack trace:
    #0 {main}
      thrown in /behat/vendor/behat/behat/bin/behat on line 30
    The command '/bin/sh -c cd /behat && ./vendor/bin/behat' returned a non-zero code: 255

**Comment by everzet** [comment]
Something is wrong with the autoloader. Check the `vendor/bin/behat` script.

**Comment by everzet** [comment]
@alberto56 any news?

**Comment by alberto56** [comment]
@everzet thanks for the suggestion. I have tried the following (without success):

 * I have tried explicitly adding the autoloader schema (in various ways) to composer.json, but the file is still not found.
 * I have confirmed that ./vendor/autoload.php is in fact loaded (it is); same with ./vendor/composer/autoload_real.php

I am now in the process of trying to figure out at which point these autoloader files fail to properly load the class `Behat\Behat\ApplicationFactory`, which is called in `./vendor/bin/behat` and defined in `./vendor/behat/behat/src/Behat/Behat/ApplicationFactory.php`.

If you want to reproduce the issue, you can copy the code from the issue description into a Dockerfile and run `docker build .`. Thanks for your help! If I find a solution I will document it here.

**Comment by everzet** [comment]
@alberto56 ok, I debugged a bit and apparently this is a [known bug in composer](https://github.com/composer/composer/issues/5564).

Please track this issue in the Composer repository as there's not much we can do to fix it on our side. In the meantime, the simplest solution for your case would be to not name your project folder `behat`.

**Comment by alberto56** [comment]
Thanks @everzet for finding that, much appreciated!

**Comment by everzet** [comment]
@alberto56 you're welcome. Quite a tricky one you've discovered ;)
