### ISSUE TITLE
Sharing context between steps of a scenario

### ISSUE THREAD

**Issue by sroze** [Behat/Behat#924]
In order to simply and have more human-readable scenarios, it would be nice to ease sharing state between steps. This idea is already explored by the [`ScenarioStateBehatExtension` extension](https://github.com/gorghoa/ScenarioStateBehatExtension) but we can have a lot of benefits and an easier syntax by adding it to the core of Behat.

# Current situation

As an example, the following scenario:
```feature
Scenario: Add a token to a bucket
   Given there is a bucket named "ContinuousPipe"
   When I add a token "1234" in the bucket "ContinuousPipe"
```

In the step definition, I can use a repository or just a property of the context to share the created `Bucket` object in this example:

```php
    /**
     * @Given there is a bucket named :name
     */
    public function iCreateABucketNamed($name)
    {
        $this->bucketRepository->save(Bucket::named($name));
    }

    /**
     * When I add a token :token in the bucket :bucketName
     */
    public function iAddATokenInTheBucket($token, $bucketName)
    {
        $bucket = $this->bucketRepository->findByName($bucketName);
        $bucket->addToken($token);
    }
```

In my point of view, the drawback here is to have to mention again the bucket name in the second step. An option would be to simply have a `bucket` property in the context but that requires every other step that wants to use this variable to have access to this property.

# Ideal situation

```feature
Scenario: Add a token to a bucket
   Given there is a bucket named "ContinuousPipe"
   When I add a token "1234" to this bucket
```

```php
    /**
     * @Given there is a bucket named :name
     */
    public function iCreateABucketNamed($name) : Bucket
    {
        return Bucket::named($name);
    }

    /**
     * @When I add a token :token to this bucket
     */
    public function iAddATokenToThisBucket(Bucket $bucket, $token)
    {
        $bucket->addToken($token);
    }
```

The value returned by the previous steps (if any) is then able to be inject in the following steps. Such a feature allow for instance to have these 2 definitions in different context files without any problem, or even to have another step that create a bucket a completely different way without any change on the second step.

I'm happy to send a PR before the 3.2.0 release if that makes sense to the community :)

**Comment by spolischook** [comment]
what about context property, that can be set in one step and read in another? Or you mean something else?

**Comment by sroze** [comment]
@spolischook just updated the issue body, I pressed "Create" too fast. Is it clearer now?

**Comment by avant1** [comment]
I like the idea of saving domain objects and avoiding calling them by name (if it is not important for scenario) in favor of something like "this bucket".
It makes scenarios less wordy and allows to concentrate on really important moments of scenario.

Basically we're using similar approach in some of our projects and it is very convinient. But we are saving _current_ objects into context property, just like @spolischook said. We divide steps implementations into 
traits and then combine them into context class, so it is not a problem to access _current_ object from different subcontexts.

And I understand that accessing to the same object instance from other context classes may be tricky.

But similar functionality can be achieved by changing the structure of contexts.
Or you could even use hooks to access other contexts: http://docs.behat.org/en/v3.0/cookbooks/accessing_contexts_from_each_other.html

**Comment by ciaranmcnulty** [comment]
What is the motivation against having a property on the context class?

@sroze I don't see how this works if there are steps inbetween the one that returns the bucket and the one that wants to use it, or if there are multiple bucket objects.

**Comment by stof** [comment]
Using the returned value to pass it to the next step is indeed a very bad idea, as it means your second step can never be used elsewhere than just before the first one (adding another step between them would break everything).

Use a property in your context. This is one of the goal of the context (and the reason of its name)

**Comment by sroze** [comment]
@ciaranmcnulty the motivation is to ease sharing context between steps of different context files and simplify the step definitions.

@stof my proposal is *definitely* not to inject the returned value of the previous step into the second one: all the returned values of every step (if any) are stored into a "bag" for the duration of the scenario. We inject parameters from the step regex (plus some transformations) at the moment; we would add this "returned value bag" as an extra option to match the steps' parameters.

The second point mentioned by @ciaranmcnulty is when we have multiple objects of the same type in our "returned values bag" or even in the step's typehints. We could introduce an annotation that would allow the developer to chose from which step would he like to have the value but I'm not fond of this idea as it would complexify both Behat's internals and the definitions, and in such case, I believe that the step definitions actually don't use reference such as "this bucket" but rather "the bucket named [...]".

**Comment by ciaranmcnulty** [comment]
@sroze I don't get how any of that is simpler than `$this->bucket` ?

**Comment by gorghoa** [comment]
Hi,

With the approcach we initially took in gorghoa/ScenarioStateBehatExtension, kindly promoted here by @sroze, i.e injecting directly a fragment of state through the method arguments, we immediatly benefits from:

1.  php type hinting
1. less state dependency testing in step method
1. fails quickly

Steps method can therefore be exclusively about what to test

**Comment by sroze** [comment]
@ciaranmcnulty as discussed offline, this is simpler for different context files as we wouldn't need to use static variables in files nor [injecting context into other contexts](http://docs.behat.org/en/v3.0/cookbooks/accessing_contexts_from_each_other.html). Also, by using `$this->bucket` you *assume* that the property is set by another step, that means you definitely *depends* of this previous step anyway...

**Comment by jon-acker** [comment]
I really like @sroze idea, I frequently come across this issue of having to refer to objects I've created in previous steps explicitly, and I'm annoyed by the verbosity. 

Other option, as @ciaranmcnulty mentions (which I often use too) is to have a new step definition e.g. 
```gherkin
When I add token "123" to this bucked
```
and refer to the bucket using `$this->bucket` in the Context
*nevertheless*
I don't like this second approach for various reasons, e.g. you don't know if/when `$this->bucket` has been set up, it feels arbitrary and there's no convention for naming (which can potentially confuse other devs coming to the Context)

I can't think immediately of any drawbacks to Sams "bag" solution, where a type-hinted parameter is search for in that bag if it doesn't has a Transformer, and I can't think of potential BC issues. Yes, you'll always be getting the same object and you can only have one, unless you rename it, but the situations in which you'd need more than one instance of Bucket are probably few - the idea is similar to PhpSpec reusing the same `double` declared previously having been matched by name.

IMO its worth a try and it clearly addresses a pain-point many people experience.

**Comment by jakzal** [comment]
> this is simpler for different context files as we wouldn't need to use static variables in files nor injecting context into other contexts

I don't see how it's simpler. What I see is lots of WTF moments trying to trace which step this variable came from. 

You don't need static variables btw.

**Comment by gorghoa** [comment]
@jakzal, I guess we could store a `debug_backtrace` when an item is placed in the bucket

**Comment by jakzal** [comment]
@gorghoa I shouldn't debug to see where these things come from. This should be self-explanatory imo. Explicit.

**Comment by gorghoa** [comment]
I do agree about explicit. But I don’t think using a classic var (static, class property, global, whatever) gives you much more knowledge about which part of code gave it its value.

You either looking for the code which set a value to a bucket or to a var. I reckon it’s the same thing.

**Comment by sroze** [comment]
@jakzal 
> I don't see how it's simpler. What I see is lots of WTF moments trying to trace which step this variable came from.

At the moment it's worst: we do have the WTF moments with "Which **step definition** populated this property?". With this method it would be a lot clearer as because your scenario definition have a very small of steps (or there is something wrong in it) and you simply have to know which **step** in your scenario did produce such a variable.

Moreover, on a step definition "point of view", it is definitely more explicit to define (via a required typed argument) it requires this `Bucket` than guessing that the `$this->bucket` property has been populated by some other random step definition.

**Comment by ciaranmcnulty** [comment]
@sroze The difference is with a property it can be `private` so it narrows my search scope - I now have to worry that some other context is populating it.

The entire job of a context is to carry state between steps in a scenario in a specific interpretation of the steps. Hiding the state is just sweeping it under the carpet. Sharing the state with other contexts is breaking encapsulation and maintainability.

**Comment by jon-acker** [comment]
Can it not be written in a way that the object is not shared between contexts? 
My main use-case (AFAICS) would be within a single context anyway.

**Comment by everzet** [comment]
My initial thought is that this feature is a newcomers nightmare. Especially with your intended use of sharing state across contexts.

**Comment by everzet** [comment]
I don't see how you're simplifying anything. You're exchanging explicit complexity with implicit one. Need for sharing between contexts highlights wrong choice of your context boundaries, not the problem with the tool.

**Comment by jakzal** [comment]
> sharing between contexts highlights wrong choice of your context boundaries

This might be tricky. Usually there's something common between most scenarios. If we wanted to avoid sharing state between contexts completely, we'd need to put everything in a single context.

**Comment by everzet** [comment]
@jakzal split contexts according to your domain boundaries, not technical components. Bounded contexts have natural loose coupling.

**Comment by jakzal** [comment]
@everzet this will make them too big

**Comment by everzet** [comment]
bounded contexts also have natural limit on language used in them :)

**Comment by ciaranmcnulty** [comment]
@jakzal Sounds like you want small files even if they break when you try and use them independently? Try Traits.

**Comment by jakzal** [comment]
Even scenarios within the same domain boundary might need different state stored between steps. If one scenario talks about a single thingy, while other scenario talks about collection of thingies I'll end up with two properties (used on different occasions). It's not an issue with two properties, but it will quickly grow.

Anyway, coming back to this PR, as mentioned earlier I think it's better to keep things explicit and keep dependencies visible. It's easier to notice something is wrong with the way we organised our contexts. Therefore 👎 for adding anything like this to the core.

**Comment by stof** [comment]
I'm with @jakzal @ciaranmcnulty and @everzet here (which means that maintainers involved here all agree btw)

**Comment by gorghoa** [comment]
I do see you all agree. But I’m not convinced how a method parameter can be less explicit than some code in the function…

**Comment by spolischook** [comment]
@gorghoa method parameter is a magic.

**Comment by gorghoa** [comment]
In my extension, I’ve used annotations to be more explicit. But I guess it will not be enough to you folks^^

```php
use Gorghoa\ScenarioStateBehatExtension\Annotation\ScenarioStateArgument;

/**
 * @When bonobo gives this banana to :monkey
 *
 * @ScenarioStateArgument("scenarioBanana")
 * @ScenarioStateArgument(name="scenarioBonobo", argument="bonobo")
 *
 * @param string $monkey
 * @param string $scenarioBanana
 * @param Bonobo $bonobo
 */
public function giveBananaToGorilla($monkey, $scenarioBanana, Bonobo $bonobo)
{
    // (note that PHPUnit is here only given as an example, feel free to use any asserter you want)
    \PHPUnit_Framework_Assert::assertEquals($monkey, 'gorilla');
    \PHPUnit_Framework_Assert::assertEquals($scenarioBanana, 'Yammy Banana');
    \PHPUnit_Framework_Assert::assertEquals($bonobo->getName(), 'Gerard');
}
```

**Comment by everzet** [comment]
@gorghoa I'm afraid not :) There are considerations we as maintainers need to take into account when accepting something into the core or not.

Biggest problem with this PR and the concept behind it is that it adds cognitive overhead to the tool that is already pretty heavy on implicit concepts. And even though slight cognitive overhead might not be an issue for power users like you or @sroze, it absolutely will be an issue for newcomers - people that just get started with the BDD.

Logic applicable primarily for power-users deserves to live outside of the core - in its own extension.
