### ISSUE TITLE
Behat 4

### ISSUE THREAD

**Issue by ciaranmcnulty** [Behat/Behat#928]
Because the issue of bumping dependencies has been raised it's worth suggesting that 3.2 could be 4.0 (or both could be released together)

4.0 would be a good opportunity to also bump PHP versions and remove depredations.

**Comment by everzet** [comment]
I don't feel like we exceeded the capability of 3.x branch and I also do not yet have a clear deprecation plan. So maybe after 3.2 or 3.3.
