### ISSUE TITLE
EOL 2.x

### ISSUE THREAD

**Issue by ciaranmcnulty** [Behat/Behat#929]
Apologies if this already happened

I still come across teams using 2.x, partly because of the until-recent situation with the docs defaulting there.

I remember @everzet giving a support timeline in a blog post but I don't know if version 2 ever got officially killed.

If it's not being maintained even for bugs (I am not clear if this is the case) it should be announced and the 2.x version of the docs should have a notice added to them to that effect

**Comment by everzet** [comment]
Behat 2 is not supported anymore. Feel free to send PR to docs

**Comment by ciaranmcnulty** [comment]
i will when I figure out how to make the docs look nice locally so I can test it

**Comment by everzet** [comment]
Added notes to the 2.5 branch of this repo: https://github.com/Behat/Behat/blob/2.5/README.md
And to the 2.5 docs index: http://docs.behat.org/en/v2.5/
