### ISSUE TITLE
Narrative filter missing for suites?

### ISSUE THREAD

**Issue by UFOMelkor** [Behat/Behat#934]
I tried to configure the new narrative filter that has been included with Behat 3.1.

While this was possible if I did it like described in 
[profile_filters.feature#L164](https://github.com/Behat/Behat/blob/fb3241979bd080ac17f157244e9d6fc84a22bf9d/features/profile_filters.feature#L164)
I could not achieve it if I tried to configure it for a single suite:
```yaml
default:
    suites:
        reporter:
            filters:
                narrative: /As a reporter/
```

```
[Behat\Testwork\Suite\Exception\SuiteConfigurationException]                                              
  `narrative` filter is not supported by the `reporter` suite. Supported types are `role`, `name`, `tags`.  
```

It looks like the filter has been added to the [GherkinExtension](https://github.com/Behat/Behat/blob/fb3241979bd080ac17f157244e9d6fc84a22bf9d/src/Behat/Behat/Gherkin/ServiceContainer/GherkinExtension.php) but not to the [LazyFeatureIterator](https://github.com/Behat/Behat/blob/fb3241979bd080ac17f157244e9d6fc84a22bf9d/src/Behat/Behat/Gherkin/Specification/LazyFeatureIterator.php).

**Comment by everzet** [comment]
Good catch. Yes, only the suite-wide filter was added. You can use the `role` filter instead for now.
