### ISSUE TITLE
3.1 - jUnit formatter

### ISSUE THREAD

**Issue by davidsteinsland** [Behat/Behat#938]
How is it really supposed to work?
A successful behat test renders an empty jUnit report file, containing only:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="default"></testsuites>
```

I then edit the scenario so that it will fail, and the XML stays the same.

The test is run like so:
```
./vendor/bin/behat -f junit -o path/to/output -f pretty -o std path/to/feature.feature
```

Am I missing something? We're using jUnit report files to let our CI servers render various information about the builds and also making them able to auto-balance the tests between nodes (works very well with phpunit's jUnit report).

**Comment by everzet** [comment]
You are obviously missing something.

<img width="577" alt="screen shot 2016-09-06 at 08 04 59" src="https://cloud.githubusercontent.com/assets/30813/18264533/b0277a76-7408-11e6-825c-05d25f74db0c.png">

**Comment by AlexeyDemidov** [comment]
We have the same issue - after recent update behat stopped sending anything into default.xml.

**Comment by everzet** [comment]
@AlexeyDemidov can you please open an issues following https://github.com/Behat/Behat/blob/master/CONTRIBUTING.md#submitting-an-issue guidelines?
