### ISSUE TITLE
3.1 - Getting scenario in After Step

### ISSUE THREAD

**Issue by davidsteinsland** [Behat/Behat#939]
Is this possible? The `AfterStepScope` and associated `StepNode` does not have any references to which scenario it is being executed in. The associated `FeatureNode` gives me the background node and a list of scenarios.

Aside from having a counter in `BeforeScenario` or something, can this be achieved?

**Comment by spolischook** [comment]
What goal you want to achieve?

**Comment by davidsteinsland** [comment]
I am implementing a simple `AfterStep` listener which gathers data about every step executed; which suite its in, which feature, which scenario, and so on. All the needed data is already provided by the scope, but not the scenario. And this made me wonder if this was a simple slip? Not to complain or anything, but it just comes off a bit weird that scenario is the only thing missing.

Because a step may be attached to a background, I thought I'd do something like:
```php
/** ScenarioLikeInterface */
$scenario = $step->hasScenario() ? $step->getScenario() : $feature->getBackground();
```

**Comment by spolischook** [comment]
I have similar task, but I don't care about scenario context https://github.com/orocrm/platform/blob/5797bf9fd64ad5a20f7ae2fc17a8c9ecf03101dc/src/Oro/Bundle/TestFrameworkBundle/Behat/Listener/StepDurationMeasureSubscriber.php

**Comment by everzet** [comment]
Your listener can listen to more than one event. If the event you look at doesn't provide needed context, try previous event in the chain - `BeforeScenario`

**Comment by Kolyunya** [comment]
@everzet imagine a scenario when we need to log step error *and* the whole scenario in which it occurred (attached to the same log message).

Currently, there's no straightforward way to achieve this because:
1. To get the error this code should belong to the `@AfterStep` handler.
2. To get the scenario this code should belong to the `@AfterScenario` handler.

So are there any real reasons why we can not have a reference to the scenario in the step node? If the answer is no, then can we reopen this one?

**Comment by snapshotpl** [comment]
@Kolyunya Workaround:

```php
    /**
     * @AfterStep
     */
    public function hook(AfterStepScope $scope): void
    {
        $currentStep = $scope->getStep();

        foreach ($scope->getFeature()->getScenarios() as $scenario) {
            foreach ($scenario->getSteps() as $step) {
                if ($step === $currentStep) {
                    // $scenario here!
                }
            }
        }
    }
```
