### ISSUE TITLE
Behat Interactive Shell

### ISSUE THREAD

**Issue by grahamc** [Behat/Behat#94]
Oftentimes while developing functional tests, I run into very minor errors. The ability to run the commands first in an interactive shell (using readline even?) where it is possible to go back and re-try tests would be wonderful. Being able to then save that out to a file would be even better.

I looked into the Gherkin source: https://github.com/Behat/Gherkin/blob/master/src/Behat/Gherkin/Loader/LoaderInterface.php

If this used `Iterator` it would be much easier, since the `next` could have a readline call in it. Otherwise, it looks like it would be pretty tricky.

So... yeah.

 :trollface:

**Comment by lindsaymacvean** [comment]
How do I implement this into my feature context file, do I use a 'use' statement or should I change this into a class?

**Comment by lindsaymacvean** [comment]
I put this trait in another file called InteractiveShell.php
Then called it from my main FeatureContext.php file like so:

`
include 'InteractiveShell.php';
class WebContext extends MinkExtension
{
  use DevelopmentDictionary;
}
`

**Comment by everzet** [comment]
I'm closing this issue as it is seems to be very old. Please reopen with updated stats if that's not the case!
