### ISSUE TITLE
JUnit Output stopped producing anything meaningful 

### ISSUE THREAD

**Issue by AlexeyDemidov** [Behat/Behat#947]
We have behat running from Jenkins. It is installed with composer using 'dev-master'. After recent 'composer update' we started getting almost empty 'default.xml' output for jUnit log output format: 

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="default"></testsuites>
```

This is a problem as we can't  see formatted test results in Jenkins.

We use following command line: 

```
bin/behat --name STAGING -f pretty -o std -f junit --out logs -p staging
```

Previous version was with commit hash '149f8881a1df56496c37094f32d05b53e0cde37b'. I tried locking behat to version '3.1'  (commit hash '359d987b3064d78f2d3a6ba3a355277f3b09b47f') but issue is still present.

**Comment by everzet** [comment]
Please provide **more context** about your test suite. Problem is not inherently in Behat an it is something absolutely local to your environment:

<img width="955" alt="screen shot 2016-09-16 at 07 57 08" src="https://cloud.githubusercontent.com/assets/30813/18577698/4778e63a-7be3-11e6-9720-3a76f84d7c51.png">

**Comment by AlexeyDemidov** [comment]
@everzet  can you please clarify - do you mean that a change in a feature, a context or `behat.yml` can completely break logging output for some formatter? Can you suggest what kind of changes I should look for?

**Comment by everzet** [comment]
No, that's not what I mean. What I mean is that I have no idea why output formatter doesn't work for you. All I know is that it *does* work for me and there's not enough information in your issue to guess why it might not work for you.

**Comment by everzet** [comment]
@AlexeyDemidov can you try to run the Behat's own test suite on your machine? In particular the `junit_format.feature`.

**Comment by AlexeyDemidov** [comment]
@everzet behat tests runs green in the same Jenkins environment. 

I have also tried checking out our project with the commit before the last 'composer update' and it produced jUnit output as expected so it is definitely not the environment. Only things changed are dependencies installed by composer and a lot of changes in behat context - developers reworked tests to use DbContext to insert DB records before running tests. I also pinned behat version to the commit which was working before but it still fails to produce jUnit output (normal -f pretty output is working as expected)

Our current composer.json

```
{
    "require": {
        "behat/behat": "dev-master#149f8881a1df56496c37094f32d05b53e0cde37b",
        "behat/mink-extension": "*",
        "behat/mink-selenium2-driver": "*",
        "behat/mink-goutte-driver": "*",
        "fzaninotto/faker": "*",
        "phpunit/phpunit": "*",
        "edmondscommerce/behat-javascript-context": "dev-master"
    },
    "config": {
        "bin-dir": "bin/"
    }
}
```

**Comment by everzet** [comment]
@AlexeyDemidov do the progress or pretty formatters produce output?

**Comment by AlexeyDemidov** [comment]
@everzet Yes, both progress and pretty formatting are working in all cases.

**Comment by AlexeyDemidov** [comment]
@everzet I did additional testing and noticed that if run individual feature then jUnit output is generated as expected. I have tried both failing and successful features and they both did produce jUnit output.

**Comment by everzet** [comment]
@AlexeyDemidov this is very strange, but we're getting somewhere. Can you show me your `behat.yml`?

**Comment by AlexeyDemidov** [comment]
@everzet it is really weird but after my last comment developers tried running full test suite and it produced jUnit output too.

 I have two explanation for this - either I missed to test full suite after tweaking composer.json dependencies  (there was no other changes to test suite since this issue was opened) or another explanation is that running individual features fixed something in DB which previously caused tests to fail and abort behat run in such way so behat failed to write default.xml at the end of run. I'm currently trying to tweak composer.json again but full test suite takes 2 hours to complete so it will take me some time to get something to report.

**Comment by everzet** [comment]
> full test suite takes 2 hours to complete
😢

**Comment by AlexeyDemidov** [comment]
I was able to reproduce failure to output jUnit format logs - test suite run failed with following message:

```                                                                                 
  [WebDriver\Exception\ScriptTimeout]                                                                                      
  timeout: Timed out receiving message from renderer: 10.000                                                               
    (Session info: chrome=49.0.2623.112)                                                                                   
    (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 3.2.0-4-amd64 x86_64  
  ) (WARNING: The server did not provide any stacktrace information)                                                       
  Command duration or timeout: 310.01 seconds                                                                              
  Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'                                          
  System info: host: 'ci.domain.com', ip: 'X.X.X.X', os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.0-4-amd64'  , java.version: '1.7.0_111'                                                                                              
  Session ID: 4f12ce8ce475736d0240aaaaf0fa9cab                                                                             
  Driver info: org.openqa.selenium.chrome.ChromeDriver                                                                     
  Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.P6u8KS, chromedriverVersion=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a)}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=49.0.2623.112, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]                              
                                                                                                                           

behat [-s|--suite SUITE] [-f|--format FORMAT] [-o|--out OUT] [--format-settings FORMAT-SETTINGS] [--init] [--lang LANG] [--name NAME] [--tags TAGS] [--role ROLE] [--story-syntax] [-d|--definitions DEFINITIONS] [--snippets-for [SNIPPETS-FOR]] [--snippets-type SNIPPETS-TYPE] [--append-snippets] [--no-snippets] [--strict] [--order ORDER] [--rerun] [--stop-on-failure] [--dry-run] [--] [<paths>]
```

**Comment by everzet** [comment]
Well, here you go. In php 5.3 and 5.4 we can not effectively render the junit output on deeper error:
https://github.com/Behat/Behat/blob/master/features/junit_format.feature#L529-L587

This is fixed for further php versions starting from 5.5. Both PHP 5.3 and 5.4 are effectively reached their end of lives years ago. I suggest you upgrade the version of php you run your tests on. As it seems your tests are isolated from your environment anyways (end-to-end), that should not require you updating your actual application (if you can't).

**Comment by AlexeyDemidov** [comment]
@everzet Actually we have PHP 5.5.38 and not 5.3 or 5.4.

**Comment by everzet** [comment]
@AlexeyDemidov can you debug a bit further on your local machine? At this point I'm at loss of ideas and am constrained by complete inability to reproduce your problem.

**Comment by AlexeyDemidov** [comment]
@everzet could you give a hint how I can approach it? I can read and tweak PHP code but I'm not a PHP developer.
