### ISSUE TITLE
3.1 - Transforms

### ISSUE THREAD

**Issue by davidsteinsland** [Behat/Behat#949]
It would be nice if the transform regex would match the value from the step, and not the definition.

Assume we have a base URL in an environment variable called "BASE_URI", I would then try to implement it as such:

```
When I am on "env:BASE_URI"
```

And then register a transformation function for the `env:[A-Z_-]+` regex. But this does not match, because the step definition of `When I am on` does not contain `env:`.

So instead I have to have a transformation function for the following regex:
```
(?P<page>[^"]+)
```
... which would match _anything_ besides `"`.

**Comment by spolischook** [comment]
I think problem in this approach that this is not readable for business person.

**Comment by davidsteinsland** [comment]
The `BASE_URI` was just an example, but I don't see the problem with the transformation matching feature though.

**Comment by everzet** [comment]
The core purpose of transformations is to keep your scenarios problem-focused and clean from all the programming craft. Seems like you're trying to make a programming language out of your scenarios. There are better tools to do just that.
