### ISSUE TITLE
Stop on failure with strict mode

### ISSUE THREAD

**Issue by estevejm** [Behat/Behat#951]
Given that
- `--strict` option will make the tests fail if there's a missing step
- `--stop-on-failure` option will stop test execution as soon as a step fails

If we run Behat with both options I would expect it to stop test execution as soon as it detects a missing step. Unfortunately, this is not how this is working currently. 

Do you think it makes sense to change this behaviour? I would be happy to help...

BTW, I'm using PHP 5.6 with Behat 3.1

**Comment by everzet** [comment]
I agree with this

**Comment by everzet** [comment]
Closed in 954
