### ISSUE TITLE
fillField function is always losing the focus of an element when triggered

### ISSUE THREAD

**Issue by kwoxer** [Behat/Behat#953]
Versions:
```
    "cweagans/composer-patches": "~1.0",
    "drupal/drupal-extension": "3.2.2",
    "behat/mink-selenium2-driver": "1.3.1",
    "jarnaiz/behat-junit-formatter": "1.3.2",
    "emuse/behat-html-formatter": "0.1.0"
```

I was reading https://github.com/Behat/Behat/issues/96 and would like to have those:

```
  When I bring the focus to input field "<id>"
  When I type "<text>" in input field "<id>"
```
But they do not exists and any way to try to create them on my own failed.

So my current state of my own function:

```
/**
   * @Given I give focus to the css selector :selector
   */
  public function iGiveFocusToTheCssSelector($css_selector)
  {
    $element = $this->getSession()->getPage()->find("css", $css_selector);
    if ($css_selector === NULL) {
      throw new \Exception(sprintf('Could not evaluate CSS Selector: "%s"', $element, $this->getSession()->getCurrentUrl()));
    }

    $element->click();
    $element->fillField("some-field","some text...");
  }
```
It works. It selects the field and types in the text. But it is always loosing focus of that field. Also If I directly try to press enter directly afterwards with:

```
    $script = "jQuery.event.trigger({ type : 'keypress', which : '13' });";
    $this->getSession()->evaluateScript($script);
```

it has still looses the focus and nothing happens anymore.

Is there a way to stop Behat/Mink from loosing the focus on fields? Why is it loosing the focus? It does not really makes sense to me.

And the reason why it is so important to me, is because I'm waiting for the suggesting box that pops out just when the focus of the field is given.

**Comment by jakzal** [comment]
This is not really Behat related. You should probably report this to https://github.com/Behat/MinkExtension.

**Comment by spolischook** [comment]
Reason - https://github.com/minkphp/MinkSelenium2Driver/blob/22c10858e5204ac8dfe85f2d0b576cdb04cd2ec3/src/Selenium2Driver.php#L679-L681

**Comment by spolischook** [comment]
You have two ways:
- Extend driver and redefine default behavior
- Add custom method to element and fill it as you wish (you can set value without TAB or set plain value to input)

**Comment by kwoxer** [comment]
Alright I openend issue here: https://github.com/Behat/MinkExtension/issues/257

You can close here.

@spolischook, I already have that patch with the Key::TAB active. My issue is more that the "fillField" is filling the field properly but losing focus of the field afterwards.

This must by some core functionality of Behat/Mink.
