### ISSUE TITLE
Behat Failing with PHP 7 Syntax Error

### ISSUE THREAD

**Issue by stevepop** [Behat/Behat#956]
I am using Behat in my Laravel Application and I am using a package, Spatie Analytics. The package uses the PHP7 type hinting syntax in the following method;
```
 public function fetchVisitorsAndPageViews(Period $period): Collection
    {
        $response = $this->performQuery(
            $period,
            'ga:users,ga:pageviews',
            ['dimensions' => 'ga:date,ga:pageTitle']
        );

        return collect($response['rows'] ?? [])->map(function (array $dateRow) {
            return [
                'date' => Carbon::createFromFormat('Ymd', $dateRow[0]),
                'pageTitle' => $dateRow[1],
                'visitors' => (int) $dateRow[2],
                'pageViews' => (int) $dateRow[3],
            ];
        });
    }
```
Behat triggers the following error;
```
Message: `syntax error, unexpected ':', expecting ';' or '{'` 
URI http://test.domain.dev/api/analytics
File: /vagrant/vendor/spatie/laravel-analytics/src/Analytics.php
Line: 43
```
Line 43 refers the start of function above.  
This functionality works without errors in normal usage so not sure why Behat fails with this error. 

PHP Version: 7.0.1
Behat version: 3.2.1

**Comment by ciaranmcnulty** [comment]
That PHP error indicates the code isn't being run on PHP 7

**Comment by everzet** [comment]
What @ciaranmcnulty said. Your application itself seems to be running on anything but PHP7. Running Behat on php7 doesn't change which version of php your application runs on.

**Comment by near93** [comment]
Changed my PHP version to 5.6.*
