### ISSUE TITLE
Transformations are not sorted properly on different php version.

### ISSUE THREAD

**Issue by rajeshtaneja** [Behat/Behat#959]
After transformation priority was introduced in Behat 3.2.1, the [usort](https://github.com/Behat/Behat/commit/028d580becb7da8832b408cd9cd305adfcefd16b#diff-8de83ac254d386c504edff73673bde33R84), transformations returned are different on different php versions. This is causing issues as transformation happens in wrong order.

What we are observing is the list of transformations returned if different order in php 5.6 and php 7.0. This can be seen by execution the code: http://sandbox.onlinephpfunctions.com/code/2682908b6d169df3c412767dcb73b20568e03675

**Comment by everzet** [comment]
Oh PHP...

**Comment by everzet** [comment]
@rajeshtaneja can you check if #963 fixes you problem?

**Comment by rajeshtaneja** [comment]
Thanks for fixing this @everzet,

Confirming, patch resolves the issue.

**Comment by tkotosz** [comment]
Oh good to know about this. Probably the controllers sort order in behat changed for me because of the same usort change in php. [see](https://github.com/ciaranmcnulty/behat-stepthroughextension/pull/6#issuecomment-253968926)
