### ISSUE TITLE
Silent error when code in beforeScenario hook throws a warning

### ISSUE THREAD

**Issue by ThomWilhelm** [Behat/Behat#960]
In my FeatureContext I had a situation where I accidentally tried setting timeouts but had referenced the wrong variable. This made me notice that if you trigger any type of PHP warning or notice in the beforeScenario function, behat fails silently and all tests are skipped, but doesn't seem to display the error in any of it's or reports.

If PHP throws a warning during a test step, I can see this error in the test result and fix it. Is there any way to do the same for hooks?

**Comment by everzet** [comment]
<img width="839" alt="screen shot 2016-10-30 at 11 17 11" src="https://cloud.githubusercontent.com/assets/30813/19836259/73f4ace0-9e92-11e6-97f2-a77429eed7b6.png">

Check you `php.ini` config and make sure you catch warnings and errors in the environment in which you run Behat.
