### ISSUE TITLE
Features directory created when a config already exists

### ISSUE THREAD

**Issue by unfunco** [Behat/Behat#964]
I was quite surprised that having an existing `behat.yml` (copied from another of my projects) and then running `behat --init` placed the Context class that was specified in my `autoload-dev` section of my `composer.json` into the `feature` directory (but excessively created additional namespace directories) – however, Behat also created an empty `features` directory which was unnecessary, so the following scenario should cover the behaviour I would have expected, I'm reporting the issue now... I don't mind looking at it when I get a moment.

```cucumber
Feature: Developer creates a new project

  Scenario: Developer initialises behat with an existing configuration
    Given I have a "behat.yml" with the following contents:
      """
      default:
        autoload:
          - %paths.base%/feature/context
        formatters:
          pretty: true
        suites:
          default:
            contexts:
              - "Replenish\\Feature\\Context\\ReplenishContext"
      """
    And I have a "composer.json" which contains the following contents:
      """
      "autoload-dev": {
        "psr-4": {
            "Replenish\\Feature\\Context\\": "feature/context/"
        }
      },
      """
    When I run "vendor/bin/behat --init"
    Then a new class should be generated in "feature/context/ReplenishContext.php"
      But a "features" folder should not exist
```

**Comment by everzet** [comment]
`features` folder was created because you didn't change the `paths` setting of your default suite:

```
default:
  suites:
    default:
      contexts:
        - 'Replenish\\Feature\\Context\\ReplenishContext'
      paths: [ '%paths.base%/features' ] # <- is the default setting
```

Behat's built-in autoloader and, by extension, `--init` does not support PSR-4. But `--init` would not attempt to generate a class if class already exists and autoloadable by Composer.

Also, if you use Composer's autoloader there's no need to specify `autoload` section in Behat.
