### ISSUE TITLE
Add Question Helper to Behat Application

### ISSUE THREAD

**Issue by spolischook** [Behat/Behat#965]
Hi!
I have some isolation around my features.
Isolation is about restore cache, or restore DB or whatever.
If some fatal error was happen during tests execution it may produce inconstancy in test application state.
As a developer
I want to inform user that state is inconstancy and  give him a choice - restore state or use current state.
http://symfony.com/doc/2.8/components/console/helpers/questionhelper.html

```gherkin
Given I run vendor/bin/behat broken_state.feature
And I should see that state is broken
And "Restore or continue R/C" question is shown on console
When I choose R
Then state will restored
```

**Comment by everzet** [comment]
Check what PhpSpec does:
https://github.com/phpspec/phpspec/blob/master/features/bootstrap/ApplicationContext.php#L117-L132

I think it answers your question. If it does, please close this issue.

**Comment by spolischook** [comment]
I discover that QuestionHelper has no any other dependencies except input and output, so I just use it in Controller. Thanks for your attention.
