### ISSUE TITLE
curlopt_httpheader in behat.yml

### ISSUE THREAD

**Issue by Trogie** [Behat/Behat#966]
Hello,

I'm looking for the best way to add headers to goutte/guzzle requests. Problem is that most environments are getting https but the termination of ssl is on the loadbalancers and not the webservers. So when I try to connect to http://projecthostname it redirects me to https://projecthostname but the non-javascript tests are being run on the machine themselfs (drupal api driver) and the localhost doesnt respond except the 'x-forwarded-proto' header is added...

Any idea how to make this happen?

Thanks,
Trogie

**Comment by stof** [comment]
this has nothing to do with Behat itself, as it does not deal with Goutte or Guzzle in any way (and so has no idea where they are configured)

**Comment by Trogie** [comment]
Yes I knew this was probably not the best place to put it but as there are so many different projects...

Thanks

**Comment by stof** [comment]
Yeah, but as I don't know which project relying on Guzzle you are using, I cannot help you
