### ISSUE TITLE
How to handle Behat errors?

### ISSUE THREAD

**Issue by pocky** [Behat/Behat#970]
Hello,

My question is related to this issue : https://github.com/richardmiller/ErrorExtension/issues/2

I would like to know how to get errors encountered by Behat during the execution of the tests. I just (and honestly) don't understand how Behat works for this.

Thanks a lot.

**Comment by everzet** [comment]
@pocky can you give me an example of what is it you're trying to do?

**Comment by pocky** [comment]
@everzet 

My context

```php
<?php

use Behat\Behat\Context\Context;
use Behat\Gherkin\Node\PyStringNode;
use Behat\Gherkin\Node\TableNode;
use Behat\Behat\Tester\Exception\PendingException;

/**
 * Defines application features from the specific context.
 */
class FeatureContext implements Context
{
    /**
     * @Then I say thanks :name
     */
    public function iSayThanks($name)
    {
        $this->customer->thanks();
    }
}
```

And result:

```
Feature: Test project

  Scenario:                               # features/beer.feature:3
    Given I am a customer                 # FeatureContext::iAmACustomer()
    When I want a beer                    # FeatureContext::iWantABeer()
    Then the bartender should give me one # FeatureContext::theBartenderShouldGiveOne()
    And I say thanks "Tom"                # FeatureContext::iSayThanks()
      Fatal error: Call to undefined method Customer::thanks() (Behat\Testwork\Call\Exception\FatalThrowableError)
    And I drink my beer                   # FeatureContext::iDrinkMyBeer()
    And I am "drunk"                      # FeatureContext::iAm()

--- Failed scenarios:

    features/beer.feature:3

1 scenario (1 failed)
6 steps (3 passed, 1 failed, 2 skipped)
0m0.02s (8.77Mb)
```

I want to catch the exception in `And I say thanks "Tom"                # FeatureContext::iSayThanks()
      Fatal error: Call to undefined method Customer::thanks() (Behat\Testwork\Call\Exception\FatalThrowableError)` with this [tester](https://github.com/richardmiller/ErrorExtension/blob/master/src/Tester/ErrorTester.php).

The actual code use [error_get_last()](https://github.com/richardmiller/ErrorExtension/blob/master/src/Tester/ErrorTester.php#L85) which, as says @stof on [my issue](https://github.com/richardmiller/ErrorExtension/issues/2#issuecomment-264834723), doesn't work with exception. I tried to catch the exception with a simple try/catch and behat events but I can't find the right solution.

Do you need more information?

**Comment by pocky** [comment]
I close this problem because I found the solution by refactoring class. ErrorTester implements StepTester to get the result of each step with ExecutedStepResult and then does its job in case of exception.

Thanks (again) for Behat and phpspec.

![phpspec](https://cloud.githubusercontent.com/assets/204451/20908120/c8b815fa-bb52-11e6-8296-425c5d1d5526.gif)
