### ISSUE TITLE
use phpunit framework in behat

### ISSUE THREAD

**Issue by mohammad073** [Behat/Behat#972]
hi all
me have problem with my project in behat.
my OS is windows 10 and install xampp and install php unit with composer and install behat with composer
but when run my project behat in shell of xampp send this error:

Fatal error: Class 'PHPUnit_Framework_Assert' not found 

how me can solve this problem ?

**Comment by Taluu** [comment]
require `phpunit` as a dev dependency, or use another assert framework such as https://github.com/webmozart/assert

**Comment by everzet** [comment]
What @Taluu said

**Comment by kenorb** [comment]
Related: sebastianbergmann/phpunit/issues/2585
