### ISSUE TITLE
Click radio buttons

### ISSUE THREAD

**Issue by SamyOteroGlez** [Behat/Behat#973]
Hi,

In order to fill a form I need to click on a radio button but the element is like:

```
<div class="row question-group question ">
    <label for="radio" class="question-label ">
        The field question?
    </label>
    <div class="radio">
        <input id="radio_1" name="radio" type="radio" value="1">
        <label for="radio_1">
            Yes
        </label>
        <input id="radio_2" name="radio" type="radio" value="0">
        <label for="radio_2">
            No
        </label>
    </div>
</div>
```
At this moment I cant use click or press() functions.

Thanks in advance.

Samy

**Comment by stof** [comment]
Radio inputs are covered by ``selectOption``, as they are about selecting a choice in a radio group.

Btw, ``<input type="radio">`` is never considered as a button in HTML, which is why our button APIs don't deal with them.

**Comment by SamyOteroGlez** [comment]
Thank you very much for the response.

I tried to use that function `selectOption($select, $option)` but I'm getting this error

```
Element is not clickable at point (1245, 9.333328247070312). 
Other element would receive the click: 
<a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
```

Also I tried writing a test to check a radio button on the bootstrap page, wish are the same I'm using in my project and it works perfectly well.

I read about it on:
[http://stackoverflow.com/questions/18979890/check-radio-button-with-behat](http://stackoverflow.com/questions/18979890/check-radio-button-with-behat)
[http://stackoverflow.com/questions/13518157/check-radio-button-state-in-a-behat-mink-scenario](http://stackoverflow.com/questions/13518157/check-radio-button-state-in-a-behat-mink-scenario)
[https://github.com/Behat/MinkExtension/issues/166](https://github.com/Behat/MinkExtension/issues/166)

Here is how looks the radio button:
![screenshot from 2016-12-16 09 52 45](https://cloud.githubusercontent.com/assets/8644532/21266824/b6e8c9a2-c375-11e6-932a-81e45eb8604a.png)


I'm not sure how to solve this.

Thanks in advance.

Samy

**Comment by SamyOteroGlez** [comment]
In this case, the radiobutton it's hidden, and you can check/un-check it using the labels and it takes the value using js.

That could be the reason of my issue?

if that is the case, 
How can I test that behaviour using behat/mink?

Thanks

Samy

**Comment by everzet** [comment]
Please open your issue at minkphp/mink There people more suited will be able to help you.
