### ISSUE TITLE
Automatically specify Context for the Feature

### ISSUE THREAD

**Issue by funivan** [Behat/Behat#975]
Is there any way to use specific context for each feature?
For example my tests directory.
```
tests/
  Users/
    Users.feature
    UsersContext.php
    RenameUser.feature
    RenameUserContext.php
  App/
    AppInit.feature
    AppInitContext.php
```
`Users.feature => UsersContext.php` - should be used
I find one way to do that. Write suites in the configuration file. But it is a little bit annoying to do that for each feature.
Other thing I try to use extensions. But I can`t do that.

**Comment by edno** [comment]
Why using one context per feature?

**Comment by everzet** [comment]
Why would you do that?

**Comment by funivan** [comment]
- Want to store features near the context. 
- Big amount of features (80) Store methods in several contexts become confusing.
- Easy to specify destination of the snippets (on the automatic snippet generation)

**Comment by stof** [comment]
Contexts are defined per suite, so this would force to have a different suite for each feature file

**Comment by funivan** [comment]
@stof Thanks. Using `Extention` and `Controller` I can add custom suites to the configuration.  Each suite contains `feature` and `contexts`
