### ISSUE TITLE
Apostrophes causing unexpected capitals in snippets

### ISSUE THREAD

**Issue by WillGibson** [Behat/Behat#976]
When we have steps like...

```
Given the Client's Account is Suspended
````

...the suggested snippets some out with a capital S in the method names where we would expect a lower one...

```
public function theClientSAccountIsSuspended()
```

...instead of this, which we would expect...

```
public function theClientsAccountIsSuspended()
```

Not a big deal really, but it is triggering some anal retentive tremors in myself and a colleague, so I will probably try to find time to make a PR to change this behaviour in the new year.

**Comment by WillGibson** [comment]
Hi @everzet,

I just started to prepare for this and figured a good first step would be to check all the Behat tests pass before I do anything so I know for sure if I broke stuff :-)

Mostly they do but I'm getting some fails like on...

```
LANG=C bin/behat features/extensions.feature:127
```

...which is failing because of some extra output at my end not being what the test is expecting...

```
Failed asserting that 'FF

      --- Failed steps:

      001 Scenario:                  # features/extensions.feature:2
            Given non-existent class # features/extensions.feature:3
              Fatal error: Class 'Non\Existent\Cls' not found (Behat\Testwork\Call\Exception\FatalThrowableError)

      002 Scenario:                   # features/extensions.feature:4
            Given non-existent method # features/extensions.feature:5
              Fatal error: Call to undefined method FeatureContext::getName() (Behat\Testwork\Call\Exception\FatalThrowableError)

      2 scenarios (2 failed)
      2 steps (2 failed)
      /private/var/folders/k1/n7wy5pjj069dvry_2tspxcxh0000gq/T/behat/3a3a1475b52d2e7f1f1542f8518417c5/custom_extension.php:12:
      string(16) "Non\Existent\Cls"
      /private/var/folders/k1/n7wy5pjj069dvry_2tspxcxh0000gq/T/behat/3a3a1475b52d2e7f1f1542f8518417c5/custom_extension.php:17:
      array(2) {
        [0] =>
        string(14) "FeatureContext"
        [1] =>
        string(7) "getName"
      }' contains "FF

      --- Failed steps:

      001 Scenario:                  # features/extensions.feature:2
            Given non-existent class # features/extensions.feature:3
              Fatal error: Class 'Non\Existent\Cls' not found (Behat\Testwork\Call\Exception\FatalThrowableError)

      002 Scenario:                   # features/extensions.feature:4
            Given non-existent method # features/extensions.feature:5
              Fatal error: Call to undefined method FeatureContext::getName() (Behat\Testwork\Call\Exception\FatalThrowableError)

      2 scenarios (2 failed)
      2 steps (2 failed)
      string(16) "Non\Existent\Cls"
      array(2) {
        [0]=>
        string(14) "FeatureContext"
        [1]=>
        string(7) "getName"
      }".
```

I think it's jsut the two lines starting with `/private/var/folders/`.

I'm sure that in some way this is my fault, but wondered if you have come across it before and could shed any light?

Currently running PHP 7.1.0 on macOS 10.12.2 if that makes any odds.

**Comment by WillGibson** [comment]
FYI I've had a go at writing a scenario which will fail until such a time as I have made the required changes to make it pass, without breaking any of the other tests of course.

https://github.com/Behat/Behat/compare/master...BiffBangPow:feature/976-apostrophes-vs-capitals-in-snippets

**Comment by stof** [comment]
I think this is because you have xdebug enabled with ``xdebug.overload_var_dump = 2`` in your php.ini, which adds the location before the dump output.

IIRC, Xdebug switched the default value of this ini setting from 1 (overload with the colored output but a compatible format) to 2 in a recent version

**Comment by WillGibson** [comment]
Thanks @stof, that solves that one. 

I have one test still failing depending on which PHP version I run them in...

Running...

```
LANG=C bin/behat features/junit_format.feature:530
```

PHP 5.6 - Passes

PHP 7.0.9 & 7.1.0 - Fails with...

```
Then it should fail with:
      """
      Call to undefined method PHPUnit_Framework_Assert::assertEqual
      """
      Failed asserting that '' contains "Call to undefined method PHPUnit_Framework_Assert::assertEqual".
```

Something changed with PHP 7+ that the tests don't yet cater for?

Or something in my config?

I don't know, but I need to get home for now.

**Comment by WillGibson** [comment]
Hi @everzet,

Just thinking out loud now, but with the way some of Behat's own tests are checking output which may depend on someone's local configuration, I'm wondering if it would be worth considering including a docker configuration so that folks like me can fire it up in an environment where we know all the tests will pass?

**Comment by WillGibson** [comment]
Never mind, a colleague suggested that I ignore the local fails and just let Travis take care of the "Did I break anything". Which will do the trick.

**Comment by WillGibson** [comment]
Hi @everzet, We have a spike day today, so I thought I'd get onto this. Then I realised I have no idea how to test any changes I make to the snippet generating code locally, `bin/behat features/snippets.feature` runs the existing compiled code of course.

I'm still trying to figure it out, but how do I run the feature through the code I'm playing with?

**Comment by WillGibson** [comment]
Actually, scratch that, I'm being thick and obviously not finding the right bit to change, hence changes having no effect. I'll get there :-)

**Comment by WillGibson** [comment]
OK, there's a couple of pull requests that go together to address this.

I'm not sure if they break backwards compatibility in a way that might upset anyone?
