### ISSUE TITLE
Setup language browser in behat.yml

### ISSUE THREAD

**Issue by Kralock** [Behat/Behat#977]
Hi guys, 

I have a problem. I can not change the language through my docker selenium chrome browser in my behat.yml.

I try lots of conf (Guzzle, extra_capabilities...)

my example : 
`jenkins:
    extensions:
        Behat\MinkExtension:
            base_url:  'http://xxxxxxxxx.xx' 
            browser_name: chrome
            sessions:
                selenium2: # fast, CLI, opens up a browser
                    selenium2:
                       wd_host: http://xx.xx.xx.xx:xxxx/wd/hub # chrome
                       capabilities: {'platform':'WINDOWS', 'browser':'chrome', 'version':'34', 'extra_capabilities': {'chromeOptions':{ 'args':['--lang=fr'] } } }`

Or 

`Behat\MinkExtension:
            goutte:
              guzzle_parameters:
                verify: false
                headers:
                  Accept-Language: fr
            base_url:  'http://xxx.xxx.xx'
            browser_name: chrome
            sessions:
                selenium2: # fast, CLI, opens up a browser
                    selenium2:
                       wd_host: http://xx.xx.xx.xx:xxxx/wd/hub # chrome
                       capabilities: {'platform':'WINDOWS', 'browser':'chrome', 'version':'34' }`
 
Not working...

I search around web and no clue for doing that... :(

**Comment by everzet** [comment]
Please open issue in https://github.com/Behat/MinkExtension
