### ISSUE TITLE
Nestable, easy to define, locations for Mink

### ISSUE THREAD

**Issue by jonathanjfshaw** [Behat/Behat#978]
We often want to restrict the focus of a particular step to it a particular part of a page (a "location").

To do this easily I find myself tempted to write horrible steps like:
```
I should see "text" in the ".region-sidebar .block-search h2" element
I fill in "value" in the "field_myfieldname_value[1]" field
```
which leak implementation details into the tests in a way that violates the spirit of BDD.

It's obviously possible to write custom step definitions for these 2 steps; but what makes this tedious in practice is that there is a bazillion of possible individual locations if we have to define them all explicitly. To get round this we need to use arguments ('I should see "text" in a "search" block), but that approach bogs down because:
1) every possible location type I want to define has about 20 possible actions I might want to define in it
2) different locations sometimes need to be nestable inside each other and if we define the different possible nestings explicitly then the combinations explode.

The solution would seem to be to develop a syntax that allows defining locations (fields, blocks, regions, elements) separately from the behaviours (seeing, filling in, pressing, checking) that can be located in them.

Then we could have steps like
```
    Then I should see "Text" in the heading in the "Search" block in the "Sidebar" region
```
Which hypothetically would use 4 differently defined things:
- The built-in behavior _Then I should see "[^".*]"_ 
- The built-in location _in the heading_
- 2 custom-defined locations: _in the "[^".*]" block_ and _in the "[^".*]" region_

The ideal way to achieve this would seem to be to 
1) have a new type of step definition @Location joining the existing family of @Given, @When etc, and @Transformation.
2) Tag existing @When/Then steps with @Locatable if they can validly be called with additional location text appended to them
3) Have these existing location steps use session->getLocation() instead of session->getPage() to make them use only the part of the page specified by  the @Locations.

I have tried to achieve something similar more simply using transformations, but have hit things that require ugly workarounds:

A) NESTING: I have not found a way to get the individual location transformations to be called in the right order (from right to left, i.e. from outer to inner), so they could make locate themselves within the previous location. Therefore I've had to instead have them return a kind of encoded string that specifies a precise search location, and then in a second stage of transformation turn that compound string into a NodeElement. Unfortunately this second-stage transformation must be defined AFTER the other location functions, which is slightly annoying.

B) ADDING THE ARGUMENT: I've no idea how to get existing step definitions to automatically accept an additional optional location argument, so I have to redefine the whole of MinkContext.

C) WEBASSERT: Some parts of WebAssert like pageTextContains() insist on accessing getPage() directly rather than accepting an (optional) $container argument and confining their search within that in the way that other parts of WebAssert like fieldExists() do.

A simplified version of the nearest I've been able to get so far by fumbling around is:
```
/**
   * Allow locating of any element using a css expression.
   * 
   * @Transform /(.*)in the "(.*)" element(.*)/
   *
   * @param string $before
   * @param string $locator
   * @param string $after
   * @return string
   */
  public function elementLocation($before ="", $locator, $after ="")
  {
    return $before . 'in the "' . $locator . '" "css" location' . $after;
  }

  /**
   * Allow locating of blocks by their id.
   * 
   * @Transform /(.*)in the "(.*)" block(.*)/
   *
   * @param string $before
   * @param string $locator
   * @param string $after
   * @return string
   */
  public function blockLocation($before="", $locator, $after ="")
  {
    return $before . 'in the "block-' . $this->stringToClassName($locator) . '" "named:id" location' . $after;
  }

  /**
   * Allow locating of headings.
   * 
   * @Transform /(.*)in the heading(.*)/
   *
   * @param string $before
   * @param string $locator
   * @param string $after
   * @return string
   */
  public function headingLocation($before="", $after ="")
  {
    return $before . 'in the "h1,h2,h3,h4,h5,h6" "css" location' . $after;
  }

  /**
   * Transform complete location argument (possibly containing multiple 
   * sub-arguments) into a NodeElement
   * 
   * @Transform /^in the "([^"]*)" "([^"]*)" location$/
   * @Transform /^in the "([^"]*)" "([^"]*)" location in the "([^"]*)" "([^"]*)" location$/
   * @Transform /^in the "([^"]*)" "([^"]*)" location in the "([^"]*)" "([^"]*)" location in the "([^"]*)" "([^"]*)" location$/
   * 
   * @param string $location1
   * @param string $locationType1
   * @param string $location2
   * @param string $locationType2
   * @param string $location3
   * @param string $locationType3
   * @return array

   */
  public function transformLocations($location1, $locationType1, $location2=NULL, $locationType2=NULL, $location3=NULL, $locationType3=NULL)
  {
    $locations = array();
    $locations[] = $this->getSession()->getPage();
    $currentLocationDescription = 'page ' . $this->getSession()->getCurrentUrl();

    if (!empty($location3)) {
      $locations = $this->getLocations($locations, $locationType3, $location3);
      if (count($locations) === 0) {
        throw new \Exception(sprintf('The "%s" %s location was not found in the %s.', $location3, $locationType3, $currentLocationDescription));
      }
      $currentLocationDescription = '"'. $location3 . '" ' . $locationType3 . ' location in the ' . $currentLocationDescription;
    }
    
    if (!empty($location2)) {
      $locations = $this->getLocations($locations, $locationType2, $location2);
      if (count($locations) === 0) {
        throw new \Exception(sprintf('The "%s" %s location was not found in the %s.', $location2, $locationType2, $currentLocationDescription));
      }
      $currentLocationDescription = '"'. $location2 . '" ' . $locationType2 . ' location in the ' . $currentLocationDescription;
    }
    
    $locations = $this->getLocations($locations, $locationType1, $location1);
    if (count($locations) === 0) {
      throw new \Exception(sprintf('The "%s" %s location was not found in the %s.', $location1, $locationType1, $currentLocationDescription));
    }

    return $locations;
  }

  /*
   * Transform a single location argument into an array of NodeElements by
   * searching within each of the current location(s) for elements matching
   * $locator using the $locatorType search method.
   * @param array $locations
   * @param string $locatorType
   * @param string $locator
   */
  protected function getLocations(array $locations, $locatorType, $locator) {

    // $locatorType can be of forms like
    // "named:id" or
    // "namedExact:content"
    // which are not in themselves valid arguments for ->find and
    // need to be translated into
    // ->find("named", array("id", ...)) and
    // ->find("namedExact", array("content", ...))
    if (substr($locatorType, 0, 5) === "named"){
      $locatorTypeParts = explode(":",$locatorType);
      $locatorType = $locatorTypeParts[0];
      $locator = array($locatorTypeParts[1],$locator);
    }

    $newLocations = array();
    foreach ($locations as $location) {
      $theseLocations = $location->findAll($locatorType, $locator);
      $newLocations = array_merge($newLocations, $theseLocations);
    }
    return $newLocations;
  }


  /**
   * Presses button with specified id|name|title|alt|value in a location
   * Example: When I press "Log In" in the "Account" block
   * Example: And I press "Log In" in the "Header" region
   *
   * @When /^(?:|I )press "(?P<button>(?:[^"]|\\")*)" (in the .*)$/
   */
  public function pressButton($button, array $locations = [])
  {
    $button = $this->fixStepArgument($button);
    $behavior = function ($location) use ($button) {
      return $location->pressButton($button);
    };
    $this->behaveInLocations($behavior, $locations);
  }

  protected function behaveInLocations($behavior, array $locations = [])
  {
    $results = array();
    foreach ($locations as $location) {
      $results[] = $behavior($location);
    }
    return $results;
  }
```

Any ideas for improving on this approach? Would this be a good feature for Mink?

**Comment by bwowk** [comment]
hey @jonathanjfshaw, you should open this at [Behat/MinkExtension](https://github.com/Behat/MinkExtension/issues)
Let's get that discussion going over there (:

**Comment by jonathanjfshaw** [comment]
Good point. I've opened https://github.com/Behat/MinkExtension/issues/265.
