### ISSUE TITLE
Implement Behat Formatter Wrapper extension point

### ISSUE THREAD

**Issue by bwowk** [Behat/Behat#981]
It would be great to have a Formatter Wrapper to be able to make some changes to step/scenario/feature text before handing it to the formatters, instead of having to implement an redundant wrapper for each of the specific formatters when there is any available (i.e.: pretty has an listener wrapper extension point, the [html formatter](https://github.com/dutchiexl/BehatHtmlFormatterPlugin) doesn't).

**Comment by bwowk** [comment]
Maybe Behat\Testwork\Call\Filter\ResultFilter(s) are the way to go about this, but currently the default Node Listeners get some of the output data from the original DefinitionCall, not from the CallResult (and even before Argument Transformations are applied).

Wouldn't it make more sense if they got everything from the CallResult so that it's possible to separately transform the result arguments?

With this approach, we could create ResultArgumentTransformers to preprocess arguments before sending them over to be formatted and outputed

**Comment by everzet** [comment]
What's your use case?

**Comment by bwowk** [comment]
I've wrote a [extension](https://github.com/ciandt-dev/behat-placeholders-extension) to allow the usage of placeholders on step arguments that can be replaced by different values based on a `--environment` CLI option and on specific @tags that appear on the scenarios. 

For example, if I have the step:
`Then I go to "${home}"`

And a yml file with mappings of that placeholder values for each environment:
```
home:
    pretty_name: the homepage
    $dev: dev.mysite.com
    $prod: www.mysite.com
```
I can run behat with `--environment=dev` to run it using the dev url, and with `--environment=prod` to use the prod one. The thing is, I wanna have that pretty_name value that will replace the placeholders on the output of every formatter, so in both cases it would read: `Then I go to" the homepage"`, to make some PO-friendly reports

**Comment by bwowk** [comment]
@everzet Would it make sense to have an `TRANSFORMATION_TAG` extension point on [OutputExtension](https://github.com/Behat/Behat/blob/a998d45dca71340d5dd79b60fe1b6f7c70ff08fe/src/Behat/Testwork/Output/ServiceContainer/OutputExtension.php) and an **OutputTransformation** interface akin to the [SimpleArgumentTransformation](https://github.com/Behat/Behat/blob/a998d45dca71340d5dd79b60fe1b6f7c70ff08fe/src/Behat/Behat/Transformation/SimpleArgumentTransformation.php) to go with it?

something like

```php
interface OutputTransformation {

    public function supportsEventAndName(Event $event, $name);

    public function transformEvent(Event $event, $name);

}
```
This way, we could make it so the [NodeEventListeningFormatter](https://github.com/Behat/Behat/blob/a998d45dca71340d5dd79b60fe1b6f7c70ff08fe/src/Behat/Testwork/Output/NodeEventListeningFormatter.php) gets an array of OutputTransformations and applies all of them to the incoming events.

If you think this makes sense I can invest myself in a PR.

**Comment by everzet** [comment]
Why don't you just replace the placeholders in Gherkin on the edge of the parsing phase?

Just implement your own version of [`GherkinFileLoader`](https://github.com/Behat/Gherkin/blob/master/src/Behat/Gherkin/Loader/GherkinFileLoader.php) and register it [as `GherkinExtension::LOADER_TAG` with higher priority than default `GherkinFileLoader`](https://github.com/Behat/Behat/blob/master/src/Behat/Behat/Gherkin/ServiceContainer/GherkinExtension.php#L227-L229). This way you can replace your placeholders on the parsing phase, making the process invisible to Behat.

**Comment by everzet** [comment]
In regards to extension point, I wouldn't touch formatters. They are easily the most complicated part of the codebase already and I'm very cautious at making it even worse.
