### ISSUE TITLE
Set a variable that can be used in any command

### ISSUE THREAD

**Issue by kwoxer** [Behat/Behat#985]
So let's say I have an URL like `Given I am on "/some-url-that-might-change-from-time-to-time"`.

This is used 50 times in 50 different scenarios. So when that URL is invalid I need to replace it. Is there a way to use a variable for that string. E.g.:` Given I am on "$url_var"`?

This would be very helpful for me. 

And I know I could extend or write my own `Given I am on "/some-url-that-might-change-from-time-to-time"` function that contains that variable. But I don't want to write more custom function that I need to.

**Comment by spolischook** [comment]
'''gherkin
Given I am on "Account Index" page
'''

and then mach this to url or even to route

**Comment by edno** [comment]
You can have a look at the extension https://github.com/edno/codeception-gherkin-param

**Comment by kwoxer** [comment]
Ahh right, via `return $url;` correct. Thank you.
