### ISSUE TITLE
Problem with ArgumentResolver

### ISSUE THREAD

**Issue by timiTao** [Behat/Behat#986]
I created extension for ZF for integration framework with behat. 
[BehatZendFrameworkExtension](https://github.com/alteris/behat-zendframework-extension/blob/master/src/Context/Argument/ServiceArgumentResolver.php)
Till 3.2 everything worked fine with argument resolver, that get services form ZF application.

On project with Behat 3.3, with container, this functionality started to set null in constructor of FeatureContext using Container and my extension.

I assume, that both solutions are now mutually exclusive?

Any option, to add both, with priority? or other solution.

**Comment by everzet** [comment]
They are exclusive on purpose to remove confusion. There is a concept of priority, but the container resolver has the highest priority there is.

If you really need to surface services from two containers, I'd suggest creating third, aggregate container, delegating to two others.

**Comment by timiTao** [comment]
Due to that, i'm working on https://github.com/timiTao/behat-aggregate-container. 

Any suggestions?
