### ISSUE TITLE
Just test specific row of a table via @tag 

### ISSUE THREAD

**Issue by kwoxer** [Behat/Behat#987]
Is there a way to set a tag on just one row.

So taking this feature here. I just want to set the tag @minimal on Trial role. So when the Testsuite minimal is running it just should test the Trial role. Is this somehow possible via table?

Or just realizable with another Scenario resulting in duplicating the code?

```
  Scenario Outline: Check if exercises are working for all roles
    Given I am logged in as a user with the <roles> role
    ...
  Examples:
  |         roles        |
  | "Flatrate"           |
  | "Trial"              |
  | "Administrator"      |
```

**Comment by pufferfishareliars** [comment]
I would love to see this feature implemented as well, as it would give greater flexibility writing up a more comprehensive set of examples and then running a sub-set of them if desired rather than creating separate duplicate scenarios.

**Comment by bwowk** [comment]
I think Behat core has everything needed for this to work. The tag filtering works on a ScenarioInterface, and ExampleNode implements it, so if an ExampleNode could get additional tags this should work out of the box.

Nowadays the ExampleNodes have tags, which are inherited from the OutlineNode.
The changes would need to be made on https://github.com/Behat/Gherkin
There's already an open issue on Behat/Gherkin#117, so let's have this discussion over there

**Comment by bwowk** [comment]
Behat/Gherkin#119 adds support for this syntax:

```Gherkin
@example_outline
  Scenario Outline: I want an example outline
    ...
    @case1
    Examples:
      | garga|marga |
      |hodi | brodi |

    @case2
    Examples:
      | garga|marga |
      |mura |    ura|
```
Which is already supported on Cucumber

**Comment by kwoxer** [comment]
So with a workaround with more than one table. Alright. Not so sexy but should work indeed. Thank you for info.
