### ISSUE TITLE
Add the ability to add output during Transforms

### ISSUE THREAD

**Issue by jeichorn** [Behat/Behat#988]
The use case is to allow you to see a summary of the data created by the transform to aid in debugging failed tests.

**Comment by jon-acker** [comment]
Did you have some idea of what this output could look like? Something like what symfony's dumper does? or phpunit?

**Comment by jeichorn** [comment]
In my case, my transform implements a simple template language, so I just need to echo the output.

So if it worked like an action, and you could just send things to stdout and they would show up it would work for me.

If it was enabled by some sort of debug flag, then some sort of dumper would make sense.

**Comment by ciaranmcnulty** [comment]
Closing this; I don't think it's something many users would benefit from and it would add complexity
