### ISSUE TITLE
Supporting Puli for extensions

### ISSUE THREAD

**Issue by Taluu** [Behat/Behat#989]
Hello,

Currently, when developping an extension, when configuring it in the behat.yml config file, we need to refer it from its FQCN rather than the defined config key (`My\BehatExtension` instead of `my_extension`). This is probably because of the fact that the "extension" is not loaded when we just require it, and have no way to tell behat "i've got a new extension".

So I was wondering if supporting Puli would be (or not..) an idea to help Behat discover the extensions, and then allow to use them directly.

For an exemple, you could look at how the discovery is done in the php-http package : 
- https://github.com/php-http/discovery/blob/master/src/Strategy/PuliBetaStrategy.php
- https://github.com/php-http/curl-client/blob/master/puli.json (example of a puli package)

If the idea is validated, I could try a PR

**Comment by everzet** [comment]
Might be interesting. As long as it doesn't introduce complexity into the core, colour me interested.

**Comment by Taluu** [comment]
I'll try to see how it could be done then, but IMO shouldn't be really complicated...

**Comment by everzet** [comment]
Two constraints I'd put on it are:

1. It needs to be completely optional
2. It mustn't introduce extra complexity to the core. Ideally, it should reduce existing complexity if possible
3. Prefer more general, less tool-specific (Puli) implementation
