### ISSUE TITLE
Context constructor initializer removes null arguments

### ISSUE THREAD

**Issue by Taluu** [Behat/Behat#991]
When trying to instanciate a context with a "nullable" service (e.g, having a `?MyService` in php 7.1), if the value is indeed `null`, the arguments seems to be filtered when passed to the instanciator.

Thus, we have the following error `UnknownParameterException: Can not find a matching value for ...`. If I pisted the thing correctly, it seems that somewhere along the way, the `null` is stripped from the arguments list. And as this is not an `optionnal`, but a `nullable` (php 7.1) parameter, the count of non optionnal parameters and given arguments is not exact and thus the exception is thrown.

In my case, after pondering it, I think that it is fine if the service is optionnal (having `null` as a default value) so I changed it, but it is not always the case...

I am not really sure how to fix this though.

**Comment by spolischook** [comment]
You can set null as dependency and then replace it in your Extension
```yml
my_own_service:
  class: Namespace\To\Class
  arguments:
    - ~
```
In this way you should have null in constructor.
In Extension you can replace this argument according to some conditions:
```php
public function process(ContainerBuilder $container)
{
$container
  ->getDefinition('my_own_service')
  ->replaceArgument(0, new Reference('dependecy_service'));
}
```

or just use setter injection

**Comment by Taluu** [comment]
Actually, that is not the point. Yes, using the container in the extension (or whatever) does the trick, but when you are using the helper container, as follows :

```yaml
suites:
    defaults:
        contexts:
            FeatureContext:
                - @my_service

        services: @my.container
```

The container being :

```php
<?php
use Interop\Container\ContainerInterface;

class MyContainer implements ContainerInterface
{
    // ...
    public function get($id) 
    {
        if ('my_service' === $id) {
            return null;
         }

         // .... other cases
     }

    // ....
}
```

And in your context, the following :

```php
<?php

// ....
public function __construct(?MyService $foo)
{
    // ...
}
```

Behat will then complain with thrown error, that it doesn't have the right number of args ; one way or another, the `null` is stripped of the arguments stack, and thus complains that there is no match for `$foo`. Hence the bug.
