### ISSUE TITLE
PSR-11 has been accepted

### ISSUE THREAD

**Issue by Taluu** [Behat/Behat#999]
PSR-11 has been officially accepted (cf https://github.com/php-fig/fig-standards/commit/a13a2f700d7c6b4de871fddde50b785b543e043e), so instead of having to use the [container-interop interfaces](https://github.com/container-interop/container-interop), we should use the [proper interfaces](https://github.com/php-fig/container). There is a compatibility though between the two sets of interfaces (container-interop now extends php-fig's container interfaces)

This may be considered a BC break though, so I guess it would only be for Behat 4 ?

**Comment by stof** [comment]
I'm quite sure we don't need to wait until Behat 4, if we keep implement the container-interop interface on our own container for BC reasons.

We can change the check for the expected ContainerInterface to expect a PSR one. This would not be a BC break, as container-interop now extends PSR-11 (we would have to bump the min version to 1.2 of course).

Removing container-interop entirely may be harder regarding BC indeed, in case someone expects the Behat container itself being an interop one. But this is not necessary for the first step of PSR-11 support.

**Comment by everzet** [comment]
Merged on master
